### ISSUE TITLE
Use `! Title` in the filters

### ISSUE THREAD

**Issue by FatOrangutan** [NanoAdblocker/NanoFilters#10]
The filters don't use `! Title`, so they show up like this in uBlock:

![capture](https://user-images.githubusercontent.com/8336638/34633618-32623886-f2a3-11e7-9abe-bee996d36191.PNG)

**Comment by jspenguin2017** [comment]
I wrote the title in the download link, it's up to uBO to save it properly.

**Comment by FatOrangutan** [comment]
https://github.com/gorhill/uBlock/issues/2501

All other filter lists, including your Nano Defender Integration, just use the Title comment.

**Comment by jspenguin2017** [comment]
It breaks my code style. If it's `# Title:` then I'll add it.
