### ISSUE TITLE
[Anti-adblock] ottawacitizen.com, kgw.com

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoFilters#100]
@okiehsch More Funding Choice stuff: 

`http://ottawacitizen.com/news/canada/ontario-election-live-2018-results-doug-ford-andrea-horwath-kathleen-wynne/wcm/d69c0ebd-b00f-449d-8c5c-5957576a0855` uses `d.3enm.com`

`https://www.kgw.com/` uses `d.emn0.com`

**Comment by okiehsch** [comment]
`3enm.com` is already blocked by `EasyPrivacy`
![unbenannt](https://user-images.githubusercontent.com/16838044/41135531-55b1e258-6ad2-11e8-9bf0-1a915e994103.PNG)




`https://www.kgw.com` 
![unbenannt](https://user-images.githubusercontent.com/16838044/41135525-4f272e48-6ad2-11e8-8da5-b1b077cc7610.JPG)
Does 
````
kgw.com##script:inject(abort-on-property-read.js, stop)
||emn0.com^$script,domain=kgw.com
````
work?

**Comment by jspenguin2017** [comment]
Yes, it does work. The second website has US GeoLock.

**Comment by jspenguin2017** [comment]
BTW, for `kgw.com`, they 403 all requests from EU. I had VPN on and forgot to turn it off, and apparently if you have it on when shutting down, it will automatically turn itself on the next time you boot.

**Comment by okiehsch** [comment]
`wtsp.com` is also blocked for all European users.
