### ISSUE TITLE
[Anti-adblock] hyperdebrid.net

### ISSUE THREAD

**Issue by sanGtH** [NanoAdblocker/NanoFilters#103]
### URLs where this issue occurs (Required)
https://hyperdebrid.net/

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/13797193/41291385-2b06194a-6e6d-11e8-962c-0d44cd4db5ce.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/13797193/41291438-53c55a08-6e6d-11e8-9736-9fbdbde3c9f7.png)

#### Environment (Required)
- Operating System and Version: Windows 7 64 Bit
- Browser and Version: Chrome 67.0.3396.62 and FF Quantum 59.0
- Nano Adblocker Version: I m using UBlock Origin v1.16.8
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)
Adblock Warning Removal List
EasyList

#### Your custom filters (Required if you have any)
NanoBase
NanoDefender
NanoWhiltelist

**Comment by jspenguin2017** [comment]
I see this rule in Nano Defender fixes it: 
```js
if (a.domCmp(["hyperdebrid.net"])) {
    a.filter("eval", a.matchMethod.string, "eval(function(p,a,c,k,e,d){");
}
```

It's kind of an old rule, and I think we can move that to a script snippet. @okiehsch

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
I just realized it is also caught in generic solution.
