### ISSUE TITLE
Akvideo.stream

### ISSUE THREAD

**Issue by Hadden89** [NanoAdblocker/NanoFilters#106]
This seems to fix the "disable adblock" on their site.
Maybe even the "on top ads" could be hidden.

```
@@||akvideo.stream^$ghide
@@||akvideo.stream^$image
```
Sample link: `https://vcrypt.pw/akv/6lfuml8a5zpt`

**Comment by mapx-** [comment]
sample working link:
`https://akvideo.stream/am4svqdb4kcr`

**Comment by jspenguin2017** [comment]
`elemhide` is not supported, it is internally converted to `ghide`. I might want to add a warning in the Linter.
