### ISSUE TITLE
[Anti-adblock] hdblog.it

### ISSUE THREAD

**Issue by Dr4gon97** [NanoAdblocker/NanoFilters#108]
### URLs where this issue occurs (Required)
https://mobile.hdblog.it/2018/06/20/ue-copyright-articolo-13-votazioni-juri/

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/37912033/41672486-5343cb34-74ba-11e8-867e-633912e2c263.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/37912033/41672653-bcd54910-74ba-11e8-94fb-446cd5f5e683.png)

### Describe the issue (Optional if obvious)
Any news article is blocked as soon as the page loads

#### Environment (Required)

- Operating System and Version: 
- Browser and Version:  Google Chrome 67.0.3396.87 64 bit
- Nano Adblocker Version: 1.0.0.53
- Nano Defender Version (Optional if you are not using it): 14.58

#### Your filter lists (Required)

Nano Defender Integration​​​​​2.655 usati su 2.699​​​​
Nano filters​​​​​76 usati su 93​​​​
Nano filters – Annoyance​​​​​14 usati su 14​​​​
Nano filters – Whitelist​​​​​0 usati su 0​​​​
uBlock filters​​​​​6.464 usati su 6.465​​​​
uBlock filters – Annoyances​​​​​164 usati su 164​​​​
uBlock filters – Badware risks​​​​​14 usati su 14​​​​
uBlock filters – Experimental​​​​​6 usati su 6​​​​
uBlock filters – Privacy​​​​​96 usati su 97​​​​
uBlock filters – Resource abuse​​​​​259 usati su 261​​​​
uBlock filters – Unbreak​​​​​473 usati su 473​​​​

Pubblicità (3/4)

Adblock Warning Removal List​​​​​432 usati su 449​​​​
Adguard Base Filters​​​​​16.890 usati su 17.836​​​​
EasyList​​​​​82.086 usati su 82.686​​​​

Privacy (2/3)

Adguard Spyware Filters​​​​​2.579 usati su 6.415​​​​
EasyPrivacy​​​​​13.844 usati su 15.162​​​​

Domini con Malware (4/4)

Malvertising filter list by Disconnect​​​​​397 usati su 3.752​​​​
Malware Domain List​​​​​1.115 usati su 1.131​​​​
Malware domains​​​​​23.062 usati su 23.079​​​​
Spam404​​​​​6.534 usati su 6.534​​​​

Elementi fastidiosi (4/5)

Adguard’s Annoyance List​​​​​11.440 usati su 13.368​​​​
Fanboy’s Annoyance List​​​​​19.882 usati su 39.732​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​68 usati su 68​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​19.816 usati su 19.844​​​​

Multiuso (5/5)

Dan Pollock’s hosts file​​​​​9.935 usati su 13.524​​​​
hpHosts’ Ad and tracking servers​​​​​41.659 usati su 45.729​​​​
MVPS HOSTS​​​​​12.109 usati su 12.615​​​​
NoCoin Filter List​​​​​296 usati su 413​​​​
Peter Lowe’s Ad and tracking server list​​​​​2.632 usati su 2.636​​​​
Regioni, lingue (2/36)
ITA: ABP X Files​​​​​4.332 usati su 4.669​​​​
ITA: EasyList Italy​​​​​4.391 usati su 4.491​​​​

Personalizzate (2/2)

Malware filter list by Disconnect​​​​​1 usati su 1.016​​​​
Nano filters – Timer bypassing (sometimes works)​​​​​0 usati su 0​​​​

**Comment by mapx-** [comment]
You are using abp x 

try
https://github.com/uBlockOrigin/uAssets/issues/2613#issuecomment-398534581

**Comment by Dr4gon97** [comment]
I'm sorry I didn't see it earlier, thank you!
