### ISSUE TITLE
For timer bypassing

### ISSUE THREAD

**Issue by Emilylove00** [NanoAdblocker/NanoFilters#11]
#
### Describe the issue (Required)
Timer bypass needed

### URLs where this issue occurs (Required)
http://madurls.com/

http://cryptoadz.win/

http://bitcoadz.pw/

http://cryptoskipad.com

http://iziwinmoney.info/

http://btc.ms/

http://elibtc.win/

http://cryptosmo.com/

http://cimi.website/
**Proper links for test:**
http://madurls.com/tdvF

http://cryptoadz.win/NkFPuJ

http://bitcoadz.pw/Ryif1vKq

http://cryptoskipad.com/Kq43kAF

http://iziwinmoney.info/Fzy49MN3mE

http://btc.ms/VD0z57V

http://elibtc.win/iUZBfAu

http://cryptosmo.com/Tnz5GG

http://cimi.website/e8Em
### Environment (Required)

- Operating System and Version: Windows 10 pro 
- Browser and Version: firefox 59
- Nano Adblocker Version: 1.0.0.26

**Comment by Emilylove00** [comment]
Give me a minute to post a proper links to test them.

**Comment by jspenguin2017** [comment]
I'll have a look when I got time.

**Comment by Emilylove00** [comment]
Ok thanks! take you time

**Comment by jspenguin2017** [comment]
I'll lock this because it's getting long, please open a new issue for other domains.

**Comment by jspenguin2017** [comment]
TODO:
```
http://iziwinmoney.info/Fzy49MN3mE

http://btc.ms/VD0z57V

http://elibtc.win/iUZBfAu

http://cryptosmo.com/Tnz5GG

http://cimi.website/e8Em
```

**Comment by jspenguin2017** [comment]
The rest are resolved in uAssets.
