### ISSUE TITLE
[Popup] vcrypt.pw, vcrypt.net

### ISSUE THREAD

**Issue by Hadden89** [NanoAdblocker/NanoFilters#111]
Sample `https://vcrypt.pw/open/7l7r1bn6gv95/King.of.the.Hill.02x03-L.artefatto.indiano.ITALIAN.SATrip.XviD-bY.SPOK.avi.mp4%C2%A0`

Looping "click to continue" if adblocker is on.
A java ""ads"" can be shown too via awkards redirects
`http://sz7.tlcbmtfrefurnish.review/22856/1558/18s/veu99/7724`

It could be a chromium 66 issue (main browser) as I don't see them on chromium 68 (g.beta)
![cattura3](https://user-images.githubusercontent.com/18642541/41799994-e0aabf90-7673-11e8-8a5e-f4725d91bd2d.PNG)

**Comment by mapx-** [comment]
I get no anti adblocking stuff.
For popups
`||vcrypt.net^$inline-script`

**Comment by jspenguin2017** [comment]
I'll assume this is fixed as you removed anti-adblock flag from the title. Closing.
