### ISSUE TITLE
[Anti-adblock] wallpapersmania.com

### ISSUE THREAD

**Issue by sanGtH** [NanoAdblocker/NanoFilters#112]
### URLs where this issue occurs (Required)

`http://www.wallpapersmania.com/`

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/13797193/41787285-8329fd4e-7665-11e8-87f3-ec2533d4017d.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/13797193/41787311-a37dcf8a-7665-11e8-8738-d6b99ced6587.png)

### Describe the issue (Optional if obvious)
The adblock detection message appers on the screen when you try to download any
wallpaper on this site

#### Environment (Required)
- Operating System and Version:  Windows7 64 bit
- Browser and Version: Chrome 67.0.3396.62 and FF 59.0.1
- Nano Adblocker Version: UBlockOrigin : 1.16.10 on both browsers
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)
Adblock Warning Removal List
Easy List

#### Your custom filters (Required if you have any)
NanoBase
NanoDefender
NanoWhitelist

**Comment by sanGtH** [comment]
@jspenguin2017 I still see the adblock detection message.

**Comment by jspenguin2017** [comment]
Can't reproduce, working fine for me: 
![image](https://user-images.githubusercontent.com/7283682/41811939-28634f02-76d6-11e8-9a40-021a500bae8f.png)

**Comment by sanGtH** [comment]
I m using UBlockOrigin and Nano filters. Are u too using the same configuration ?
Please share your configuration. I will check at my end what are the differences.

**Comment by sanGtH** [comment]
1. When i use Nanodefender, i am still seeing the Adblock message.
2. Then when i m using the  Nano Adblocker, the adblock message is no more there on the site.
So, this needs your attention : **Nano defender only working with Nano Adblocker, not with the UblockOrigin.**
Please fix it..

**Comment by jspenguin2017** [comment]
What do you mean? It works fine for me either way: 
![image](https://user-images.githubusercontent.com/7283682/41820067-faf4de24-7788-11e8-946a-97dd94c66b4a.png)

**Comment by sanGtH** [comment]
I see but in my case, when i used **(UblockOrigin + Nanodefender)**, the Adblock warning message
still appeared. Could you please  share the screenshot of the UblockOrigin Filters settings ?
Maybe i am missing on something.
Thanks

**Comment by jspenguin2017** [comment]
It still works for me, the settings is just default + [instructions here](https://jspenguin2017.github.io/uBlockProtector/). It's clearly a problem on your side. 
![image](https://user-images.githubusercontent.com/7283682/41881816-b101a4ee-78a2-11e8-80e1-f9d37fd529ad.png)
