### ISSUE TITLE
[Anti-adblock] usgamer.net

### ISSUE THREAD

**Issue by Daniel-USA** [NanoAdblocker/NanoFilters#113]
https://www.usgamer.net/

https://imgur.com/a/UKWbAEF

adblocker detected

just go to website

nano blocker and nano defender on chrome

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
I see a fix in uBlock filters. Make sure to update your filters.
