### ISSUE TITLE
[Anti-adblock] Vg247 blocks use of site with ublock origin and nano defender enabled

### ISSUE THREAD

**Issue by Nakina** [NanoAdblocker/NanoFilters#115]
### URLs where this issue occurs (Required)
https://www.vg247.com/

### Screenshots (Required)
![capture](https://user-images.githubusercontent.com/40581511/41877623-a17b1a74-7897-11e8-981a-cd94f4c912be.PNG)

### Screenshot of console (Required, press `F12` to open the console)
![console](https://user-images.githubusercontent.com/40581511/41877915-b0d4a5fc-7898-11e8-8ed9-793af29495dd.PNG)

### Describe the issue (Optional if obvious)
See screenshots

### Reproduction Steps (Optional if trivial)
Just go to the website with ublock origin and nano defender enabled (I also tried nano adblocker and that did the same thing)

#### Environment (Required)

- Operating System and Version: Windows 7 (latest build as of 6/12/2018) 
- Browser and Version: Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Nano Adblocker Version: Version 14.58
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)
My filters are all default plus the added filters for installing nano defender with ublock origin.

**Comment by mapx-** [comment]
fixed today in uBo
https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L1333
https://github.com/uBlockOrigin/uAssets/issues/2667

update ublock filters

**Comment by Nakina** [comment]
Thanks, sorry for posting a duplicate issue.

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/2667

**Comment by Poofey** [comment]
I just downloaded Nano adblocker and defender because of this site. It does not block the anti ad block.
![image](https://user-images.githubusercontent.com/8733219/42080863-d7e63ae6-7b38-11e8-8ded-15bd6552f103.png)
