### ISSUE TITLE
[Anti-adblock] finanzfrage.net

### ISSUE THREAD

**Issue by Symbai** [NanoAdblocker/NanoFilters#12]
### Describe the issue (Required)
If you visit this site a popup will appear and notify about you are using an adblocker (takes 1-2 seconds to show up).

### URLs where this issue occurs (Required)
https://www.finanzfrage.net/frage/nochmal-meine-frage-kann-ich-auf-grund-einer-lehrtaetigkeit-als-kampfsporttrainer-fuer-kinder-gewerbesteuerpflichtig-werden-obwohl-ich-auch-umst-befreit-bin

### Screenshots (Required)
https://imgur.com/a/2Ek7c

### Screenshot of console (Required, press `F12` to open the console)
https://imgur.com/a/Dwj5x (Note: ss was taken from Chrome console since I know devs are using and wanted to see if adblock detection is bypassed there which isnt the case)

### Environment (Required)

- Operating System and Version:  Windows 10 
- Browser and Version:  FF 57.0.4
- Nano Adblocker Version:  1.0.0.26
- Nano Defender Version: 13.17

#### Your filter lists (Required)
Default filter list

**Comment by jspenguin2017** [comment]
@mapx- Another source point one.
