### ISSUE TITLE
[Annoyance, GDPR Wall] tumblr.com, gry.pl, macplanete.com, allrecipes.co.uk

### ISSUE THREAD

**Issue by krystian3w** [NanoAdblocker/NanoFilters#124]
### URLs where this issue occurs (Required)

```
https://www.tumblr.com/tagged/wallpaper-blog
http://www.gry.pl/gra/wormax-io
https://www.macplanete.com/politique-de-confidentialite
http://allrecipes.co.uk/
http://allrecipes.co.uk/consent/?dest=/
```

### Screenshots (Required)

![www tumblr com_privacy_consent_redirect http 3a 2f 2fzermatia1920 tumblr com 2f](https://user-images.githubusercontent.com/35370833/42483572-94c8751c-83ee-11e8-8a9f-2b24fb9f783f.png) | ![www tumblr com_privacy_consent_redirect http 3a 2f 2fzermatia1920 tumblr com 2f 1](https://user-images.githubusercontent.com/35370833/42483576-a0d9156e-83ee-11e8-8e7d-a342abeacb28.png) | 
---- | ---- 
![www tumblr com_privacy_consent_redirect http 3a 2f 2fzermatia1920 tumblr com 2f 2](https://user-images.githubusercontent.com/35370833/42483587-b1a3e39c-83ee-11e8-9bf4-e6c39e6e2962.png) | ![allrecipes_co_uk_privacy_consent_redirect http  3a 2f 2fallrecipes co uk 2f consent 2f dest](https://user-images.githubusercontent.com/35370833/47713039-96707880-dc39-11e8-8ac6-1562e264aab6.png)|

### Screenshot of console (Required, press `F12` to open the console)
 
N/A

###### tumblr

```
##HTML.guce-gdpr-context BUTTON.yes.btn[data-submit="agree"]

<button data-submit="agree" class="btn yes">OK</button>
```

###### allrecipes

```
##DIV#st-container.gridResponsive__module.st-container button[onclick="sendAndRedirect();"]

<button style="order:2" onclick="sendAndRedirect();">Continue</button>
```

### Reproduction Steps (Optional if trivial)

N/A

#### Environment (Required)

- Operating System and Version:  Windows 10 Pro
- Browser and Version: Chrome 69
- Nano Adblocker Version: 1.0.0.55
- Nano Defender Version (Optional if you are not using it):  N/A

#### Your filter lists (Required)

Nano default + Nano filters - Annoyance

#### Your custom filters (Required if you have any)

N/A

**Comment by jspenguin2017** [comment]
When there is a choice, I don't really want to click on accept for you.

**Comment by krystian3w** [comment]
In my opionion tumblr do no have choice "don't really want to click on accept for you" - "forget about tumblr or accept GDPR".

**Comment by jspenguin2017** [comment]
What `manage options` do? I'm not on EU VPN right now.

**Comment by krystian3w** [comment]
OK, tumblr can off this options:

![obraz](https://user-images.githubusercontent.com/35370833/42483195-6200dfae-83ec-11e8-917c-b4b09f6bbdcc.png) |
--- |

after digging through 2 buttons in advanced options (**manage options** > **Manage** > **Our partners**)

**Comment by jspenguin2017** [comment]
Yea... If you have some choice and there isn't a "reject all" button, I rather leave it as-is.

**Comment by krystian3w** [comment]
I must click "done" button on the bottom and "OK" on first site.

**Comment by jspenguin2017** [comment]
As of now, annoyance filter only remove cookie walls, like accept or leave type. If there's an options page, I'd like to be leave the choice to the user. 

This isn't final decision and obviously I'm still open for discussion. But I don't want to be too aggressive with privileged filters for now.

**Comment by jspenguin2017** [comment]
Also `https://www.macplanete.com/politique-de-confidentialite`: 
![image](https://user-images.githubusercontent.com/7283682/43036756-6e747a62-8cc4-11e8-804b-da447e616e10.png)

**Comment by krystian3w** [comment]
`www.macplanete.com` works when block `quantcast` by `/cmpui-popup.js`

BaB on `www.macplanete.com` is another problem:


![obraz](https://user-images.githubusercontent.com/35370833/43037039-adde0120-8d08-11e8-8cf0-12f318e9cdf1.png)

**Comment by jspenguin2017** [comment]
I know, BAB is being handled in uAssets.

**Comment by jspenguin2017** [comment]
Test links: 
```
https://www.tumblr.com/tagged/wallpaper-blog
http://www.gry.pl/gra/wormax-io
https://www.macplanete.com/politique-de-confidentialite
```

**Comment by krystian3w** [comment]
```
http://elderscrolls.wikia.com/wiki/The_Elder_Scrolls_Wiki
https://gta.fandom.com/wiki/Main_Page
```
