### ISSUE TITLE
[Anti-adblock] blogforgeeks.co.uk

### ISSUE THREAD

**Issue by marcocorriero** [NanoAdblocker/NanoFilters#125]
### URLs where this issue occurs (Required)
https://blogforgeeks.co.uk/ 

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/16446639/42494027-4e30f594-841f-11e8-882e-968f6b116dc1.png)

### Describe the issue (Optional if obvious)
Testing this new anti-adblocker and seems it detects the adblock.

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
I can't reproduce this problem. Please try the [troubleshooting tips here](https://jspenguin2017.github.io/uBlockProtector/#troubleshooting). If that didn't work, please provide the following information: 
- The complete list of extensions that you have installed, including their version
- The complete list of filter lists that you have subscribed
- The complete list of your custom filter rules
- The country that you are in, and your VPN if you are using one
