### ISSUE TITLE
jetanime.co

### ISSUE THREAD

**Issue by flover2102** [NanoAdblocker/NanoFilters#135]
#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
Works fine for me. Closing as invalid as you have not filled the template. 
![image](https://user-images.githubusercontent.com/7283682/42734918-117f9086-8809-11e8-8b1d-18b473012030.png)
