### ISSUE TITLE
[Breakage] yesmovies.to

### ISSUE THREAD

**Issue by freddieromero23** [NanoAdblocker/NanoFilters#154]
### URLs where this issue occurs (Required)
`https://yesmovies.to/movie/avengers-infinity-war-24689/1366025-16/watching.html`

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/35078959/43551248-a094656a-95a3-11e8-8bae-9cdb9c966699.png)

### Screenshot of console (Required, press `F12` to open the console)

![image](https://user-images.githubusercontent.com/35078959/43551252-a4747832-95a3-11e8-8967-b53733c98e8c.png)

### Describe the issue (Optional if obvious)
Player is not loading video.

#### Environment (Required)

- Operating System and Version: Windows 10 Home
- Browser and Version: Chrome latest
- Nano Adblocker Version: 1.0.0.58
- Nano Defender Version (Optional if you are not using it): 1.5.0.0.24

#### Your filter lists (Required)
Default

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
