### ISSUE TITLE
[Anti-adblock] shinden.pl

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoFilters#157]
```
Reference: Quick Issue Reporter

Message:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Nano Defender 15.0.0.25

[Anti-adblock] https://shinden.pl/external-video/45139-boku-no-hero-academia/view/140118#column-one-inner
```

Reported from Poland. 

Requires account, has popup and ads (only) if Polish regional filter is enabled.

**Comment by ghajini** [comment]
account=
username & password = bugmenot123

it seems lot of exceptions filters in regional filter list

**Comment by jspenguin2017** [comment]
Hum, I don't see anything changing with an account, so might be Geo Lock. The Poland location in my VPN is pretty weak, I'll try again this weekend.

**Comment by MajkiIT** [comment]
I find solution. I will check it.
https://github.com/MajkiIT/polish-ads-filter/issues/8544

**Comment by jspenguin2017** [comment]
Alright.

**Comment by MajkiIT** [comment]
@jspenguin2017 They use to 2 way script. First I solved by Polish Filters, but after 30s adblock return. Can you check it ?

**Comment by jspenguin2017** [comment]
Is it Geo Locked?

**Comment by okiehsch** [comment]
Well, what is the issue ads, popups or anti-adblock or all of them?

With default setup and polish list at
````
 https://shinden.pl/external-video/45139-boku-no-hero-academia/view/140118#column-one-inner
````
I can't reproduce anything, even if I am logged in.

At 
````
https://shinden.pl/external-video/52827-hanebado/view/167318
````
I can reproduce an `anti-adblock` message
![image](https://user-images.githubusercontent.com/16838044/43984199-5ffe4436-9cff-11e8-8448-1212a16b363b.png)

Adding
````
@@||shinden.pl^$generichide
@@||smartadserver.com/ac$script,domain=shinden.pl
````
fixes it.

> Have you pinned down the offending code?

For the issue I can reproduce
`https://shinden.pl/f/js/main-obfuscated.js?Q`

**Comment by jspenguin2017** [comment]
It's just anti-adblock. The Polish filter had a bad solution that whitelisted a lot of ads and popups.

**Comment by jspenguin2017** [comment]
Closing in favor of https://github.com/NanoMeow/QuickReports/issues/93
