### ISSUE TITLE
[Annoyance, GDPR Wall] gry.pl

### ISSUE THREAD

**Issue by hawkeye116477** [NanoAdblocker/NanoFilters#159]
### URLs where this issue occurs (Required)

`http://www.gry.pl/gra/wormax-io`

### Screenshots (Required)
![screenshot_20180806_160254](https://user-images.githubusercontent.com/19818572/43721107-3347218a-9992-11e8-8976-595defe7e479.png)

### Screenshot of console (Required, press `F12` to open the console)
![screenshot_20180806_160340](https://user-images.githubusercontent.com/19818572/43721141-4cf14afc-9992-11e8-9b70-b665ce129758.png)

### Describe the issue (Optional if obvious)
I can't play game without accepting GDPR.

### Anything else you believe to be useful (Optional)
My solution:
```
gry.pl##+js(nanop-easy-set-cookie.js, euconsent=BOR-LGFOR-LHnABABAPLBE_AAACDWABgACEGoA, /;)
gry.pl###priorConsentScreen
```

#### Environment (Required)

- Operating System and Version: Manjaro 17.1.11 Hakoila
- Browser and Version: Vivaldi 1.15.1147.55 (based on Chromium 65.0.3325.183)
- Nano Adblocker Version: 1.0.0.60
- Nano Defender Version (Optional if you are not using it): n/a

#### Your filter lists (Required)

![screenshot_20180806_160806](https://user-images.githubusercontent.com/19818572/43721391-ec698ab8-9992-11e8-9fcc-5f36434936b7.png)

**Comment by jspenguin2017** [comment]
Hum, if I click settings and turn off some of the stuff, the website breaks until I clear cookies. The cookie value is `BOSFCrqOSFCrqABABAENBEBAAACDWABgACEGoA`. I'll see if it is consistent.

**Comment by jspenguin2017** [comment]
I'll merge this into https://github.com/NanoAdblocker/NanoFilters/issues/124
