### ISSUE TITLE
[Breakage] thepiratebay.org

### ISSUE THREAD

**Issue by doclucas** [NanoAdblocker/NanoFilters#162]
`https://thepiratebay.org/torrent/18269623/LINUX_UBUNTU_16.10_32X64`

### Screenshots (Required)
https://lh3.googleusercontent.com/-s7TUZLcY2ok/W2rEyBj-J9I/AAAAAAAAKlU/LUYJtSO3pisbPnlR6Y5oNADUvGZxmdlogCHMYCw/s0/chrome_2018-08-08_17-24-06.png

### Screenshot of console (Required, press `F12` to open the console)
https://lh3.googleusercontent.com/-s7TUZLcY2ok/W2rEyBj-J9I/AAAAAAAAKlU/LUYJtSO3pisbPnlR6Y5oNADUvGZxmdlogCHMYCw/s0/chrome_2018-08-08_17-24-06.png

### Describe the issue (Optional if obvious)
After logging in to thepiratebay.org you have the option to comment on torrents pages.
When clicking the comment button, the input box does not open, and there are errors in the console.
I have debugged this myself already and found out that easylist is disabling some vital components that make submitting comments impossible, while Nano Defender Integration blocks other components that prevent the inline js to open up the comments box.
I will open another bug report on easylist bug tracker as well.

### Anything else you believe to be useful (Optional)
As I wrote above,
disabling Nano Defender Integration allows the comments box to show up when clicking "comments".
I believe this is the offending code: `||thepiratebay.org^$inline-script`
disabling EasyList allows to submit the comment (and a bug report will be opened there too, as they are blocking jquery.js via `||thepiratebay.$script,domain=thepiratebay.cr|thepiratebay.org|thepiratebay.red`)

#### Environment (Required)

- Operating System and Version: WIN10 x64
- Browser and Version: Chrome x64 v67
- Nano Adblocker Version: Nano Adblocker v1.0.0.61
- Nano Defender Version (Optional if you are not using it): 15.0.0.26

**Comment by doclucas** [comment]
Just for reference, this is the bug report on EasyList forums:
https://forums.lanik.us/viewtopic.php?f=64&t=41367

**Comment by jspenguin2017** [comment]
I need a proper test link.

**Comment by doclucas** [comment]
Any thepiratebay.org torrent page, like the one in my screenshot for example:
https://thepiratebay.org/torrent/18269623/LINUX_UBUNTU_16.10_32X64

Note that you must be logged in to thepiratebay.org for the comment link (seen in my screenshot) to actually show up. Then click it.

Thank you

**Comment by doclucas** [comment]
By the way, the HTML of that comment link is:
`<dd><span id="NumComments">1</span>
                                <a href="#" class="comments" title="Write comment" onclick="document.getElementById('CommentDiv').style.display='block';document.getElementById('add_comment').focus();return false">Write comment</a>
                            </dd>`

And your `||thepiratebay.org^$inline-script` is simply blocking this.

**Comment by doclucas** [comment]
Just for learning purposes, if I write a filter list like this and write
`||thepiratebay.org^$inline-script` but want to exclude `class="comments"`
Is this the proper syntax?
`||thepiratebay.org^$inline-script#@#.comments`

Thanks

**Comment by jspenguin2017** [comment]
OK, I'll test this tonight. 

> Is this the proper syntax?

The syntax highlighter will tell you.

**Comment by jspenguin2017** [comment]
I'll just remove the rule, the crypto miner is already blocked by other means.
