### ISSUE TITLE
polsatnews.pl

### ISSUE THREAD

**Issue by MajkiIT** [NanoAdblocker/NanoFilters#167]
### Screenshots (Required)
https://screenshots.firefox.com/k96LHbWg49ZJx7xl/www.polsatnews.pl

### Screenshot of console (Required, press `F12` to open the console)
```
[Nano] IMA Event Ignored :: adsManagerLoaded ima3.js:99:25
[Nano] Nano Defender Activated :: platform.twitter.com core.js:12:5
[Nano] Excluded :: All Generically Applied Solutions rules-common.js:68:9
[Nano] Nano Defender Activated :: staticxx.facebook.com core.js:12:5
[Nano] Excluded :: All Generically Applied Solutions rules-common.js:68:9
[Nano] Nano Defender Activated :: www.facebook.com core.js:12:5
[Nano] Excluded :: All Generically Applied Solutions rules-common.js:68:9
perf_trace {"name": "e2e", "parent": "PageEvents.BIGPIPE_ONLOAD"}
```

### Describe the issue (Optional if obvious)
If I disable nano Defender then I don't see Adblock. If I enable then ADB. 

### Reproduction Steps (Optional if trivial)

http://www.polsatnews.pl/wideo/to-nietrafiony-eksperyment-prof-rymsza-o-moscie-w-genui-_6719819/

#### Environment (Required)

- Operating System and Version: Ubuntu 
- Browser and Version: FF 61.01
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
Can't reproduce, works fine for me. You must be using an obsolete version of ND, IMA SDK is disabled in recent version. 

If I enable Polish filter, I don't see the anti-adblock message, although I still see the Geo Lock message. 
![image](https://user-images.githubusercontent.com/7283682/44241009-7115b780-a17e-11e8-9937-b332cf3c7866.png)
