### ISSUE TITLE
otakustream.tv

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoFilters#17]
![2018-01-15 02_53_23-otakustream - watch anime online english subbed hd](https://user-images.githubusercontent.com/5884000/34923906-3877d5ec-f9a0-11e7-986f-0ce759873391.png)
`https://otakustream.tv/`

![2018-01-15 03_14_36-developer tools - https___otakustream tv_](https://user-images.githubusercontent.com/5884000/34924207-4d11a710-f9a2-11e7-8a54-004595fd4a1e.png)

some 1/20 times i have a gray screen in main site and i don't can move or click anything
and i not see graphic/images

to reproduct
+ clear cookie/cache
+ click f5
+ scroll down
+ click button back to top

my filters
https://gist.github.com/KonoromiHimaries/48e9a12ec92d5ef105073ec1485326d3

Nano Adblocker 1.0.0.27
Nano Defender 13.20
Chrome 63.0.3239.132

**Comment by jspenguin2017** [comment]
Well, that's going to be a pain to test.

**Comment by KonoromiHimaries** [comment]
@jspenguin2017 I caught it
![2018-01-15 03_18_14-otakustream - watch anime online english subbed hd](https://user-images.githubusercontent.com/5884000/34924288-d888023a-f9a2-11e7-80da-459fe43373f7.png)

**Comment by jspenguin2017** [comment]
OK, do you use any annoyance filter? I think their blocking is incomplete.

**Comment by KonoromiHimaries** [comment]
![2018-01-15 03_22_06-https___gist githubusercontent com_konoromihimaries_48e9a12ec92d5ef105073ec14853](https://user-images.githubusercontent.com/5884000/34924389-50cd5c22-f9a3-11e7-92d0-941cc80b828e.png)

**Comment by jspenguin2017** [comment]
I'm really not sure how to reproduce this.
