### ISSUE TITLE
NanoResources.txt blocking nearly all my websites.

### ISSUE THREAD

**Issue by xox3x** [NanoAdblocker/NanoFilters#170]
### URLs where this issue occurs (Required)

google.com
reddit.com
nearly all websites

### Screenshots (Required)

![nano](https://user-images.githubusercontent.com/42531270/44322483-cb986780-a44d-11e8-9991-caae8cb444a5.PNG)

### Screenshot of console (Required, press `F12` to open the console)
![nano2](https://user-images.githubusercontent.com/42531270/44322546-16b27a80-a44e-11e8-8fdb-dcf362105d42.PNG)

Console is showing nothing.

### Describe the issue (Optional if obvious)

Well I don't know what happened, but suddenly I can't access to any websites anymore. The only solution is to disable the nanoresources.txt

### Reproduction Steps (Optional if trivial)

Tested this also in Edge Browser and it is happening there too.

#### Environment (Required)

- W10 1803
- Chrome 68.0.3440.106 
- Nano Adblocker Version:  using uMatrix
- Nano Defender Version : 15.0.0.35

#### Your filter lists (Required)

uBlock filters
uBlock filters – Annoyances
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
Adblock Warning Removal List
EasyList
Malvertising filter list by Disconnect
Malware Domain List
Malware domains
Fanboy’s Annoyance List
Fanboy’s Anti-Thirdparty Social (see warning inside list)
Fanboy’s Social Blocking List
Peter Lowe’s Ad and tracking server list

#### Your custom filters (Required if you have any)
https://mirror1.malwaredomains.com/files/immortal_domains.txt
Anti popads.net
CJX's Annoyance List
Nano Defender Integration
Nano filters
uBlock Filters Plus
(NanoResources.txt ) causing the bug if enabled

**Comment by jguc** [comment]
Same here, it started today.

**Comment by jspenguin2017** [comment]
You are using it wrong. Go read the instructions here: https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin

**Comment by xox3x** [comment]
Sorry, but can you tell me what I did wrong? I'm not a tech guy and I already checked the installation guide before I opened the request. Maybe the answer is a really simple one for you but I just don't know how to solve this problem. Instead of just telling me I'm wrong, it would have been more helpful to tell me where I'm wrong.

**Comment by jspenguin2017** [comment]
The resource file is **not** a filter, if you load it as a filter, then it will result in undefined behavior. 

Remove it from filters subscription and load it in advanced settings.

**Comment by jspenguin2017** [comment]
I'm really surprised that more than one person loaded the resource file as a filter, I added a warning in the install steps. 

This is not a problem on my side. That line (`//`) is not a mistake.
