### ISSUE TITLE
[Ads] iqiyi.com

### ISSUE THREAD

**Issue by CincaiLa** [NanoAdblocker/NanoFilters#172]
### URLs where this issue occurs (Required)

`https://www.iqiyi.com/v_19rqyv48lo.html`

### Screenshots (Required)
![a](https://user-images.githubusercontent.com/42729429/44641270-ce203180-a9f8-11e8-91ad-2709c1192abd.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![b](https://user-images.githubusercontent.com/42729429/44641396-4ab31000-a9f9-11e8-880f-fe05683f7643.jpg)
![a](https://user-images.githubusercontent.com/42729429/44641427-77ffbe00-a9f9-11e8-8519-5ff75f1f2392.jpg)
![b](https://user-images.githubusercontent.com/42729429/44641499-c4e39480-a9f9-11e8-9b39-df6b4559f3ee.jpg)
![a](https://user-images.githubusercontent.com/42729429/44641545-f65c6000-a9f9-11e8-801f-a0ded171ed42.jpg)
![b](https://user-images.githubusercontent.com/42729429/44641560-06743f80-a9fa-11e8-9363-9722c41c8d85.jpg)

### Describe the issue (Optional if obvious)
 Every video before play it have to watch a 65 sec ads.

### Reproduction Steps (Optional if trivial)
 How can i block the ads?

### Anything else you believe to be useful (Optional)
I had try another extension and it work on it. ( https://chrome.google.com/webstore/detail/%E5%B9%BF%E5%91%8A%E5%87%80%E5%8C%96%E5%99%A8/cbiaicifbmeokbhollcjfeaoakmppfeh )

#### Environment (Required)

- Operating System and Version: Windows 10 Pro 1803
- Browser and Version: Google Chrome Canary 70.0.3533.0
- Nano Adblocker Version: v1.0.0.65
- Nano Defender Version (Optional if you are not using it): 15.0.0.39

#### Your filter lists (Required)
 
![a](https://user-images.githubusercontent.com/42729429/44641770-3bcd5d00-a9fb-11e8-9b41-7eda8aefad11.jpg)

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
I can reproduce, I can simply block the video-ad and after the site repeatedly requests it for about 30 seconds, the "real" video starts on my end.
This should really be fixed in a Chinese List.
````
||akamai.inter.71edge.com/videos/other/*.f4v$xmlhttprequest,domain=iqiyi.com
@@||static.iqiyi.com/js/player_v1/sdk/*$script,first-party
````

The second filter fixes some pretty obvious site breakage on my end and I will add it to `uBO-unbreak`.

**Comment by jspenguin2017** [comment]
> after the site repeatedly requests it for about 30 seconds

So it will take 30 seconds for the real video to start?

**Comment by okiehsch** [comment]
That differs on my end, if I redirect the xvrrequest the result is the same and redirecting only works with Chrome anyway.
I would say it takes between 15 and 30 seconds after the page has finished loading before the video starts.

**Comment by jspenguin2017** [comment]
Hum, that's not really ideal... 

Anyway, do you know who's maintaining Chinese regional filters?

**Comment by okiehsch** [comment]
> Anyway, do you know who's maintaining Chinese regional filters?

No.
@mapx- any idea?

**Comment by ZaphodBeebblebrox** [comment]
I believe its @cjx82630. He does not appear to have the list on github any longer, though he does maintain a Chinese annoyance list at cjx82630/cjxlist. Their [forum](http://abpchina.org/forum/forum.php) still lists him as the maintainer.

**Comment by cjx82630** [comment]
You need ABP3.2 and  a filter in EasyList China
/\/videos\/other\/(.*?\.f4v)/$rewrite=/videos/othez/$1

**Comment by jspenguin2017** [comment]
It doesn't look like the rules are getting into the regional filter anytime soon.

**Comment by okiehsch** [comment]
I can add 
`||akamai.inter.71edge.com/videos/other/*.f4v$xmlhttprequest,domain=iqiyi.com`
but there is the caveat of the delay and I really don't like to play around with sites on which I can't recognize a single letter.

**Comment by jspenguin2017** [comment]
Yea, 30 seconds black screen is a bit too much... I can read the site fine but I'm busy with school and the report filter server.

**Comment by cjx82630** [comment]
Blocking video ads on iqiyi.com will get warning message and stop playing. 
for now use Rewrite filters to handle video ads, Check [ELC](https://easylist-downloads.adblockplus.org/easylistchina.txt)

**Comment by trevuchet** [comment]
> caveat of the delay 

I prefer silence to noise that injures my privacy.

If the spotify app hacks simply had zero audio during commercials it would be similarly difficult to catch in analytics.

**Comment by jspenguin2017** [comment]
Fixed upstream
