### ISSUE TITLE
[Anti-adblock] finobe.com

### ISSUE THREAD

**Issue by hyperak** [NanoAdblocker/NanoFilters#173]
### URLs where this issue occurs (Required)

`https://finobe.com/`

### Screenshots (Required)
![firefox_2018-09-03_18-45-14](https://user-images.githubusercontent.com/29081800/45002924-72cae200-afaa-11e8-9c9b-4bc3f1f87a21.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/29081800/45002853-7873f800-afa9-11e8-94ae-37d373d8e779.png)

### Describe the issue (Optional if obvious)
The warning in the header, and the whole website being invaded with the "HACKED BY DARK GARY" background.

#### Environment (Required)

- Operating System and Version: Windows 10 Version 1709 (x64)
- Browser and Version: Firefox Quantum 61.0.2
- Nano Adblocker Version: Was cached at Sat, 01 Sep 2018 19:52:37 GMT
- Nano Defender Version (Optional if you are not using it): Using Nano Adblocker's integration for uBlock Origin

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/29081800/45002841-57130c00-afa9-11e8-8171-34c80a66d94d.png)

#### Your custom filters (Required if you have any)
None, if you consider Nano Adblocker as a standard filter

**Comment by jspenguin2017** [comment]
@okiehsch FYI
