### ISSUE TITLE
[Anti-adblock] myvidster.com

### ISSUE THREAD

**Issue by bleakwire** [NanoAdblocker/NanoFilters#175]
`http://www.myvidster.com/video/154403481/Aston_Martin_Lagonda_Taraf_Limited_Edition_2015_Exterior_and_Interior`

<img width="1680" alt="screen shot 2018-09-07 at 7 04 50 am" src="https://user-images.githubusercontent.com/43065558/45215749-64abe880-b26c-11e8-9dcc-643dc320f2e7.png">

<img width="1680" alt="screen shot 2018-09-07 at 7 06 21 am" src="https://user-images.githubusercontent.com/43065558/45215826-9f158580-b26c-11e8-93db-bf891a32cc4a.png">

Issue:
Ads blocked by site

Steps to reproduce:
1. Go to www.myvidster.com 
2. Click on any video
3. Wait 3-5 seconds
4. Message pops

'We notice that you like our web site and you are also running Adblock :(

We 100% understand why you are running Adblock, but we still need ad revenue to keep the servers running. Please disable Adblock (or add myvidster.com to your whitelist) to continue using our wonderful service. You can also upgrade to MyVidster PRO which includes ad removal for popular bookmarked tube sites and you are allow to use your Adblock!' 

System:
- Operating System and Version: macOS High Sierra 10.13.4
- Browser and Version: Google Chrome/Version 68.0.3440.106 (Official Build) (64-bit)
- Nano Adblocker Version: Nano Adblocker v1.0.0.66
- Nano Defender Version (Optional if you are not using it): 15.0.0.42

Default filters and settings only

**Comment by jspenguin2017** [comment]
Cannot reproduce. Try updating your filters.
