### ISSUE TITLE
[Anti-adblock] hdblog.it

### ISSUE THREAD

**Issue by MaschineBrennt** [NanoAdblocker/NanoFilters#180]
Hi.

Maybe this one is hard to defeat (hdblog.it's articles):

https://hardware.hdblog.it/2018/09/10/amd-ryzen-7-2800x

### **with Nano AdBlocker enabled**
![withadblock](https://user-images.githubusercontent.com/43149870/45318144-4c71ed00-b53c-11e8-9a04-207fae93672a.png)
**----------------------------------------------------------------------------------------------------------------------**

### **with Nano AdBlocker disabled**
![withoutadblock](https://user-images.githubusercontent.com/43149870/45318310-d457f700-b53c-11e8-844a-1aad7eef84cc.png)
**----------------------------------------------------------------------------------------------------------------------**

The same with other site/domain's article, e.g.:
https://www.hdblog.it/2018/09/10/qualcomm-snapdragon-wear-3100-caratteristiche/
https://huawei.hdblog.it/2018/09/01/huawei-mate-20-lite-ufficiale-prezzo-specifiche/
etc.

- Windows 8.1 Pro x64
- Chromium v69 stable
- Nano Adblocker v1.0.0.66 
- Nano Defender v15.0.0.42

Thanks

**Comment by mapx-** [comment]
I get no problem using uBo + default setup (FF / chrome)

**Comment by andreap-** [comment]
same problem here since 1 week (before it was working properly)
FF + nanoAdblocker+Nano defender
everything updated to latest
