### ISSUE TITLE
[Anti-adblock] cuti.in

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#185]
http://cuti.in/3RxS33Bg

Environment (Required)

    Operating System and Version: Windows 10 version 1803
    Browser and Version: Chrome 69
    Nano Adblocker Version: 1.0.0.66
    Nano Defender Version (Optional if you are not using it): 15.0.0.42

Your filter lists (Required)
Default + Nano Defender Integration

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/3550
already fixed.

**Comment by jspenguin2017** [comment]
OK, looks good.
