### ISSUE TITLE
[Anti-adblock]  rmdown.com

### ISSUE THREAD

**Issue by eromoe** [NanoAdblocker/NanoFilters#186]
### URLs where this issue occurs (Required)

http://www.rmdown.com/link.php?hash=1831385108ac59700ee2cf32305584a567a82cf8ed0

### Screenshots (Required)

![image](https://user-images.githubusercontent.com/3938751/45924803-9941c480-bf3b-11e8-9a4d-b2af92bd4706.png)

**Comment by jspenguin2017** [comment]
@okiehsch @mapx- Loses race condition when refreshed. 
![image](https://user-images.githubusercontent.com/7283682/45929408-5a494a00-bf0e-11e8-9a3e-e467bdd59c0f.png)

**Comment by mapx-** [comment]
right, I tested only in FF (and still working for FF)

**Comment by mapx-** [comment]
seems working using only:

```
rmdown.com##+js(abort-on-property-write.js, open)
rmdown.com###foote1r:style(height: 1 px !important; visibility: collapse !important;)
rmdown.com##A[href][target="_blank"]:style(height: 1px !important; visibility: collapse !important;)
```

**Comment by crackerjohn** [comment]
the website has a different strategy now. You will see nothing on the page if the nana adblock is on.  Once you disable nano adblock, you will see whole screen of Ads

**Comment by jspenguin2017** [comment]
Please refrain from digging up years old issues. I have opened a new one here: https://github.com/NanoAdblocker/NanoFilters/issues/329
