### ISSUE TITLE
[Anti-adblock] ourl.io

### ISSUE THREAD

**Issue by gabri25ele** [NanoAdblocker/NanoFilters#187]
on every ourl.io we are "Please disable Adblock to proceed to the next page."
for example, this page https://ourl.io/AzmoWi
appears like this

https://i.imgur.com/dGITnTO.png

**Comment by gabri25ele** [comment]
what model?

**Comment by jspenguin2017** [comment]
The template that you deleted. Don't delete it, fill it.
