### ISSUE TITLE
bootstrapcdn.com : 92 detections in 9 files on VirusTotal.  Not blocked?

### ISSUE THREAD

**Issue by Logic-Elliven** [NanoAdblocker/NanoFilters#188]
I'm no pro but have come across a good # sites loading stuff from 
bootstrapcdn.com
This is what VirusTotal has to say about the URL:

Latest files that are detected by at least one antivirus solution and embed URL pattern strings with the domain provided.
1/57 040c80a5444ebf9831ee4e0576c45fddbb1a1344150ad93ba0ef682562ffc467
3/62 421b49d18c6984bb590e18b9c8a334a292eecd25b09c4cecbe4f53d9d10790cb
60/64 3a986295d25e68feec3d257c7e371e7697fee6a7769440125363e1a554c9e792
19/65 c0aca81866e92022c125c29511c7bb94cf5599023122c8f22fb51257029843ce
1/60 4531108262ebd63163f5bc47fdd3099f8aceca4532705916debada54336a09d0
5/66 0cb79d348bd033187a086da7e05ed8aa2cae9cadf5bb4c2f193facb028f251ce
1/67 8f7cc4c731341c373a6223c06a43c5412557dc179823ec5164927fc75244e7a1
1/59 d20d05164c149b442831d9c429bb15fbc13dc6ab197a0d59fbd125eeeff3da19
1/57 c8c4aadafb7861b8e3839a88a18e3763ffe232ef61b594446f8d35ab3e339303

I hope I'm not wasting your time reporting this, but it seems worth looking at to me?

**Comment by jspenguin2017** [comment]
Nano Filters doesn't handle malicious websites. You should report to Safe Browsing instead: https://safebrowsing.google.com/
