### ISSUE TITLE
[Anti-adblock] programiz.com

### ISSUE THREAD

**Issue by chelseaislan** [NanoAdblocker/NanoFilters#189]
### URLs where this issue occurs (Required)

https://www.programiz.com/dsa/circular-queue

### Screenshots (Required)
![screenshot 177](https://user-images.githubusercontent.com/30471081/46337713-6d6bc080-c658-11e8-9696-54b05281ad93.png)

### Screenshot of console (Required, press `F12` to open the console)
![screenshot 178](https://user-images.githubusercontent.com/30471081/46337742-883e3500-c658-11e8-9ae8-d1237e920a06.png)

### Describe the issue (Optional if obvious)
Anti-adblock that can be dismissed easily

#### Environment (Required)

- Operating System and Version: Windows 10 1803
- Browser and Version: Chrome 69
- Nano Adblocker Version: 1.0.0.69
- Nano Defender Version (Optional if you are not using it): 15.0.0.50

#### Your filter lists (Required)

Default ones

#### Your custom filters (Required if you have any)
-

**Comment by mapx-** [comment]
fixed in uBo annoyances list
