### ISSUE TITLE
NSFW! [Anti-adblock] pornoman.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoFilters#192]
### URLs where this issue occurs (Required)
`https://pornoman.pl/strony/ladny-naturalny-biust-i-duzo-piegow,13669`

### Screenshots (Required)
![2018-10-14-ladny naturalny biust i duzo piegow](https://user-images.githubusercontent.com/5884000/46916815-194dce00-cfc0-11e8-9ba7-3a0cc51c601f.png)

### Describe the issue (Optional if obvious)

anti-adblock

### Anything else you believe to be useful (Optional)
https://github.com/uBlockOrigin/uAssets/issues/3696

#### Environment (Required)

- Operating System and Version: w10 latest release
- Browser and Version: chrome latest release
- Nano Adblocker Version: uBlock Origin latest release
- Nano Defender Version (Optional if you are not using it):  15.0.0.57

#### Your custom filters (Required if you have any)

https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by jspenguin2017** [comment]
@okiehsch @MajkiIT

**Comment by jspenguin2017** [comment]
Need to refresh once to trigger.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/issues/3696

**Comment by KonoromiHimaries** [comment]
@okiehsch it sems work, and there is still a popup to a random domian

**Comment by KonoromiHimaries** [comment]
@jspenguin2017 majki does not supported adult sites

**Comment by okiehsch** [comment]
> majki does not support adult sites

I did not know that, I will add the fix to `uBO-filters`.
I can't reproduce any popups, can you post your logger output in regards to the popup?

**Comment by KonoromiHimaries** [comment]
@okiehsch clear cookie/cache and click ctrl+f5
then click `Jestem pełnoletni` and you be moved in to next card, 
in the present card there will be a redirection to a random domian.

**Comment by okiehsch** [comment]
> then click Jestem pełnoletni and you be moved in to next card,
in the present card there will be a redirection to a random domian.

I can only reproduce if I don't add `pornoman.pl##+js(abort-current-inline-script.js, atob, tabunder)`

If you update your `uBO-filter` ist can you still reproduce the redirection?
