### ISSUE TITLE
[Timer] za.gl

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoFilters#193]
### URLs where this issue occurs (Required)
`https://za.gl/B2VQwj`

### Screenshots (Required)
![2018-10-15-za gl](https://user-images.githubusercontent.com/5884000/46930044-91110c80-d043-11e8-9b8a-0704a0702fbe.png)

### Describe the issue (Optional if obvious)

timer

#### Environment (Required)

- Operating System and Version: w10 latest release
- Browser and Version: chrome latest release
- Nano Adblocker Version: uBlock Origin latest release
- Nano Defender Version (Optional if you are not using it):  15.0.0.57

#### Your custom filters (Required if you have any)

https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by jspenguin2017** [comment]
Most of them are validated on server side these days. I'll test it later...

**Comment by jspenguin2017** [comment]
Validated on server side.
