### ISSUE TITLE
[Anti-adblock] jagobd.com

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#195]
[Anti-adblock] in videos

http://www.jagobd.com/atnnews

**Comment by jspenguin2017** [comment]
Can't reproduce. Closing as invalid since you did not fill the template. 
![image](https://user-images.githubusercontent.com/7283682/47159324-da16ca00-d2aa-11e8-91f8-cdb1f0faca3a.png)
