### ISSUE TITLE
[Anti-adblock, Popup] expansion.com

### ISSUE THREAD

**Issue by JoseHidalgo** [NanoAdblocker/NanoFilters#198]
### URLs where this issue occurs (Required)
http://www.expansion.com/fueradeserie/viajes/album/2018/10/18/5bc85ac8268e3e73788b46f7.html

### Screenshots (Required)
https://preview.ibb.co/jj7W80/2018-10-19-19-05-23.jpg

### Screenshot of console (Required, press `F12` to open the console)
https://preview.ibb.co/cbeB80/2018-10-19-19-06-17.jpg

### Describe the issue (Optional if obvious)
The whole expansion.com website works as follows : you can read any of its articles, but for a lot of them there's a timer : after 15-20 seconds, you always get that annoying pop-up saying that you have an adblocker and that you need to disengage it in order to keep reading. You can refresh the page, but after 15-20 seconds you'll always get the pop-up back.

### Reproduction Steps (Optional if trivial)

1. Go to this URL : http://www.expansion.com/fueradeserie/viajes/album/2018/10/18/5bc85ac8268e3e73788b46f7.html
2. Wait for 15-20 seconds without doing anything

#### Environment (Required)
- Operating System and Version: Windows 7 SP1
- Browser and Version: Firefox 64bit (latest version)
- Nano Adblocker Version: I don't have Nano Adblocker
- Nano Defender Version (Optional if you are not using it): 15.0.0.59

#### Your filter lists (Required)
Default settings

#### Your custom filters (Required if you have any)
None

**Comment by jspenguin2017** [comment]
Can't reproduce, works fine for me. Waited over 1 minute. 
![image](https://user-images.githubusercontent.com/7283682/47236957-db272480-d39a-11e8-9ded-7b858e26ec5d.png)

**Comment by JoseHidalgo** [comment]
Thanks jspenguin.
- I have Firefox + uBlock Origin (latest version, default settings, fresh install) + Nano Defender.
- You seem to have Chrome + Nano Block + Nano Defender.
Could you please try on Firefox + uBlock Origin + Nano Defender ? Thank you.
The problem can be reproduced 100% on my side. It always happens before 20 sec, and actually it's been annoying me for months on expansion.com, until I finally decided to report it to you. Thanks.

**Comment by JoseHidalgo** [comment]
Thanks jspenguin.

I see that you have Chrome + Nano Block + Nano Defender, so I have installed Chrome + Nano Block + Nano Defender for testing purposes. And in that case, it works 100%.

But with Firefox 61.0.2 + uBlock Origin (latest, fresh install) + Nano Defender (latest, fresh install), I can confirm that it doesn't work.

If you try yourself on a Firefox + uBlock Origin + Nano Defender, you'll see that it doesn't work. Maybe you can understand why, and come up with a fix for us Firefox users ? (at least understanding if the problem comes from uBlock Origin, or from Nano Defender for Firefox, etc.). Thank you.

The problem can be reproduced 100% on my side. It always happens before 20 sec, and actually it's been annoying me for months on expansion.com, until I finally decided to report it. Thanks.

**Comment by LiCybora** [comment]
Still cannot reproduce, regardless how long I wait...

![screenshot from 2018-10-21 10-22-26](https://user-images.githubusercontent.com/40160522/47262468-2452b200-d51c-11e8-9acf-93b30050e593.png)

**Comment by JoseHidalgo** [comment]
EDIT - it seems to work now ! I have updated all the filter lists according to this ( https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin ), and it seems to have done the trick.
Case closed apparently !
