### ISSUE TITLE
[Suggestion] warning box scriptlet

### ISSUE THREAD

**Issue by elypter** [NanoAdblocker/NanoFilters#2]
there are many websites that users want to be warned of but do not want them blocked. it would be very helpful if there was an injectable scriptlet that can show a localized warning message that remembers its state. firefox can already do something like this for phishing sites and will soon do the same for hacked sites but it can be used for all sorts of lists of websites like untrustworthy news sites, fake accounts, different kinds of fraud...

**Comment by jspenguin2017** [comment]
There isn't a safe way to show that kind of box, it will always be manipulable by the page.

**Comment by jspenguin2017** [comment]
I'll mark it as wontfix for now, until someone can show me an absolute safe way to show such warning box.

**Comment by jspenguin2017** [comment]
What we can do is have one filter with strict blocking which after opt-in, will prevent such sites from loading.

**Comment by elypter** [comment]
cant this be done the same way as the panel that opens when clicking the extension icon?

**Comment by jspenguin2017** [comment]
The popup? There is no way to open the popup without the user clicking.

**Comment by elypter** [comment]
too bad that addons are this crippled. an alternative but not a replacement could be behaving like if the html is being blocked and only load the page after the user confirmed but allow the use of a custom message. this also wouldnt work as simple scrip snippet though.

**Comment by jspenguin2017** [comment]
You can just do `||example.com^$document`. No snippet needed.

**Comment by elypter** [comment]
but you cannot include a message or further information.

**Comment by jspenguin2017** [comment]
Hum, interesting... 

It is a really big heavy hammer, and I don't want to open Nano for abuse. Security first, I can't allow arbitrary message to be displayed. But a few hard coded built in message could be possible.

**Comment by jspenguin2017** [comment]
This has be added to [pending features list](https://github.com/NanoAdblocker/NanoCore/blob/master/notes/pending-features.MD). 
Discussion can continue while this issue is closed. 

Also, for future feature requests, please open issues in Nano Core repository instead.
