### ISSUE TITLE
nano adblocker blocking everything

### ISSUE THREAD

**Issue by kuratowakiru** [NanoAdblocker/NanoFilters#201]
### URLs where this issue occurs (Required)
any

### Screenshots (Required)
https://i.imgur.com/EUrAllj.png

### Screenshot of console (Required, press `F12` to open the console)
https://i.imgur.com/sgmlzlD.png

### Describe the issue (Optional if obvious)
nanowhitelist.txt, nanodefender.txt , nanobase.txt  
all have the * line in it, I think this cause nano adblock to block everything.
everything work again when I disable these filters.

### Reproduction Steps (Optional if trivial)
enable nanowhitelist.txt, nanodefender.txt , nanobase.txt  
go to any site

#### Environment (Required)

- Operating System and Version:  windows 7
- Browser and Version: chrome Version 69.0.3497.100 (Official Build) (64-bit)
- Nano Adblocker Version: Nano Adblocker v1.0.0.73
- Nano Defender Version (Optional if you are not using it):  Nano Defender
15.0.0.65

#### Your filter lists (Required)

Auto-update filter lists 
Parse and enforce cosmetic filters
Ignore generic cosmetic filters
91,995 network filters ＋ 47,002 cosmetic filters from:
 My filters​​​​​16 used out of 18​​​​
Built-in (8/11)
Nano Defender Integration​​​​​2,632 used out of 2,685​​​​
Nano filters​​​​​149 used out of 152​​​​
OFF Nano filters – Annoyance​​​​​​​​​
Nano filters – Whitelist​​​​​0 used out of 0​​​​
uBlock filters​​​​​9,988 used out of 9,990​​​​
uBlock filters – Annoyances​​​​​​​​​
uBlock filters – Badware risks​​​​​41 used out of 41​​​​
OFF uBlock filters – Experimental​​​​​​​​​
uBlock filters – Privacy​​​​​144 used out of 145​​​​
uBlock filters – Resource abuse​​​​​279 used out of 280​​​​
uBlock filters – Unbreak​​​​​598 used out of 598​​​​
Ads (2/4)
Adblock Warning Removal List​​​​​462 used out of 479​​​​
OFF Adguard Base Filters​​​​​​​​​
OFF Adguard Mobile Filters​​​​​​​​​
EasyList​​​​​85,250 used out of 85,499​​​​
Privacy (1/3)
OFF Adguard Spyware Filters​​​​​​​​​
EasyPrivacy​​​​​15,509 used out of 15,703​​​​
OFF Fanboy’s Enhanced Tracking List​​​​​​​​​
Malware domains (2/4)
OFF Malvertising filter list by Disconnect​​​​​​​​​
Malware Domain List​​​​​1,096 used out of 1,111​​​​
Malware domains​​​​​26,837 used out of 26,837​​​​
OFF Spam404​​​​​​​​​
Annoyances (0/5)
OFF Adguard’s Annoyance List​​​​​​​​​
OFF Fanboy’s Annoyance List​​​​​​​​​
OFF Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
OFF Fanboy’s Cookiemonster List​​​​​​​​​
OFF Fanboy’s Social Blocking List​​​​​​​​​
Multipurpose (1/5)
OFF Dan Pollock’s hosts file​​​​​​​​​
OFF hpHosts’ Ad and tracking servers​​​​​​​​​
OFF MVPS HOSTS​​​​​​​​​
OFF NoCoin Filter List​​​​​​​​​
Peter Lowe’s Ad and tracking server list​​​​​2,608 used out of 2,609​​​​

#### Your custom filters (Required if you have any)
AakList (Anti-Adblock Killer)​​​​​103 used out of 2,178​​​​
nanowhitelist.txt, 
nanodefender.txt , 
nanobase.txt  
Nano filters – Timer bypassing (sometimes works)​​​​​0 used out of 0​​​​

**Comment by jspenguin2017** [comment]
Reset your settings.
