### ISSUE TITLE
[Anti-adblock] leechall.com

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#203]
http://leechall.download/go/5PRW6IMFJKT8XQV

Use this link for testing in leechall.com. Anti-adblock appear after clicking on generate link.
http://rapidgator.net/file/fb4a6f08efb350664f0ae1d17725b3d6/Chilling.Adventures.of.Sabrina.S01E01.Chapter.One.October.Country.NF.WEB-DL.DD5.1.x264-NTG.mkv.html

**Comment by jspenguin2017** [comment]
Works fine for me. Closing as invalid as you have not filled the template.
