### ISSUE TITLE
[Anti-adblock] internetretailing.com.au, insideretail.com.au

### ISSUE THREAD

**Issue by kulfoon** [NanoAdblocker/NanoFilters#205]
https://github.com/uBlockOrigin/uAssets/issues/3833

### Describe the issue (Optional if obvious)

Anti-Adblock message appears, after disabling Nano Defender and it's filter lists the message is gone.

### `internetretailing.com.au`
![ss1](https://user-images.githubusercontent.com/43844449/47590075-7ad04e00-d96b-11e8-856b-ae03c559d2dc.png)

### `insideretail.com.au`
![ss2](https://user-images.githubusercontent.com/43844449/47590085-86bc1000-d96b-11e8-8b8e-215052d8776e.png)

### `internetretailing.com.au`
![ss1](https://user-images.githubusercontent.com/43844449/47588921-f5976a00-d967-11e8-989e-29a9943ee9dd.png)

### `insideretail.com.au`
![ss2](https://user-images.githubusercontent.com/43844449/47590574-ecf56280-d96c-11e8-99a8-9ab22c7fda24.png)

#### Environment (Required)

- Nano Defender Version (Optional if you are not using it):  15.0.0.65

#### Your filter lists (Required)

Nano Defender Integration​​​​​
Nano filters​​
Nano filters - Whitelist​

uBO default +

uBO Annoyance
Adblock Warning Removal List
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/commit/1705ab6b937752905da501c98de77c60640ae0cf
