### ISSUE TITLE
[Anti-adblock] bigfreegiveaway.com

### ISSUE THREAD

**Issue by kulfoon** [NanoAdblocker/NanoFilters#206]
https://github.com/uBlockOrigin/uAssets/issues/3832

### Describe the issue (Optional if obvious)

Anti-Adblock message appears, after disabling Nano Defender and it's filter lists, the message is gone.

### Screenshot
![ss1](https://user-images.githubusercontent.com/43844449/47590165-cd116f00-d96b-11e8-8668-d14660a3541f.png)

### Screenshot of console (Required, press `F12` to open the console)

![ss1](https://user-images.githubusercontent.com/43844449/47589454-76a33100-d969-11e8-857c-47bfb8223917.png)

#### Environment (Required)

- Nano Defender Version (Optional if you are not using it):  15.0.0.65

#### Your filter lists (Required)

Nano Defender Integration​​​​​
Nano filters​​
Nano filters - Whitelist​

uBO default +

uBO Annoyance
Adblock Warning Removal List
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/commit/1705ab6b937752905da501c98de77c60640ae0cf
