### ISSUE TITLE
[Anti-adblock] techstext.com

### ISSUE THREAD

**Issue by kulfoon** [NanoAdblocker/NanoFilters#207]
### URLs where this issue occurs (Required)

http://www.techstext.com/

### Screenshot of console (Required, press `F12` to open the console)

![ss1](https://user-images.githubusercontent.com/43844449/47589679-2aa4bc00-d96a-11e8-8a5c-9260b61750ac.png)

### Describe the issue (Optional if obvious)

Anti-Adblock message appears, after disabling Nano Defender and it's filter lists, the message is gone.

### Reproduction Steps (Optional if trivial)

Visit the website

#### Environment (Required)

- Operating System and Version: Windows 7 SP1 64bit
- Browser and Version: Firefox 63.0 64bit
- Nano Adblocker Version: uBlock Origin version: 1.17.2
- Nano Defender Version (Optional if you are not using it):  15.0.0.65

#### Your filter lists (Required)

Nano Defender Integration​​​​​
Nano filters​​
Nano filters - Whitelist​

uBO default +

uBO Annoyance
Adblock Warning Removal List
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/commit/1705ab6b937752905da501c98de77c60640ae0cf
