### ISSUE TITLE
[Anti-adblock] lacartes.com

### ISSUE THREAD

**Issue by kulfoon** [NanoAdblocker/NanoFilters#208]
### URLs where this issue occurs (Required)

http://www.lacartes.com/

### Screenshot of console (Required, press `F12` to open the console)

![ss1](https://user-images.githubusercontent.com/43844449/47589956-101f1280-d96b-11e8-80d4-37e9371af835.png)

### Describe the issue (Optional if obvious)

Anti-Adblock message appears, after disabling Nano Defender and it's filter lists, the message is gone.

### Reproduction Steps (Optional if trivial)

Visit the website

#### Environment (Required)

- Operating System and Version: Windows 7 SP1 64bit
- Browser and Version: Firefox 63.0 64bit
- Nano Adblocker Version: uBlock Origin version: 1.17.2
- Nano Defender Version (Optional if you are not using it):  15.0.0.65

#### Your filter lists (Required)

Nano Defender Integration​​​​​
Nano filters​​
Nano filters - Whitelist​

uBO default +

uBO Annoyance
Adblock Warning Removal List
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/commit/2714fbbc37fab6be0f47a2c98a282bcd17c9cc33

**Comment by jspenguin2017** [comment]
I'll build & test tonight.
