### ISSUE TITLE
[Breakage] roboticsandautomationnews.com

### ISSUE THREAD

**Issue by kulfoon** [NanoAdblocker/NanoFilters#209]
### URLs where this issue occurs (Required)

http://roboticsandautomationnews.com/

### Screenshots (Required)

![ss2](https://user-images.githubusercontent.com/43844449/47601221-a7b54d00-d9cd-11e8-8fdb-3a9eedd7cacf.png)

### Screenshot of console (Required, press `F12` to open the console)

![ss1](https://user-images.githubusercontent.com/43844449/47601225-abe16a80-d9cd-11e8-9aca-acc23ab6ff3f.png)

### Describe the issue (Optional if obvious)

Some elements (images etc) on the website aren't loaded, after disabling Nano Defender and it's filter lists, the issue is gone.

### Reproduction Steps (Optional if trivial)

Visit the website

#### Environment (Required)

- Operating System and Version: Windows 7 SP1 64bit
- Browser and Version: Firefox 63.0 64bit
- Nano Adblocker Version: uBlock Origin version: 1.17.2
- Nano Defender Version (Optional if you are not using it):  15.0.0.65

#### Your filter lists (Required)

Nano Defender Integration​​​​​
Nano filters​​
Nano filters - Whitelist​

uBO default +

Adblock Warning Removal List

**Comment by jspenguin2017** [comment]
They are using an insanely old jQuery...
