### ISSUE TITLE
[Anti-adblock] superbru.com

### ISSUE THREAD

**Issue by brru8999** [NanoAdblocker/NanoFilters#212]
### URLs where this issue occurs (Required)
`https://www.superbru.com/player/dashboard.php`

### Screenshots (Required)

![image](https://user-images.githubusercontent.com/38956371/47731535-4e018c80-dc32-11e8-89dc-e6181ebb30a7.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/38956371/47731582-64a7e380-dc32-11e8-90bd-abe9dc37f6d0.png)

#### Environment (Required)

- Operating System and Version:  Windows 7 Pro
- Browser and Version: Chrome
- Nano Adblocker Version:  1.0.0.74
- Nano Defender Version (Optional if you are not using it):  15.0.0.66

**Comment by brru8999** [comment]
Nano Defender Integration​​​​​2,630 used out of 2,683​​​​
Nano filters​​​​​140 used out of 141​​​​
Nano filters – Whitelist​​​​​0 used out of 0​​​​
uBlock filters​​​​​10,392 used out of 10,396​​​​
uBlock filters – Badware risks​​​​​41 used out of 41​​​​
uBlock filters – Privacy​​​​​144 used out of 145​​​​
uBlock filters – Resource abuse​​​​​280 used out of 281​​​​
uBlock filters – Unbreak​​​​​626 used out of 626​​​​
Ads (2/4)
Adblock Warning Removal List​​​​​480 used out of 497​​​​
EasyList​​​​​85,411 used out of 85,665​​​​
Privacy (1/3)
EasyPrivacy​​​​​15,552 used out of 15,746​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,096 used out of 1,111​​​​
Malware domains​​​​​26,842 used out of 26,842​​​​
Annoyances (0/5)
Multipurpose (1/5)
Peter Lowe’s Ad and tracking server list​​​​​2,610 used out of 2,611​​​​

**Comment by jspenguin2017** [comment]
I need a test link.

**Comment by brru8999** [comment]
https://www.superbru.com/player/dashboard.php

**Comment by ZaphodBeebblebrox** [comment]
I made an account, I cannot reproduce either with uBO or NA+ND.

**Comment by brru8999** [comment]
I believe it is a sporadic alert. I can reproduce when clearing cache.

**Comment by brru8999** [comment]
Am still getting annoyances about white listing from Superbru. I am logged in with an account atm.

![image](https://user-images.githubusercontent.com/38956371/75985530-15bb2f80-5eb2-11ea-8bf9-9cfc3e409c64.png)

![image](https://user-images.githubusercontent.com/38956371/75985566-27043c00-5eb2-11ea-8a38-76899311cf76.png)

**Comment by jspenguin2017** [comment]
I need a test account. You can submit one using the Quick Issue Reporter. Alternatively, you can open a confidential issue here: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues

**Comment by brru8999** [comment]
Issue reported using quick issue reporter. Thanks!

**Comment by jspenguin2017** [comment]
OK, I'll take a look when I have time. 

Merging this issue to https://github.com/NanoMeow/QuickReports/issues/3225
