### ISSUE TITLE
NSFW! [Anti-Adblock] oload.fun

### ISSUE THREAD

**Issue by Brolyns** [NanoAdblocker/NanoFilters#214]
https://oload.fun/f/7i-2RFBGvtI The publisher of this file doesnt allow adblock, please disable and [reload] !

**Comment by jspenguin2017** [comment]
Works fine for me. Closing as invalid as you have not filled the template.

**Comment by kulfoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues/3997
