### ISSUE TITLE
NSFW! [Anti-adblock] avgle.com

### ISSUE THREAD

**Issue by accountforadg** [NanoAdblocker/NanoFilters#215]
My filter
![image](https://user-images.githubusercontent.com/39081420/47890664-da0df100-de8a-11e8-9d86-383513916997.png)

https://avgle.com/video/IqVmcmOcEmv
![image](https://user-images.githubusercontent.com/39081420/47890678-e98d3a00-de8a-11e8-8a10-d4d98f5a4aa0.png)

This is a very famous website, I believe I don't need too much description.

**Comment by accountforadg** [comment]
Actually ？there is no solution? Avgle can be transformed into an advertising company.

**Comment by jspenguin2017** [comment]
It's not really "no solution", it's just that they watch our solutions and patch them quickly. 

If an advertising company try to do that, we'll be fighting back and wait for them to make a mistake that bricks many websites and go out of business. 

We've been having a lot of trouble dealing with first party custom anti-adblock solutions.

**Comment by kulfoon** [comment]
https://github.com/uBlockOrigin/uAssets/issues/4000

**Comment by jspenguin2017** [comment]
I'm closing this, it's already listed on ND homepage.
