### ISSUE TITLE
[Anti-adblock] sport-tv-guide.live

### ISSUE THREAD

**Issue by patrickdrd** [NanoAdblocker/NanoFilters#216]
when you do a search in the page: https://sport-tv-guide.live/user it says adblocker detected, I've got nano filter of course, how do they do it?

**Comment by patrickdrd** [comment]
well, the lines:

@@||sport-tv-guide.live^$generichide
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*$script,domain=sport-tv-guide.live


aren't fixing this issue, I guess I'm talking about a new one

take a look:
https://imgur.com/mV5kvv0

**Comment by patrickdrd** [comment]
I filled the template

**Comment by jspenguin2017** [comment]
Still work fine for me. Try disabling non-default filters. You may also need to update your browser. 
![image](https://user-images.githubusercontent.com/7283682/47922144-fe160600-de7b-11e8-802e-dfc0c6394327.png)

**Comment by patrickdrd** [comment]
ok but I disabled all the non-default filters as I said and "my filters" and "my rules", 
the result was the same,
anyway, updating the browser is not a simple process 
(from 52.9 esr to quantum is like throwing 52.9 to the trash bin and 
setting up quantum from scratch) and I don't want to do it,
because I don't like quantum and many things I enjoy using now won't work,
anyway, thanks for your time
