### ISSUE TITLE
[Anti-adblock] di.fm

### ISSUE THREAD

**Issue by brru8999** [NanoAdblocker/NanoFilters#218]
www.di.fm

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/38956371/48095617-c809b680-e1da-11e8-9d63-cd720ec76d46.png)

### Screenshot of console (Required, press `F12` to open the console)

![image](https://user-images.githubusercontent.com/38956371/48095655-e1aafe00-e1da-11e8-98c7-99162d1c5927.png)
![image](https://user-images.githubusercontent.com/38956371/48095676-ef608380-e1da-11e8-9bd3-7d6aa5e2d87b.png)

### Describe the issue (Optional if obvious)

Site loads fine. Upon playing a stream, I am redirected to a splash page.

### Reproduction Steps (Optional if trivial)

Visit site, then press play on a stream,

#### Environment (Required)

- Operating System and Version:  Windows 7 Pro
- Browser and Version:  Chrome Version 71.0.3578.30 (Official Build) beta (64-bit)
- Nano Adblocker Version: 1.0.0.75
- Nano Defender Version (Optional if you are not using it):  15.0.0.69

#### Your filter lists (Required)

92,612 network filters ＋ 47,111 cosmetic filters from:
 My filters​​​​​0 used out of 0​​​​
Built-in (8/11)
Nano Defender Integration​​​​​2,602 used out of 2,654​​​​
Nano filters​​​​​147 used out of 148​​​​
Nano filters – Whitelist​​​​​0 used out of 0​​​​
uBlock filters​​​​​10,563 used out of 10,563​​​​
uBlock filters – Badware risks​​​​​42 used out of 42​​​​
uBlock filters – Privacy​​​​​144 used out of 145​​​​
uBlock filters – Resource abuse​​​​​280 used out of 281​​​​
uBlock filters – Unbreak​​​​​647 used out of 649​​​​
Ads (2/4)
Adblock Warning Removal List​​​​​479 used out of 496​​​​
EasyList​​​​​85,487 used out of 85,740​​​​
Privacy (1/3)
EasyPrivacy​​​​​15,584 used out of 15,778​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,096 used out of 1,111​​​​
Malware domains​​​​​26,843 used out of 26,843​​​​
Annoyances (0/5)
Multipurpose (1/5)
Peter Lowe’s Ad and tracking server list​​​​​2,926 used out of 2,927​​​​

#### Your custom filters (Required if you have any)
None

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/48096456-6a726b80-e1d4-11e8-95b5-7665d0ffb564.png)

**Comment by brru8999** [comment]
Could it be my version of Chome?

**Comment by jspenguin2017** [comment]
Try clearing your cache.

**Comment by Gonzalox** [comment]
For some reason when clearing cache or disabling it the anti-adblock screen still appears. If I delete all cookies (in addition to the cache) the site works correctly, so far without problems.

**Comment by matt-tatnell** [comment]
I was just about to submit this to uAssets, but then I noticed this issue here.  I use di.fm daily and this has just started happening to me today as well (I have seen this splash screen in the past over the years as they presumably update their anti-adblock software).

The client-side flag in question appears to be "__amplify__abw" in localstorage.  If you clear that, the block disappears, but only until the next song change and adblock is re-detected.  Basically you have to clear the flag every time this screen appears and refresh.

**Comment by jspenguin2017** [comment]
It takes like 5 min to test...

**Comment by jspenguin2017** [comment]
Can you still reproduce with 15.0.0.71?

**Comment by brru8999** [comment]
Confirmed this is occuring with 15.0.0.71

**Comment by jspenguin2017** [comment]
I can't seem to reproduce it, does it work after clearing cookies and cache?

**Comment by Gonzalox** [comment]
For me works fine after clearing cookies and cache now. Thanks!

**Comment by brru8999** [comment]
Same here. Confirmed it was working for a few minutes then shut off.

**Comment by Gonzalox** [comment]
Adblock notice usually appears after listening to music for approximately 30 minutes (using account). Here are the messages from the console: https://i.imgur.com/WhSrkhG.png

**Comment by ZaphodBeebblebrox** [comment]
I left it running in the background for a while with nano adb + nano defender and I got it to show up. I checked around 24 minutes after I started it, so I am not certain exactly how long it takes to get it.

**Comment by jspenguin2017** [comment]
@ZaphodBeebblebrox Does it happen with just uBO default? I don't think I have a rule that affects this domain anymore.

**Comment by jspenguin2017** [comment]
Honestly those 2k lines of spaghetti code inherited from AAK is basically dumpster fire at this point.

**Comment by jspenguin2017** [comment]
Is it good now? Can someone test?

**Comment by ZaphodBeebblebrox** [comment]
It stopped for me with NA+ND. Once that happened, if I switched to uBO it remained blocked, so I added a fix to Ublock Filters.

**Comment by brru8999** [comment]
Still getting. I switched to uBO with ND.
![image](https://user-images.githubusercontent.com/38956371/48629427-3559dc00-e97f-11e8-87f4-a85b5538ba47.png)

**Comment by jspenguin2017** [comment]
This just feels like FuckAdBlock. Does `@@||di.fm^$generichide` work? 
![image](https://user-images.githubusercontent.com/7283682/48634519-f168d600-e982-11e8-81cb-05c1ef2280ad.png)

**Comment by brru8999** [comment]
New news! I went back to NA and ND and it played fine for an hour. Had to shut down and leave work but I never got an ad blocker notice.

**Comment by kennethb22** [comment]
I can reproduce. Exiting Chrome - deleting all cookies, caches, etc. - allows di.fm to play a few songs, but then anti-adblock message comes up. I've repeated three times. It gets through a few songs, then throws up the "Turn off your ad blocker" message. Here's my console from the last run:

![screen shot 2018-11-17 at 1 31 49 pm](https://user-images.githubusercontent.com/19860067/48664553-47667800-ea6e-11e8-8f78-b153bf829982.jpg)

**Comment by jspenguin2017** [comment]
How many is a "few"?

**Comment by kennethb22** [comment]
It varies. 5 to 8, between 20 and 30 minutes.

**Comment by brru8999** [comment]
Greetings. This issue has resurfaced/

![image](https://user-images.githubusercontent.com/38956371/58558797-52e9e700-81e7-11e9-907e-31416f88d6eb.png)

![image](https://user-images.githubusercontent.com/38956371/58558890-8af12a00-81e7-11e9-90a1-0db6b7f7784d.png)

![image](https://user-images.githubusercontent.com/38956371/58558926-9d6b6380-81e7-11e9-8893-dde332bf0f4e.png)

![image](https://user-images.githubusercontent.com/38956371/58558949-ab20e900-81e7-11e9-99bb-a67d0e21f876.png)

![image](https://user-images.githubusercontent.com/38956371/58558980-b8d66e80-81e7-11e9-889c-91fc08bbc062.png)

**Comment by brru8999** [comment]
**Environment (Required)**
Operating System and Version: Windows 10 Enterprise
Browser and Version: Chrome Version 75.0.3770.54 (Official Build) beta (64-bit)
Nano Adblocker Version: 1.0.0.112
Nano Defender Version (Optional if you are not using it): 15.0.0.147
**Your filter lists (Required)**
Built-in (8/11)
Nano Defender Integration​​​​​2,604 used out of 2,649​​​​
Nano filters​​​​​214 used out of 218​​​​
Nano filters – Whitelist​​​​​0 used out of 1​​​​
uBlock filters​​​​​16,716 used out of 16,734​​​​
uBlock filters – Badware risks​​​​​129 used out of 129​​​​
uBlock filters – Privacy​​​​​158 used out of 159​​​​
uBlock filters – Resource abuse​​​​​112 used out of 112​​​​
uBlock filters – Unbreak​​​​​950 used out of 952​​​​
Ads (2/5)
Adblock Warning Removal List​​​​​651 used out of 672​​​​
EasyList​​​​​92,484 used out of 92,816​​​​
Privacy (1/3)
EasyPrivacy​​​​​17,090 used out of 17,165​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,090 used out of 1,105​​​​
Malware domains​​​​​26,898 used out of 26,898​​​​
Annoyances (0/6)
Multipurpose (1/4)
Peter Lowe's Ad and tracking server list​​​​​2,944 used out of 2,945​​​​

**Comment by jspenguin2017** [comment]
I can't seem to reproduce. 
![image](https://user-images.githubusercontent.com/7283682/58604490-c0caf880-8251-11e9-8c43-7388bcb34d06.png)

**Comment by LessRekkless** [comment]
I can reproduce. Without logging on, I can go the full allowed 30 minutes without triggering the anti-adblock page before it tells me to make an account and disables playback.

After logging in as a free member, it takes only a couple songs before the anti-adblock splash page is triggered.

**Comment by scalp42** [comment]
I can confirm here, with a free account, it'll kick in very quick.

**Comment by jspenguin2017** [comment]
I need a test account, to provide one, you can either: 
Open a confidential issue here: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/-/issues 
Or submit a private message here with reference `218`: https://legacy.hugoxu.com/PrivateMessage/

**Comment by mooman65** [comment]
The issue has just resurfaced for me today, so I checked this ticket again.  An account can easily be created with no verification required on e-mail, but I've created one and can send the details through to you.

Regarding the issue, it's the same as before: as a guest there is the 30min block, but when logged in, after a bit of time it'll stop playing music and trigger the anti-adblock interstitial.

**Comment by mapx-** [comment]
using a free account, after a 4 min song and another one still playing .. no anti adb on my end

**Comment by mjcolom-git** [comment]
The issue happens on firefox for android version 68.xx.xx (New firefox cannot play mp3 files, says di.fm). Android version 6, Latest nano adblocker & defender for firefox. Replacing Nanos with ublock origin does not do any good. It started to happen last night, Never happened before. Cannot reproduce over windows 7 pro & firefox 79 for windows with latest nanoadblocker & defender for firefox installed, however.

**Comment by mjcolom-git** [comment]
Now it started to happen on windows 7 pro, firefox 80.0b6 (64-bit),  Nano Adblocker1.0.0.151 , Nano Defender 15.0.0.201, Tampermonkey 4.11.6117 with userscript (source code below) , plays one song and says "Please Disable your AdBlocker"

// ==UserScript==
// @name         Don't bug me, Digitally Imported
// @namespace    https://github.com/jonlandrum/di
// @description  Closes the "Are you still there?" dialog box
// @include      https://www.di.fm/*
// @exclude      https://www.di.fm/login
// @grant        none
// @author       Jonathan Landrum
// @version      1.0
// ==/UserScript==
/* jshint -W097 */
'use strict';

setInterval(function() {
    var modal = document.getElementById('modal-region');
    if (typeof(modal) !== 'undefined' && modal !== null && modal.children.length !== 0) {
        document.querySelectorAll("button[type='button']")[1].click();
    }
}, 1000);

**Comment by mapx-** [comment]
could you test these filters

```
@@||synchrobox.adswizz.com/*gdpr$script,domain=di.fm
@@||cdn.adswizz.com/adswizz/js/SynchroClient2.js$script,domain=di.fm
```

**Comment by mjcolom-git** [comment]
> 
> 
> could you test these filters
> 
> ```
> @@||synchrobox.adswizz.com/*gdpr$script,domain=di.fm
> @@||cdn.adswizz.com/adswizz/js/SynchroClient2.js$script,domain=di.fm
> ```

Sorry , no changes, play one theme and then shows "Please disable your AdBlocker"

**Comment by brru8999** [comment]
I hadn't noticed these up until this morning. I can confirm I'm getting the same behavior.

**Comment by mjcolom-git** [comment]
And all that is needed to test is a free account. Filters posted mapx  do not work on my setup.

**Comment by mjcolom-git** [comment]
Since more than one user commented they cannot reproduce the issue, I thought that one´s ip address could have a role in this, so i tested di fm using Thor 9.5.1 with Nano Adblocker1.0.0.151 & Nano Defender 15.0.0.201 as sole add ons, and the issue presented itself after two songs, (Please disable your Adblocker), so i think is safe to say that the ip address plays no role on this issue,

**Comment by llacb47** [comment]
> New firefox cannot play mp3 files

Off topic but you should file a webcompat bug here `http://webcompat.com`.

I can reproduce, I listened for about 30 minutes 
![image](https://user-images.githubusercontent.com/16567977/89920881-fba51c00-dbca-11ea-8dae-d632446efb2c.png)

Here's the stack trace of sending the ad request `https://pubads.g.doubleclick.net/gampad/ads?sz=300x250&ciu_szs=300x250&iu=/1009675/radio_di_vocaltrance&url=https%3A%2F%2Fwww.di.fm%2Fplaylists&correlator=1597161858106&description_url=%5Bdescription_url%5D&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1`:
```
  | send | @ | application-bf70c2b….js:formatted:3674
-- | -- | -- | --
  | ajax | @ | application-bf70c2b….js:formatted:3495
  | e.get | @ | application-bf70c2b….js:formatted:41898
  | e.get | @ | application-bf70c2b….js:formatted:41673
  | e._parse | @ | application-bf70c2b….js:formatted:40971
  | e.parse | @ | application-bf70c2b….js:formatted:40942
  | e.get | @ | application-bf70c2b….js:formatted:40667
  | (anonymous) | @ | application-bf70c2b….js:formatted:42103
  | l | @ | application-bf70c2b….js:formatted:1788
  | add | @ | application-bf70c2b….js:formatted:1802
  | (anonymous) | @ | application-bf70c2b….js:formatted:42095
  | l | @ | application-bf70c2b….js:formatted:1788
  | add | @ | application-bf70c2b….js:formatted:1802
  | requestAds | @ | application-bf70c2b….js:formatted:42093
  | startAd | @ | application-bf70c2b….js:formatted:42256
  | startAd | @ | application-bf70c2b….js:formatted:42427
  | requestAd | @ | application-bf70c2b….js:formatted:42403
  | requestMidrollAd | @ | application-bf70c2b….js:formatted:42476
  | (anonymous) | @ | application-bf70c2b….js:formatted:8708
  | request | @ | application-bf70c2b….js:formatted:8775
  | request | @ | application-bf70c2b….js:formatted:10220
  | playNextItem | @ | application-bf70c2b….js:formatted:43340
  | (anonymous) | @ | application-bf70c2b….js:formatted:8708
  | execute | @ | application-bf70c2b….js:formatted:8755
  | execute | @ | application-bf70c2b….js:formatted:10217
  | onWebplayerEnd | @ | application-bf70c2b….js:formatted:43320
  | s | @ | application-bf70c2b….js:formatted:6688
  | trigger | @ | application-bf70c2b….js:formatted:6650
  | onEnded | @ | application-bf70c2b….js:formatted:39009
  | s | @ | application-bf70c2b….js:formatted:6688
  | trigger | @ | application-bf70c2b….js:formatted:6650
  | onAudioEvent_ | @ | application-bf70c2b….js:formatted:38945
  | dispatch | @ | application-bf70c2b….js:formatted:2251
  | m.handle | @ | application-bf70c2b….js:formatted:2191
```


Here's the stack trace redirecting me to adblock wall:
```
  | send | @ | application-bf70c2b….js:formatted:3674
-- | -- | -- | --
  | ajax | @ | application-bf70c2b….js:formatted:3495
  | a.ajax | @ | application-bf70c2b….js:formatted:7302
  | a.sync | @ | application-bf70c2b….js:formatted:7288
  | sync | @ | application-bf70c2b….js:formatted:6745
  | fetch | @ | application-bf70c2b….js:formatted:6838
  | fetch | @ | application-bf70c2b….js:formatted:26151
  | onChangeUrl | @ | application-bf70c2b….js:formatted:26125
  | s | @ | application-bf70c2b….js:formatted:6700
  | trigger | @ | application-bf70c2b….js:formatted:6650
  | set | @ | application-bf70c2b….js:formatted:6783
  | xhrpagesNavigate | @ | application-bf70c2b….js:formatted:25928
  | (anonymous) | @ | application-bf70c2b….js:formatted:8708
  | execute | @ | application-bf70c2b….js:formatted:8755
  | execute | @ | application-bf70c2b….js:formatted:10217
  | navigateToWall | @ | application-bf70c2b….js:formatted:40337
  | disableWebplayerPlayback | @ | application-bf70c2b….js:formatted:40317
  | setWallEnforced | @ | application-bf70c2b….js:formatted:40321
  | (anonymous) | @ | application-bf70c2b….js:formatted:8708
  | execute | @ | application-bf70c2b….js:formatted:8755
  | execute | @ | application-bf70c2b….js:formatted:10217
  | noAdsAvailable | @ | application-bf70c2b….js:formatted:42217
  | onReceiveAds | @ | application-bf70c2b….js:formatted:42134
  | (anonymous) | @ | application-bf70c2b….js:formatted:40668
  | (anonymous) | @ | application-bf70c2b….js:formatted:40943
  | (anonymous) | @ | application-bf70c2b….js:formatted:40975
  | (anonymous) | @ | application-bf70c2b….js:formatted:41911
  | l | @ | application-bf70c2b….js:formatted:1788
  | fireWith | @ | application-bf70c2b….js:formatted:1839
  | n | @ | application-bf70c2b….js:formatted:3390
  | (anonymous) | @ | application-bf70c2b….js:formatted:3656
  | error (async) |   |  
  | send | @ | application-bf70c2b….js:formatted:3665
  | ajax | @ | application-bf70c2b….js:formatted:3495
  | e.get | @ | application-bf70c2b….js:formatted:41898
  | e.get | @ | application-bf70c2b….js:formatted:41673
  | e._parse | @ | application-bf70c2b….js:formatted:40971
  | e.parse | @ | application-bf70c2b….js:formatted:40942
  | e.get | @ | application-bf70c2b….js:formatted:40667
  | (anonymous) | @ | application-bf70c2b….js:formatted:42103
  | l | @ | application-bf70c2b….js:formatted:1788
  | add | @ | application-bf70c2b….js:formatted:1802
  | (anonymous) | @ | application-bf70c2b….js:formatted:42095
  | l | @ | application-bf70c2b….js:formatted:1788
  | add | @ | application-bf70c2b….js:formatted:1802
  | requestAds | @ | application-bf70c2b….js:formatted:42093
  | startAd | @ | application-bf70c2b….js:formatted:42256
  | startAd | @ | application-bf70c2b….js:formatted:42427
  | requestAd | @ | application-bf70c2b….js:formatted:42403
  | requestMidrollAd | @ | application-bf70c2b….js:formatted:42476
  | (anonymous) | @ | application-bf70c2b….js:formatted:8708
  | request | @ | application-bf70c2b….js:formatted:8775
  | request | @ | application-bf70c2b….js:formatted:10220
  | playNextItem | @ | application-bf70c2b….js:formatted:43340
  | (anonymous) | @ | application-bf70c2b….js:formatted:8708
  | execute | @ | application-bf70c2b….js:formatted:8755
  | execute | @ | application-bf70c2b….js:formatted:10217
  | onWebplayerEnd | @ | application-bf70c2b….js:formatted:43320
  | s | @ | application-bf70c2b….js:formatted:6688
  | trigger | @ | application-bf70c2b….js:formatted:6650
  | onEnded | @ | application-bf70c2b….js:formatted:39009
  | s | @ | application-bf70c2b….js:formatted:6688
  | trigger | @ | application-bf70c2b….js:formatted:6650
  | onAudioEvent_ | @ | application-bf70c2b….js:formatted:38945
  | dispatch | @ | application-bf70c2b….js:formatted:2251
  | m.handle | @ | application-bf70c2b….js:formatted:2191
```

@brru8999 @mjcolom-git can you test this filter? `@@||pubads.g.doubleclick.net/gampad/ads*www.di.fm$xhr,domain=di.fm`

**Comment by mjcolom-git** [comment]
@mapx-
with "||pubads.g.doubleclick.net/gampad/ads*www.di.fm$xhr,domain=di.fm,redirect=noopjs" lasted 8 songs before poping up the infamus "Please disable you AdBlocker". 
Interesting

**Comment by llacb47** [comment]
@mapx- this works in chrome and ff: `di.fm##+js(set, di.VAST.XHRURLHandler, noopFunc)`

**Comment by mjcolom-git** [comment]
> 
> 
> this works in chrome and ff: `di.fm##+js(set, di.VAST.XHRURLHandler, noopFunc)`

So far...Rocks in FF ! Many thanks...Got to test it in FF for android.

**Comment by brru8999** [comment]
I can confirm with the following, about 30-45 mins of smooth play.
![image](https://user-images.githubusercontent.com/38956371/89933061-1cbe3a80-dbd4-11ea-864b-17727300a953.png)

**Comment by mjcolom-git** [comment]
Works like a Champ on FF for android too.

**Comment by scalp42** [comment]
@brru8999 can you share the code in the screenshot, bit easier to copy

**Comment by mjcolom-git** [comment]
> 
> 
> @brru8999 can you share the code in the screenshot, bit easier to copy

Only the line #4 is necessary. Your remarks are useful nonetheless.

**Comment by mapx-** [comment]
@brru8999 just an observation: you didn't add correctly my filters => you removed the leading `@@`

**Comment by brru8999** [comment]
`@@||synchrobox.adswizz.com/*gdpr$script,domain=di.fm
@@||cdn.adswizz.com/adswizz/js/SynchroClient2.js$script,domain=di.fm
@@||pubads.g.doubleclick.net/gampad/ads*www.di.fm$xhr,domain=di.fm,redirect=noopjs
di.fm##+js(set, di.VAST.XHRURLHandler, noopFunc)`

**Comment by brru8999** [comment]
`
`@@||synchrobox.adswizz.com/*gdpr$script,domain=di.fm
`@@||cdn.adswizz.com/adswizz/js/SynchroClient2.js$script,domain=di.fm
`@@||pubads.g.doubleclick.net/gampad/ads*www.di.fm$xhr,domain=di.fm,redirect=noopjs
`di.fm##+js(set, di.VAST.XHRURLHandler, noopFunc)

**Comment by brru8999** [comment]
@mapx-

Sorry I deleted in error. They are restored.

**Comment by jspenguin2017** [comment]
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/-/issues/58

**Comment by jspenguin2017** [comment]
@mooman65 Thanks, I got the test account. I'll take a look this weekend when I have more time.

**Comment by jspenguin2017** [comment]
I just tested this, can't reproduce any issue with the latest filters.

**Comment by scalp42** [comment]
It's still happening on my end:

```
! 8/13/2020 https://www.di.fm
@@||synchrobox.adswizz.com/*gdpr$script,domain=di.fm
@@||cdn.adswizz.com/adswizz/js/SynchroClient2.js$script,domain=di.fm
@@||pubads.g.doubleclick.net/gampad/ads*www.di.fm$xhr,domain=di.fm,redirect=noopjs
di.fm##+js(set, di.VAST.XHRURLHandler, noopFunc)
```

![Screen Shot 2020-08-18 at 13 03 39](https://user-images.githubusercontent.com/1475276/90560014-53a3cb80-e153-11ea-8e1e-6c57c9407f10.png)

**Comment by jspenguin2017** [comment]
I couldn't reproduce on the standard setup. Reset your setup back to the standard setup (NA and ND on default settings, no other extensions) and try again.

**Comment by brru8999** [comment]
I had the site up all day today and didn’t get any issues.

**Comment by mooman65** [comment]
Same.  For the last six daysish it's been working fine again: no more anti-adblock wall.

**Comment by scalp42** [comment]
Confirming it's working now 🏆

**Comment by llacb47** [comment]
I think it's back...
