### ISSUE TITLE
[Anti-adblock] file-upload.com

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#219]
**URLs where this issue occurs (Required)**
After clicking on free download on the site.
https://www.file-upload.com/lw926zansi6j  

**Screenshots (Required)**
![capture bb](https://user-images.githubusercontent.com/43067841/48179330-db3a9480-e348-11e8-82e6-e89dffb6b72d.JPG)

Environment (Required)

    Operating System and Version: Windows 10 Pro
    Browser and Version: Chrome
    Nano Adblocker Version: 1.0.0.74
    Nano Defender Version : 15.0.0.71

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/48206218-1cbc4700-e32b-11e8-840b-fd8d21beea61.png)

**Comment by okiehsch** [comment]
Fixed.
