### ISSUE TITLE
NSFW! [Popup, Anti-adblock] asianclub.tv

### ISSUE THREAD

**Issue by frenzyoutlook** [NanoAdblocker/NanoFilters#220]
### URLs where this issue occurs (Required)
https://asianclub.tv/v/p6og6x1zxvj

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/45134737/48667868-db076b00-eaa5-11e8-8d3a-4fded2cf9e8d.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/45134737/48667874-173acb80-eaa6-11e8-8ba0-92166ee0bbf7.png)

### Describe the issue (Optional if obvious)
Upon first viewing of the webpage, the video player would load and streaming the video perfectly fine.

However, upon any subsequent visit to the same webpage (or to any other links under the asianclub.tv domain), all additional attempts at streaming videos via the video player on page would lead to an anti-adblocker message as seen in the screenshot above.

### Reproduction Steps (Optional if trivial)
1. Open the webpage via the url above
2. Wait for the webpage to load the video player
3. Click anywhere on the video player to allow the pop ups to open
4. Once you can interact with the video player, click on the "play" button that's overlaid on top of the video player
4. Wait for the video player to load the video
6. Once the video player starts to stream the video, refresh the webpage
7. Wait for the video player to load again
8. Click anywhere on the video player to allow the pop ups to open
9. Once the pop ups have opened, you should be able to interact with the video player and click on the "play" button
7. Now, the video would stream for 1 or 2 seconds but the video would then be quickly replaced by a message that says: "please turn off adblocker to continue watching"

#### Environment (Required)
- Operating System and Version: 
macOSX Mojave
Version 10.14.1

- Browser and Version: 
Google Chrome
Version 70.0.3538.102 (Official Build) (64-bit)

- Nano Adblocker Version: 
Nano Adblocker 1.0.0.77

- Nano Defender Version (Optional if you are not using it): 
Nano Defender Version 15.0.0.73

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/45134737/48667919-3d14a000-eaa7-11e8-97ba-0e068a134b9c.png)

#### Your custom filters (Required if you have any)
No custom filters

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock. It has a popup though. @okiehsch

**Comment by frenzyoutlook** [comment]
@jspenguin2017 Thank you for the quick reply!

There are a couple popups overlaid on top of the video player. 

However, once you click on the video player on the page and allow those popups to open on your browser, you should then be able to play the video and reproduce the anti-adblock issue.

i.e.
1. click video players and allow the popups to open
2. click on the player button and allow the video player to stream the video
3. refresh the webpage and repeat steps 1 and 2 above 

I will update the repro steps above, and hopefully this will make your triage easier.

thanks for your time to look into the issue and your help!

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
@frenzyoutlook Works fine for me. Refreshed multiple times.

**Comment by jspenguin2017** [comment]
Tested on Windows and Ubuntu, can't reproduce. It is likely a problem on your side.

**Comment by jspenguin2017** [comment]
Oh weird, now I can reproduce. Looks like it's a magic variable served from a XHR.

**Comment by jspenguin2017** [comment]
@okiehsch After 5~10 refreshes, the server will serve a XHR with different flags. I assume it's IP based. Can you reproduce? 
![image](https://user-images.githubusercontent.com/7283682/48668370-d09aa080-eaa8-11e8-8fb1-eaa6c3bc111e.png)

**Comment by okiehsch** [comment]
Yes.
