### ISSUE TITLE
[Annoyance, Cookie Wall] wikia.com, fandom.com

### ISSUE THREAD

**Issue by krystian3w** [NanoAdblocker/NanoFilters#221]
### URLs where this issue occurs (Required)

```
http://www.wikia.com/
http://elderscrolls.wikia.com/wiki/The_Elder_Scrolls_Wiki
https://gta.fandom.com/wiki/Main_Page
```

### Screenshots (Required)

![image](https://user-images.githubusercontent.com/35370833/48695163-b06cfd80-ebde-11e8-89c9-bb81a7f1cab9.png)  | ![image](https://user-images.githubusercontent.com/35370833/48694991-245ad600-ebde-11e8-86ad-ebed16d73e58.png) | ![image](https://user-images.githubusercontent.com/35370833/48695034-4f452a00-ebde-11e8-9210-1061452baa4d.png) 
:---: | :---: | :---:
`www.wikia.com` |  `elderscrolls.wikia.com` | `gta.fandom.com`

### Screenshot of console (Required, press `F12` to open the console)

N/A [](https://github.com/MajkiIT/polish-ads-filter/issues/9946)

### Describe the issue (Optional if obvious)

Without click: 
<kbd>ACCEPT ADVERTISING COOKIES</kbd> / <kbd>REJECT ADVERTISING COOKIES</kbd>

no possible see video on `http://fandom.wikia.com/video`

<ul>

###### AdGuard scripts solution (recject advertisement cookies):

- `fandom.com#%#document.cookie = "tracking-opt-in-status=rejected";`

   cookies_specific.txt[#L1720](https://github.com/AdguardTeam/AdguardFilters/blob/45af1b823f56b3e90c82007f2362442261111732/AnnoyancesFilter/sections/cookies_specific.txt#L1720)
- `wikia.com#%#document.cookie = "tracking-opt-in-status=rejected";`

    cookies_specific.txt[#L1752](https://github.com/AdguardTeam/AdguardFilters/blob/45af1b823f56b3e90c82007f2362442261111732/AnnoyancesFilter/sections/cookies_specific.txt#L1720)

###### Script click solution (accept advertisement cookies):

```js
if(url.match(/wikia.com/) || url.match(/fandom.com/))
{
    document.addEventListener("DOMContentLoaded", function(event) {
        var btnYes = document.body.querySelector('[data-tracking-opt-in-accept="true"]');
        if (btnYes)
        {
            btnYes.click();
        }
    });
}
```

</ul>

### Reproduction Steps (Optional if trivial)

Open with European IP and should see cookies / advertisement wall

#### Environment (Required)

- Operating System and Version: Windows 7
- Browser and Version: Opera 56
- Nano Adblocker Version:  1.0.0.77
- Nano Defender Version (Optional if you are not using it): 15.0.0.74

#### Your filter lists (Required)

Nano Adblocker default + uBO Annoyance + Nano Annoyance + Nano Defender Integration

#### Your custom filters (Required if you have any)

both work:

`fandom.wikia.com,www.wikia.com##+js(cookie-remover.js, Geo)`

but this no works on other subdomains `wikia.com` / `fandom.com`

**Comment by jspenguin2017** [comment]
I can write cookies with privileged script snippets. But since this cookie wall gives the user a choice, I'll put this as `under consideration` for now. 

See: https://github.com/NanoAdblocker/NanoFilters/issues/124#issuecomment-403667249

**Comment by hawkeye116477** [comment]
Maybe just create another filterlist which contains rules which accepts all things.

**Comment by krystian3w** [comment]
and I have probably incorrectly copied the latest domain names for cookies.

It's like two and it's still easy to make a mistake.
