### ISSUE TITLE
icdrama.to

### ISSUE THREAD

**Issue by klingon888** [NanoAdblocker/NanoFilters#222]
http://icdrama.to/watch-online-survivor-s-law-2-episode-15-19541.html

![image](https://user-images.githubusercontent.com/30375535/48811138-5a8d7800-ecfa-11e8-957d-9effbd563881.png)

![image](https://user-images.githubusercontent.com/30375535/48811088-2914ac80-ecfa-11e8-8a07-65b345de0035.png)

### Reproduction Steps (Optional if trivial)
Open the Url and anti-adblock msg comes up

#### Environment (Required)

- Operating System and Version: Linux Mint 19 Cinnamon
- Browser and Version: Chrome Version 70.0.3538.102 (Official Build) (64-bit)
- Nano Adblocker Version: Ublock Origin 1.17
- Nano Defender Version (Optional if you are not using it): 15.0.0.74

#### Your filter lists (Required)
Std Ublock + Nano Defender for Ublock Origin

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/48813315-8a854d00-ecf3-11e8-88ad-6b0c6f1a65b2.png)

**Comment by klingon888** [comment]
It seems to be caused by EasyList.  When I disable EasyList, ads show up at the beginning of the show. Enable EasyList and the anti-adblocker msg back.

**Comment by mapx-** [comment]
added, however I'm able to reproduce the anti adb issue, so fixed

**Comment by klingon888** [comment]
Thank you. Your fix worked. Purged cache, refreshed and no more anti block msg.
