### ISSUE TITLE
ouest-france.fr

### ISSUE THREAD

**Issue by Francois-dag** [NanoAdblocker/NanoFilters#223]
https://www.ouest-france.fr/

Some links like "Comunes" does not work, the target seems to be "Javascript: ;"

I'm currently using 15.0.0.75 on firefox with last uBo but the problem remains the same using
chrome.

cheers !

**Comment by jspenguin2017** [comment]
Works fine for me. Closing as invalid as you have not filled the template. 
![image](https://user-images.githubusercontent.com/7283682/48945886-29bf6580-eee9-11e8-8b5f-2bb04e1705f8.png)
