### ISSUE TITLE
[Anti-adblock] hdblog.it

### ISSUE THREAD

**Issue by FrancYescO** [NanoAdblocker/NanoFilters#224]
### URLs where this issue occurs (Required)
https://www.hdblog.it/2018/11/29/banda-ultra-larga-fibra-aree-bianche-nessuna-tlc/

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/4574593/49229132-2cd8bb00-f3ed-11e8-835d-a49d63939d0b.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/4574593/49229256-64dffe00-f3ed-11e8-8db3-8c5a9f8de2f5.png)

#### Environment (Required)

- Operating System and Version: macos 10.14.1
- Browser and Version: Chrome 70.0.3538.110 
- Nano Adblocker Version: ublock 1.17.0
- Nano Defender Version (Optional if you are not using it): 15.0.0.79

#### Your filter lists (Required)
![image](https://user-images.githubusercontent.com/4574593/49229315-87721700-f3ed-11e8-8f47-001a408d0b77.png)

**Comment by mapx-** [comment]
Did you update ublock filters ?

**Comment by FrancYescO** [comment]
@mapx- forceupdated now and is working, thanks.
