### ISSUE TITLE
[Anti-adblock] dorama.site

### ISSUE THREAD

**Issue by surya27895** [NanoAdblocker/NanoFilters#226]
### Screenshots (Required)
![image](https://i.imgur.com/3KcHYT2.jpg)
### Screenshot of console (Required, press `F12` to open the console)

![image](https://i.imgur.com/OuCvxTw.jpg)
### Describe the issue (Optional if obvious)

the adblocker detected by the anti-adblock

#### Environment (Required)

- Operating System and Version:  Windows 10 Pro x64, 1803 build 17134.471
- Browser and Version: Google Chrome 71.0.3578.98 x64
- Nano Adblocker Version:  1.0.0.82
- Nano Defender Version (Optional if you are not using it):  15.0.0.81

#### Your filter lists (Required)
96,365 network filters ＋ 50,010 cosmetic filters from:
 My filters​​​​​14 used out of 15​​​​
Built-in (8/11)
Nano Defender Integration​​​​​2,621 used out of 2,675​​​​
Nano filters​​​​​169 used out of 170​​​​
Nano filters – Whitelist​​​​​1 used out of 1​​​​
uBlock filters​​​​​11,544 used out of 11,547​​​​
uBlock filters – Badware risks​​​​​48 used out of 48​​​​
uBlock filters – Privacy​​​​​157 used out of 158​​​​
uBlock filters – Resource abuse​​​​​286 used out of 287​​​​
uBlock filters – Unbreak​​​​​732 used out of 734​​​​
Ads (2/4)
Adblock Warning Removal List​​​​​586 used out of 604​​​​
EasyList​​​​​86,258 used out of 86,490​​​​
Privacy (1/3)
EasyPrivacy​​​​​15,786 used out of 15,980​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,095 used out of 1,110​​​​
Malware domains​​​​​26,858 used out of 26,858​​​​
Annoyances (0/5)
Multipurpose (1/5)
Peter Lowe's Ad and tracking server list​​​​​2,921 used out of 2,922​​​​
Regions, languages (1/38)
IDN, MYS: ABPindo​​​​​4,822 used out of 4,842​​​​

**Comment by jspenguin2017** [comment]
@mapx-
