### ISSUE TITLE
[Anti-adblock] vod.tvp.pl

### ISSUE THREAD

**Issue by MeDeVILe** [NanoAdblocker/NanoFilters#227]
### URLs where this issue occurs (Required)
https://vod.tvp.pl/video/ojciec-mateusz,odc-264-powolanie,40221041

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/6697190/50108834-8850d880-0236-11e9-965e-a757ef98a812.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/6697190/50108918-afa7a580-0236-11e9-9cee-c7cb1ae279e0.png)

### Anything else you believe to be useful (Optional)
Prabobly geoblocked so VPN needed

#### Environment (Required)

- Operating System and Version: Linux Mint 19
- Browser and Version: Google Chrome 71.0.3578.98
- Nano Adblocker Version: 1.0.0.83
- Nano Defender Version (Optional if you are not using it): 15.0.0.81

#### Your filter lists (Required)

Nano Defender Integration
Nano filters​​​​​
Nano filters – Whitelist
uBlock filters​​​​​
uBlock filters – Badware risks​​​​​
Block filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​u
uBlock filters – Unbreak​​​​​
Adblock Warning Removal​​​​
EasyList​​​​​
EasyPrivacy​​​​
Malware Domain 
Malware domains​​​​​
Anti-Facebook 
Peter Lowe's Ad and tracking server
Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda​​​​​
Nano filters – Timer bypassing (sometimes works)​​​​​
Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for uBlock Origin​​​​​

**Comment by mapx-** [comment]
It seems to be fixed in 
`POL: Oficjalne polskie filtry przeciwko alertom o Adblocku`
