### ISSUE TITLE
[Popups] naturalbd.com, ihub.live

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#228]
### URLs where this issue occurs (Required)
http://www.naturalbd.com/
http://ihub.live

### Describe the issue (Optional if obvious)
1st time Clicking on any link in the webpage takes you to ads/pop up links.
Redirect to different ads site.

    Operating System and Version: Windows 10 Pro 1803
    Browser and Version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
    Nano Adblocker Version: 1.0.0.75
    Nano Defender Version (Optional if you are not using it): 15.0.0.81

**Comment by mapx-** [comment]
I get no popup, redirection, even if the malicious code is arriving from
`policityseriod.info`

add
`||policityseriod.info^`

**Comment by Joyer1234** [comment]
Did you click on any links on the page? Try to download a movie,  It opens a New tab with ads site.
Same thing happens if you reload the page.

**Comment by mapx-** [comment]
Did you try the filter above ?

**Comment by Joyer1234** [comment]
> 
> 
> Did you try the filter above ?

Yes, didn't do anything for me.

**Comment by mapx-** [comment]
Test separately these filters
```
ihub.live,naturalbd.com##+js(abort-on-property-read.js, encodeURIComponent)
||info$script,domain=ihub.live|naturalbd.com
```

**Comment by Joyer1234** [comment]
Wow.

This worked.
ihub.live,naturalbd.com##+js(abort-on-property-read.js, encodeURIComponent)

This doesn't do anything.
||info$script,domain=ihub.live|naturalbd.com
