### ISSUE TITLE
[Anti-adblock] ilpuntotecnico.com

### ISSUE THREAD

**Issue by MarioLinoTuttoAttaccato** [NanoAdblocker/NanoFilters#229]
### URLs where this issue occurs (Required)

https://repository.ilpuntotecnico.com/files/

### Screenshots (Required)
Look below the link....
### Screenshot of console (Required, press `F12` to open the console)
https://i.imgur.com/4VVuBlP.png?1

### Describe the issue (Optional if obvious)
It's need to be registered to forum to access this page..... after login on forum you can access to repository and immediatelly after it's appears this message.

#### Environment (Required)

- Operating System and Version: Windows 10 Home Last Build
- Browser and Version: Chrome 70.0.3538.77
- Nano Adblocker Version: 1.0.0.83
- Nano Defender Version (Optional if you are not using it): 15.0.0.81

#### Your filter lists (Required)
From default setup i have enabled only -> ITA EasyList

Thanks in advance....... i have also tryed to use Firefox when i have Ublock + NanoDefender setup.
Apparently there's same issue... it's NanoDefender relevated.... block..

**Comment by jspenguin2017** [comment]
I need a test account, send a private message here, with reference `229`: https://legacy.hugoxu.com/PrivateMessage/

Alternatively, you can open a confidential issue here: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues

**Comment by MarioLinoTuttoAttaccato** [comment]
Ok... i thinks i can register a new account on forum for test it. 
If need to activate access to repo i thinks i can also activate it.
Wait the info of this account.............

**Comment by DjDiabolik** [comment]
I thinks i can help....... if i use correctly the Reference upper here.

**Comment by jspenguin2017** [comment]
@DjDiabolik The test account does not seem to work.

**Comment by DjDiabolik** [comment]
mmmmmmm.. strange... it's my credentials and it's impossible not works. 
Are you sure have inserted whit correctly uppercase ?
This upper links.... issue/38 it's not works... it's say error 404.

**Comment by jspenguin2017** [comment]
If the issue gives you 404 it means you don't have the privilege to view it.

**Comment by jspenguin2017** [comment]
It doesn't work for me. I'm sure I copied the credentials correctly. 

![image](https://user-images.githubusercontent.com/7283682/51362921-c7bb5080-1a92-11e9-920f-c78e4288db01.png)

**Comment by DjDiabolik** [comment]
mmmmmm.... have you need before to access on main forum home.
After you have access to main forum you can acess on repository.
If you try to login directly on repository links apparently there's no works..... i thinks for a cookie issue or somethings similar.

Try to login here before:
https://www.ilpuntotecnico.com/forum/index.php

**Comment by mapx-** [comment]
fixed

**Comment by jspenguin2017** [comment]
Alright closing.
