### ISSUE TITLE
[Popup] bdiptv.stream

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#231]
URLs where this issue occurs (Required)

http://www.bdiptv.stream/index.html

Describe the issue (Optional if obvious)
1st time Clicking on video in the webpage takes you to ads/pop up links.

Redirect to this popup 
http://i62e2b4mfy.com/pqnrqeegx?key=0f22c1fd609f13cb7947c8cabfe1a90d&psid=14335761

Operating System and Version: Windows 10 Pro 1803
Browser and Version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Nano Adblocker Version: 1.0.0.75
Nano Defender Version (Optional if you are not using it): 15.0.0.81

**Comment by mapx-** [comment]
fixed
