### ISSUE TITLE
[Anti-adblock] douploads.com

### ISSUE THREAD

**Issue by andrewxyxyxy** [NanoAdblocker/NanoFilters#232]
### URLs where this issue occurs (Required)

https://douploads.com/65kw7821mhxn

### Screenshots (Required)

![screenshot_2018-12-21 douploads - upload files earn money](https://user-images.githubusercontent.com/26189057/50343181-42419080-0526-11e9-9cd8-69ce6cce4189.png)

### Screenshot of console (Required, press `F12` to open the console)

![console](https://user-images.githubusercontent.com/26189057/50343389-f0e5d100-0526-11e9-80b7-ec65117f35e8.png)

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Firefox 64.0
- uBlock Version: 1.17.4
- Nano Defender Version (Optional if you are not using it): 15.0.0.81

#### Your filter lists (Required)

Adblock Warning Removal List
EasyList

**Comment by mapx-** [comment]
You should update ublock filters (purge caches + update now) and test again

**Comment by patrickdrd** [comment]
it was opened by me (and fixed in ublock filters) some days ago:
https://github.com/uBlockOrigin/uAssets/issues/4349#event-2037050308
