### ISSUE TITLE
[Anti-adblock] vizer.tv

### ISSUE THREAD

**Issue by xitero** [NanoAdblocker/NanoFilters#238]
### Describe the issue (Required)
I can not click on any button on the site, either to search or to log into my account. When I click, I'm redirected to the following link: `http://udriveme2.com/show?bver=1&refer=http%3A%2F%2Fvizer.tv%2F&kw=%5B%22vizer%22%2C%22tv%22%2C%22-%22%2C%22assistir%22%2C%22filmes%22%2C%22e%22%2C%22s%C3%A9ries%22%2C%22online%22%2C%22hd%22%5D&key=50ebb83f8c66e52e9767a508f92d5dad&scrWidth=1920&scrHeight=1080&tz=-3&ship=&pst=&res=4.31&dev=r&psid=var2_f`

After pressing F5 a few times, the problem is resolved and I can access other pages from that same site normally. However, the problem returns some time later during the use of the site. When I use Adblock Plus, this problem does not occur. The only relation to this I found was the following link where the specified domain above is on this list:
```
||udriveme2.com^$third-party
https://easylist-downloads.adblockplus.org/liste_fr+easylist.txt
```

### Screenshots (Required)
https://prnt.sc/iwawuv (Look at the image on the lower left side)

### Screenshot of console (Required, press `F12` to open the console)
http://prntscr.com/iwb230
https://prnt.sc/iwb113

### URLs where this issue occurs (Required if applicable)
http://vizer.tv/

### Reproduction Steps (Optional if trivial)
Just open the site, close the screen asking to enjoy facebook and wait a few seconds and then try clicking on any area of the site.

#### Environment (Required)

- Operating System and Version: Windows 10 1709 16299.309
- Browser and Version: Google Chrome 65.0.3325.181 64 bits
- Nano Adblocker Version: 1.0.0.37
- Nano Defender Version: 13.49

**Comment by bogachenko** [comment]
@okiehsch @mapx-
https://vizer.tv/assistir/filme/captain-marvel
popup shit
![1](https://user-images.githubusercontent.com/8535285/54508572-263f6680-493e-11e9-9101-6408eeb4e0fc.gif)

**Comment by bogachenko** [comment]
it seems fixed like this 
`vizer.tv##+js(window.open-defuser.js)`
