### ISSUE TITLE
[Annoyance] hayate.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoFilters#247]
### URLs where this issue occurs (Required)

`http://hayate.pl/projects/fma_prototype/1/1/view#1`

### Screenshots (Required)
![2018-12-22-fullmetal alchemist_ prototype - tom 1 - oneshot 1 - fullmetal alchemist_ protot](https://user-images.githubusercontent.com/5884000/50370011-2e864080-059f-11e9-992e-f4cdf98070f3.png)

if i use other extension to download then
![1](https://user-images.githubusercontent.com/5884000/50370025-67261a00-059f-11e9-8f15-f38196892ca9.jpg)

### Describe the issue (Optional if obvious)

anti-right-click,
anti-copy

#### Environment (Required)

- Operating System and Version: w10, stable, latest 
- Browser and Version: chr, stable, latest
- Nano Adblocker Version: **
- Nano Defender Version (Optional if you are not using it): stable, latest

#### Your filter lists (Required)
https://gist.github.com/KonoromiHimaries/9bc55fcafd3fab612f1f8dfa59f8f572

**Comment by jspenguin2017** [comment]
It is scrambled on the server side. 
This does not really fit into the scope of Nano Filters, so probably won't fix.

**Comment by jspenguin2017** [comment]
Yea, won't fix. This is not client side JavaScript based anti-copy.
