### ISSUE TITLE
[Anti-adblock] live.bdiptv.stream

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#248]
**### URLs where this issue occurs (Required)**
http://live.bdiptv.stream/tv/43

**Describe the issue (Optional if obvious)**

ad block sign on the video.

**Environment (Required)**

- Operating System and Version: Windows 10 Home Last Build
- Browser and Version: Chrome 70.0.3538.77
- Nano Adblocker Version: 1.0.0.83
- Nano Defender Version (Optional if you are not using it): 15.0.0.81

**Comment by jspenguin2017** [comment]
Can't reproduce. Screenshot?

**Comment by mapx-** [comment]
I removed a csp filter (breaking streaming), but I get no anti adb stuff
