### ISSUE TITLE
[Anti-adblock] dn.se

### ISSUE THREAD

**Issue by benjick** [NanoAdblocker/NanoFilters#249]
### URLs where this issue occurs (Required)

https://www.dn.se/nyheter/varlden/trump-skyller-barnens-dod-pa-demokraterna/

### Screenshots (Required)
<img width="966" alt="screenshot 2018-12-29 at 21 38 59" src="https://user-images.githubusercontent.com/430872/50542000-2dae6980-0bb2-11e9-867f-f0dbcb93c9c2.png">

### Screenshot of console (Required, press `F12` to open the console)
<img width="516" alt="screenshot 2018-12-29 at 21 39 59" src="https://user-images.githubusercontent.com/430872/50542008-55053680-0bb2-11e9-8dfd-43fbb09fb40b.png">

#### Environment (Required)

- Operating System and Version: OSX 10.14
- Browser and Version: Chrome 71
- Nano Adblocker Version: 1.0.0.83
- Nano Defender Version (Optional if you are not using it): 15.0.0.82

#### Your filter lists (Required)
Defaults, pasted below:

94,155 network filters ＋ 47,591 cosmetic filters from:
 My filters​​​​​ 0 used out of 0​​​​
Built-in (8/11)
Nano Defender Integration​​​​​2,557 used out of 2,675​​​​
Nano filters​​​​​ 169 used out of 171​​​​
Nano filters – Whitelist​​​​​1 used out of 1​​​​
uBlock filters​​​​ ​11,581 used out of 11,642​​​​
uBlock filters – Badware risks​​​​​48 used out of 48​​​​
uBlock filters – Privacy​​​​​154 used out of 158​​​​
uBlock filters – Resource abuse​​​​​160 used out of 287​​​​
uBlock filters – Unbreak​​​​​710 used out of 736​​​​
Ads (2/5)
Adblock Warning Removal List​​​​​601 used out of 607​​​​
EasyList​​​​​ 86,499 used out of 86,615​​​​
Privacy (1/3)
EasyPrivacy​​​​​ 15,972 used out of 16,019​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,095 used out of 1,110​​​​
Malware domains​​​​​26,858 used out of 26,858​​​​
Annoyances (0/5)
Multipurpose (1/5)
Peter Lowe's Ad and tracking server list​​​​​
2,939 used out of 2,939​​​​

**Comment by mapx-** [comment]
fixed in the regional list

**Comment by benjick** [comment]
Sorry, thanks!
