### ISSUE TITLE
[Ads] cwtv.com

### ISSUE THREAD

**Issue by Warren1001** [NanoAdblocker/NanoFilters#25]
cwtv.com seems to be testing a new player which embeds ads into the player and will not let you skip past them. It appears the newest episodes of Riverdale and The Flash are the only shows using the new player at the time. You can tell by the &extended segment of text at the end of the link.

http://www.cwtv.com/shows/riverdale/chapter-twenty-five-the-wicked-and-the-divine/?play=130737d1-b003-42c1-9ac7-a31ecb2cd438&extended
http://www.cwtv.com/shows/the-flash/honey-i-shrunk-team-flash/?play=10cd69da-0e4b-4767-a88b-8abad1464c5d&extended

Here is the new episode of The Flash using the new player: https://gyazo.com/b0f9b841b69e069f3185c0f8a42459b9
And here is the newest episode of Dynasty, which does not use the new player (and adblock works on):
https://gyazo.com/5984ae73e1aa4496f9c299ba3a482ec5

https://gyazo.com/9aadd12cf23ae73b4a6a8a9f424a9a75

Simply attempt to watch the above links. At the time of writing they are the only two to use the new player. Ctrl + F5 may be required if you have already watched these specific episodes prior to today.

- Operating System and Version: Windows 10 Pro, Version 1709, OS Build 16299.192
- Browser and Version: Chrome Version 64.0.3282.140 (Official Build) (64-bit)
- Nano Adblocker Version: Nano Adblocker v1.0.0.28

https://gyazo.com/f10ae5f44683509c92065578bdc2eed3
All region disabled, no custom lists.

No custom filters.

**Comment by jspenguin2017** [comment]
Could be related to https://github.com/jspenguin2017/uBlockProtector/issues/660
We are falling behind in the arm race. We don't have a good system to remove ads that are baked into video stream.

**Comment by Warren1001** [comment]
Clever the steps they've taken to avoid adblockers. Most viable solution at the moment may be to simply find a version of the video somewhere on the internet that only has the video content, like some various streaming website. Shame as those are typically lower quality. Unfortunately I have nothing to contribute to the arms race, so I wish you luck in potentially cracking this beast.

**Comment by Ravizz** [comment]
I'm geo-locked.

**Comment by ghajini** [comment]
No video ads as of now

**Comment by jspenguin2017** [comment]
See https://github.com/uBlockOrigin/uAssets/issues/1905
