### ISSUE TITLE
[Annoyance] ffmovies.ru

### ISSUE THREAD

**Issue by jb241** [NanoAdblocker/NanoFilters#251]
### URLs where this issue occurs (Required)
`https://ffmovies.ru`

### Screenshots (Required)
![untitled](https://user-images.githubusercontent.com/27972350/50575167-7b032480-0dc6-11e9-85d4-9efbf6338f8c.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![capture](https://user-images.githubusercontent.com/27972350/50575168-80606f00-0dc6-11e9-940b-61c3694e7a64.JPG)

### Describe the issue (Optional if obvious)

Popup multiple times on the right corner of browser.

#### Environment (Required)

- Operating System and Version: Windows 10 Pro x64 v1803
- Browser and Version: Mozilla Firefox 64.0
- uBlock Origins 1.17.4
- Nano Defender 15.0.0.80

#### Your filter lists (Required)

![capture1](https://user-images.githubusercontent.com/27972350/50575183-ecdb6e00-0dc6-11e9-8a03-3f8f52031b58.JPG)

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/50575352-27d7a480-0dbb-11e9-9e08-b9c2fea86170.png)

**Comment by mapx-** [comment]
maybe a consequence of using other blocking stuff  (noscript / scriptsafe) ?

**Comment by jb241** [comment]
Disabled all other blockers except for uBlock w/ Nano Defender. Problem still persists.
