### ISSUE TITLE
[Annoyance] mixcloud.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoFilters#255]
### Describe the issue

https://github.com/uBlockOrigin/uAssets/issues/4554

popup if i try to close this card

### Screenshot(s)

![2019-01-06-window](https://user-images.githubusercontent.com/5884000/50735893-e463a880-11b5-11e9-93b8-89aa38ee090a.png)

sugested rule
`mixcloud.com##+js(addEventListener-defuser.js, beforeunload)`

### Details

- Browser/version: latest, stable
- uBlock Origin version: latest, stable

https://gist.github.com/KonoromiHimaries/9bc55fcafd3fab612f1f8dfa59f8f572

**Comment by jspenguin2017** [comment]
This is out of scope as per current filter policy.

**Comment by KonoromiHimaries** [comment]
https://github.com/yourduskquibbles/webannoyances/commit/3bbaab2512036a45179ba4b2b65805c49aa047a4
