### ISSUE TITLE
[Anti-adblock] bdix.org

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#259]
### URLs where this issue occurs (Required)
After login to this site.
https://www.bdix.org/index.php

Environment (Required)

    Operating System and Version: Windows 10 Pro
    Browser and Version: Chrome
    Nano Adblocker Version: 1.0.0.74
    Nano Defender Version (Optional if you are not using it): 15.0.0.87

**Comment by jspenguin2017** [comment]
I don't see anything wrong. 
![image](https://user-images.githubusercontent.com/7283682/51420792-a28e1700-1b52-11e9-8f1f-3847fd059bf0.png)

**Comment by LiCybora** [comment]
Possibly fixed in LiCybora/NanoDefenderFirefox#94

Also mind the adblocker and defender version...

**Comment by Joyer1234** [comment]
This fixes the issue for me.
@@||bdix.org^$generichide

**Comment by jspenguin2017** [comment]
Works fine with latest filters. You need to keep your stuff up to date.
