### ISSUE TITLE
Reddit Alpha PROMOTED

### ISSUE THREAD

**Issue by Emilylove00** [NanoAdblocker/NanoFilters#26]
https://imgur.com/a/9QNgH

For some days now reddit show PROMOTED content.

Its the new reddit design*

**Comment by jspenguin2017** [comment]
Need test link.

**Comment by Emilylove00** [comment]
Only link i know is this. https://www.reddit.com/r/redesign/ I was asked and joined the new design.

**Comment by Emilylove00** [comment]
Op! found it! https://alpha.reddit.com/

**Comment by jspenguin2017** [comment]
Can't reproduce. Closing as invalid due to the lack of template.
