### ISSUE TITLE
[Annoyance] fanfiction.net

### ISSUE THREAD

**Issue by DandelionSprout** [NanoAdblocker/NanoFilters#260]
### URLs where this issue occurs (Required)

`https://www.fanfiction.net/s/2945837/1/Halflife-Fulllife-Consequences`

### Screenshots (Required)

(Not applicable, as the issue is invisible.)

### Screenshot of console (Required, press `F12` to open the console)

![image](https://user-images.githubusercontent.com/22780683/51451719-eb062a00-1d36-11e9-8d85-e744921b9b52.png)

### Describe the issue (Optional if obvious)

Seeing that https://github.com/NanoAdblocker/NanoFilters#filter-policy lists 'Hostile anti-copy' as a feasible criteria, I hereby propose a filter entry to remove such a mean feature on `fanfiction.net`, that prevents me from copying text from that site's fanfictions.

### Reproduction Steps (Optional if trivial)

1) Go to `https://www.fanfiction.net/s/2945837/1/Halflife-Fulllife-Consequences`.
2) Try to copy text, and see that nothing gets selected, due to the element having a `nocopy` element value.

### Anything else you believe to be useful (Optional)

I've had a fix for this in my personal filters for some weeks now, in the form of `fanfiction.net##.storytextp:style(user-select: text !important)`. I therefore hereby propose adding that entry to whichever one of your lists.

#### Environment (Required)

Operating System and Version: Windows 10 October 2018 Update (Last installed update: KB4480116)
Browser and Version: Chrome 71.0.3578.98 64-bit
Nano Adblocker Version: 1.0.0.83
Nano Defender Version (Optional if you are not using it): 15.0.0.87

#### Your filter lists (Required)

(Not applicable, as far as I can personally determine.)

#### Your custom filters (Required if you have any)

(This issue was tested without my personal custom filters.)

**Comment by jspenguin2017** [comment]
@okiehsch FYI

**Comment by okiehsch** [comment]
Fixed.

**Comment by theinstantmatrix** [comment]
@okiehsch can you apply this same fix to `fictionpress.com` as well? both sites have the same structure, only difference is that fictionpress only hosts original stories

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/83da8487d04f8e63ba69e2e5f1f919e24b505035
