### ISSUE TITLE
[Anti-adblock] topflix.tv

### ISSUE THREAD

**Issue by xitero** [NanoAdblocker/NanoFilters#263]
### URLs where this issue occurs (Required)
https://topflix.tv/series/assistir-online-sons-of-anarchy/#/

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/28655175/51946785-c9c5cd80-2409-11e9-94fd-bb2463e29d1c.png)
Just choose an episode and try to watch, you will receive this screen.

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/28655175/51946859-0f829600-240a-11e9-8248-a7d9fdd6ed65.png)
****

#### Environment (Required)

- Operating System and Version: Windows 10 1809
- Browser and Version: Google Chrome 72.0.3626.81
- Nano Adblocker Version: 1.0.0.86

- Nano Defender Version (Optional if you are not using it): 15.0.0.89

#### Your filter lists (Required)
<!--
List filters you have enabled or disabled from the default settings.
Default Settings

**Comment by jspenguin2017** [comment]
@okiehsch FYI. Tried Portuguese regional filter.

**Comment by okiehsch** [comment]
Fixed.
