### ISSUE TITLE
[Anti-adblock] free-mp3-download.net

### ISSUE THREAD

**Issue by Shinzawaii** [NanoAdblocker/NanoFilters#264]
### URLs where this issue occurs (Required)
https://free-mp3-download.net

### Screenshots (Required)
![https://i.imgur.com/8LtrB4U.png](https://i.imgur.com/8LtrB4U.png)

### Screenshot of console (Required, press `F12` to open the console)
![](https://i.imgur.com/ooZVd5J.png)

#### Environment (Required)

- Operating System and Version: W10 (up to date)
- Browser and Version: Chrome 73.0.3679.0 (up to date)
- Nano Adblocker Version: uBlock origin 1.18.2
- Nano Defender Version (Optional if you are not using it): 15.0.0.89

#### Your filter lists (Required)
![](https://i.imgur.com/cMo5Qdw.png)

Thanks for taking a look.

**Comment by mapx-** [comment]
fixed

**Comment by Shinzawaii** [comment]
Much obliged, however it doesn't seem fixed on my end (yet).. Updated lists and restarted browser, there's no custom snippet I should add to my filters right?

**Comment by mapx-** [comment]
probably the list wasnìt updated (did you purge / update ?)

add those filters as custom ones, see if works for you

**Comment by Shinzawaii** [comment]
It does, thanks again!

**Comment by bogachenko** [comment]
@mapx- again

**Comment by mapx-** [comment]
I cannot reproduce FF / chrome

**Comment by mapx-** [comment]
probably fixed here:
https://github.com/uBlockOrigin/uAssets/commit/476e3df23e677fd2c339943e8216c48701e960b7

**Comment by bogachenko** [comment]
seems to be working. By the way, you can not put all php on nooptext on this site?
does not seem to break, I hope @mapx-

**Comment by bogachenko** [comment]
because they soon? rename it again
