### ISSUE TITLE
[Breakage] pandora.com

### ISSUE THREAD

**Issue by det427** [NanoAdblocker/NanoFilters#265]
### URLs where this issue occurs (Required)
Pandora.com
Please use the domain as the title
-->Pandora.com

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/32418037/52178643-fe2ce700-2785-11e9-8dcc-9ae0fc4aa270.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/32418037/52178680-55cb5280-2786-11e9-8d66-259de1a8fbcb.png)

### Describe the issue (Optional if obvious)
When I click the replay arrow on any song it does not work unless I disable Nano Adblocker.

Link: https://www.pandora.com

#### Environment (Required)

- Operating System and Version: Windows 10 1809
- Browser and Version: Chrome 72.0.3626.81 (Official Build) (64-bit)
- Nano Adblocker Version: Nano Adblocker v1.0.0.86
- Nano Defender Version (Optional if you are not using it): 15.0.0.90

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/32418037/52178924-de4af280-2788-11e9-8caf-f74e9864a5fe.png)

#### Your custom filters (Required if you have any)
None

**Comment by jspenguin2017** [comment]
Is there a specific song to test? The replay button is grayed out for me. 
![image](https://user-images.githubusercontent.com/7283682/52179222-d85b0e80-2794-11e9-9e18-61064ef6b624.png)

**Comment by jspenguin2017** [comment]
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/39

**Comment by det427** [comment]
Web page says not found:

**Comment by jspenguin2017** [comment]
Eh... This can be hard... 
![image](https://user-images.githubusercontent.com/7283682/52180237-f75f9d80-27a0-11e9-881f-0c1c5e840da3.png)

**Comment by jspenguin2017** [comment]
@det427 Can you test this rule? Does it have any side effect? 
```
@@||adserver.pandora.com/haymaker/api/v1/serve/$xmlhttprequest,domain=pandora.com
```

@okiehsch FYI.

**Comment by det427** [comment]
Don't know how to do that. 
I am not a programmer. 
I know that the replay button worked about a week ago though. 
One of the updates since then broke the replay button.

**Comment by jspenguin2017** [comment]
I don't see any immediate issues, @okiehsch want to add the rule and see?

**Comment by okiehsch** [comment]
Sorry, I forgot to address this issue I will add your filter.

**Comment by jspenguin2017** [comment]
I thought an upper level domain would not be treated as `1p`?

**Comment by jspenguin2017** [comment]
OK, I tested it, and `1p` does work. 

I don't know why I thought `1p` worked differently.

**Comment by det427** [comment]
Thank you both!
