### ISSUE TITLE
1fichier.com

### ISSUE THREAD

**Issue by Francois-dag** [NanoAdblocker/NanoFilters#266]
https://1fichier.com/?3hjqaaaeweodtgmk5zah

### Screenshots (Required)

![1fichier](https://user-images.githubusercontent.com/8970219/52463639-f1d6ce80-2b77-11e9-8fd7-225bd6ca2c45.png)

### Describe the issue (Optional if obvious)
The screenshot shows the screen with esthetic filters disabled within ublock and disabling adblocker is requested. Selecting "dowload" just loops.

#### Environment (Required)

- Operating System and Version:  windows 10 64 bits
- Browser and Version: firefox 65.0
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it): 15.0.0.90

#### Your custom filters (Required if you have any)

www.lesechos.fr##.paywall-fx > .container

! 12/12/2018 à 15:37:30 https://www.lesechos.fr/
www.lesechos.fr##.main-header
www.lemonde.fr##.Header

! 13/12/2018 à 07:45:50 https://www.lequipe.fr/
www.lequipe.fr##.navigation__home

! 13/12/2018 à 07:50:23 http://www.lefigaro.fr/
www.lefigaro.fr##.full.figh__full

! 13/12/2018 à 07:50:41 http://www.lefigaro.fr/
www.lefigaro.fr##.header-placeholder

! 28/01/2019 https://www.bookys-gratuit.com
www.bookys-gratuit.com##.corps > center:nth-of-type(1)

**Comment by Francois-dag** [comment]
filter list : easylist, fanboys, nano integration

**Comment by jspenguin2017** [comment]
Can't reproduce. No anti-adblock message for me and the file downloads fine.

**Comment by Francois-dag** [comment]
Yes, was due to the new Firefox strict blocking, thanx a lot.
