### ISSUE TITLE
[Anti-Adblock] dailybest.it

### ISSUE THREAD

**Issue by Dr4gon97** [NanoAdblocker/NanoFilters#267]
### URLs where this issue occurs (Required)

https://www.dailybest.it/tv-cinema/il-primo-re-non-e-un-film-perfetto-ma-la-strada-e-quella-giusta/

### Screenshots (Required)
![dailybestaab](https://user-images.githubusercontent.com/37912033/52494440-4b69e800-2bce-11e9-879d-63ceb8af350b.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![dailybestaabconsole](https://user-images.githubusercontent.com/37912033/52494498-76ecd280-2bce-11e9-9f17-8accbc2ac121.jpg)

### Describe the issue (Optional if obvious)
The website loads everything normally. However few instants before completing the rendering, the text turns black and a red box appears on the left saying "Il nostro sito esiste grazie alla pubblicità che mostriamo ai lettori. Per favore prendi in considerazione l'idea di disabilitare il tuo Ad Block."

### Reproduction Steps (Optional if trivial)

-Open the website https://www.dailybest.it/ 
-Choose to read a random article
-Wait for the rendering to be almost complete
-Black text/red box show up

### Anything else you believe to be useful (Optional)
Disabling JavaScript makes the page load normally without any annoyance

#### Environment (Required)

- Operating System and Version: Windows 10 Pro 64 Bit
- Browser and Version: Chrome  v72.0.3626.96
- Nano Adblocker Version: 1.0.0.87
- Nano Defender Version (Optional if you are not using it): 15.0.0.90

#### Your filter lists (Required)

Nano Defender Integration ​​​​​2.617 usati su 2.671​​​​
Nano filters ​​​​​177 usati su 180​​​​
Nano filters – Whitelist​​​​​ 0 usati su 1​​​​
uBlock filters ​​​​​13.470 usati su 13.483​​​​
uBlock filters – Badware risks​​​​​ 63 usati su 63​​​​
uBlock filters – Privacy​​​​​ 158 usati su 159​​​​
uBlock filters – Resource abuse​​​​​ 280 usati su 280​​​​
uBlock filters – Unbreak​​​​​ 802 usati su 804​​​​
Adblock Warning Removal List​​​​​ 597 usati su 615​​​​
EasyList ​​​​​87.427 usati su 87.652​​​​
EasyPrivacy​​​​​ 16.324 usati su 16.539​​​​
Domini con Malware (2/4)
Malware Domain List ​​​​​1.094 usati su 1.109​​​​
Malware domains​​​​​ 26.880 usati su 26.880​​​​
Peter Lowe's Ad and tracking server list ​​​​​2.969 usati su 2.969​​​​
ITA: EasyList Italy​​​​​ 4.750 usati su 4.765​​

**Comment by mapx-** [comment]
fixed
