### ISSUE TITLE
netflix.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoFilters#27]
> "Netflix of its customers who view content on a PC divides into two categories. The first one is using the only right Microsoft Edge browser, the second one is used by other browsers."

this is a advertisement of the microsoft edge in netflix

please unlock the 1080p and 4k source in chrome on linux or windows

**Comment by jspenguin2017** [comment]
I don't see it.

**Comment by KonoromiHimaries** [comment]
lol..

**Comment by KonoromiHimaries** [comment]
https://github.com/truedread/netflix-1080p

**Comment by jspenguin2017** [comment]
Can you fill the template and explain it? I don't have time to read through articles.
