### ISSUE TITLE
[Anti-adblock] blockadblock.com

### ISSUE THREAD

**Issue by Avik-B** [NanoAdblocker/NanoFilters#271]
https://blockadblock.com/

![image](https://user-images.githubusercontent.com/2894306/52913083-5ca6a900-32e0-11e9-8609-473d24464648.png)

![image](https://user-images.githubusercontent.com/2894306/52913096-76e08700-32e0-11e9-9875-d90ad149bfc2.png)

After 1-2 second the block popup appears.

#### Environment (Required)

- Operating System and Version: Windows 10 N version 1809
- Browser and Version: Opera 58.0.3135.65
- Nano Defender Version: 15.0.0.93

**Comment by jspenguin2017** [comment]
Can't reproduce. Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/52917641-403c4980-32ab-11e9-827f-1846756ce478.png)
