### ISSUE TITLE
[Anti-adblock] aternos.org

### ISSUE THREAD

**Issue by froinchi** [NanoAdblocker/NanoFilters#272]
### URLs where this issue occurs (Required)
https://aternos.org/server/

### Screenshots (Required)
![ss](https://user-images.githubusercontent.com/47212347/52956641-d43c0d00-33a0-11e9-9d8d-917bb18f4a2b.png)

### Screenshot of console (Required, press `F12` to open the console)
![console](https://user-images.githubusercontent.com/47212347/52956678-f3d33580-33a0-11e9-86ff-d212e714bb7e.png)

### Describe the issue (Optional if obvious)
I can't skip the Anti-Adblock on Aternos. My native language is Turkish, if you ask so.

### Reproduction Steps (Optional if trivial)
>Sign in Aternos
>Try to reach server console

#### Environment (Required)

- Operating System and Version: Windows 10 , version 1809
- Browser and Version: Opera, 58.0.3135.65
- Nano Adblocker Version: 1.0.0.88
- Nano Defender Version (Optional if you are not using it): 15.0.0.93

#### Your filter lists (Required)
Nano Defender Integration
Nano filters​​​​​
Nano filters – Whitelist​​​​​
uBlock filters
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​​
Adblock Warning Removal List​​​​​
EasyList
EasyPrivacy
Malware Domain List​​​​​
Malware domains​​​​​
Peter Lowe's Ad and tracking server list​​​​​
TUR: AdGuard Turkish filter​​​​​

**Comment by kubapolish** [comment]
aternos recently updated their anti adblock so i don't know if nano can still block it since i can't use it rn but i made this userscript to fix it, could it be useful?

```js
// ==UserScript==
// @name     aternos anti anti adblock
// @version  1
// @match        https://aternos.org/*
// @grant none
// @run-at       document-start
// ==/UserScript==

//window.eval("console.warn={}");//force syntax error to halt js execution of anti adblock handler//doesnt work anymore lol

window.addEventListener('beforescriptexecute', function(e) {
  if(e.target.innerHTML.includes("// disabling this script tag will make the page unusable ;)"))//oh really?
  {
    e.target.innerHTML=e.target.innerHTML.replace(`$('#adUnit').css("display") !== "none" && $('.ad').css("display") !== "none" && typeof pbjsChunk === "function" && typeof __cmp === "function"`
                                                  ,"true");
    console.log("oops, ads fucked!!!");
  }
});
```

**Comment by jspenguin2017** [comment]
Requires test account. See: https://github.com/NanoMeow/QuickReports/issues/25

**Comment by kubapolish** [comment]
aternos team updated it again and responded to my script heh, nice one
sorry if i'm spamming this issue but i don't know any other place where i could post this so

```js
// ==UserScript==
// @name     aternos anti anti adblock
// @version  1
// @match        https://aternos.org/*
// @grant none
// @run-at       document-start
// ==/UserScript==

window.addEventListener('beforescriptexecute', function(e) {
  if(e.target.innerHTML.includes("// ( •̀ᴗ•́ ) hi, i'm an evil comment"))// (:
  {
    //e.target.innerHTML=e.target.innerHTML.replace(`$('#adUnit').css("display") !== "none" && $('.ad').css("display") !== "none" && typeof pbjsChunk === "function" && typeof __cmp === "function"`
    //                                              ,"true");
    
    e.target.innerHTML=e.target.innerHTML.replace(`$(window).width() < 300`,`true`);
    
    //nice one aternos team :p
    //to be honest, i'm doing this just for fun, i enjoy reverse engineering stuff, and i'm really grateful for your
    //service, so uh, i'm wondering, is there any way i could donate a small amount of monies to you? i can't find
    //anywhere any donate form so i guess you don't accept donations either way but uh again thank you for your free service (:
  }
});
```

**Comment by llacb47** [comment]
These two filters seem to work. It does require an account to reproduce, though.
```
aternos.org##+js(abort-on-property-read.js,Intl)
aternos.org##div[id]:has(div[style]:has(.fa-frown))
```

**Comment by machinesmith42** [comment]
still triggering

**Comment by llacb47** [comment]
Test filters linked here https://github.com/NanoMeow/QuickReports/issues/1643#issuecomment-535089832

**Comment by machinesmith42** [comment]
That works thanks

**Comment by machinesmith42** [comment]
aternos.org##+js(acis, $, Date)
! placeholders
aternos.org##aside:has(.ad)
aternos.org##div.ad

the code that works

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1643

**Comment by machinesmith42** [comment]
breaks functionality

**Comment by machinesmith42** [comment]
no buttons are working

**Comment by llacb47** [comment]
https://github.com/NanoMeow/QuickReports/issues/1643#issuecomment-535089832

**Comment by machinesmith42** [comment]
tested all buttons are non funtional

**Comment by llacb47** [comment]
Did you add the filters in https://github.com/NanoMeow/QuickReports/issues/1643#issuecomment-535089832 @machinesmith42

**Comment by machinesmith42** [comment]
yes

**Comment by machinesmith42** [comment]
i use ublock origin

**Comment by machinesmith42** [comment]
my rules
aternos.org##+js(acis, $, Date)
! placeholders
aternos.org##aside:has(.ad)
aternos.org##div.ad

**Comment by llacb47** [comment]
You need to add `aternos.org##div[id][style]:has(>div[style*="z"] > div[style*="x"])`

**Comment by machinesmith42** [comment]
fixed
