### ISSUE TITLE
[Anti-adblock] vvvvid.it

### ISSUE THREAD

**Issue by xlollomanx** [NanoAdblocker/NanoFilters#277]
### URLs where this issue occurs (Required) 
https://www.vvvvid.it/#!show/845/sword-art-online-alicization/939/540113/il-sigillo-nell-occhio-destro

### Screenshots (Required)
https://prnt.sc/mpxs8k

### Screenshot of console (Required, press `F12` to open the console)
https://prnt.sc/mpy41v

### Describe the issue (Optional if obvious)
The filter `vvvvid.it##+js(nano-vvvvid-it.js)` make trigger the anti-adblocker. This should be removed and replaced with `@@||ads.mperience.net/vast$xhr,domain=imasdk.googleapis.com` as stated here `https://forums.lanik.us/viewtopic.php?p=145893#p145893`

#### Environment (Required)

- Operating System and Version: windows 10 Pro 1809
- Browser and Version: Google Chrome 72.0.3626.119
- Nano Adblocker Version:  1.0.0.89
- Nano Defender Version (Optional if you are not using it): 15.0.0.97

**Comment by mapx-** [comment]
`@@||ads.mperience.net/vast$xhr,domain=imasdk.googleapis.com` was already added to `ublock filters` list

**Comment by xlollomanx** [comment]
@mapx- so assuming should be removed only `vvvvid.it##+js(nano-vvvvid-it.js)` that it make the advice triggers

**Comment by mapx-** [comment]
exactly, @jspenguin2017  will decide what to do

**Comment by jspenguin2017** [comment]
Updated the script snippet. Can you test again?

**Comment by jspenguin2017** [comment]
Actually, since it is in uBlock filters, I'll just demote the script snippet to be experimental.

**Comment by xlollomanx** [comment]
@jspenguin2017 tested now and it's working fine. Thank you!
