### ISSUE TITLE
[Annoyance, Cookie Wall] mapy.geoportal.gov.pl

### ISSUE THREAD

**Issue by krystian3w** [NanoAdblocker/NanoFilters#278]
### URLs where this issue occurs (Required)

`http://mapy.geoportal.gov.pl/imap/` https://github.com/MajkiIT/polish-ads-filter/issues/12250

### Screenshots (Required)

![obraz](https://user-images.githubusercontent.com/35370833/53366604-47ff8c00-3944-11e9-9c77-5c6bd4d3bd51.png) |
--- |

### Screenshot of console (Required, press `F12` to open the console)

N/A

### Describe the issue (Optional if obvious)

Website no load map without accept cookies.

No tested normal script e.g. `set-constant.js`

>> Do poprawnego działania aplikacja używa ciasteczek(cookies), a korzystanie z zasobów witryny >> internetowej **Geoportal.gov.pl** oznacza akceptację niniejszego <ins>**Regulaminu**</ins>.
>
> For proper operation, the application uses cookies (cookies), and the use of resources on the > **Geoportal.gov.pl** website means acceptance of these <ins>**Regulations**</ins>.

### Reproduction Steps (Optional if trivial)

Trival if no geolock

### Anything else you believe to be useful (Optional)

`mapy.geoportal.gov.pl##+js(nanop-easy-set-cookie.js, regulationsAccepted=true)`

#### Environment (Required)

- Operating System and Version: Windows 7
- Browser and Version:  Chrome 72
- Nano Adblocker Version: 1.0.0.89
- Nano Defender Version (Optional if you are not using it): N/A

#### Your filter lists (Required)

uBO Annoyance / Nano Annoyance.

#### Your custom filters (Required if you have any)

N/A

**Comment by krystian3w** [comment]
`nanop-click-elements-onload.js` - generate error "another app is opened"

`nanop-click-elements-onready.js` - generate loop clicking

**Comment by hawkeye116477** [comment]
Or just create cookie :smile:

**Comment by jspenguin2017** [comment]
No GeoLock.

**Comment by krystian3w** [comment]
PS. "Nie" (tranlate "no") - close app, no possible open without accept **Regulations** / Rules.
