### ISSUE TITLE
[Anti-adblock] brainly.co.id

### ISSUE THREAD

**Issue by chelseaislan** [NanoAdblocker/NanoFilters#28]
Hi mate,
I appreciate your great work to block so many ads, and I haven't found anti adblock scripts until this one.
This happened on Brainly.co.id page. The appearance looks like this:

![screenshot 26](https://user-images.githubusercontent.com/30471081/36163402-e7c25cba-111b-11e8-8cd9-c89a2f0a77d4.png)
https://brainly.co.id/tugas/995959

When I click the blue button (Ok, I won't block ads on Brainly) the alert to whitelist the page shows with the link like this:

abp:subscribe?location=https%3A%2F%2Fid-static.z-dn.net%2Ffiles%2Fadmin%2Fbrainly.id.txt&title=Brainly.co.id
![screenshot 27](https://user-images.githubusercontent.com/30471081/36163571-5236f902-111c-11e8-8a48-f17c373f8115.png)

Screenshot of console:
![screenshot 28](https://user-images.githubusercontent.com/30471081/36163694-bb127794-111c-11e8-9c55-12ae9639744b.png)

### Environment (Required)
- Operating System and Version: Windows 10 1709 64-bit
- Browser and Version: Chrome Version 64.0.3282.140 (Official Build) (64-bit)
- Nano Adblocker Version: 1.0.0.30

#### Your filter lists (Required)
The default ones + Nano Filters (Annoyance) & ABPindo

**Comment by jspenguin2017** [comment]
`brainly.co.id##.brn-ads-box` I'll sync the rules later.
