### ISSUE TITLE
[Anti-adblock] imore.com

### ISSUE THREAD

**Issue by Scraft** [NanoAdblocker/NanoFilters#282]
### URLs where this issue occurs (Required)
https://www.imore.com/google-now-owns-very-important-part-next-pokemon-go

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/294599/53880223-5e72ab00-4008-11e9-937a-f1961df2114b.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/294599/53880257-79451f80-4008-11e9-9844-d75fb9baf996.png)

### Describe the issue (Optional if obvious)
The site detects AdBlock.

### Reproduction Steps (Optional if trivial)
Just visiting the website should be enough (no scrolling etc. required)

### Anything else you believe to be useful (Optional)
N/A

#### Environment (Required)

- Operating System and Version: Windows 10 Pro 64bit
- Browser and Version: Firefox 65.0.2
- Nano Adblocker Version: N/A
- uBlock Origin Version: 1.18.4
- Nano Defender Version (Optional if you are not using it): 15.0.0.106

#### Your filter lists (Required)
No changes since following installation steps.

#### Your custom filters (Required if you have any)
No changes since following installation steps.

**Comment by mapx-** [comment]
fixed as annoyance (you can click "continue with the adblocker")
