### ISSUE TITLE
[Anti-adblock] washingtonpost.com

### ISSUE THREAD

**Issue by mikhoul** [NanoAdblocker/NanoFilters#283]
https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue

### URLs where this issue occurs (Required)
https://www.washingtonpost.com/politics/michael-cohen-sues-trump-organization-over-millions-in-unpaid-legal-fees/2019/03/07/06f35348-4102-11e9-922c-64d6b7840b82_story.html?noredirect=on&utm_term=.ca564e54dd14

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/5678673/53988910-9a823a80-40f2-11e9-8fa9-5c4b47cffa9f.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/5678673/53988971-c56c8e80-40f2-11e9-848f-b0a9694160fe.png)

#### Environment (Required)

- Operating System and Version:   Win 7
- Browser and Version:  Latest Chromium
- Nano Adblocker Version:   Latest
- Nano Defender Version (Optional if you are not using it):   Latest

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/5678673/53989057-0c5a8400-40f3-11e9-9558-917ad8894620.png)

#### Your custom filters (Required if you have any)
None

**Comment by jspenguin2017** [comment]
Works fine for me. Make sure to update your filters.

**Comment by mikhoul** [comment]
You're right the after I updated the filter it work.

Regards :+1:
