### ISSUE TITLE
[Breakage] hinative.com

### ISSUE THREAD

**Issue by freMea** [NanoAdblocker/NanoFilters#284]
### Describe the issue (Required)
When I browse hinative.com like [here](https://hinative.com/en-US/questions/12606170), the 👍is invisible as long as Nano is enable.

### Screenshots (Required)
Default Nano settings for this page
![Default](https://i.snag.gy/zZx7mp.jpg)

Tried this for test purpose to no avail
![Default](https://i.snag.gy/RpMoH8.jpg)

Result in both case: no 👍on the user post
![When is ON](https://i.snag.gy/tueidw.jpg)

But when Nano is disable for the site, voilà
![When is OFF](https://i.snag.gy/IBDfeJ.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![When is OFF](https://i.snag.gy/eAcZvs.jpg)

### URLs where this issue occurs (Required if applicable)
[here](https://hinative.com/en-US/questions/12606170)

### Anything else you believe to be useful (Optional)
Please, any user can try to reproduce this and report results?

#### Environment (Required)

- Operating System and Version: Win 10 1607
- Browser and Version: Vivaldi 2.3.1440.60
- Nano Adblocker Version: 1.0.0.92
- Nano Defender Version (Optional if you are not using it): 15.0.0.108

#### Your filter lists (Required)
[screenshot](https://i.snag.gy/gsIcme.jpg)

#### Your custom filters (Required if you have any)
[pastebin](https://paste.ubuntu.com/p/hKYMjFnqzq/)

**Comment by jspenguin2017** [comment]
Looks like a test account is required.

**Comment by freMea** [comment]
Yes, one will needs to sign in to test. Not a big deal for testers to create a dummy account, though.

**Comment by mapx-** [comment]
add
`hinative.com#@#.like_block`

cause:
`##.like_block`

from fanboy's annoyances list @ryanbr

**Comment by freMea** [comment]
Thanks a lot @mapx- . I add `#@#.like_block` to disable this rule on every site.

Problem solved.

**Comment by jspenguin2017** [comment]
Issue related to annoyance filters, won't fix in Nano filters.
