### ISSUE TITLE
[Anti-adblock, Ads] encoretvb.com

### ISSUE THREAD

**Issue by dmarii** [NanoAdblocker/NanoFilters#286]
### URLs where this issue occurs (Required)
https://encoretvb.com/english/videos/26-Highs_And_Lows/5997631664001

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/48536954/54323122-ceaf9c80-45c5-11e9-990e-3c47415ebafb.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/48536954/54323162-fbfc4a80-45c5-11e9-9c9c-d973c38f4018.png)

### Describe the issue (Optional if obvious)
This website detects adblock, and video cannot be played. 

### Reproduction Steps (Optional if trivial)
Website is "encoretvb . com"
In order to test it, just click a random video and no account required.

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
- Nano Adblocker Version: 1.0.0.92
- Nano Defender Version (Optional if you are not using it): 15.0.0.108

#### Your filter lists (Required)

Auto-update filter lists 
Parse and enforce cosmetic filters
Ignore generic cosmetic filters
96,757 network filters ＋ 48,003 cosmetic filters from:
 My filters​​​​​0 used out of 0​​​​
Built-in (8/11)
Nano Defender Integration​​​​​2,623 used out of 2,671​​​​
Nano filters​​​​​185 used out of 188​​​​
Nano filters – Whitelist​​​​​0 used out of 1​​​​
uBlock filters​​​​​14,080 used out of 14,094​​​​
uBlock filters – Badware risks​​​​​67 used out of 67​​​​
uBlock filters – Privacy​​​​​156 used out of 157​​​​
uBlock filters – Resource abuse​​​​​281 used out of 281​​​​
uBlock filters – Unbreak​​​​​864 used out of 866​​​​
Ads (2/5)
Adblock Warning Removal List​​​​​601 used out of 619​​​​
EasyList​​​​​87,880 used out of 88,080​​​​
Privacy (1/3)
EasyPrivacy​​​​​16,413 used out of 16,625​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,090 used out of 1,105​​​​
Malware domains​​​​​26,913 used out of 26,913​​​​
Annoyances (0/6)
Multipurpose (1/5)
Peter Lowe's Ad and tracking server list​​​​​2,948 used out of 2,948​​​​

**Comment by jspenguin2017** [comment]
@okiehsch @mapx-

**Comment by okiehsch** [comment]
Fixed.
