### ISSUE TITLE
[Anti-adblock] browserleaks.com

### ISSUE THREAD

**Issue by anarki999** [NanoAdblocker/NanoFilters#292]
### URLs where this issue occurs (Required)
https://browserleaks.com/proxy

### Describe the issue (Optional if obvious)
The website will detect what filters you use. If this website can detect it, so do other advanced website.

#### Environment (Required)

- Operating System and Version: Windows 7
- Browser and Version: Chrome 73.0.3683.86
- Nano Adblocker Version: 1.0.0.97
- Nano Defender Version (Optional if you are not using it): 15.0.0.112

#### Your filter lists (Required)

Built-in (8/11)
Nano Defender Integration​​​​​2,625 used out of 2,670​​​​
Nano filters​​​​​192 used out of 195​​​​
Nano filters – Whitelist​​​​​0 used out of 1​​​​
uBlock filters​​​​​14,283 used out of 14,298​​​​
uBlock filters – Badware risks​​​​​99 used out of 99​​​​
uBlock filters – Privacy​​​​​156 used out of 157​​​​
uBlock filters – Resource abuse​​​​​108 used out of 108​​​​
uBlock filters – Unbreak​​​​​882 used out of 884​​​​

Ads (4/5)
Adblock Warning Removal List​​​​​605 used out of 632​​​​
AdGuard Base filter​​​​​21,858 used out of 23,372​​​​
AdGuard Mobile Ads filter​​​​​3,075 used out of 3,541​​​​
EasyList​​​​​87,758 used out of 88,312​​​​

Privacy (2/3)
EasyPrivacy​​​​​15,820 used out of 16,697​​​​
Fanboy's Enhanced Tracking List​​​​​2,990 used out of 3,062​​​​
Malware domains (4/4)
Malvertising filter list by Disconnect​​​​​417 used out of 2,788​​​​
Malware Domain List​​​​​1,090 used out of 1,105​​​​
Malware domains​​​​​26,892 used out of 26,907​​​​
Spam404​​​​​6,671 used out of 6,671​​​​
Annoyances (0/6)
Multipurpose (2/4)
hpHosts' Ad and tracking servers​​​​​44,606 used out of 45,739​​​​
Peter Lowe's Ad and tracking server list​​​​​2,945 used out of 2,946​​​​

Regions, languages (3/37)
CHN: EasyList China (中文)​​​​​17,063 used out of 17,215​​​​
ITA: ABP X Files​​​​​4,411 used out of 4,736​​​​
KOR: YousList​​​​​6,087 used out of 6,127​​​​

**Comment by mapx-** [comment]
`browserleaks.com##+js(set-constant.js, proxy_abc, trueFunc)`
or
```
@@||browserleaks.com/img/*.gif
@@*$image,domain=browserleaks.com,3p
```

**Comment by mil1i** [comment]
I see this marked as closed and fixed 23 days ago, but I just installed nano blocker and nano defender.

It still detects all the adblock lists subscriptions.

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/NanoMeow/QuickReports/issues/903
