### ISSUE TITLE
[Anti-adblock] viafree.se

### ISSUE THREAD

**Issue by Sopor** [NanoAdblocker/NanoFilters#298]
![image](https://user-images.githubusercontent.com/5789283/55594956-0d0e2680-5742-11e9-9c1d-9f8e6b3e192a.png)

Environment (Required)
Operating System and Version: Windows 10
Browser and Version: Firefox 66.0.1 and Chrome 73.0.3683
Nano Adblocker Version: uBlock origin 1.18.16
Nano Defender Version (Optional if you are not using it): 15.0.0.120
Your filter lists (Required)
FIN: Adblock List for Finland​​​​​
SWE: Frellwit's Swedish Filter​​​​​

**Comment by jspenguin2017** [comment]
https://github.com/NanoMeow/QuickReports/issues/456
Requires account.

**Comment by Sopor** [comment]
Yes, but the account is free. I can create a new one, but i don't know if i will add them here?

**Comment by jspenguin2017** [comment]
Send the credentials here: https://legacy.hugoxu.com/PrivateMessage/
With reference 298

OR

Open a confidential issue here: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues

**Comment by jspenguin2017** [comment]
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/41

@okiehsch FYI.

**Comment by okiehsch** [comment]
Works fine with the regional list enabled on my end.

**Comment by jspenguin2017** [comment]
Yep, verified. Works fine with Swedish regional filters. 
https://github.com/NanoMeow/QuickReports/issues/456#issuecomment-480140122

**Comment by Sopor** [comment]
Yes, i can confirm that too. Very strange because i haven't changed anything and now it suddenly works.
