### ISSUE TITLE
[Anti-adblock] richmond-news.com

### ISSUE THREAD

**Issue by chelseaislan** [NanoAdblocker/NanoFilters#30]
Hi mate,
I found another website (http://www.richmond-news.com) which has detected my adblock, but it didn't cover the whole page.

### URLs where this issue occurs (Required)
http://www.richmond-news.com/news/chinese-railway-built-in-just-9-hours-by-1-500-feverish-workers-1.23154197

### Screenshots (Required)
![screenshot 31](https://user-images.githubusercontent.com/30471081/36218571-6d177ec4-11e7-11e8-81b1-45b4daf3195c.png)

### Screenshot of console (Required, press `F12` to open the console)
![screenshot 32](https://user-images.githubusercontent.com/30471081/36218631-a1ea149a-11e7-11e8-930c-2d006b6b6628.png)

### Environment (Required)
Operating System and Version: Windows 10 1709 64-bit
Browser and Version: Chrome Version 64.0.3282.140 (Official Build) (64-bit)
Nano Adblocker Version: 1.0.0.30

#### Your filter lists (Required)
The default ones + Nano Filters (Annoyance) & ABPindo

**Comment by jspenguin2017** [comment]
`@@/js/ads.js$script,first-party,domain=richmond-news.com` I'll add it later.
