### ISSUE TITLE
[Anti-adblock] byggahus.se

### ISSUE THREAD

**Issue by Sopor** [NanoAdblocker/NanoFilters#300]
![image](https://user-images.githubusercontent.com/5789283/55673505-00f0a900-58a9-11e9-9dc8-f38767031414.png)

Environment (Required)
Operating System and Version: Windows 10
Browser and Version: Firefox 66.0.1
Nano Adblocker Version: uBlock origin 1.18.16
Nano Defender Version (Optional if you are not using it): 15.0.0.121
Your filter lists (Required)
FIN: Adblock List for Finland​​​​​
SWE: Frellwit's Swedish Filter​​​​​

It seems to work in Chrome.

**Comment by mapx-** [comment]
```
@@||byggahus.se^$generichide
byggahus.se###ad-zone-panorama
```

**Comment by jspenguin2017** [comment]
Or just `byggahus.se##.abd-message-container`. 

Are you adding a solution to uBlock annoyance filter?

**Comment by mapx-** [comment]
fixed

**Comment by Sopor** [comment]
Any reason why it was showing up in Firefox, but not in Chrome?

**Comment by mapx-** [comment]
I get the message in chrome too

**Comment by Sopor** [comment]
@mapx- odd, but who cares, now it is gone, thanks :)
