### ISSUE TITLE
[Ads] cuurl.net

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#301]
### Describe the issue (Required)
can't download my file from this website :https://www.up-4.net/dl 

### Screenshots (Required)
![with Nano Adblocker enabled](https://user-images.githubusercontent.com/34688076/55676188-0ceb6380-58c7-11e9-9d6a-fb20129839cd.png) with Nano Adblocker enabled .
![with Nano Adblocker Disabled](https://user-images.githubusercontent.com/34688076/55676190-17a5f880-58c7-11e9-9d5f-43da752f383f.png) with Nano Adblocker Disabled .

### Screenshot of console (Required, press `F12` to open the console)
![Console](https://user-images.githubusercontent.com/34688076/55676208-b16da580-58c7-11e9-87cc-c02f1564c2bd.PNG)

### URLs where this issue occurs (Required if applicable)

https://www.up-4.net/dl
#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
May need a better test link.

**Comment by YASINEDr** [comment]
you can follow this shortned link until you get the result mentioned above : 
https://cuurl.net/kAcAPKCY

**Comment by jspenguin2017** [comment]
@okiehsch `cuurl.net` has a popup.

**Comment by jspenguin2017** [comment]
The webpage is submitting a flag, may need to whitelist some script. 
![image](https://user-images.githubusercontent.com/7283682/55693802-3612ff00-596e-11e9-9fc2-37510451b798.png)

**Comment by okiehsch** [comment]
Fixed the popup, I can only download the file via right click "save link as"

**Comment by jspenguin2017** [comment]
Yea, the button works identically with or without adblocker enabled.

**Comment by YASINEDr** [comment]
doesn't work for me 
![Capture](https://user-images.githubusercontent.com/34688076/55694729-6d54d080-59ad-11e9-956a-cd81c8a6a0ee.PNG)

**Comment by okiehsch** [comment]
Works for me.
![image](https://user-images.githubusercontent.com/16838044/55694874-70a08a00-59b6-11e9-8984-dc0a6d43cd19.png)

**Comment by YASINEDr** [comment]
you're using ublock not nano adblocket

**Comment by okiehsch** [comment]
I know so does **jspenguin2017**.

**Comment by okiehsch** [comment]
Also I can't see a reason why right click behaviour would work with uBO but not with Nano.

**Comment by jspenguin2017** [comment]
It works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/55695082-2bf3ff00-5974-11e9-8706-afcd3217ddbc.png)

**Comment by jspenguin2017** [comment]
Closing. Complete the issue template if it still doesn't work for you.

**Comment by YASINEDr** [comment]
may I need to whitelist some script ?

**Comment by jspenguin2017** [comment]
Not for now at least, they aren't doing anything with the flag.

**Comment by ghajini** [comment]
still it generates popups when clicked on `click to download`

**Comment by jspenguin2017** [comment]
Hum... Chrome's Popup Blocker should not allow 2 navigations for one user gesture, unless there's a new bypass... 

I did see something blinking once, but no popup is left behind. Can you open a new issue with the template filled?

**Comment by ghajini** [comment]
Okay will open
