### ISSUE TITLE
[Anti-adblock] polsatsport.pl

### ISSUE THREAD

**Issue by reenlam** [NanoAdblocker/NanoFilters#302]
### URLs where this issue occurs
https://www.polsatsport.pl/wiadomosc/2019-04-08/mistrz-ufc-udusil-kibica-wideo/
http://www.polsatnews.pl/wiadomosc/2019-04-08/w-poniedzialek-protest-taksowkarzy-w-warszawie/

### Screenshots
https://www.polsatsport.pl/wiadomosc/2019-04-08/mistrz-ufc-udusil-kibica-wideo/
![polsatSport_AntiADB](https://user-images.githubusercontent.com/25178165/55741351-56ee5980-5a2d-11e9-9e83-e61fec850cd4.png)

console:
![polsatSport_console](https://user-images.githubusercontent.com/25178165/55741406-77b6af00-5a2d-11e9-8318-cf8e0e3d076f.png)

http://www.polsatnews.pl/wiadomosc/2019-04-08/w-poniedzialek-protest-taksowkarzy-w-warszawie/
![polsatNews_AntiADB](https://user-images.githubusercontent.com/25178165/55741428-84d39e00-5a2d-11e9-8b8d-93b966fe7758.png)

console:
![polsatNews_console](https://user-images.githubusercontent.com/25178165/55741458-90bf6000-5a2d-11e9-8631-1776a102d47d.png)

#### Environment

- Operating System and Version: Ubuntu 17.10
- Browser and Version: Firefox Quantum 61.0.1 (64-bit)
- Nano Adblocker Version: 1.0.0.103
- Nano Defender Version: 15.0.0.124

#### Your filter lists
Only default filters obtained by Nano Adblocker installation

**Comment by jspenguin2017** [comment]
This is fixed by Polish regional filters.
