### ISSUE TITLE
[Anti-adblock] happypancake.fi

### ISSUE THREAD

**Issue by krisu5** [NanoAdblocker/NanoFilters#303]
### URLs where this issue occurs (Required)
https://www.happypancake.fi/messages

### Screenshots (Required)
![Screen Shot 2019-04-08 at 22 50 45](https://user-images.githubusercontent.com/3540275/55752485-d7728180-5a50-11e9-80f0-6a83b2946465.png)

### Screenshot of console (Required, press `F12` to open the console)
![Clipboard01](https://user-images.githubusercontent.com/3540275/55752704-4cde5200-5a51-11e9-92df-dfcc27c5c483.jpg)

Plaintext: https://bin.privacytools.io/?d1c4454b820e84f5#hWu8/A1lnzXt8PbT4Z29AsvoE/4Xsshx6Odl48mfQZw=

### Describe the issue (Optional if obvious)
After loading the URL, wait for 10-20sec to that anti-adblock message appear. It disables chat's message box at the bottom.

You don't need to start a chat with a person, just loading that page is enough.

### Anything else you believe to be useful (Optional)
Needs login. Maybe geolocked? Not sure, this is dating site for finnish people only.

#### Environment (Required)

- Operating System and Version: Windows 10 Home, build 1809
- Browser and Version: Firefox 66.0.2
- Nano Defender Version: 15.0.0.124 (using uBlock Origin 1.18.16)

#### Your filter lists (Required)
- uBlock filters – Annoyances​​​​​
- uBlock filters – Badware risks​
- uBlock filters – Experimental​
- uBlock filters – Privacy​​​​​
- uBlock filters – Resource abuse​​​​​
- uBlock filters – Unbreak​​​​
- Adblock Warning Removal List​
- AdGuard Base filter​
- EasyList​
- AdGuard Spyware filter​
- EasyPrivacy​
- Malvertising filter list by Disconnect​​​​​
- Malware Domain List​​​​​
- Malware domains​
- Spam404
- AdGuard Annoyances filter​
- Anti-Facebook List​
- Fanboy's Cookie List​
- FIN: Adblock List for Finland

#### Your custom filters (Required if you have any)
https://ssl.bblck.me/blacklists/ublock-origin.txt
https://raw.githubusercontent.com/bcye/Hello-Goodbye/master/filterlist.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
https://raw.githubusercontent.com/IDKwhattoputhere/uBlock-Filters-Plus/master/uBlock-Filters-Plus.txt

**Comment by jspenguin2017** [comment]
Requires account. 

https://github.com/NanoMeow/QuickReports/issues/949

**Comment by krystian3w** [comment]
```
happypancake.fi##+js(set, canRunAds, true)
@@||happypancake.fi/static/prebid.*.js$script,domain=www.happypancake.fi
@@||googletagmanager.com/gtm.js$script,domain=www.happypancake.fi
```

I no have fix for gtm and prebid with scriplets, redirect no help on my side.

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Do you have a test account?
@peace2000 if 
````
happypancake.fi##+js(set, canRunAds, true)
@@||happypancake.fi/static/prebid.*.js$script,domain=www.happypancake.fi
@@||googletagmanager.com/gtm.js$script,domain=www.happypancake.fi
````
works they could be added to the finnish list.

**Comment by peace2000** [comment]
Sorry but I don't have a write access to the Finnish list. Only the owner of that list @theel0ja has it. He probably wants to see personally that things work before he merges.

**Comment by krystian3w** [comment]
Firefox maybe need a Little more if we have enabled qouery `security.csp.enable` in `about:config`

I prefre disable this CSP crap.

**Comment by krisu5** [comment]
Anti-adblock might have been removed: https://github.com/finnish-easylist-addition/finnish-easylist-addition/issues/103#issuecomment-581484583

Closing the issue.
