### ISSUE TITLE
[Anti-adblock] frenchpdf.com

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#305]
### Describe the issue (Required)
Adblock Detected on this website : https://frenchpdf.com/?fbclid=IwAR3jLRv55uuxsNeMaRfneNo8LnZPYZlgPzceXpxi0kIRI0szRwTF7pJb51c

### Screenshots (Required)

![Annotation 2019-04-12 010250](https://user-images.githubusercontent.com/34688076/56003545-d0e94180-5cbe-11e9-9320-ce9f037544dd.png)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
This comes up a lot hey? Maybe I should add a generic solution...
