### ISSUE TITLE
[Anti-Adblock] elbotola.com

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#308]
can't play video while nano is enabled
### URLs where this issue occurs (Required)
 https://www.elbotola.com/video/details/5cb62b7bc5a4b06432d8fe1e/
Please use the domain as the title
-->

### Screenshots (Required)

![screenshot-www elbotola com-2019 04 16-20-59-43](https://user-images.githubusercontent.com/34688076/56240156-a4e90a00-608a-11e9-84eb-9c44bdd5aed9.png)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by mapx-** [comment]
fixed

**Comment by YASINEDr** [comment]
![screenshot-www elbotola com-2019 04 16-20-59-43](https://user-images.githubusercontent.com/34688076/56241257-5c7f1b80-608d-11e9-9c1d-edeb37334b83.png)
not yet for me ! 
 And There is no filter update
![Filters](https://user-images.githubusercontent.com/34688076/56241307-77ea2680-608d-11e9-84c8-34a7ca760094.PNG)

**Comment by mapx-** [comment]
update `ublock filters`

**Comment by mapx-** [comment]
or add in "my filters"
```
@@||imasdk.googleapis.com/js/sdkloader/ima3.js?$script,domain=cdnvideo.me
@@||elbotola.com^$generichide
@@||cdnvideo.me^$generichide
```

**Comment by YASINEDr** [comment]
Thank you man well fixed !
![screenshot-www elbotola com-2019 04 16-21-28-10](https://user-images.githubusercontent.com/34688076/56241832-bfbd7d80-608e-11e9-80de-bac72f4958ec.png)
