### ISSUE TITLE
[Ads] world-of-gamers.net

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#309]
Example link: http://world-of-gamers.net/

There's an ad video from EasyAds which isn't blocked by default.

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed in the regional list.

**Comment by jspenguin2017** [comment]
Yep, fixed in Russian regional filters. Sorry for the false alarm.

**Comment by Cyberavater** [comment]
Just scroll a little bit, it is reproducible.

**Comment by jspenguin2017** [comment]
Works fine for me, even if I scroll to the bottom.

**Comment by Cyberavater** [comment]
Will I have to enable Russian regional filters from the settings?

**Comment by jspenguin2017** [comment]
Yes, if you use Russian websites, you need the Russian regional filters.

**Comment by Cyberavater** [comment]
So, it's not enabled by default?

**Comment by Cyberavater** [comment]
Yes, found it. It was not enabled by default. I thought it was missing from the filter list sorry.

**Comment by Cyberavater** [comment]
BTW, why it wasn't enabled by default?

**Comment by okiehsch** [comment]
The regional list corresponding to ones browser locale is enabled by default.

**Comment by Cyberavater** [comment]
Got it, thanks!
