### ISSUE TITLE
[Anti-adblock] hongkong.fastdrama.me, hk.fastdrama.me

### ISSUE THREAD

**Issue by KiraYamatoSD** [NanoAdblocker/NanoFilters#311]
### URLs where this issue occurs (Required)

http://hongkong.fastdrama.me/
http://hk.fastdrama.me

### Screenshots (Required)
![2019-04-19 02_19_53-The Learning Curve of a Warlord - 大帥哥 - Episode 30 English Subtitles - Hong Kong](https://user-images.githubusercontent.com/19279071/56382466-07d4cf80-624a-11e9-88a1-40c972eafb31.png)

### Screenshot of console (Required, press `F12` to open the console)
![2019-04-19 02_19_47-DevTools - hk fastdrama me_watch-online_the-learning-curve-of-a-warlord_ep-30-e-](https://user-images.githubusercontent.com/19279071/56382438-f4296900-6249-11e9-9898-d428a9efff43.png)

### Describe the issue (Optional if obvious)
http://hk.fastdrama.me/watch-online/the-learning-curve-of-a-warlord/ep-30-e-sub

### Anything else you believe to be useful (Optional)
It is running a script to detect adblockers
[http://www1.fastdrama.me/scripts/fuckadblock.js](http://www1.fastdrama.me/scripts/fuckadblock.js)

#### Environment (Required)

- Operating System and Version: Windows 10 Pro x64
- Browser and Version: Chrome
- Nano Adblocker Version: 1.0.0.104
- Nano Defender Version (Optional if you are not using it): 15.0.0.132

#### Your filter lists (Required)

Default filters in the "built-in" section.

**Comment by mapx-** [comment]
fixed
