### ISSUE TITLE
[Anti-adblock] lcomlearning.com

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#312]
### URLs where this issue occurs (Required)
http://www.lcomlearning.com
Please use the domain as the title
-->

### Screenshots (Required)

![screenshot-www lcomlearning com-2019 04 19-01-23-49](https://user-images.githubusercontent.com/34688076/56398699-d526d900-6241-11e9-9353-beaa16c6320d.png)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
@okiehsch More `$tieE3`. This thing is getting out of hand.

**Comment by okiehsch** [comment]
Fixed.
