### ISSUE TITLE
[Anti-adblock] onlinecoursebay.com

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#313]
### URLs where this issue occurs (Required)
https://onlinecoursebay.com/
Please use the domain as the title
-->

### Screenshots (Required)
![screenshot-onlinecoursebay com-2019 04 19-06-11-09](https://user-images.githubusercontent.com/34688076/56407944-f3a0ca80-6269-11e9-9aec-2121ca5eba57.png)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
@okiehsch FYI. 

Note that this is fixed in Nano Defender.
