### ISSUE TITLE
[Anti-adblock] uploadev.org

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#314]
**### URLs where this issue occurs (Required)**
https://uploadev.org/dapji50r3hwt

**Screenshots (Required)**

![Screenshot_2019-04-22 UploadEv - Upload Files Easy Way To Earn Money](https://user-images.githubusercontent.com/43067841/56477260-5d68e080-64c5-11e9-81d3-2cc30ea0e647.png)

**Describe the issue (Optional if obvious)**
Issue occurs clicking on create download link after waiting 20 sec.

**Environment (Required)**

    Operating System and Version: Windows 10 Home, build 1803
    Browser and Version: Firefox 66.0.3
    Nano adblocker Version: 1.0.0.104
    Nano Defender Integration

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
