### ISSUE TITLE
[Anti-adblock] dropapk.com

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#316]
**### URLs where this issue occurs (Required)**
https://dropapk.com/g9bnlweip98v

**Screenshots (Required)**

![Screenshot_2019-04-24](https://user-images.githubusercontent.com/43067841/56630745-2553d000-6674-11e9-8359-d853829ab771.png)

Describe the issue (Optional if obvious)

Environment (Required)

Operating System and Version: Windows 10 Home, build 1803
Browser and Version: Firefox 66.0.3
Nano adblocker Version: 1.0.0.104
Nano Defender Integration

**Comment by Joyer1234** [comment]
This does not happen, if I use Nano Defender + ublock origin on Firefox.
Issue occurs only with Nano adblocker + Nano Defender Integration.

**Comment by mapx-** [comment]
fixed

**Comment by remoteitworker** [comment]
Works on Firefox to some degree. But with almost 300 blocks on uBlock not a site I'd want to spend the time getting to work. I'm pretty sure many if not most of those blocks are trying to infect your computer. Malwarebytes even kicks in and blocks one of their main script links.

**Comment by jspenguin2017** [comment]
You need the Nano Defender extension for either case, the integration filter cannot be used alone.
