### ISSUE TITLE
[Anti-adblock] t66y.com

### ISSUE THREAD

**Issue by crackerjohn** [NanoAdblocker/NanoFilters#317]
### URLs where this issue occurs (Required)

http://t66y.com/htm_data/2/1904/3506733.html

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/25247024/56712581-94f3b900-6761-11e9-898f-0c0e114c912b.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/25247024/56712636-be144980-6761-11e9-8950-13d41648b1e7.png)

### Describe the issue (Optional if obvious)
You click into any thread and will see a warming in Chinese means "ADblock detected, you need to wait 60s". Then the real content will show after 60s.

### Reproduction Steps (Optional if trivial)
just click into any thread and wait for 60s.

### Anything else you believe to be useful (Optional)
this just happened in these two days. Obviously the website has introduced new method against nano adblocker. 

#### Environment (Required)

- Operating System and Version: WIN10 LTSB 2019
- Browser and Version: chrome 73.0.3683.103
- uBlock Origin Version: 1.18.16
- Nano Defender Version (Optional if you are not using it): 15.0.0.137

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/25247024/56713184-a938b580-6763-11e9-9571-1c9ed1a2ffbe.png)

**Comment by jspenguin2017** [comment]
Not sure how long will the fix last but let's call this good for now.

**Comment by crackerjohn** [comment]
the fix lasted for one day :(

**Comment by jspenguin2017** [comment]
RIP

**Comment by jspenguin2017** [comment]
Has a few small ads placeholders, but can't reproduce anti-adblock.

**Comment by jspenguin2017** [comment]
@mapx- New test link: `http://t66y.com/htm_data/2/1905/3513299.html`

**Comment by crackerjohn** [comment]
wow, looks like the web master checked this issue every week. Now it's more aggressive, once nano adblock is on, it shows 
![image](https://user-images.githubusercontent.com/25247024/57577719-efa24a00-74af-11e9-9fee-aca7ff9ce4da.png) means "web-page contents are destroyed by fliter"

**Comment by jspenguin2017** [comment]
Yea, there's not much we can do.
