### ISSUE TITLE
[Anti-adblock] m4maths.com

### ISSUE THREAD

**Issue by aayushjain** [NanoAdblocker/NanoFilters#318]
### URLs where this issue occurs (Required)
`https://m4maths.com`

### Screenshots (Required)
![1. Screen before clicking the window alert box](https://user-images.githubusercontent.com/10961880/56893928-effb1800-6aa1-11e9-8b6e-664183d185ec.png)
![2. Screen after clicking OK in the alert box. Loaded website content disappears.](https://user-images.githubusercontent.com/10961880/56894036-40727580-6aa2-11e9-8f81-a5878b948ed0.png)

### Screenshot of console (Required, press `F12` to open the console)
![List of JS files not loaded in console.](https://user-images.githubusercontent.com/10961880/56894152-a0691c00-6aa2-11e9-984a-38b16a33919f.png)

### Describe the issue (Optional if obvious)
Adblocking seems to work fine, but anti-adblocker being detected.
Similar to #270

### Reproduction Steps (Optional if trivial)
- Open website. UBO already blocks some scripts as seen in console.
- Yet a window alert asking to disable adblocker comes up (as seen in screenshot 1). Behind the alert-box the website elements load normally. 
- The website does not stop loading, but no network activity is happening.
- Clicking the OK button suddenly hides all loaded website elements (as seen in screenshot 2) and user is asked to disable AdBlocker.
- Same issue persists on other subpages of the same website.

### Anything else you believe to be useful (Optional)
![Screenshot of domains already being blocked by UBO](https://user-images.githubusercontent.com/10961880/56894504-ba572e80-6aa3-11e9-9897-5de0a122cd02.png)
Screenshot of domains already being blocked by UBO

#### Environment (Required)

- Operating System and Version: Windows 10 Pro 1803
- Browser and Version: Firefox 66 (64bit)
- Nano Adblocker Version: Using lists through [uBlock](https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin)
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)

`98,238 network filters ＋ 48,387 cosmetic filters from:`

**Built-in (5/7)**
- uBlock filters​
- uBlock filters – Badware risks​​​
- uBlock filters – Privacy​​​​​
- uBlock filters – Resource Abuse
- uBlock filters – Unbreak

**Ads (2/4)**
- Adblock Warning Removal List​
- EasyList

**Privacy (1/3)**
- EasyPrivacy​

**Malware domains (2/4)**
- Malware Domain List​​​​​
- Malware domains​

**Annoyances (0/6)**

**Multipurpose (1/4)**
- Peter Lowe’s Ad and tracking server list​

**Regions, languages (0/37)**

**Custom (3/3)**
- Nano Defender Integration​​
- Nano Filters​​
- Nano Filters​​ – Whitelist​​

**Comment by mapx-** [comment]
fixed
