### ISSUE TITLE
[Anti-adblock] frag-mutti.de

### ISSUE THREAD

**Issue by bunducafe** [NanoAdblocker/NanoFilters#320]
Another website I cannot get rid of the popup that I am surfing with anti-adblock enabled. Any thoughts on this?

https://www.frag-mutti.de

<img width="1084" alt="Bildschirmfoto 2019-05-01 um 14 43 39" src="https://user-images.githubusercontent.com/15003826/57017446-94569900-6c1f-11e9-928d-ac877f087907.png">
<img width="784" alt="Bildschirmfoto 2019-05-01 um 14 43 17" src="https://user-images.githubusercontent.com/15003826/57017453-9882b680-6c1f-11e9-90e6-71c378fb46ba.png">

- MacOS 10.14.4 
- Chrome 74.0.3729.131: 
- Nano Adblocker Version: 1.0.0.105
- Nano Defender Version: 15.0.0.139

#### Your filter lists (Required)
Default lists enabled

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/57051943-4f435e80-6c41-11e9-99aa-3d7e970a19b8.png)

**Comment by bunducafe** [comment]
Hm, do have the same pop up all the time when Scrips are active. Once I disable the Java Script it runs smoothly without annoyances. That does the trick and I am fine. But on other webpages I might need the script to work properly. Technically we could close it here :)
