### ISSUE TITLE
[Breakage] forbes.com

### ISSUE THREAD

**Issue by hossamee44** [NanoAdblocker/NanoFilters#323]
### URLs where this issue occurs (Required)
https://www.forbes.com/video/6006406737001/#671136e16fec

### Screenshots (Required)

![Annotation 2019-05-07 143316](https://user-images.githubusercontent.com/50141256/57299561-2d305d00-70d5-11e9-84db-cca87cf326bb.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![Annotation 2019-05-07 143453](https://user-images.githubusercontent.com/50141256/57299622-4e914900-70d5-11e9-9cb3-7e840c914924.jpg)

### Describe the issue (Optional if obvious)
video do not work with Nano Adblocker

#### Environment (Required)

- Operating System and Version: windows 10 1903
- Browser and Version: edge Chromium 75.0.3770.18 
- Nano Adblocker Version: 1.0.0.106
- Nano Defender Version (Optional if you are not using it): 15.0.0.140

#### Your filter lists (Required)
Default

**Comment by mapx-** [comment]
fixed in unbreak list
