### ISSUE TITLE
[Ads] oxy.cloud

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#324]
Example Link: https://oxy.cloud/d/kny/2/ecc2b2665c9630c9bf5c94af0a80db44

I'm getting an ad from MediaMonkey there even with the russian regional filter enabled.

**Comment by mapx-** [comment]
```
oxy.cloud##[href^="http://advertisesimple.info/"]
oxy.cloud##[href*="http://et-cod.com/clicks/"]
```

**Comment by jspenguin2017** [comment]
@dimisa-RUAdList

**Comment by dimisa-RUAdList** [comment]
https://hg.adblockplus.org/ruadlist/rev/a37fe9ea5dc0
