### ISSUE TITLE
[Anti-adblock] geilink.com, linuxph.com

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#325]
http://geilink.com/HpHYf
http://linuxph.com/HpHYf

Please use the domain as the title

### Screenshots (Required)
![screenshot-linuxph com-2019 05 08-00-46-19](https://user-images.githubusercontent.com/34688076/57341637-b9b93a80-712a-11e9-9caf-cc6e6ad91685.png)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
Fixed by Nano Defender, download it here: https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb

@mapx- FYI.

**Comment by mapx-** [comment]
both sites are completely broken / down on my side

**Comment by jspenguin2017** [comment]
Yea, the domain no longer resolve... Closing for now.
