### ISSUE TITLE
[Anti-adblock] starzone.cc

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#326]
**URLs where this issue occurs (Required)**
https://www.starzone.cc/?r=aHR0cHM6Ly9kcml2ZS5rbG9wLm1lL2ZpbGUvM2M2NGFm#landing

**Environment (Required)**

    Operating System and Version: Windows 10 Home, build 1809
    Browser and Version: Firefox 66.0.5
    Nano Defender Version: 15.0.0.124 (using uBlock Origin 1.18.16)

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
