### ISSUE TITLE
[Anti-adblock] sataniabatch.blogspot.com

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#328]
Example Link: https://sataniabatch.blogspot.com/2019/01/Forex-is-Invest-of-Future.html#?o=b2835909ef0ee1985aea146a924b6861b0a3c7c513a04cd6ffcdb1c53059067fc6e63b0fb6327ad676363cad82bb7826d1e0ecfd8a2857a8b0f2cc20af64ffa2ce8d3dc4aa0ffd78d423dea730e745e608b41ad7fd8919e0

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
