### ISSUE TITLE
[Anti-adblock] rmdown.com

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoFilters#329]
`http://www.rmdown.com/link.php?hash=1831385108ac59700ee2cf32305584a567a82cf8ed0`

---

the website has a different strategy now. You will see nothing on the page if the nana adblock is on.  Once you disable nano adblock, you will see whole screen of Ads

_Originally posted by @crackerjohn in https://github.com/NanoAdblocker/NanoFilters/issues/186#issuecomment-491468228_

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/af4f95dc68b494681d5bb258929d5ed5b27991ff
