### ISSUE TITLE
tvp.pl

### ISSUE THREAD

**Issue by MajkiIT** [NanoAdblocker/NanoFilters#33]
### Describe the issue (Required)
Adblock on player

### URLs where this issue occurs (Required)
http://sport.tvp.pl/igrzyska/35828422/pjongczang-2018-skoki-narciarskie-m-konkurs-indywidualny-duza-skocznia

### Screenshots (Required)
https://screenshots.firefox.com/e5B7OoegEuiWX1vl/sport.tvp.pl

### Environment (Required)

- Operating System and Version: Win 10
- Browser and Version: FF 58.0.1
- Nano Adblocker Version: 1.0.0.31

#### Your filter lists (Required)

Polish filters, Easylist and all default filters.

**Comment by jspenguin2017** [comment]
I'm getting 404 on that link.

**Comment by MajkiIT** [comment]
Ok I see. It’s end of this stream. Tomorow there are new on page http://sport.tvp.pl/igrzyska/ on transmisje online section.

**Comment by MajkiIT** [comment]
`http://sport.tvp.pl/igrzyska/35828443/pjongczang-2018-hokej-na-lodzie-m-kanada-korea-poludniowa`

**Comment by jspenguin2017** [comment]
I get a blank screen even without extensions.

**Comment by MajkiIT** [comment]
@jspenguin2017 today it's end of stream :(

**Comment by SebaK666** [comment]
Check this:
http://sport.tvp.pl/transmisje
and:
http://sport.tvp.pl/igrzyska/transmisje
During Pyongchang live transmissions

**Comment by jspenguin2017** [comment]
I can't reproduce issues on those links.

**Comment by SebaK666** [comment]
Geo block? I was afraid of it

**Comment by jspenguin2017** [comment]
I got a VPN, and I still can't reproduce it. 
![image](https://user-images.githubusercontent.com/7283682/40571325-04681508-6054-11e8-8d2a-6e91a2598143.png)
