### ISSUE TITLE
[Anti-adblock] folla.life

### ISSUE THREAD

**Issue by hossamee44** [NanoAdblocker/NanoFilters#330]
### URLs where this issue occurs (Required)
http://folla.life/5cb87d05c6661

### Screenshots (Required)
![Annotation 2019-05-12 233016](https://user-images.githubusercontent.com/50141256/57588002-10998800-750e-11e9-8d0e-ab7657f32010.jpg)

### Screenshot of console (Required, press `F12` to open the console)

![Annotation 2019-05-12 233044](https://user-images.githubusercontent.com/50141256/57588006-155e3c00-750e-11e9-9b64-22dfdadf92f5.jpg)

#### Environment (Required)

- Operating System and Version: windows 10 1903
- Browser and Version: edge Chromium  76.0.3782.0 
- Nano Adblocker Version: 1.0.0.107
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)
Deafult

**Comment by jspenguin2017** [comment]
Caught by Nano Defender, get it here: https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb

@mapx- FYI.

**Comment by mapx-** [comment]
fixed
