### ISSUE TITLE
[Breakage] warframe.fandom.com

### ISSUE THREAD

**Issue by Iota147** [NanoAdblocker/NanoFilters#332]
### URLs where this issue occurs (Required)

https://warframe.fandom.com/wiki/*

### Screenshots (Required)
**What it looks like with NA active**
![image](https://user-images.githubusercontent.com/9082996/57962734-d999ec80-78e8-11e9-9f99-e646f4bd9b89.png)
**What it's supposed to look like (minus the ads) **
![image](https://user-images.githubusercontent.com/9082996/57962754-16fe7a00-78e9-11e9-83b1-c76860f62e0e.png)

### Screenshot of console (Required, press `F12` to open the console)
**Nano AdBlocker active**
![image](https://user-images.githubusercontent.com/9082996/57962764-3c8b8380-78e9-11e9-9741-35d226bafe5a.png)

### Reproduction Steps (Optional if trivial)

The particular page shown [https://warframe.fandom.com/wiki/Prime_Vault](https://warframe.fandom.com/wiki/Prime_Vault) should allow for easy replication.

#### Environment (Required)

- Operating System and Version: Windows 10 Educational Version 1809
- Browser and Version: Chrome Version 74.0.3729.157 (Official Build) (64-bit)
- Nano Adblocker Version: v1.0.0.109
- Nano Defender Version (Optional if you are not using it): v15.0.0.146

#### Your filter lists (Required)

Left as Default

#### Your custom filters (Required if you have any)
! 08/04/2019 https://www.digitaltrends.com
www.digitaltrends.com##.fc-dialog-container > section
www.digitaltrends.com##.fc-ab-root > .fc-dialog-overlay
www.digitaltrends.com##.fc-ab-root

#### Your other extensions (Required if you have any)
LastPass
Poper Blocker
Remote Torrent Adder
Checker Plus for Gmail
LinkedIn
AutoRefresh Pro
Chrome Remote Desktop
Discord
Grammarly

If anything is required, let me know.

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/57962884-05fa3c80-78da-11e9-8b51-aca9bcf78ee4.png)

**Comment by Iota147** [comment]
> Works fine for me.
> ![image](https://user-images.githubusercontent.com/7283682/57962884-05fa3c80-78da-11e9-8b51-aca9bcf78ee4.png)

Try the link in the description. The asterisk is because there's more than just one page causing the issue.

**Comment by jspenguin2017** [comment]
Next time, put a working test link on top. Still can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/57962905-596c8a80-78da-11e9-89fd-0bbd60d9df90.png)
