### ISSUE TITLE
[Anti-adblock] powerclicks.xyz

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#334]
### URLs where this issue occurs (Required)
Adblock detected on https://powerclicks.xyz/TN1L2syR
Use the domain as the title

https://powerclicks.xyz

### Screenshots (Required)

![screenshot-powerclicks xyz-2019 05 19-02-58-35](https://user-images.githubusercontent.com/34688076/57977175-3b8a4d00-79e2-11e9-9cb0-ecf1102045e7.png)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
Caught by Nano Defender. 

@mapx-

**Comment by mapx-** [comment]
fixed
