### ISSUE TITLE
https://www.sbsun.com

### ISSUE THREAD

**Issue by ansul1001** [NanoAdblocker/NanoFilters#336]
### URLs where this issue occurs (Required)
https://www.sbsun.com

### Screenshots (Required)
![Capture](https://user-images.githubusercontent.com/49883320/58187743-38a28d00-7c6c-11e9-9c78-603d76f179e7.PNG)

### Screenshot of console (Required, press `F12` to open the console)
![Capture 2](https://user-images.githubusercontent.com/49883320/58187863-79020b00-7c6c-11e9-9299-4a6e47925a1e.PNG)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)
![Capture 3](https://user-images.githubusercontent.com/49883320/58187960-b1a1e480-7c6c-11e9-9b8a-5f5b2a16aa26.PNG)

**Comment by mapx-** [comment]
fixed

**Comment by ansul1001** [comment]
Yep works now thanks
