### ISSUE TITLE
gamersheroes.com

### ISSUE THREAD

**Issue by TheOne320** [NanoAdblocker/NanoFilters#344]
### URLs where this issue occurs (Required)
http://www.gamersheroes.com/game-guides/assassins-creed-origins-legendary-weapons-guide/#

### 

### Screenshots (Required)
<img width="469" alt="gamersheroes" src="https://user-images.githubusercontent.com/7705568/58716677-d6632e00-83c9-11e9-9e3a-55d77ac07f62.PNG">

### Screenshot of console (Required, press `F12` to open the console)
Edge
<img width="475" alt="gamersheroes2" src="https://user-images.githubusercontent.com/7705568/58716745-fe529180-83c9-11e9-9ae6-309c762d7739.PNG">

Firefox
<img width="959" alt="gamersheroes5" src="https://user-images.githubusercontent.com/7705568/58717540-bdf41300-83cb-11e9-9835-e384a1f5c6ab.PNG">

### Describe the issue (Optional if obvious)
Unable to open collapsible when nano adblocker is enabled.

### Reproduction Steps (Optional if trivial)

click on "+" symbol.

#### Environment (Required)

- Operating System and Version: Windows 10 x64
- Browser and Version: Tested on Firefox 67 x64 and Edge 
- Nano Adblocker Version:
Firefox version 10.0.0. 112 and Edge version 0.0.112.0
- Nano Defender Version (Optional if you are not using it): 
Firefox version: 15.0.0.147

#### Your filter lists (Required)

Edge version:
<img width="362" alt="gamersheroes3" src="https://user-images.githubusercontent.com/7705568/58717091-baac5780-83ca-11e9-989d-09ff54cb8287.PNG">

Firefox version:
<img width="338" alt="gamersheroes4" src="https://user-images.githubusercontent.com/7705568/58717438-84230c80-83cb-11e9-8057-660f2ccf471f.PNG">

#### Your other extensions (Required if you have any)
Firefox
![gamersheroes6](https://user-images.githubusercontent.com/7705568/58717716-2511c780-83cc-11e9-9c2a-f6963ca8968f.PNG)

**Comment by mapx-** [comment]
update your lists

**Comment by TheOne320** [comment]
Cool it works now. Thanks for fixing it so quickly.
