### ISSUE TITLE
[Anti-adblock] oregonlive.com

### ISSUE THREAD

**Issue by Seantourage** [NanoAdblocker/NanoFilters#346]
### URLs where this issue occurs (Required)
[oregonlive.com](url)

### Screenshots (Required)
![oregonlive](https://user-images.githubusercontent.com/50155192/58821141-48fe2480-85e9-11e9-9a13-1e66a375a43d.png)

### Screenshot of console (Required, press `F12` to open the console)
![console](https://user-images.githubusercontent.com/50155192/58821147-4b607e80-85e9-11e9-9b48-ac2ad7408da8.png)

#### Environment (Required)

- Operating System and Version: Windows 10 Pro - 1903
- Browser and Version: Firefox 67
- Nano Adblocker Version: 1.0.0.113
- Nano Defender Version (Optional if you are not using it): 15.0.0.149

#### Your filter lists (Required)
![filters](https://user-images.githubusercontent.com/50155192/58821197-68954d00-85e9-11e9-8e2f-f4bae0e44881.png)

#### Your custom filters (Required if you have any)
None

#### Your other extensions (Required if you have any)
Bitwarden
Universal Bypass

**Comment by mapx-** [comment]
fixed as annoyance
