### ISSUE TITLE
[Anti-adblock] lifesurance.info

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#347]
Example Link: http://lifesurance.info/?id=Nm93WCtscHhocFU2OGpWdEFFZFh5U0FjbXNQTzAzZmx4NlNTR2JwRFp6Z0pHZkpBY0RvbmZ5OUF3NHNTTDJxcEFrS2ZDdW95bkxBdnpDYTVROTRCQ0E9PQ==

**Comment by mapx-** [comment]
fixed 3 days ago, update the lists before reporting

**Comment by Cyberavater** [comment]
Okay, Thanks for the feedback!

**Comment by Cyberavater** [comment]
BTW, Shouldn't it be auto-updated?

**Comment by mapx-** [comment]
yep, if you wait other 1-2 days the list will be updated but when report here or on uAssets just be sure the issue is still to be fixed (and for this ..you have to manually update the lists)

**Comment by Cyberavater** [comment]
Okay, will keep that in mind. Thanks for the advice!
