### ISSUE TITLE
[Annoyance, Cookie Notice] virustotal.com

### ISSUE THREAD

**Issue by hawkeye116477** [NanoAdblocker/NanoFilters#349]
### URLs where this issue occurs (Required)

`https://www.virustotal.com/gui/home/upload`

### Screenshots (Required)
![Screenshot_20190605_205722](https://user-images.githubusercontent.com/19818572/59016584-db990080-8841-11e9-8379-0d3520a3f502.png)

### Describe the issue (Optional if obvious)
Cookie message in open shadow root.

### Anything else you believe to be useful (Optional)
uBO can hide it with `virustotal.com###euConsent`, but Nano Adblocker on Chromium can't (on Nano Adblocker on FF this works).
Possible solution: `virustotal.com##+js(nanop-easy-set-cookie.js, euConsent=1)`.

#### Environment (Required)

- Operating System and Version: Manjaro 18.0.4 Illyria
- Browser and Version: Chromium 75.0.3770.80
- Nano Adblocker Version: 1.0.0.113
- Nano Defender Version (Optional if you are not using it): N/A

#### Your filter lists (Required)
![Screenshot_20190606_100503](https://user-images.githubusercontent.com/19818572/59016884-96290300-8842-11e9-84e4-a5b0bc3db256.png)

#### Your other extensions (Required if you have any)
N/A

**Comment by jspenguin2017** [comment]
UserCSS goes through shadow root?

**Comment by jspenguin2017** [comment]
That's so weird... OK, I'll prioritize https://github.com/NanoAdblocker/NanoCore/issues/243
Hopefully I can have a look at it this weekend.

**Comment by jspenguin2017** [comment]
I'll close this as duplicate. I want to keep the functionality of DOM Inspector though, so I need to think of a way to have the best of both worlds.
