### ISSUE TITLE
[Anti-adblock] solvetube.site

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#350]
Example Link: http://solvetube.site/how-to-install-teenage-mutant-ninja-turtles-mutants-in-manhattan-game-without-errors/

From: http://oceanofgames.com/teenage-mutant-ninja-turtles-mutants-in-manhattan-free-download/

The download will not start if the NanoAdblocker is not disabled.

Edit: You'll have to use the 2nd link's download button (and wait a little bit) to reproduce this issue.

**Comment by mapx-** [comment]
test
```
||pagead2.googlesyndication.com/pagead/$script,redirect=noopjs,domain=solvetube.site,important
||google-analytics.com/analytics.js$script,redirect=google-analytics.com/analytics.js,important
@@*$script,domain=solvetube.site
```
