### ISSUE TITLE
[Anti-adblock] mega-debrid.eu

### ISSUE THREAD

**Issue by ramyong** [NanoAdblocker/NanoFilters#351]
### URLs where this issue occurs (Required)

https://www.mega-debrid.eu/index.php?page=debrideur&lang=en

### Screenshots (Required)
![msg anti-adblock](https://user-images.githubusercontent.com/51445867/59034701-e8324e80-886b-11e9-94cd-dc49e52d3ebb.PNG)

### Screenshot of console (Required, press `F12` to open the console)
![console mega-debrid](https://user-images.githubusercontent.com/51445867/59034723-fda77880-886b-11e9-89c3-e3a8d61c87f4.PNG)

### Describe the issue (Optional if obvious)
It is when i try to debride a link

#### Environment (Required)

- Operating System and Version: Microsoft Windows 10 Pro version 17134.765
- Browser and Version: Chromium Version 74.0.3729.169
- Nano Adblocker Version: 1.0.0.113
- Nano Defender Version : 15.0.0.150

#### Your filter lists (Required)

Deafult

**Comment by mapx-** [comment]
see if works
`mega-debrid.eu##+js(set-constant.js, Advertisement, 1)`

**Comment by ramyong** [comment]
@mapx- it works, thanks a lot !
