### ISSUE TITLE
[Anti-adblock] infoladnydom.pl

### ISSUE THREAD

**Issue by krystian3w** [NanoAdblocker/NanoFilters#353]
### URLs where this issue occurs (Required)

`http://infoladnydom.pl/temat/ladnydom/siding+wewn%C4%99trzny`

### Screenshots (Required)

![](https://user-images.githubusercontent.com/35370833/59164018-424f4000-8b08-11e9-9ff5-ab9d4a9f46ac.png)

### Screenshot of console (Required, press `F12` to open the console)

N/A

### Describe the issue (Optional if obvious)

Anti-adblock with recommend `Adblock Warning Removal List`

### Reproduction Steps (Optional if trivial)

try activate `Adblock Warning Removal List` in uBO / Nano Adblocker

### Anything else you believe to be useful (Optional)

Should visible after 2-nd / 3-rd refresh page

#### Environment (Required)

- Operating System and Version:  Windows 10
- Browser and Version:  Firefox 67.0.1
- Nano Adblocker Version:  uBo 1.19.6 / Nano Adblocker 1.0.113
- Nano Defender Version (Optional if you are not using it):  N/A

#### Your filter lists (Required)

Default.

#### Your custom filters (Required if you have any)

PL

#### Your other extensions (Required if you have any)

N/A

---

fix:

`@@||onnetwork.tv/adblock_notify.js$script,1p`

or

`onnetwork.tv##+js(set-constant.js, isAdBlockActive, false)`

**Comment by jspenguin2017** [comment]
https://github.com/NanoAdblocker/NanoFilters/commit/72f4ac445e5a8bf96bbf7482e19e1c133e29a577
