### ISSUE TITLE
[Anti-adblock] reevown.com

### ISSUE THREAD

**Issue by RenVer** [NanoAdblocker/NanoFilters#355]
### URLs where this issue occurs (Required)
https://reevown.com/

### Screenshots (Required)
[![1.png](https://i.postimg.cc/fLGPXLwW/1.png)](https://postimg.cc/qhGQHphW)

### Screenshot of console (Required, press `F12` to open the console)
[![3.png](https://i.postimg.cc/5ypkrmBy/3.png)](https://postimg.cc/GT8Q8GSn)

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Chrome 75.0.3770.80
- Nano Adblocker Version: 1.0.0.114
- Nano Defender Version (Optional if you are not using it): 15.0.0.151

#### Your filter lists (Required)

Default filters in the "built-in" section.

**Comment by jspenguin2017** [comment]
Can't reproduce.
