### ISSUE TITLE
aranzulla.it

### ISSUE THREAD

**Issue by Barabba2** [NanoAdblocker/NanoFilters#356]
#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment]
I don't see any problem. 
![image](https://user-images.githubusercontent.com/7283682/59396198-d3aaf600-8d44-11e9-9cfe-06cd6b5a80d7.png)
