### ISSUE TITLE
csmonitor.com

### ISSUE THREAD

**Issue by llacb47** [NanoAdblocker/NanoFilters#357]
### URLs where this issue occurs (Required) 
`https://www.csmonitor.com/Environment/2019/0610/How-Baltimore-is-saving-urban-forests-and-its-city`

### Screenshots (Required)
![Screenshot](https://user-images.githubusercontent.com/16567977/59527084-9f504a80-8ea8-11e9-8052-95f7dfdcd3d6.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![Console screenshot](https://user-images.githubusercontent.com/16567977/59527193-e63e4000-8ea8-11e9-9f13-63faf2337a1f.jpg)

### Describe the issue (Optional if obvious)
Anti-adblock nag box appears after a few seconds

### Reproduction Steps (Optional if trivial)
Go to the page and wait a few seconds

#### Environment (Required)

- Operating System and Version: Windows 10 
- Browser and Version: Chromium Stable Build 70.0.3538.110 (64-bit)
- Nano Adblocker Version: 1.0.0.114
- Nano Defender Version (Optional if you are not using it): 15.0.0.152

#### Your filter lists (Required)
![Filterlists](https://user-images.githubusercontent.com/16567977/59527330-48974080-8ea9-11e9-8128-0bc8804e298a.jpg)

#### Your custom filters (Required if you have any)
[Here](https://pastebin.com/raw/P7bMpy9N)
#### Your other extensions (Required if you have any)
None that would conflict with Nano

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/e12b1d58377d38cfe4f0855663909ce2c20a781f
