### ISSUE TITLE
[Anti-adblock] razergamingseries.com 

### ISSUE THREAD

**Issue by Sopor** [NanoAdblocker/NanoFilters#359]
### URLs where this issue occurs (Required)
https://razergamingseries.com/razer-abyssus-essential

-->

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/5789283/59538675-e6672b80-8efa-11e9-9ae5-f2dd5653f928.png)

### Environment (Required)
- Operating System and Version: Windows 10
- Browser and Version: Firefox 67.0.2
- Nano Adblocker Version: uBlock origin 1.19.6
- Nano Defender Version (Optional if you are not using it): 15.0.0.152

### Your filter lists (Required)
- [x] uBlock filters
- [x] uBlock filters – Annoyances​​​​​
- [x] uBlock filters – Badware risks​
- [x] uBlock filters – Privacy​​​​​
- [x] uBlock filters – Resource abuse​​​​​
- [x] uBlock filters – Unbreak​​​​​
- [x] Adblock Warning Removal List
- [x] EasyPrivacy
- [x] Malware Domain List
- [x] Malware domains
- [x] Fanboy’s Annoyance List
- [x] Peter Lowe’s Ad and tracking server list
- [x] SWE: Frellwit's Swedish Filter​​​​​

**Comment by mapx-** [comment]
fixed
