### ISSUE TITLE
[Anti-adblock] ovagames.com

### ISSUE THREAD

**Issue by ajhix36** [NanoAdblocker/NanoFilters#360]
### URLs where this issue occurs (Required)

http://www.ovagames.com/

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/15352262/59576730-6eb11200-905c-11e9-85f1-095340eb4f02.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/15352262/59576734-72449900-905c-11e9-836e-9190af5a4168.png)

### Describe the issue (Optional if obvious)
Anti-adblock nag box appears after a few seconds

### Reproduction Steps (Optional if trivial)

Go to the page and wait a few seconds

#### Environment (Required)

- Operating System and Version: Windows 10 v1903
- Browser and Version:  Chrome, Version 74.0.3729.169 (Official Build) (64-bit)
- Nano Adblocker Version:  uBlock Origin v1.19.6
- Nano Defender Version (Optional if you are not using it): Unsure, I installed it today.

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/15352262/59576862-eda64a80-905c-11e9-9098-360892a2d1ae.png)

#### Your other extensions (Required if you have any)

uBlock Origin Extra

**Comment by jspenguin2017** [comment]
You didn't install Nano Defender. Get it here: https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb

**Comment by ajhix36** [comment]
You are correct, I am sorry, I did all the advanced steps and didn't realize I hadn't done the real step one. It works now. <3
