### ISSUE TITLE
[Anti-adblock] calciomercato.com

### ISSUE THREAD

**Issue by Nikimen16999999999** [NanoAdblocker/NanoFilters#361]
URLs where this issue occurs (Required)
https://www.calciomercato.com/news/napoli-avanti-tutta-per-james-contatti-positivi-in-giornata-fiss-62443

Screenshot of console (Required, press F12 to open the console)
<a href="https://imgur.com/zsjPpWE"><img src="https://i.imgur.com/zsjPpWE.png" title="source: imgur.com" /></a>
### Describe the issue (Optional if obvious)
Reproduction Steps (Optional if trivial)
When Nano Adblocker is on, it shows anti-adblock warning.

Your filter lists (Required)

ublock-origin default install + custom nano defender

Environment (Required)
Operating System and Version: Windows 10
Browser and Version: Chrome v75.0.3770.100 (Official Build) (64-bit)
Nano Adblocker Version: uBlock origin 1.20.0
Nano Defender Version (Optional if you are not using it): 15.0.0.153

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Can you point me to the placeholders?

**Comment by Nikimen16999999999** [comment]
Thanks for the quick fix.

**Comment by jspenguin2017** [comment]
@okiehsch Never mind, the placeholder is removed by Italian regional filters.
