### ISSUE TITLE
[Anti-adblock] next-episode.net

### ISSUE THREAD

**Issue by kaktus42** [NanoAdblocker/NanoFilters#363]
next-episode.net

### Screenshots (Required)
![next-episode](https://user-images.githubusercontent.com/1608815/59878236-1190c580-93a8-11e9-8916-f2f5f7baba05.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![next-episode2](https://user-images.githubusercontent.com/1608815/59878340-4d2b8f80-93a8-11e9-861f-c80e4d450105.jpg)

### Describe the issue (Optional if obvious)
After Login, a popup opens, extorting to disable the ad-blocker.

### Reproduction Steps (Optional if trivial)
Go to website
Log In (via top left drop down form)

### Anything else you believe to be useful (Optional)
N/A

#### Environment (Required)

- Operating System and Version: Windows 10 (64-Bit)
- Browser and Version: Firefox 67.0.4 (64-Bit)
- Nano Adblocker Version: 1.0.0.41
- Nano Defender Version: 15.0.0.153

#### Your filter lists (Required)
**All Enabled:**
Nano Defender Integration​​​​​
Nano filters​
Nano filters – Whitelist
uBlock filters​
uBlock filters – Badware
uBlock filters – Privacy​
uBlock filters – Resource abuse​
uBlock filters – Unbreak​
Adblock Warning Removal List
EasyList​
EasyPrivacy
Malware Domain List
Malware domains​
Fanboy's Social Blocking List
Peter Lowe's Ad and tracking server list​​​​​
DEU: EasyList Germany​​​​​

#### Your custom filters (Required if you have any)
N/A

#### Your other extensions (Required if you have any)
N/A

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/59890376-d6819880-938d-11e9-80cb-46573ec0517a.png)

**Comment by jspenguin2017** [comment]
Can't reproduce without logging in. May need a test account. 
![image](https://user-images.githubusercontent.com/7283682/59890376-d6819880-938d-11e9-80cb-46573ec0517a.png)

**Comment by kaktus42** [comment]
I created a test-account, but was unable to reproduce it with that brand new account. They seem to have a period, where the site is without ads and without the anti ad-blocker.

Is there an instruction on how to fix this myself? I am an experienced programmer, also in JS.

**Comment by jspenguin2017** [comment]
If you're a programmer you can try to reverse engineer their detection code, and figure out what they are doing then deploy a countermeasure.

**Comment by kaktus42** [comment]
Unfortunately I was not able to identify the code that generates the overlay. I can not find it in the debugger of the dev-console in Firefox

**Comment by mapx-** [comment]
fixed.

alternative filter
`next-episode.net##+js(abort-on-property-read.js, scrfail2)`

we had before `next-episode.net##+js(abort-on-property-read.js, scrfail)`
