### ISSUE TITLE
[Breakage] drive.google.com

### ISSUE THREAD

**Issue by krystian3w** [NanoAdblocker/NanoFilters#365]
### URLs where this issue occurs (Required)

`https://drive.google.com/drive/folders/1gV6kYi-qP0lUIxtVcklMrusd8p2q9d08`

### Screenshots (Required)

N/A

### Screenshot of console (Required, press `F12` to open the console)

N/A

### Describe the issue (Optional if obvious)

N/A

### Reproduction Steps (Optional if trivial)

block CSP break Google scan file, so I must wait 30 seconds to fail scan file.

### Anything else you believe to be useful (Optional)

helps:

```
@@||csp.withgoogle.com/csp/$csp_report,domain=google.com
||google.com^*/viewerimpressions?$badfilter
```

#### Environment (Required)

- Operating System and Version:  Windows 10
- Browser and Version:  Chrome 75
- Nano Adblocker Version:  1.0.115
- Nano Defender Version (Optional if you are not using it):  N/A

#### Your filter lists (Required)

Default

#### Your custom filters (Required if you have any)

N/A

#### Your other extensions (Required if you have any)

N/A

**Comment by jspenguin2017** [comment]
Their service may be unstable or down right now. It doesn't work in guest mode neither. 
![image](https://user-images.githubusercontent.com/7283682/59967971-94706800-94ef-11e9-95fa-6a5eb34d856a.png)

**Comment by krystian3w** [comment]
No possible view zip online on Drive.

Download no start in minute wait?

**Comment by jspenguin2017** [comment]
Same behavior in guest mode, how did you conclude it's a filter issue?

**Comment by krystian3w** [comment]
Second is form EasyPrivacy first from "block CSP reports":

`no-csp-reports: * true`

**Comment by jspenguin2017** [comment]
You didn't answer my question.

**Comment by krystian3w** [comment]
ok rules issue:

```
drive.google.com https://csp.withgoogle.com/csp/ csp_report allow
```

**Comment by jspenguin2017** [comment]
I have no idea what you're trying to say.

**Comment by krystian3w** [comment]
I try see:

Block CSP on google drive break scan files before download, also generate lag waiting to fail scan (+30 s / 1 minute more wait to start download small zip files).

**Comment by jspenguin2017** [comment]
Why does CSP reports have anything to do with virus scanning? That does not make any sense. 

Here I have tried it in guest mode, with no extensions loaded, the scanning still fail: 
![image](https://user-images.githubusercontent.com/7283682/59979850-79166300-95aa-11e9-97ec-0eecb3e34b5d.png)

**Comment by jspenguin2017** [comment]
The files are not zip files, they are 7z files, a different format. I'm not sure if Google Drive is suppose to be able to preview & scan those files, but either way, it's an issue on their end.

**Comment by krystian3w** [comment]
Yes fail and and extends start the download time from 30 seconds to even 1 minute.

**Comment by jspenguin2017** [comment]
This issue has nothing to do with Nano. You're wasting my time. Locking.
