### ISSUE TITLE
[Ads] getsl.me

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#367]
Example Link: http://getsl.me/glR2
You'll see (well not technically see it but it'll coverup invisibly so you'll redirect to a false site when you click on anywhere on the page) it after completing the captcha.

I've marked it with the element picker (if it helps);
> getsl.me##[href="//iz682noju02ye5.com/1462751.html"]

**Comment by mapx-** [comment]
add
`getsl.me##A[href$=".html"][rel="nofollow norefferer noopener"]`

**Comment by mapx-** [comment]
or
`getsl.me##+js(set-constant.js, atob, trueFunc)`

**Comment by mapx-** [comment]
fixed

**Comment by Cyberavater** [comment]
Somehow it's re-appearing;
http://gsurl.co/gCQM

**Comment by jspenguin2017** [comment]
That's a different domain. 
https://github.com/NanoMeow/QuickReports/issues/1545
