### ISSUE TITLE
[Other] pasted.co

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#368]
Example Link: http://pasted.co/a19e8e3d

Ad videos at the lower end of the page (no need to scroll down tho, you'll hear the sound of that video after a few secs).

**Comment by jspenguin2017** [comment]
I see a few embedded Twitch streams, but no auto-playing videos.

**Comment by Cyberavater** [comment]
For some reason, it's auto-playing for me.

**Comment by Sopor** [comment]
For me it is auto-playing, the first video is not but the second video is playing.

**Comment by jspenguin2017** [comment]
Hum... Yea, sometimes one of the video plays... @okiehsch Can you have a look?

**Comment by okiehsch** [comment]
`||player.twitch.tv^$frame,domain=pasted.co`
@ryanbr

**Comment by ryanbr** [comment]
Why would we block twitch?

**Comment by okiehsch** [comment]
It's about autoplaying videos on a pastebin site.
It's atleast an annoyance on such a site no?

**Comment by jspenguin2017** [comment]
Also, I noticed that the new captcha design doesn't look secure, maybe it can be bypassed.

**Comment by Sopor** [comment]
@jspenguin2017 The captcha is moving around. Is that easy to bypass?

**Comment by jspenguin2017** [comment]
For me, the content is covered under the captcha overlay.

**Comment by Sopor** [comment]
This is how it looks for me, but it seems to depend on the web browser i use.

![nanofilter](https://user-images.githubusercontent.com/5789283/60771726-27162700-a0ec-11e9-8b26-c1b37cdc9c30.gif)

**Comment by Cyberavater** [comment]
Removing the overlay and both videos with element picker should work.

**Comment by jspenguin2017** [comment]
I meant removing the entire overlay.

**Comment by Cyberavater** [comment]
This Issue is no longer relevant.
