### ISSUE TITLE
spiegel.de

### ISSUE THREAD

**Issue by rix1337** [NanoAdblocker/NanoFilters#37]
**http://www.spiegel.de/** today started displaying a harder to circumvent anti-adblocking technique

![spiegel de](https://user-images.githubusercontent.com/9930448/36905060-9eec02f6-1e32-11e8-99ee-6cfe8e77b30e.JPG)

![console](https://user-images.githubusercontent.com/9930448/36905162-ded0df2c-1e32-11e8-9b28-bfe7482fdea0.JPG)

No custom filters,.. this seems resistant!

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/NanoAdblocker/NanoDefender/issues/28

**Comment by jspenguin2017** [comment]
NVM it broke again.

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/NanoAdblocker/NanoDefender/issues/28

**Comment by jspenguin2017** [comment]
Update your filters.
