### ISSUE TITLE
[Forced Notification] sprysphere.com, ouo.today, oxy.cloud

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoFilters#370]
Test link: `http://sprysphere.com/BiZZ`

---

See also: 
https://github.com/uBlockOrigin/uAssets/issues/5890
More test links in original issue. 

---

May be useful: 
The destination URL is hard coded in the DOM. 
https://github.com/uBlockOrigin/uAssets/issues/5890#issuecomment-508495628

---

These issues are merged into here: 
https://github.com/NanoMeow/QuickReports/issues/3231

**Comment by jspenguin2017** [comment]
Also, need to update filters policy to address these new ways to misuse browser features.

**Comment by ghajini** [comment]
Another such site (may be more URL shorteners)



`https://ww10.ouo.today/?cr=aHR0cDovL3VsdGltYXRlLnR1cmtkb3duLmNvbS9saW5rLnBocD9saW5rPWFIUjBjSE02THk5Nk1ta3VZMjl0TDI5a1IweHhSMHQ2&oID=82904`

Screenshot=

`https://user-images.githubusercontent.com/20338483/61239037-7e8c4680-a72d-11e9-847c-aceea5002d66.jpg`

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/issues/5890#issuecomment-593845837

`https://oxy.cloud/d/pyH`

**Comment by ghajini** [comment]
Actually many random domains are doing this ,you can't count 
@jspenguin2017

**Comment by jspenguin2017** [comment]
First one fixed with generic rule. 

Still have two more to fix, unfortunately, it looks like these would need specific rules. 

`https://ww10.ouo.today/?cr=aHR0cDovL3VsdGltYXRlLnR1cmtkb3duLmNvbS9saW5rLnBocD9saW5rPWFIUjBjSE02THk5Nk1ta3VZMjl0TDI5a1IweHhSMHQ2&oID=82904`

`https://oxy.cloud/d/pyH`

**Comment by jspenguin2017** [comment]
I think specific ones are better implemented as script snippets, although I'm not sure if they should be privileged.

**Comment by jspenguin2017** [comment]
`https://oxy.cloud/d/pyH` fixed with specific rule.

**Comment by jspenguin2017** [comment]
@ghajini All test links here are fixed. Let me know if there are more.

**Comment by ghajini** [comment]
How to test? 
I tried version nano defender pro 15.0.0.193
(& all relevant extra installation steps for ublock origin), 

doesn't work for `ouo.today` and `oxy.cloud`

**Comment by jspenguin2017** [comment]
You need to download the tip of master, new changes will be included in 15.0.0.194.

**Comment by ghajini** [comment]
Did you mean "load unpacked extension" I downloaded ublock protector repo in zip format,extracted then Dev mode ,loaded from unpacked, it says manifest error

**Comment by jspenguin2017** [comment]
@ghajini You need to load the `src` directory into a Chromium-based browser. If you can't figure it out, I'll release a build in a few days.

**Comment by ghajini** [comment]
Confirmed to be working for me....

Did you plan to fix bypass for 

`https://linkvertise.com/26117/553.2888002977298/dynamic?r=aHR0cDovLzE2My4xNzIuODMuMTQ1L2RlYi9hcGkvYXBpMjAvP2Fkcz1hSFIwY0hNNkx5OTBhVzU1ZFhKc0xtTnZiUzl6ZW01bE16aDQ%3D`
(https://github.com/uBlockOrigin/uAssets/issues/6065)

& remove ads here
https://github.com/NanoMeow/QuickReports/issues/2096

These fixes will be beneficial, (counting from how many days it doesn't get fixed in ublock origin)

**Comment by jspenguin2017** [comment]
@ghajini Those are quite different and require different solutions. I created separate issues for them.

**Comment by jspenguin2017** [comment]
@ghajini Those are different and require completely different solutions, I'll take a look later. I created separate issues for them.

**Comment by ghajini** [comment]
`https://shre.su/F0NV`
Redirects to intermediate sites
`https://1.keilanarius.com/index/c1?diff=8&source=og&campaign=18410&content=trabayle&clickid=i0mdw9gy6tdfgyfp&aurl=https%3A%2F%2Fshre.su%2Fredirect&an=&term=F0NV&site=82166&darken=0&allFull=0&isubs=0#`
Or

`https://gumk.pro/access-website?h=waWQiOjEwMjg3NjQsInNpZCI6MTAzNTcwNiwid2lkIjo2NDY3MCwic3JjIjoyfQ==eyJ&click_id=&si1=F0NV&si2=82166`

Which do forced notifications to proceed further

**Comment by jspenguin2017** [comment]
@ghajini 
https://github.com/NanoMeow/QuickReports/issues/3429
Do not dig up old threads, open new issue instead.
