### ISSUE TITLE
[Breakage] kissanime.ru

### ISSUE THREAD

**Issue by w4tadrag** [NanoAdblocker/NanoFilters#371]
Test Link
 https://kissanime.ru/Anime/Mob-Psycho-100-II-Dub/Episode-005?id=158585&s=nova

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/32439406/60742784-bb418c00-9f3c-11e9-9cff-65e19832b60a.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/32439406/60742821-d7452d80-9f3c-11e9-9cbf-06d7fd56b51f.png)

### Describe the issue (Optional if obvious)
Video player dissapears when the video starts, found out Nano Defender was causing it as I disabled it and it worked. Re-enabled it and had the same issue

### Reproduction Steps (Optional if trivial)
1. go to the link provided above
2. press play on the video (I chose Nova and Beta servers)
3. video disappears

#### Environment (Required)

- Operating System and Version: Win 10 1809
- Browser and Version: Chrome 75.0.3770.100
- Nano Adblocker Version: 1.0.0.120
- Nano Defender Version (Optional if you are not using it): 15.0.0.153

#### Your filter lists (Required)
default

**Comment by jspenguin2017** [comment]
@okiehsch There's also a pretty big blank space, not sure if you want to remove it: 
```
kissanime.*##[id^='adsIfrme']:has(:scope > iframe[src^='/ads/'])
```

**Comment by okiehsch** [comment]
Thanks.
