### ISSUE TITLE
[Annoyance, Cookie Wall] nl.hardware.info, tweakers.net

### ISSUE THREAD

**Issue by DrIT2016** [NanoAdblocker/NanoFilters#374]
### Describe the issue (Required)
Many of the cookie filters in Annoyance don't see to work? Like f.e. hardware.info, buienradar and marktplaats.

### Screenshot of console (Required, press `F12` to open the console)
![cookies](https://user-images.githubusercontent.com/17800931/61533392-0a9fb600-aa2d-11e9-97d2-a9978151c759.png)

### URLs where this issue occurs (Required if applicable)
nl.hardware.info
buienradar.nl
marktplaats.nl

#### Environment (Required)

- Operating System and Version: Windows 7
- Browser and Version: Vivaldi 2.1.1337.36 (Stable channel) (64-bit)
- Nano Adblocker Version: 1.0.0.121
- Nano Defender Version (Optional if you are not using it): 15.0.0.155

#### Your filter lists (Required)
Default ootb + Nano filters – Annoyance

**Comment by jspenguin2017** [comment]
GeoLock. 
Reproduced on the first 2 domains. 
`marktplaats.nl` is not a cookie wall, you need to report it to Fanboy if it's not already fixed there.

**Comment by DrIT2016** [comment]
Also tweakers.net. Marktplaats and buienradar seems fixed with fanboy's annoyance and cookie list.
Is there something i can do myself? I i can understand how auto accept with js function etc works?

**Comment by jspenguin2017** [comment]
Have a look at `nanop-click-elements-onready.js` and `nanop-click-elements-onload.js`. You may need to change advanced settings `nanoMakeUserFiltersPrivileged`.

**Comment by DrIT2016** [comment]
Thanks, did indeed have to set advanced settings nanoMakeUserFiltersPrivileged to true for my own filters to work.

These filters do the trick for the mentioned sites:
tweakers.net##+js(nanop-click-elements-onready.js, #cookieAcceptForm > span > button)
hardware.info##+js(nanop-click-elements-onload.js, #decision)

Btw this one also works: hardware.info##+js(nanop-click-elements-onready.js, .cookie-wall__cookie-container__cookie > button#decision[name="accept"])
