### ISSUE TITLE
[Anti-adblock] cnbc.com

### ISSUE THREAD

**Issue by kpad-git** [NanoAdblocker/NanoFilters#378]
### URLs where this issue occurs (Required)
https://www.cnbc.com/video/2019/07/18/david-rosenberg-slumping-earnings-point-to-economic-recession.html

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/43962888/61633904-1aeaa780-ac5e-11e9-9085-66dfaaebb5eb.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/43962888/61633939-2e960e00-ac5e-11e9-9777-ad5279ec6753.png)

#### Environment (Required)

- Operating System and Version: win10 professional
- Browser and Version: Chrome Version 75.0.3770.142 (Official Build) (64-bit)
- Nano Adblocker Version: Ublock Origin 1.21.4
- Nano Defender Version (Optional if you are not using it): 15.0.0.155

#### Your filter lists (Required)
I don't remember the defaults, but here is everything I have enabled:

uBlock filters​​​​​18,156 used out of 18,176​​​​
uBlock filters – Badware risks​​​​​276 used out of 277​​​​
uBlock filters – Privacy​​​​​161 used out of 162​​​​
uBlock filters – Resource abuse​​​​​113 used out of 113​​​​
uBlock filters – Unbreak​​​​​994 used out of 996​​​​

Adblock Warning Removal List​​​​​686 used out of 696​​​​
EasyList​​​​​90,170 used out of 90,364​​​​

EasyPrivacy​​​​​17,284 used out of 17,356​​​​

Malware Domain List​​​​​1,090 used out of 1,105​​​​
Malware domains​​​​​26,893 used out of 26,893​​​​

AdGuard Annoyances​​​​​19,895 used out of 20,497​​​​
AdGuard Social Media​​​​​8,820 used out of 8,851​​​​
Anti-Facebook List​​​​​68 used out of 68​​​​

Peter Lowe’s Ad and tracking server list​​​​​2,982 used out of 2,983​​​​

Nano Defender Integration​​​​​2,528 used out of 2,649​​​​
Nano Filters​​​​​249 used out of 257​​​​

**Comment by llacb47** [comment]
That's not the console, that's the DOM tree. Click on `Console` and take the screenshot again.

**Comment by kpad-git** [comment]
> That's not the console, that's the DOM tree. Click on `Console` and take the screenshot again.

Oops, sorry. Here it is (in multiple images because of too many lines):

![image](https://user-images.githubusercontent.com/43962888/61639846-3eb3ea80-ac6a-11e9-9720-5225d9face1c.png)

![image](https://user-images.githubusercontent.com/43962888/61639896-5c814f80-ac6a-11e9-96d8-52010abef8db.png)

![image](https://user-images.githubusercontent.com/43962888/61639918-673be480-ac6a-11e9-979e-a496460f63ef.png)

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/61674734-5fa02e00-acb2-11e9-83ab-6e6850cccbb1.png)

**Comment by okiehsch** [comment]
Fixed.
