### ISSUE TITLE
[Annoyance, Cookie Wall] radar.avrotros.nl

### ISSUE THREAD

**Issue by DrIT2016** [NanoAdblocker/NanoFilters#382]
### Describe the issue (Required)
Site asks to accept cookies (3 categories) before you can scroll page cq read disqus comments.
When cookies cleared button is to accept all, but when you selct the categories (e.g. top above to deny, last one accept) button changes to save settings.
Last case (not accept all, so set some cookies first) i could not get to work with this rule: avrotros.nl##+js(nanop-click-elements-onload.js, button.ccm_btn:nth-child(3))
First case (accept all cookies) i did get working in chrome (vivaldi) with this rule: avrotros.nl##+js(nanop-click-elements-onload.js, button.ccm_btn:nth-child(1))
But this does not work in firefox somehow (only when refreshing multiple times), please help.

### Screenshot of console (Required, press `F12` to open the console)
![avrotros](https://user-images.githubusercontent.com/17800931/62009228-0fffad80-b15d-11e9-9847-ba63417ebef4.png)
![avrotros_cookies select](https://user-images.githubusercontent.com/17800931/62009229-12620780-b15d-11e9-92f7-3381e24ca849.png)

### URLs where this issue occurs (Required if applicable)
https://radar.avrotros.nl/

#### Environment (Required)

- Operating System and Version: Windows
- Browser and Version: Firefox/Waterfox latest
- Nano Adblocker Version: 1.0.0.122
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)

default ootb

#### Your custom filters (Required if you have any)
avrotros.nl##+js(nanop-click-elements-onload.js, button.ccm_btn:nth-child(1))

**Comment by jspenguin2017** [comment]
The script snippet is not designed to handle complex operations like clicking multiple buttons, because you can't control the order in which the clicks happen.

**Comment by jspenguin2017** [comment]
For Firefox-specific issues, report to @LiCybora .

**Comment by LiCybora** [comment]
`||cookies.avrotros.nl^$script`

Isn't blocking the cookie script solve the problem? I guess this works for Chromium as well

**Comment by DrIT2016** [comment]
Unfortunately this doesn't work (at least not in waterfox) :(
