### ISSUE TITLE
[Anti-adblock] viu.tv

### ISSUE THREAD

**Issue by misaka00251** [NanoAdblocker/NanoFilters#388]
### URLs where this issue occurs (Required)
https://viu.tv/

### Screenshots (Required)

uBlock Origin with Nano Defender enabled.
![image](https://user-images.githubusercontent.com/3908746/62822493-165b4400-bbb7-11e9-870c-49cbb1ce3698.png)

It says `Please disable ad blocker to support the free content.`

### Screenshot of console (Required, press `F12` to open the console)

![image](https://user-images.githubusercontent.com/3908746/62822429-e95a6180-bbb5-11e9-9a8e-38baa185e01a.png)

### Anything else you believe to be useful (Optional)

If you want to watch online, you need a HongKong IP address. Somehow two months ago with default settings, it works fine. Maybe they upgrade something.

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Google Chrome 77.0.3865.19 (Official Build) beta (64-bit)
- Nano Defender Version (Optional if you are not using it): 15.0.0.159
- uBlock Origin: 1.21.6

#### Your filter lists (Required)
 - uBlock Origin's default
 - Nano Defender's requirement
 - Regions, languages: CHN: CJX's EasyList Lite
 - Regions, languages: CHN: EasyList China（中文）

**Comment by jspenguin2017** [comment]
@okiehsch @mapx- Play a video to trigger (example: `https://viu.tv/encore/haters-gonna-stay/haters-gonna-staye1lo-hoi-sin`). Requires Hong Kong IP (Hola works). 
![image](https://user-images.githubusercontent.com/7283682/62825208-54c81300-bb65-11e9-802b-ef194fb6edf3.png)

**Comment by mapx-** [comment]
triggered even using european ip, could you test on your side ?

**Comment by jspenguin2017** [comment]
Looks good.

**Comment by misaka00251** [comment]
After this fix it does work, but the video won't play then...

![image](https://user-images.githubusercontent.com/3908746/62829050-9c16d800-bc27-11e9-9823-b3d99d6cd35a.png)

When disable uBlock Origin:

![image](https://user-images.githubusercontent.com/3908746/62829116-2ad82480-bc29-11e9-9b05-5a9e9e40b7ed.png)

Sometimes this does not work at all:

![image](https://user-images.githubusercontent.com/3908746/62829139-8bfff800-bc29-11e9-84ff-d2da2126737f.png)

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/62829471-879cf600-bbbb-11e9-814d-96555c4e42b1.png)
