### ISSUE TITLE
idntheme.com, arlinadzgn.com

### ISSUE THREAD

**Issue by arifpedia** [NanoAdblocker/NanoFilters#39]
### URLs where this issue occurs (Required)

- https://www.idntheme.com/
- https://www.arlinadzgn.com/2017/02/notifikasi-adblocker-adsense-ala-kompi-ajaib.html

### Screenshots (Required)

![](https://s18.postimg.org/jw17tla7t/Capture.png)

### Screenshot of console

![](https://s18.postimg.org/c3ak1mbyh/Console.png)

#### Environment (Required)

- Operating System and Version:  Windows 7 32bit 
- Browser and Version: Google Chrome 32bit Version 64.0.3282.186
- Nano Adblocker Version: 1.0.0.34
- Nano Defender Version: 13.39

#### Your filter lists (Required)
- Default + Regional IDN (chrome-extension://gabbbocakeomblphkmmnoamkioajlkfo/asset-viewer.html?url=IDN-0)

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.

**Comment by abiebdragx** [comment]
[https://www.abiebdragx.me](url)

**Comment by jspenguin2017** [comment]
Not sure what you mean, this still works fine for me. Either way, do not dig up old threads, open new issues instead.
