### ISSUE TITLE
[Anti-adblock] kachelmannwetter.com

### ISSUE THREAD

**Issue by anti-adblock** [NanoAdblocker/NanoFilters#390]
https://kachelmannwetter.com

![image](https://user-images.githubusercontent.com/54172231/63157533-70c12e00-c017-11e9-862c-9ee46b64cbd5.png)

![screenshot-console](https://user-images.githubusercontent.com/54172231/63157914-618eb000-c018-11e9-91da-a74af6011345.png)

anti-adblock appears at loading webpage, making website useless

#### Environment (Required)

- Lubuntu 18.04.3 LTS 
- Firefox 68.01 (64bit)  
- uBlock origin 1.21.2 
- Nano Defender 15.0.0.158 

#### Your filter lists (Required)
recommended defaults + recommended nano defaults

**Comment by mapx-** [comment]
Did you update uBo lists before posting here ?

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/63205096-b9e7a100-c05c-11e9-836d-2bbda3cdbdc7.png)
