### ISSUE TITLE
[Ads] identi.li

### ISSUE THREAD

**Issue by rd184** [NanoAdblocker/NanoFilters#392]
### URLs where this issue occurs (Required)
identi.li

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/8683399/63414901-6c539700-c3c2-11e9-9c00-411d9e477bf2.png)
![image](https://user-images.githubusercontent.com/8683399/63414924-770e2c00-c3c2-11e9-8b66-ace8ee3e9810.png)

### Screenshot of console (Required, press `F12` to open the console)
It seems it actively clears the console. The popups does not show when the console is open
![image](https://user-images.githubusercontent.com/8683399/63414834-41694300-c3c2-11e9-899e-e0b2d2540a3b.png)

### Describe the issue (Optional if obvious)
After you click on a link, it starts opening pop-ups. 

### Reproduction Steps (Optional if trivial)
- Open the website
- Click on a link

#### Environment (Required)

- Operating System and Version: Windows 10 version 1903
- Browser and Version: Google Chrome 75.0.3770.142
- Nano Adblocker Version: 1.0.0.123
- Nano Defender Version (Optional if you are not using it): 15.0.0.160

#### Your filter lists (Required)
![image](https://user-images.githubusercontent.com/8683399/63415103-d10ef180-c3c2-11e9-85bd-983db20b1d40.png)

#### Your other extensions (Required if you have any)
SessionBox, Tampermonkey, EditThisCookie, LastPass, AHA Music, PreMiD

**Comment by mapx-** [comment]
fixed
