### ISSUE TITLE
[Anti-adblock] egybest.org

### ISSUE THREAD

**Issue by gingfre** [NanoAdblocker/NanoFilters#393]
### Screenshots (Required)
![Annotation 2019-08-21 211226](https://user-images.githubusercontent.com/53033450/63473869-55bb4780-c477-11e9-8090-fea11b4d081a.png)

### Screenshot of the console (Required, press `F12` to open the console)
![Capture](https://user-images.githubusercontent.com/53033450/63474003-be0a2900-c477-11e9-92f2-1fa735f377ce.PNG)

### Describe the issue (Optional if obvious)
New domain so it's not working if you touch anything in the UI there new tab open /click.php
### Reproduction Steps (Optional if trivial)
To reproduce just go to egy.best then it will redirect to one of their new domains  
#### Environment (Required)
-windows 10
-chrome
#### My filter lists
easylist
Nano Defender Integration
adguard Ar list

**Comment by jspenguin2017** [comment]
@okiehsch New domain.

**Comment by gingfre** [comment]
hay! any update?

**Comment by llacb47** [comment]
It's sticky... so previous fixes all broke very soon after implementation.

**Comment by jspenguin2017** [comment]
Merging this issue into https://github.com/NanoAdblocker/NanoFilters/issues/376
