### ISSUE TITLE
[Anti-adblock] kachelmannwetter.com

### ISSUE THREAD

**Issue by maki-chan** [NanoAdblocker/NanoFilters#394]
### URLs where this issue occurs (Required)
https://kachelmannwetter.com/

### Screenshots (Required)
![Website](https://i.imgur.com/lJ4jTH0.png)

### Screenshot of console (Required, press `F12` to open the console)
![Console](https://i.imgur.com/BNzkJhr.png)

### Describe the issue (Optional if obvious)
When opening any URL of the Kachelmannwetter website (a website to look at weather forecasts), it redirects to the above shown error page (an anti-adblock message stating to either buy a premium account or to disable the adblocker).

### Anything else you believe to be useful (Optional)
The issue was closed 4 days ago as not reproducible, but I have the same error as the OP had there, so it is an issue for more than one person. See #390 

#### Environment (Required)
- Operating System and Version: Macbook Pro 15" (Late 2011); macOS 10.13.6
- Browser and Version: Google Chrome 76.0.3809.100
- Nano Adblocker Version: 1.0.0.124
- Nano Defender Version (Optional if you are not using it): 15.0.0.162

#### Your filter lists (Required)
- Nano Defender Integration
- Nano filters
- Nano filters - Whitelist
- uBlock filters
- uBlock filters - Badware risks
- uBlock filters - Privacy
- uBlock filters - Resource abuse
- uBlock filters - Unbreak
- Adblock Warning Removal List
- EasyList
- EasyPrivacy
- Malware Domain List
- Malware domains
- Peter Lowe's Ad and tracking server list
- DEU: EasyList Germany

#### Your custom filters (Required if you have any)
```
! 5.6.2019 https://www.questionablecontent.net
www.questionablecontent.net##center > .row

! 5.6.2019 https://www.wildelifecomic.com
www.wildelifecomic.com###yagahouse
www.wildelifecomic.com###tower

! 6.6.2019 https://telekomhilft.telekom.de
telekomhilft.telekom.de##.lia-desktop-only.mod-fasttrackbuttons

! 11.6.2019 https://www.minecraft.net
www.minecraft.net##.cc-container

! 16.6.2019 https://xkcd.com
||imgs.xkcd.com/static/howto_tour.png$image

! 7.7.2019 https://clevo-computer.com
clevo-computer.com##.ssWidgetRight.ssWRS.ssWidgetBox.ssWidget

! 25.7.2019 https://shop.roeder-feuerwerk.de
shop.roeder-feuerwerk.de##.has--btn.block-group.notification-bar--inner
```

```
no-csp-reports: * true
no-large-media: behind-the-scene false
no-scripting: behind-the-scene false
* * 3p-frame block
* clips.twitch.tv * noop
* consensu.org * noop
* consent-pref.trustarc.com * noop
* consent.google.com * noop
* disqus.com * noop
* evidon.com * noop
* https://www.google.com/recaptcha/api2/ sub_frame noop
* internet-siegel.net * block
* myunidays.com * noop
* nintendo-europe.com * noop
* nintendo.com * noop
* nintendo.net * noop
* pressekompass.net * noop
* shopify.com * noop
* shopifycs.com * noop
* stripe.com * noop
* twitter.com * noop
* vgwort.de * allow
* vimeo.com * noop
* youtube-nocookie.com * noop
* youtube.com * noop
account.microsoft.com * 3p-frame noop
behind-the-scene * * noop
behind-the-scene * 1p-script noop
behind-the-scene * 3p noop
behind-the-scene * 3p-frame noop
behind-the-scene * 3p-script noop
behind-the-scene * image noop
behind-the-scene * inline-script noop
gasfritzen.de paypal.com * noop
gronkh.shop getshirts.de * noop
hentaihaven.org lewd.host * noop
hentaihaven.org paw.network * noop
jsfiddle.net jshell.net * noop
meindoppelleben.blogspot.com blogger.com * noop
my.asos.com gigya.com * noop
my.playstation.com sonyentertainmentnetwork.com * noop
partner.muenchener-verein.de mv-versicherung.de * noop
play.pocketcasts.com paddle.com * noop
shop.roeder-feuerwerk.de bidswitch.net * block
shop.roeder-feuerwerk.de facebook.net * block
shop.roeder-feuerwerk.de google-analytics.com * block
shop.roeder-feuerwerk.de google.com * block
shop.roeder-feuerwerk.de hyj.mobi * block
shop.roeder-feuerwerk.de paypal.com * noop
wusstestdu.es www.openpetition.de * noop
www.asos.de asos.com * noop
www.asos.de custhelp.com * noop
www.nfl.com gigya.com * noop
www.nfl.com https://nfl.demdex.net other allow
www.nfl.com https://p.nfltags.com/omniture/dtm/gridiron-v2/ xmlhttprequest allow
www.nflgamepass.com gigya.com * noop
www.patreon.com tokenex.com * noop
www.rb-deggendorf.de * 3p-frame noop
www.reddit.com www.redditmedia.com * noop
www.reichelt.de reevoo.com * noop
www.sat1.de jiffybox.net * noop
www.ssv-jahnshop.de * 3p-frame noop
www.telekom.de * 3p-frame noop
www.trainstationgame.com pixelfederation.com * noop
www.wiwo.de tableau.com * noop
```

#### Your other extensions (Required if you have any)
- 1Password X (aeblfdkhhhdcdjpifhhbdiojplfjncoa)
- cookies.txt (njabckikapfpffapmjgojcnbfjonfjfg)
- Google Analytics Opt-Out (fllaojicojecljbmefodhfapmkghcbnh)
- EditThisCookie (fngmhnnpilhplaeedifhccceomclgfbg)
- Enhanced Steam (okadibdjfemgnhjiembecghcbfknbfhg)
- Google Docs Offline (ghbmnnjooekpmoecnnnilnnbdlolhkhi)
- HTTPS Everywhere (gcbommkclmclpchllfjekcdonpmejbdp)
- IBA Opt-out (gbiekjoijknlhijdjbaadobpkdhmoebb)
- MEGA (bigefpfhnfcobdlfbedofhhaibnlghod)
- Nano Adblocker (gabbbocakeomblphkmmnoamkioajlkfo)
- Nano Defender (ggolfgbegefeeoocgjbmkembbncoadlb)
- Skype Calls (blakpkgjpemejpbmfiglncklihnhjkij)
- Steam Database (kdbmhfkmnlmbkgbabkdealhhbfhlmmon)
- Tampermonkey BETA [no scripts for the blocked site active] (gcalenpjmijncebpfijmoaglllgpjagf)
- Xdebug Helper (eadndfjplgieldjbigjakmdgkmoaaaoc)

**Comment by mapx-** [comment]
update all your lists, test again

**Comment by maki-chan** [comment]
It does work now, thank you very much for your help 👍
