### ISSUE TITLE
[Anti-adblock] fiatclub.eu

### ISSUE THREAD

**Issue by lormico** [NanoAdblocker/NanoFilters#397]
### URLs where this issue occurs (Required)
http://en.fiatclub.eu

### Screenshots (Required)
![Immagine](https://user-images.githubusercontent.com/41483803/64100373-bdbd3800-cd6b-11e9-89a2-eb954c5f66d1.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![Immagine](https://user-images.githubusercontent.com/41483803/64100725-72575980-cd6c-11e9-9c4b-4d4cc64ee65f.jpg)

### Describe the issue (Optional if obvious)
The site is completely locked

### Reproduction Steps (Optional if trivial)
Just accessing any url within the domain, with nano enabled, is enough to trigger the protection

#### Environment (Required)

- Operating System and Version: Windows 10 x64
- Browser and Version: Google Chrome 76.0.3809.100 x64
- Nano Adblocker Version: 1.0.0.124
- Nano Defender Version (Optional if you are not using it): 15.0.0.166

#### Your filter lists (Required)
Nano Defender Integration
Nano filters
Nano filters – Whitelist​​​​​
uBlock filters
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak
Adblock Warning Removal List​​​​​
EasyList
EasyPrivacy​​​​​
Malware Domain List
Malware domains
ITA: EasyList Italy​​​​​

#### Your other extensions (Required if you have any)
Only relevant:
Tampermonkey (no script in use though)
I don't care about cookies

**Comment by mapx-** [comment]
fixed

**Comment by lormico** [comment]
Thanks a lot!
