### ISSUE TITLE
This site passes filter:  https://chrome.google.com/webstore/detail/nano-defender/ggolfgbegefeeoocgjbmkembbncoadlb/support?utm_source=chrome-app-launcher-info-dialog

### ISSUE THREAD

**Issue by nordanland** [NanoAdblocker/NanoFilters#4]
### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version:

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/issues/999
