### ISSUE TITLE
[Breakage] www.op.gg

### ISSUE THREAD

**Issue by onmyouji** [NanoAdblocker/NanoFilters#400]
### URLs where this issue occurs (Required)
https://www.op.gg/summoner/userName=pvman

### Screenshots (Required)
![Image 001a](https://user-images.githubusercontent.com/8424198/65138005-7950be00-da34-11e9-9840-b9ac358f6a95.png)

### Screenshot of console (Required, press `F12` to open the console)
![Image 002](https://user-images.githubusercontent.com/8424198/65138067-91284200-da34-11e9-835e-2f723aa304bc.png)
![Image 003](https://user-images.githubusercontent.com/8424198/65138106-a00ef480-da34-11e9-82d0-2b9fac091b6b.png)

### Describe the issue (Optional if obvious)
I can't open the drop down when I click the down arrow (the part that I circle red on the screenshot). It only works when I disable uBlock origin.

### Anything else you believe to be useful (Optional)
I use Brave browser and I already tested it with its internal adblocker disabled.

#### Environment (Required)

- Operating System: Windows 10 Home 1803
- Browser: Brave Version 0.68.138 Chromium: 77.0.3865.75 (Official Build) (64-bit)
- uBlock origin Version: 1.22.2
- Nano Defender Version: 15.0.0.168

#### Your filter lists (Required)
![Image 004](https://user-images.githubusercontent.com/8424198/65139248-81116200-da36-11e9-9ace-9fcab7723dde.png)

**Comment by mapx-** [comment]
disable all other blocking extensions and test again, I have no issue in FF / brave

**Comment by onmyouji** [comment]
It still doesn't work :(

I already disabled everything and only enabled uBlock origin, it is so strange. I tested the same thing in Chrome and found no problem. I think this is Brave issues.

Thanks for the response.
