### ISSUE TITLE
[Anti-adblock] linksht.com

### ISSUE THREAD

**Issue by nmhung1985** [NanoAdblocker/NanoFilters#403]
### URLs where this issue occurs (Required)
https://linksht.com/d1d9b46

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/39881978/65389650-b72a4b00-dd82-11e9-8ac0-4428e0565a6b.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/39881978/65389666-d2955600-dd82-11e9-8f26-0f81d2e0888f.png)

### Describe the issue (Optional if obvious)
Instead of the captcha box, the page will show a red sentence stating that there is an adblocker.

#### Environment (Required)

- Operating System and Version: Windows 10 1607
- Browser and Version: Chrome newest version as of Sep 22, 2019
- Nano Adblocker Version: Also newest version
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)
EasyList,
Region VIE (ABPVN)

**Comment by jspenguin2017** [comment]
Works fine for me.

**Comment by nmhung1985** [comment]
Weird, it now also works for me! 😮 Ok, I think we can close now. I'll re-open if the issue is easily reproducible.
