### ISSUE TITLE
[Anti-adblock] uploadship.com

### ISSUE THREAD

**Issue by avoxismith** [NanoAdblocker/NanoFilters#405]
### URLs where this issue occurs (Required)
https://uploadship.com

### Describe the issue (Optional if obvious)
I have Nano Adblocker installed as an addon with the latest Firefox 69.0. I also have Nano defender and nano filter list enabled. But still Nano adblocker is getting detected. It stops getting detected if I enable inline scripts, but that closes down some other functionality.

#### Environment (Required)

- Operating System and Version: Win 7
- Browser and Version: Firefox 69.0
- Nano Adblocker Version: 1.0.0.127
- Nano Defender Version (Optional if you are not using it):

**Comment by llacb47** [comment]
Need a better test URL. Please provide the specific link.

**Comment by avoxismith** [comment]
Hi,
It is a upload service and I have uploaded few files to test the adblock features. The test url is : https://www.uploadship.com/496e3647cb78da95

Once you open it on your browser, Adblock detection pops up as an error.
If you want you can upload a file and test it out. I have attached screenshots.[Screenshot_2019-09-30 default Error - UploadShip.png]

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by avoxismith** [comment]
Hi,
It is a upload service and I have uploaded few files to test the adblock features. The test url is : https://www.uploadship.com/496e3647cb78da95

Once you open it on your browser, Adblock detection pops up as an error.
If you want you can upload a file and test it out. I have attached screenshots.

**Comment by avoxismith** [comment]
I don't know why, but the screenshot didn't get attached - I provided an imgur url. https://imgur.com/lfQQxVL

**Comment by avoxismith** [comment]
This is the script that is firing the Adblock detection:

<script type="text/javascript">if (document.getElementById("bannerad") == undefined){	document.getElementById("adblockinfo").style.display = "block";  	window.location.replace('https://www.uploadship.com/error.html?e55318040a854ebdc4d4404d2521bee5=e55318020a154ebdc8d4404d2522bee5-496e3647cb78da95-e55318020a142ebdc4d4404d2522bee5');	$(document).ready(function()	{		$('section').remove();	});}</script><script type="text/javascript">(function(){  var e55318040a8544bda8d0508d4544bee5 = document.createElement('div');  e55318040a8544bda8d0508d4544bee5.innerHTML = '&nbsp;';  e55318040a8544bda8d0508d4544bee5.className = 'adsbygoogle';  document.body.appendChild(e55318040a8544bda8d0508d4544bee5);  window.setTimeout(function() {    if (e55318040a8544bda8d0508d4544bee5.offsetHeight === 0) {  document.getElementById("adblockinfo").style.display = "block";    window.location.replace('https://www.uploadship.com/error.html?e55318040a854ebdc4d4404d2521bee5=e55318020a154ebdc8d4404d2522bee5-496e3647cb78da95-e55318020a142ebdc4d4404d2522bee5');    }    e55318040a8544bda8d0508d4544bee5.remove();  }, 100);})();</script><script type="text/javascript">window.onload = function() {if (!adsbygoogle.loaded) {  	document.getElementById("adblockinfo").style.display = "block";  	window.location.replace('https://www.uploadship.com/error.html?e55318040a854ebdc4d4404d2521bee5=e55318020a154ebdc8d4404d2522bee5-496e3647cb78da95-e55318020a142ebdc4d4404d2522bee5');	$(document).ready(function()	{		$('section').remove();	});}}</script><script type="text/javascript">function e55411240a854ebdc4d4404d2122bee5() {    document.getElementById("adblockinfo").style.display = "block";  	window.location.replace('https://www.uploadship.com/error.html?e55318040a854ebdc4d4404d2521bee5=e55318020a154ebdc8d4404d2522bee5-496e3647cb78da95-e55318020a142ebdc4d4404d2522bee5');	$(document).ready(function()	{		$('section').remove();	});}</script>

**Comment by jspenguin2017** [comment]
I can't seem to reproduce it. Do you have the latest filters?

**Comment by jspenguin2017** [comment]
Was able to reproduce after a few refreshes. @okiehsch race condition?

**Comment by avoxismith** [comment]
Yes, I do have the latest filters. I have purged cache and updated all of them.

**Comment by okiehsch** [comment]
Does it work if you add
````
uploadship.com#@#+js(abort-current-inline-script, document.getElementById, undefined)
uploadship.com##+js(abort-current-inline-script, document.getElementById, adblock)
````
to your filter list?

**Comment by okiehsch** [comment]
I get occasionally redirected with that filter but 
````
uploadship.com##+js(acis, document.getElementById, adblock)
uploadship.com##+js(std, adblock)
````
seems to work consistently on my end.

**Comment by okiehsch** [comment]
@jspenguin2017 the same issue has been opened at `uAssets`. 
I will reference https://github.com/uBlockOrigin/uAssets/issues/6370 in the fix.

**Comment by avoxismith** [comment]
@okiehsch 
It doesn't work, moreover I tried these following filters:

uploadship.com##+js(abort-current-inline-script, document.getElementById, bannerad)
uploadship.com##+js(abort-current-inline-script.js, document.getElementById, style.display)
@@||uploadship.com/showads.js$script,first-party
uploadship.com##^script:has-text(e55318040a8544bda8d0508d4544bee5)

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/032383f91494cbfc5e1278bbddec50875b29441b

**Comment by avoxismith** [comment]
@okiehsch 
Added the changes to my filter list
`uBlockOrigin/uAssets@032383f
uBlockOrigin/uAssets@2058e4a`

Still no luck, I have purged all the filter cache and updated them. Still the page redirects toAdblock error message.

**Comment by okiehsch** [comment]
Hm, I have allowed everything the site checks, so I don't know why it deos not work for you.
It does worrk on my end.

**Comment by avoxismith** [comment]
@okiehsch Thnx for your effort, really appreciate it! So, I went aheade and created a fresh Firefox profile without private mode and added Nano Adblocker and tried the above mentioned filter list and it worked, **but the moment I turned on private mode the filters stopped working and the Adblock message came up.**
So, either the filter list stops working in private mode or the Anti-Adblock script detects private moode and maybe has added protection.

**Comment by okiehsch** [comment]
> but the moment I turned on private mode the filters stopped working and the Adblock message came up.

The Firefox private mode blocks requests before `uBO` can allow them. There is no way for `uBO` to fix that.

**Comment by avoxismith** [comment]
@okiehsch Thnx a lot! No issues, I will try to use Firefox containers I think the issue is now resolved. Amazing, the prompt resolutions from you guys!! Keep up the good work. BTW is there an option for donation/contribution, coz I didn't see that on the homepage.
