### ISSUE TITLE
[Anti-adblock] igg-games

### ISSUE THREAD

**Issue by bryce-lynch** [NanoAdblocker/NanoFilters#406]
### URLs where this issue occurs (Required)
https://igg-games.com

### Screenshots (Required)
![Screenshot](https://i.imgur.com/gEx6Egf.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![Screenshot](https://i.imgur.com/wkzNk6N.jpg)

### Describe the issue (Optional if obvious)
When you load the page, a popup appears after a few seconds, with the message "Adblock detected"

#### Environment (Required)

- Operating System and Version: Arch Linux - kernel 5.3.1
- Browser and Version: Firefox 69.0.2
- Nano Adblocker Version: 15.0.0.167
- Nano Defender Version (Optional if you are not using it): using uBlock Origin 1.22.4

#### Your filter lists (Required)
all built-in uBlock filters, Easylist, EasyPrivacy, Malware domains, Peter Lowe's list, plus the following lists:
https://raw.githubusercontent.com/r4vi/block-the-eu-cookie-shit-list/master/filterlist.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin-ublock.txt
https://raw.githubusercontent.com/bcye/Hello-Goodbye/master/filterlist.txt

#### Your other extensions (Required if you have any)

CSS Exfil Protection, Decentraleyes, Canvasblocker, ETag Stoppa, HTTPS Everywhere, IDN Safe, Link Fixer, Neat URL, Privacy-Oriented Origin Policy, Temporary Containers, uBlock Origin

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/66256408-c201ba00-e74a-11e9-824d-ed4b582cf417.png)

**Comment by bryce-lynch** [comment]
Not sure why... I tried again now, and as before, after about 10 seconds the popup appears. Nano is enabled, so I guess something else on my side. You can close the issue if you want, I don't use that site but noticed the popup and wanted to report it.
