### ISSUE TITLE
[Anti-adblock] rp5.ru

### ISSUE THREAD

**Issue by UnclWish** [NanoAdblocker/NanoFilters#407]
### URLs where this issue occurs (Required)
https://rp5.ru/%D0%9F%D0%BE%D0%B3%D0%BE%D0%B4%D0%B0_%D0%B2_%D0%9F%D1%80%D1%8F%D0%BC%D0%B8%D1%86%D1%8B%D0%BD%D0%BE

### Screenshots (Required)
![Screenshot](https://rusfriends.clan.su/Other/rp5.ru.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![Screenshot](https://rusfriends.clan.su/Other/rp5.ru-console.jpg)

### Describe the issue (Optional if obvious)
Anti adblock. Determines the nano adblocker and writes "adblock" instead of weather info.

### Reproduction Steps (Optional if trivial)
Just opening the site.

#### Environment (Required)

- Operating System and Version: Windows 10 x64 Pro
- Browser and Version: SRWare Iron 76.0.3950.0 x64
- Nano Adblocker Version: 1.0.0.127
- Nano Defender Version (Optional if you are not using it): 15.0.0.168

#### Your filter lists (Required)

Nano Defender Integration
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks
uBlock filters – Experimental
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak

Adblock Warning Removal List​​​​​
AdGuard Base List
AdGuard Mobile Ads​​​​​
EasyList​​​​
Nano contrib filter – Placeholder buster​​​​​

AdGuard Tracking Protection
EasyPrivacy​​​​
Fanboy's Enhanced Tracking List

Malware Domain List
Malware domains

Peter Lowe's Ad and tracking server list

RUS: AdGuard Russian
RUS: RU AdList​​​​​

**Comment by mapx-** [comment]
fixed

**Comment by UnclWish** [comment]
But how I can solve this?

**Comment by jspenguin2017** [comment]
Just update your filters.

**Comment by UnclWish** [comment]
Oh, thanks! Now it works!
