### ISSUE TITLE
[Anti-adblock] wi.cr, wikimotors.net

### ISSUE THREAD

**Issue by sanGtH** [NanoAdblocker/NanoFilters#413]
### URLs where this issue occurs (Required)
URL : http://wi.cr/dMkmIWC
the above link after solving captcha redirects to this one below
https://wikimotors.net/road-to-resilience-becoming-mentally-strong/
or any wikimotors.net link. This wikimotors.net link detects Adblock

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/13797193/67430572-22747080-f600-11e9-85fe-c65e3e2e7930.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/13797193/67430711-741cfb00-f600-11e9-8b75-63350fae6d33.png)

### Describe the issue (Optional if obvious)
URL : http://wi.cr/dMkmIWC
the above link after solving captcha redirects to this one below
https://wikimotors.net/road-to-resilience-becoming-mentally-strong/
or any wikimotors.net link. This wikimotors.net link detects Adblock

#### Environment (Required)

- Operating System and Version: WIN 7 64 Bit Ultimate
- Browser and Version: Chrome v77.0.3865.120
- Nano Adblocker Version: 1.0.0.128
- Nano Defender Version (Optional if you are not using it): 15.0.0.168

#### Your filter lists (Required)
Adblock warning removal list
EasyList
Nano defender Integration
Nano Filters
Nano filters - Whitelist

#### Your other extensions (Required if you have any)
UBlock Origin v1.22.4

**Comment by mapx-** [comment]
@sanGtH Did you update uBo lists ? Are uBo lists still enabled in your uBo / nano ?

**Comment by sanGtH** [comment]
@mapx- Bro i saw the filters you mentioned in the uBlockOrigin/uAssets@062f6fb. Do i have to copy 
the last filters mentioned there ->
@@||cdnjs.cloudflare.com/ajax/libs/fuckadblock/*/fuckadblock.min.js$script,domain=wikimotors.net
@@||wikimotors.net^$generichide
to My filters of UBlock ? Or is it sufficient to purge the cache and update filters ?
Secondly, yes I am using 2 adblockers. Which one you suggest to keep ? Please reply. Thanks

**Comment by mapx-** [comment]
Remove 1 of them: if you use Nano defeneder keep Nano adblocker.
Then: **I asked you if you see in the logger the filters.**

After removing 1 of the adblockers, purge + update, repeat the test.

**Comment by sanGtH** [comment]
@mapx- When i copied the filters to Nano adblocker (Ublock off) it works fine. But when i copied the
filters to Ublock (Nano off) it does not work. What's the reason bro  ?

**Comment by mapx-** [comment]
The filters are already in the list, you have only to update (purge + update) it.
Stick with Nano adblocker, **default settings**, remove completely any other adblocker.

**Comment by jspenguin2017** [comment]
This works fine for me. Make sure to update your filters and stick with default settings. 
![image](https://user-images.githubusercontent.com/7283682/67534535-c48d6a80-f68b-11e9-8cb8-e3434f70d449.png)
