### ISSUE TITLE
[Anti-adblock] kizi.com

### ISSUE THREAD

**Issue by TheMuffinPony** [NanoAdblocker/NanoFilters#414]
### URLs where this issue occurs (Required)
kizi.com, a flash games website unblocked at my school

### Screenshots (Required)
Includes both the console and the website.
<img width="960" alt="Screen Shot" src="https://user-images.githubusercontent.com/36351178/67447050-e1646800-f5cf-11e9-8a90-0d68ba3331c2.png">

### Describe the issue (Optional if obvious)
Upon visiting kizi.com, it requests that you disable your adblocker.

### Reproduction Steps (Optional if trivial)
Happens with both a completely fresh installation of both extensions in a fresh profile (no settings touched) and with hard-mode (1st party scripts allowed).

### Anything else you believe to be useful (Optional)
Using force scroll mode after using the element picker/zapper to remove the overlay and the fade background works, but breaks layout.  Disabling JavaScript also breaks the layout.  Nano Defender's experimental rules does nothing.  This is caused by the blocking of `https://cdn8.kizi.com/assets/advertisement/advertisement-29da443a30492ce3f4fb8af8a10ff812.js`, of which the exclusive purpose is to set a variable to "false," disabling the blocker script in the document.

#### Environment (Required)

- Operating System and Version: macOS Catalina 10.15 Beta (19A582a)
- Browser and Version: Latest Firefox version (69.0.3)
- Nano Adblocker Version: 1.0.0.127
- Nano Defender Version (Optional if you are not using it): 15.0.0.167

#### Your filter lists (Required)
Reproducible with updated default filters (Dashboard > Filter Lists > Update Now)

#### Your custom filters (Required if you have any)
N/A

#### Your other extensions (Required if you have any)
N/A, freshly installed Nano Adblocker/Defender on a brand new browser profile

**Comment by llacb47** [comment]
@mapx- `kizi.com##+js(acis, $, adblock)`

**Comment by jspenguin2017** [comment]
@okiehsch Hard anti-adblock.

**Comment by okiehsch** [comment]
Fixed.
