### ISSUE TITLE
[Anti-adblock] onlystream.tv

### ISSUE THREAD

**Issue by Majkovsky** [NanoAdblocker/NanoFilters#416]
https://videopenny.net/seriale-pol/39-i-pol-tygodnia/39-i-pol-tygodnia-odc-9-s01e09,96196,2284

"**The publisher doesnt allow adblock, please disable and reload to watch the video!**"

Nano Defender **15.0.0.167**
Mozilla Firefox **70.0.0**

**Comment by mapx-** [comment]
fixed
