### ISSUE TITLE
quora.com

### ISSUE THREAD

**Issue by gparyani** [NanoAdblocker/NanoFilters#42]
### URLs where this issue occurs (Required)
All Quora question URLs **when accessed with an internal link** (bug **cannot be reproduced** if clicking a link here from this issue)

Screenshot below is from https://www.quora.com/JetBlue-Airways-What-is-the-best-way-to-get-an-Even-More-Space-seat-without-paying-for-it

### Screenshots (Required)
[![blurred text quora][1]][1]

### Screenshot of console (Required, press `F12` to open the console)
[![blurred text quora logs][2]][2]

### Describe the issue (Optional if obvious)
Properly removes the pop-up box and gray shading, but fails to un-blur the text.

### Reproduction Steps (Optional if trivial)
1. Visit any Quora question, either from Google or by clicking on a link from this issue. (e.g. https://www.quora.com/JetBlue-Airways-If-you-dont-select-a-seat-upon-booking-your-flight-and-when-you-arrive-at-the-airport-there-are-only-Even-More-Space-seats-remaining-will-you-be-assigned-one-free-of-charge)
2. Click on any internal link to another question, under the Related Questions. For example, click on the first one on the right sidebar or just under the question body text. (If it doesn't appear blurred, close the new tab it opened and try another one.)

### Anything else you believe to be useful (Optional):
N/A

#### Environment (Required)

- Operating System and Version: Windows 10 version 1709
- Browser and Version: Microsoft Edge 41.16299.248.0
- Nano Adblocker Version: Nano Adblocker v1.0.0.29
- Nano Defender Version (Optional if you are not using it): 13.31

#### Your filter lists (Required)

- My filters
- Nano Defender Integration
- Nano filters
- Nano filters - Timer bypassing
- Nano filters - Whitelist
- uBlock filters
- uBlock filters - Badware risks
- uBlock filters - Privacy
- uBlock filters - Resource abuse
- uBlock filters - Unbreak
- Adblock Warning Removal List
- EasyList
- EasyPrivacy
- Malware Domain List
- Malware domains
- Peter Lowe's Ad and tracking server list

#### Your custom filters (Required if you have any)
    ||wheregoes.com/img/banners/2017-07-maxbounty.png$image

[1]: https://user-images.githubusercontent.com/6440487/37235781-2c01afe4-23c7-11e8-9869-aab6dbc83d63.PNG
[2]: https://user-images.githubusercontent.com/6440487/37235828-c039c5ca-23c7-11e8-8f99-ef70bc98a877.PNG

**Comment by jspenguin2017** [comment]
@okiehsch 
![image](https://user-images.githubusercontent.com/7283682/37236454-d0a3aab4-23c4-11e8-98c7-3e26c6f5136d.png)
I see that uBlock filters tries to get rid of the signup overlay, but the blur style is not overriden.

**Comment by gparyani** [comment]
Perhaps you should make it more clear in the rules that the format of the tile is just supposed to be the domain?

**Comment by okiehsch** [comment]
Hm, I can't reproduce with Edge, or Firefox. if I go to 
````
https://www.quora.com/JetBlue-Airways-What-is-the-best-way-to-get-an-Even-More-Space-seat-without-paying-for-it
````
and then click any link, for example the first of the "Related Questions"

![unbenannt](https://user-images.githubusercontent.com/16838044/37237684-250fabdc-2417-11e8-8f68-eedfc8d32f6a.JPG)

**Comment by jspenguin2017** [comment]
I can reproduce quite reliably... 
![image](https://user-images.githubusercontent.com/7283682/37237703-5c6a566a-23d4-11e8-98a1-82be2b2ed4eb.png)

**Comment by okiehsch** [comment]
With Chrome, yes but the OP stated that he used
````
Environment (Required)
Operating System and Version: Windows 10 version 1709
Browser and Version: Microsoft Edge 41.16299.248.0`
````

Regarding Chrome, I am open for suggestions :).

**Comment by jspenguin2017** [comment]
```
quora.com##.signup_wall_prevent_scroll .SiteHeader,.signup_wall_prevent_scroll .LoggedOutFooter,.signup_wall_prevent_scroll .ContentWrapper:style(filter: none !important;)
```

**Comment by okiehsch** [comment]
Thanks, added.
