### ISSUE TITLE
mac-torrent-download.net

### ISSUE THREAD

**Issue by Abyade** [NanoAdblocker/NanoFilters#427]
### URLs where this issue occurs (Required if applicable)
`https://mac-torrent-download.net/path-finder-9-0-4/`

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by ZaphodBeebblebrox** [comment]
I do not see any nag screen or anti-adblock.

**Comment by mapx-** [comment]
yeah, OP should update the lists

**Comment by jspenguin2017** [comment]
I don't see anything wrong with this website. Closing as invalid as you did not fill the template.

**Comment by Abyade** [comment]
look

On 21/11/2019 at 11:34 PM, "Hugo Xu"  wrote:

	I don't see anything wrong with this website. Closing as invalid as
you did not fill the template.

**Comment by Abyade** [comment]
![Sans titre](https://user-images.githubusercontent.com/8308071/69422133-3d332580-0d23-11ea-89c0-31348657cc5d.jpg)
![block](https://user-images.githubusercontent.com/8308071/69422145-41f7d980-0d23-11ea-804f-a84b57b3629f.jpg)
VOILA

**Comment by Abyade** [comment]
look

On 21/11/2019 at 7:44 PM, "mapx-"  wrote:

	yeah, OP should update the lists

**Comment by Abyade** [comment]
On 21/11/2019 at 7:31 PM, "ZaphodBeebblebrox"  wrote:

	I do not see any nag screen or anti-adblock.

**Comment by jspenguin2017** [comment]
I can't reproduce, it works fine for me.
