### ISSUE TITLE
[Anti-adblock] nintendolife.com

### ISSUE THREAD

**Issue by MysticalOS** [NanoAdblocker/NanoFilters#429]
### Screenshots (Required)
![Screen Shot 2019-11-24 at 5 17 04 PM](https://user-images.githubusercontent.com/1899149/69502536-7c59a600-0ede-11ea-930e-53c783e63db1.jpg)

### Screenshot of console (Required, press `F12` to open the console)

![Screen Shot 2019-11-24 at 5 19 23 PM](https://user-images.githubusercontent.com/1899149/69502548-a1e6af80-0ede-11ea-914c-53884ff2a0f3.jpg)

### Anything else you believe to be useful (Optional)
today is first sighting of this,I suspect it's a new addition to this site since i visit it nearly daily

#### Environment (Required)

- Operating System and Version: macOS
- Browser and Version: Chrome 78.0.3904.108
- Nano Adblocker Version: ublock Origin (completely configured with nano defender and has been working well on other sites like cwtv)
- Nano Defender Version (Optional if you are not using it): 15.0.0.170

#### Your custom filters (Required if you have any)
just the nano filters required for use with ublock

#### Your other extensions (Required if you have any)
ublock origin, ublock extra

**Comment by jspenguin2017** [comment]
Works fine for me. Do you have the latest filters?

**Comment by MysticalOS** [comment]
Not showing when i visit now. perhaps they don't always run check, or filters updated between then and now. I know when i saw popup i opened filters list but none showed expired out of date and I didn't hit manual update. but maybe the very act of opening filters list updated them. I'll keep an eye for the popup again :)

**Comment by MysticalOS** [comment]
It actually did keep happening but I just got used to clicking them off since it seems to only happen like 1 in 3 visits or so.

**Comment by jspenguin2017** [comment]
I clicked 5 articles, still can't reproduce.

**Comment by CodyMKW** [comment]
I got it sometimes I just made a local userstyle in Stylus to hide it so I wouldn't see it

**Comment by jspenguin2017** [comment]
It still works fine for me. Try resetting to default settings.
