### ISSUE TITLE
vod.walla.co.il

### ISSUE THREAD

**Issue by ghost** [NanoAdblocker/NanoFilters#43]
#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by MaorOvadia794** [comment]
there ads in the video when i play Video Advertisement
20 seconds more or less
in this link for example https://vod.walla.co.il/episode/2926712

**Comment by jspenguin2017** [comment]
Fill the template.
