### ISSUE TITLE
[Anti-adblock] soy502.com

### ISSUE THREAD

**Issue by devjoseluis** [NanoAdblocker/NanoFilters#430]
### URLs where this issue occurs (Required)

Every page in the domain soy502.com

### Screenshots (Required)
![soy502.com](https://i.postimg.cc/T1L7yfnk/soy502-com.png)

### Screenshot of the console (Required, press `F12` to open the console)
![developer-tools-console](https://i.postimg.cc/nhkyfV27/Screen-Shot-2019-11-28-at-14-34-47.png)

#### Environment (Required)

- Operating System and Version: macOS 10.15.1
- Browser and Version: Google Chrome 78.0.3904.108
- Nano Adblocker Version: v1.0.0.130
- Nano Defender Version (Optional if you are not using it): v15.0.0.170

#### Your filter lists (Required)

I'm using the default settings.

**Comment by mapx-** [comment]
fixed

**Comment by devjoseluis** [comment]
Thank you so much, @mapx- and @jspenguin2017 😸
