### ISSUE TITLE
animeshd.biz

### ISSUE THREAD

**Issue by Fireninee** [NanoAdblocker/NanoFilters#431]
### URLs
https://www.animeshd.biz/video/16985

### Screenshots
![image](https://user-images.githubusercontent.com/58319034/69842753-3a649300-1243-11ea-9e10-a7b0236d35cc.png)

### Screenshot of console
![image](https://user-images.githubusercontent.com/58319034/69842857-af37cd00-1243-11ea-9a67-23a5db25f19c.png)

### Describe the issue (Optional if obvious)
Adblock detected

#### Environment (Required)

- Operating System and Version: Windows 10 64bits
- Browser and Version: Google Chrome Versão 78.0.3904.97
- Adblocker Version: 4.0.1
- Nano Defender Version (Optional if you are not using it): 15.0.0.170

**Comment by jspenguin2017** [comment]
Can't reproduce with standard setup. You must use either Nano Adblocker or uBlock Origin, other adblockers are not supported.
