### ISSUE TITLE
[Anti-adblock] bde4.com

### ISSUE THREAD

**Issue by motorar** [NanoAdblocker/NanoFilters#432]
### URLs where this issue occurs (Required)
bde4.com

### Screenshots (Required)
https://imgse.com/i/QtASRx

### Screenshot of console (Required, press `F12` to open the console)
https://imgse.com/i/QtAuSP

#### Environment (Required)

Environment (Required)
Operating System and Version: windows 10 x64
Browser and Version: firefox 68.0.1
Nano Adblocker Version: 1.0.0.120
Nano Defender Version (Optional if you are not using it): 15.0.0154

**Comment by jspenguin2017** [comment]
@okiehsch Comes up after a bit, hard anti-adblock.

**Comment by okiehsch** [comment]
Fixed.
