### ISSUE TITLE
[Ads] washingtonpost.com

### ISSUE THREAD

**Issue by rob-4x4** [NanoAdblocker/NanoFilters#433]
https://www.washingtonpost.com/business/2019/10/08/first-time-history-us-billionaires-paid-lower-tax-rate-than-working-class-last-year/?fbclid=IwAR2rHusCg48w9Eq_Q54OMSs4kGY4WZxzy-_OOr5gY5pvtQuVqlLiWcFpj-Q
#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by llacb47** [comment]
What is the issue? Paywalls are on hold.

**Comment by jspenguin2017** [comment]
Ads placeholders fixed, can't reproduce other issues.
