### ISSUE TITLE
Anti Ad Block -  www.statesman.com (admiral)

### ISSUE THREAD

**Issue by brru8999** [NanoAdblocker/NanoFilters#434]
##
### URLs where this issue occurs (Required)
www.statesman.com

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/38956371/70743586-acc68000-1ce5-11ea-883a-27b2b39f8965.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/38956371/70743613-c071e680-1ce5-11ea-8ed6-8d75d2e3f65e.png)
![image](https://user-images.githubusercontent.com/38956371/70743644-cf589900-1ce5-11ea-9e4a-1e15559503a7.png)

### Describe the issue (Optional if obvious)
Demand to whitelist will pop up for the first few times with an option to dismiss, now it will not go away unless white listed. 

### Reproduction Steps (Optional if trivial)
Visiting any page on the site.

#### Environment (Required)

- Operating System and Version:  Windows 10
- Browser and Version:  Chrome  Version 78.0.3904.87 (Official Build) (64-bit)
- Nano Adblocker Version: 1.0.0.130
- Nano Defender Version (Optional if you are not using it): 15.0.0.170

#### Your filter lists (Required)
![image](https://user-images.githubusercontent.com/38956371/70743754-0b8bf980-1ce6-11ea-89db-7be8761f06d4.png)

**Comment by mapx-** [comment]
annoyance => enable `uBlock filters - Annoyances`
