### ISSUE TITLE
[Anti-adblock] pilot.wp.pl

### ISSUE THREAD

**Issue by Majkovsky** [NanoAdblocker/NanoFilters#435]
https://pilot.wp.pl/tv/#tvp-1-hd

**"Dzięki reklamom masz dostęp do bezpłatnych kanałów. Wyłącz program blokujący reklamy lub tryb incognito i odśwież stronę, aby oglądać."**

Nano Defender **15.0.0.170**
Mozilla Firefox **71.0**

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1806
