### ISSUE TITLE
[Anti-adblock] strims.world

### ISSUE THREAD

**Issue by Majkovsky** [NanoAdblocker/NanoFilters#437]
http://strims.world/SkokiKwalifikacje.php?source=1

**"BRAK PLAYERA? WYŁĄCZ ADBLOCKA!"**

Nano Defender **15.0.0.170**
Mozilla Firefox **71.0**

**Comment by jspenguin2017** [comment]
Can't reproduce. Closing as invalid as you did not fill the template. 
![image](https://user-images.githubusercontent.com/7283682/71312530-46c6b080-23e9-11ea-8f5d-b3040ca94ea5.png)

**Comment by krystian3w** [comment]
https://github.com/LiCybora/NanoDefenderFirefox/issues/new
