### ISSUE TITLE
[Anti-adblock] digitalmusicnews.com

### ISSUE THREAD

**Issue by Sopor** [NanoAdblocker/NanoFilters#438]
### URLs where this issue occurs (Required)
https://www.digitalmusicnews.com/2017/11/30/youtube-geo-block-chrome-extension/

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/5789283/71322241-b9a55980-24c5-11ea-9e31-4897e1d9c5e2.png)

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Firefox 71.0
- Nano Adblocker Version: uBlock Origin 1.24.2
- Nano Defender Version (Optional if you are not using it): 15.0.0.170

#### Your custom filters (Required if you have any)
- [x] uBlock filters
- [x] uBlock filters – Annoyances​​​​​
- [x] uBlock filters – Badware risks​
- [x] uBlock filters – Privacy​​​​​
- [x] uBlock filters – Resource abuse​​​​​
- [x] uBlock filters – Unbreak​​​​​
- [x] Adblock Warning Removal List
- [x] EasyPrivacy
- [x] Malware Domain List
- [x] Malware domains
- [x] Fanboy’s Annoyance List
- [x] Peter Lowe’s Ad and tracking server list
- [x] SWE: Frellwit's Swedish Filter​​​​​

**Comment by llacb47** [comment]
`||maddeningpowder.com^`

**Comment by jspenguin2017** [comment]
Added. Thanks.
