### ISSUE TITLE
[Ads] bing.com

### ISSUE THREAD

**Issue by AaronKelley** [NanoAdblocker/NanoFilters#439]
### URLs where this issue occurs (Required)

https://www.bing.com/search?q=used+cars

### Screenshot

![1](https://user-images.githubusercontent.com/404829/71524388-4d4aa180-289b-11ea-97e5-897101b9851f.png)

The site is replacing the descriptions with an image.  The blue rectangle is there because I selected one of the images to make it clear that it is an image and not text.

### Screenshot of console

![2](https://user-images.githubusercontent.com/404829/71524465-c0ecae80-289b-11ea-877e-4e803fd6b1fb.png)

### Describe the issue

Bing is somehow detecting the presence of uBlock Origin and firing some code that reinserts the ads, and replaces the descriptions of each entry in the search results with an image, making it impossible to differentiate ads from regular results.  If uBlock Origin is disabled, this replacement does not occur, the description beneath each link will be text.

### Reproduction Steps

Just open the page.

### Anything else you believe to be useful

I'm having trouble reproducing this 100% of the time, I am not sure why, but the image-ad-replacement code on the Bing side doesn't always seem to fire.  Maybe as a "new feature" it is in partial rollout right now?

Here is a Reddit thread discussing the issue (including references to its not-always-reproducibility).  The suggested workaround is a uBlock Origin filter that only works with Firefox.  I think that it might make more sense to target the JavaScript code that is doing the adblock detection. 
[https://www.reddit.com/r/uBlockOrigin/comments/ebuc1o/bing_changing_text_to_images_with_ublock_on/](https://www.reddit.com/r/uBlockOrigin/comments/ebuc1o/bing_changing_text_to_images_with_ublock_on/)

#### Environment

- Operating System and Version: Windows 10 1903
- Browser and Version: Reproduced with Chromium Edge 79.0.309.56 and Firefox 68.3.0 (ESR)
- Nano Adblocker Version: Actually using uBlock Origin (latest - 1.23.0 Edge, 1.24.2 Firefox)
- Nano Defender Version: 15.0.0

#### Your filter lists

Default settings + recommended lists for uBlock Origin / Nano Defender from the "extra installation steps"

**Comment by llacb47** [comment]
`bing.com##+js(set, Blob, noopFunc)` works for me @mapx-

**Comment by jspenguin2017** [comment]
I can't reproduce this. Tried 5 different queries.

**Comment by llacb47** [comment]
How I reproduced:
Go to bing homepage, type in search box `book flight` or `hotels`

**Comment by AaronKelley** [comment]
> `bing.com##+js(set, Blob, noopFunc)` works for me @mapx-

Thank you.  This seems to have fixed it for me as well.

**Comment by jspenguin2017** [comment]
This seems to work for me (adapted from the rule on Reddit): 
```
bing.com##+js(nano-remove-elements-onready, #b_results > .b_ad)
```

**Comment by jspenguin2017** [comment]
@okiehsch
