### ISSUE TITLE
blazor-demo.github.io

### ISSUE THREAD

**Issue by ScottRFrost** [NanoAdblocker/NanoFilters#44]
Not necessarily an ad problem, but try loading this page (heavy WebAssembly) with Nano Defender enabled.  Something like 35-40 seconds, right?  Now try loading it with Nano Defender disabled... nearly instant.

Occurs on Firefox 60.0b2 (64-bit) w/ Nano Defender 13.41 & Chrome Version 65.0.3325.125 (Official Build) beta (64-bit) w/ Nano Defender 13.42.

As we (hopefully) see more WebAssembly based web apps in the future, we need to make sure Nano Defender doesn't break them.

**Comment by jspenguin2017** [comment]
Something is stuck in an infinite loop, but it has nothing to do with WebAssembly, see this demo, it works fine with Nano Defender enabled: http://webassembly.org/demo/Tanks/

**Comment by jspenguin2017** [comment]
V8 has some performance issue when enumerating large arrays, feels like an engine bug, but I found a workaround.

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/commit/9708a891d105a37a94310f098311ecfcb87ab4e7

**Comment by ScottRFrost** [comment]
Thanks for the quick fix!
