### ISSUE TITLE
[Ads] controlc.com

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoFilters#441]
Split from https://github.com/NanoAdblocker/NanoFilters/issues/368

`https://controlc.com/a19e8e3d`

Twitch video in the page, not sure if it should be considered to be ads.

**Comment by Cyberavater** [comment]
It seems they removed the Twitch ad videos.

**Comment by jspenguin2017** [comment]
Interesting, it's gone now. Alright, closing for now.
