### ISSUE TITLE
[Anti-adblock] distractify.com

### ISSUE THREAD

**Issue by Sopor** [NanoAdblocker/NanoFilters#443]
### URLs where this issue occurs (Required)
https://www.distractify.com

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/5789283/72115272-c4297500-3346-11ea-9ca5-26def78cf468.png)

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Firefox 72.0.1
- Nano Adblocker Version: uBlock Origin 1.24.2
- Nano Defender Version (Optional if you are not using it): 15.0.0.177

#### Your filter lists (Required)
- [x] uBlock filters
- [x] uBlock filters – Annoyances​​​​​
- [x] uBlock filters – Badware risks​
- [x] uBlock filters – Privacy​​​​​
- [x] uBlock filters – Resource abuse​​​​​
- [x] uBlock filters – Unbreak​​​​​
- [x] Adblock Warning Removal List
- [x] EasyPrivacy
- [x] Malware Domain List
- [x] Malware domains
- [x] Fanboy’s Annoyance List
- [x] Peter Lowe’s Ad and tracking server list
- [x] SWE: Frellwit's Swedish Filter​​​​​

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
We have fixed the same issue in `uBO-filters` and annoyances.

I have to think about it.

**Comment by llacb47** [comment]
`distractify.com##+js(acis, atob, googlefc)` doesn't work in Nano Adblocker nor uBo for me, even though it (supposedly) worked 2 days ago https://github.com/NanoMeow/QuickReports/issues/2670 ??

**Comment by okiehsch** [comment]
generichide works.

**Comment by llacb47** [comment]
``distractify.com##+js(acis, atob, googlefc)` only works for the homepage. For article pages add `distractify.com##+js(aopw, scripts)`

**Comment by okiehsch** [comment]
I prefer generichide to ``distractify.com##+js(aopw, scripts)`.

I am pondering if it is an annoyance or not,
It seems to like the message is wrongly claiming or hinting that the site is not working correctly and therefore the adblocker should be disabled.

**Comment by okiehsch** [comment]
I tried other domainswith the same issue and I get the same problem on some of them.

@llacb47 can you test if
`example.com##+js(nostif, removeChild, 100)`
works for you?

**Comment by llacb47** [comment]
It works!

**Comment by okiehsch** [comment]
Thanks.
@jspenguin2017 I will fix it in `uBO-filters`.
