### ISSUE TITLE
[Ads] sportingnews.com

### ISSUE THREAD

**Issue by DandelionSprout** [NanoAdblocker/NanoFilters#444]
### URLs where this issue occurs (Required)

`https://www.sportingnews.com/`

### Screenshots (Required)

Impossible to demonstrate with a still-image.

### Screenshot of console (Required, press `F12` to open the console)

![image](https://user-images.githubusercontent.com/22780683/72347436-7d39d780-36d8-11ea-8170-5b96fcecd873.png)

### Describe the issue (Optional if obvious)

Nano Defender's anti-`g00` functionality doesn't seem to me to be working properly on `https://www.sportingnews.com/`. Although it does block the `g00` ads there, the site tries to load several hundred scripts and images from its `g00` domains, causing very sluggish loading and a CPU usage of around 50% for around 20~30 seconds.

### Reproduction Steps (Optional if trivial)

1) Visit `https://www.sportingnews.com/`.
2) Scroll a bit up and down if the mass-loading doesn't show immediate effects.

### Anything else you believe to be useful (Optional)

As I've never used uBO Extra, I have zero idea if this issue applies to that extension as well, although I presume it does.

Also note that the `g00` stuff does **not** get loaded, if the console tab is open at the time of a page reload.

#### Environment (Required)

- Operating System and Version: Windows 10 November 2019 Update
- Browser and Version: Chrome 64-bit
- Nano Adblocker Version: 1.0.0.135
- Nano Defender Version (Optional if you are not using it): 15.0.0.180

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/22780683/72347339-377d0f00-36d8-11ea-87eb-89c06a5fc52f.png)

#### Your custom filters (Required if you have any)

None that are related to this in any conceivable way.

#### Your other extensions (Required if you have any)

![image](https://user-images.githubusercontent.com/22780683/72347517-b114fd00-36d8-11ea-8af5-f9925135750e.png)

**Comment by llacb47** [comment]
https://github.com/jspenguin2017/uBlockProtector/blob/master/src/content/rules-common.js#L303

**Comment by jspenguin2017** [comment]
Yea, as @llacb47 mentioned, uBO-Extra is currently disabled in ND. It was causing breakage in the past, and I'm not sure if it's safe to turn it back on yet. I don't think there was any significant changes in uBO-Extra since `g00` updated their script.

**Comment by jspenguin2017** [comment]
Also the console detection fix in Chromium seems to have regressed, I recall it was fixed some time ago, but the latest version is once again detectable. 

https://bugs.chromium.org/p/chromium/issues/detail?id=672625#c20
