### ISSUE TITLE
mult.love

### ISSUE THREAD

**Issue by Cufee** [NanoAdblocker/NanoFilters#445]
http://mult.love/ and their sub domains

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/10448622/72414458-20194280-3727-11ea-9139-3b091067d19b.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/10448622/72414560-5fe02a00-3727-11ea-94d7-e424bbd11461.png)

### Describe the issue (Optional if obvious)
Video player displays a ad-block warning message and will not play with Nano Adblocker enabled

### Reproduction Steps (Optional if trivial)
Open http://mult.love/
Click on any of the picture previews. All have their own domain.
Click on any video
Observer the Ad-block warning

#### Environment (Required)

- Operating System and Version: Windows 10 1909
- Browser and Version: Microsoft Edge Version 81.0.381.0 (Official build) dev (64-bit)
- Nano Adblocker Version: Nano Adblocker 1.0.0.135
- Nano Defender Version (Optional if you are not using it): 15.0.0.180

#### Your filter lists (Required)
![image](https://user-images.githubusercontent.com/10448622/72417959-c3ba2100-372e-11ea-9874-0e38e2d32408.png)

#### Your custom filters (Required if you have any)
! 4/10/2019 https://vk.com
vk.com###chat_tab_wrap

! 8/21/2019 https://fxhome.com
fxhome.com###cookie-notice

! 11/9/2019 https://www.instagram.com
www.instagram.com##.FrS-d.QZZGH.pbNvD
www.instagram.com##.Yx5HN.RnEpo

! 11/27/2019 https://blitzhangar.com
blitzhangar.com##.cookie-consent-banner__container
blitzhangar.com##.cookie-consent-banner

#### Your other extensions (Required if you have any)
NA

**Comment by mapx-** [comment]
fixed

**Comment by Cufee** [comment]
Thanks for quick fix :D
