### ISSUE TITLE
lequipe.fr 

### ISSUE THREAD

**Issue by DiaoulDu** [NanoAdblocker/NanoFilters#446]
### Describe the issue (Required)
lequipe.fr does not show the same infos whether or not nano adblocker is enabled. This can be verified accessing https://www.lequipe.fr/Football/ and following the link "Voir les directs" which is supposed to give in real-time the evolution of scores during games. When nano adblocker is enabled the scores are sticky and remain updated when disabling nano adb.

### Screenshot of console (Required, press `F12` to open the console)
```
[Nano] Nano Defender Activated :: www.lequipe.fr core.js:43:24
[Nano] Excluded :: uBO-Extra rules-common.js:306:28
Échec du chargement pour l’élément <script> dont la source est « https://www.lequipe.fr/js/app.13e4c1722d20186b65d3.js ». Football:1143:1
Échec du chargement pour l’élément <script> dont la source est « https://www.lequipe.fr/js/vendors.13e4c1722d20186b65d3.js ». Football:1143:1
```

### URLs where this issue occurs (Required if applicable)

`https://www.lequipe.fr/Directs`

### Reproduction Steps (Optional if trivial)
wait till 8:30 pm in order to have games in process

### Anything else you believe to be useful (Optional)
I've tried to report to @LiCybora but unfortunately he does not answer.

#### Environment (Required)

- Operating System and Version: windows 10
- Browser and Version: FF 72.0.1
- Nano Adblocker Version: 1.0.0.134
- Nano Defender Version (Optional if you are not using it): 15.0.0.177

#### Your filter lists (Required)
standard filters only

#### Your other extensions (Required if you have any)

flagfox, don't care about cookies, Neat URL

**Comment by DiaoulDu** [comment]
works fine when using chrome, brand new install on firefox does not work.

**Comment by jspenguin2017** [comment]
In that case, you have to wait for LiCybora, I don't maintain the Firefox build. 

Let me know if he doesn't respond in 7 days.
