### ISSUE TITLE
Unzap element on a Nano defended site.

### ISSUE THREAD

**Issue by boywonder1971** [NanoAdblocker/NanoFilters#447]
### Describe the issue (Required)
Hello there and wonderful work on this superior adblocker and anti-adblocker software .

I am not so much reporting an issue as I am adding to a wishlist of future features I guess.
Although this feature may be possible now but I have not then been able to figure out quite how to do it.  So here is my explaination.

When I am on a site the has an element that I would like to ad to the block list.  I can create it with the zapper.  Which is absolutely awesome and needed from time to time.  But I would like the ability to do the inverse if it is possible.

So for example I use a website called watchseries.  The address is listed in the url section below.
When u make a account on this website to watch my tv  you can track your shows and episodes you have already watched.  For each show there is a button on the page to track the show.  As well for each episode of the show there is a button to say you have already watched that episode.

Now I love the fact that nano blocker blocks all the ads on this page because they are killer but I find that I have to shut it down for a moment while I press either of the two buttons mentioned above to have them function as intended and then turn the adblocker back on.  It is not a horrible inconvenience but an inconvenience non the less.  So what I was hoping I would have the power to do is to have the whole page blocked as usual but have like a unzap element kind of tool where I can pick those to buttons and add them to a list. So even tho the is being ad-blocked, those buttons would function normally without having to first disable the ad-block and then click my button and the re-enable my ad-blocker. 

If this is currently an ability of the software then please forgive my ignorance because I have not been able to figure out how and crawling the web for an answer did not end fruitfully.

And If this is not currently a feature,  I humbly ask that you may consider it an add-on feature for a future release.  Thanks again so much for the great work.

Can someone please respond to me if this is currently something I can accomplish with the current software at pcperfect.windsor@gmail.com , it would be greatly appreciated.

### Screenshots (Required)
![Project1](https://user-images.githubusercontent.com/35278620/73460906-481fbd00-4347-11ea-994f-7c96c7845068.png)

### URLs where this issue occurs (Required if applicable)
https://www1.swatchseries.to/

#### Environment (Required)
- Operating System and Version:  Windows 7
- Browser and Version: Chrome version Version 79.0.3945.130 (Official Build) (64-bit)
- Nano Adblocker Version:  1.0.0.135
- Nano Defender Version (Optional if you are not using it): 15.0.0.180

**Comment by jspenguin2017** [comment]
The DOM Inspector has some ability to create cosmetic filtering rules as well as removing them, however, due to the way CSS works, it's usually better to use Element Picker for creation. 

Note that when something doesn't work right, it's not always an issue with cosmetic filtering, so I think it's better to have the tools related to unbreaking a website in the same place (the Logger).
