### ISSUE TITLE
[Anti-adblock] skip.az

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#448]
Example Link; https://skip.az/XBi7N

**Comment by jspenguin2017** [comment]
Works fine for me.

**Comment by Cyberavater** [comment]
Any non-default filters you are using?
![Screenshot (3)](https://user-images.githubusercontent.com/32187927/73532715-797fb200-4447-11ea-8510-6488d0e3dfb4.png)

**Comment by jspenguin2017** [comment]
Works fine with latest filters on default settings. Did you update your filters?

**Comment by Cyberavater** [comment]
Working fine after updating, thanks!
