### ISSUE TITLE
[Anti-adblock] ghacks.net

### ISSUE THREAD

**Issue by semce2** [NanoAdblocker/NanoFilters#449]
### Screenshots (Required)
![image](https://user-images.githubusercontent.com/52109032/73545288-0a836880-4409-11ea-8d6a-a74812fa4efb.png)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by mapx-** [comment]
fixed https://github.com/uBlockOrigin/uAssets/commit/1cc57be9bfcec1c1fac377a1cac32a90e1eb604a
