### ISSUE TITLE
[Anti-adblock] derstandard.at

### ISSUE THREAD

**Issue by kajover** [NanoAdblocker/NanoFilters#45]
### URLs where this issue occurs

https://derstandard.at/Web

### Screenshots
![screen shot 2018-03-14 at 13 31 42](https://user-images.githubusercontent.com/37370744/37402595-813e426a-278c-11e8-842b-d1955f18686f.jpg)

### Screenshot of console
![screen shot 2018-03-14 at 13 32 53](https://user-images.githubusercontent.com/37370744/37402602-8841198e-278c-11e8-8d4a-350c7dcc2e2b.jpg)

### Describe the issue
Anti adblock cannot be circumvented. It was working before, when refreshing the page 2-3 times.  (maybe the Chrome 65 update is to blame or derstandard.at changed their blocking system)

### Anything else you believe to be useful
In case that it works, wait some time as the implemented anti adblock does not block your access to the website at first.

#### Environment

- Operating System and Version: macOS 10.13.3
- Browser and Version: Chrome 65.0.3325.162 (64-bit)
- Nano Adblocker Version: 1.0.0.34
- Nano Defender Version: 13.43

#### Your filter lists

My filters​​​​​ 0 used out of 0​​​​
Nano Defender Integration​​​​​ 2,719 used out of 2,757​​​​
Nano filters​​​​​ 59 used out of 59​​​​
Nano filters – Timer bypassing (sometimes works)​​​​​ 0 used out of 0​​​​
Nano filters – Whitelist​​​​​ 0 used out of 0​​​​
uBlock filters​​​​​ 4,401 used out of 4,401​​​​
uBlock filters – Badware risks​​​​​ 8 used out of 8​​​​
uBlock filters – Privacy​​​​​ 65 used out of 65​​​​
uBlock filters – Resource abuse​​​​​ 216 used out of 218​​​​
uBlock filters – Unbreak​​​​​ 321 used out of 321​​​​

Adblock Warning Removal List​​​​​ 393 used out of 409​​​​
EasyList​​​​​ 81,571 used out of 81,894​​​​

EasyPrivacy​​​​​ 14,347 used out of 14,516​​​​

Malware Domain List​​​​​ 1,128 used out of 1,143​​​​
Malware domains​​​​​ 17,644 used out of 17,644​​​​

Peter Lowe’s Ad and tracking server list​​​​​ 2,596 used out of 2,600​​​​

DEU: EasyList Germany​​​​​ 9,225 used out of 9,245​​​​

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
@okiehsch Kind of hard to reproduce, need to refresh 6~7 times and wait a bit.

**Comment by okiehsch** [comment]
This is quite tricky, it is related to https://github.com/uBlockOrigin/uAssets/issues/1334

````
||imagesrv.adition.com/js/srp.js$script,redirect=noopjs,domain=derstandard.at
@@||derstandard.at/MetaAdServer/MAS.aspx$xmlhttprequest,first-party
@@||derstandard.at/s/*$image,first-party
````
fixed that issue, but the redirection does not work anymore.

`@@||imagesrv.adition.com/js/srp.js$script,domain=derstandard.at` fixes the issue on my end, you have to delete the existing cookies if you already get the anti-adblock warning.

Blocking cookies outright also fixes the issue.

I am open for any other possible solutions.

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/37437064-c92c7eec-27b0-11e8-8faf-9c361907b0c4.png)
Seems like the GUID is responsible for the block screen. I'm worried that if I change it login will break... I guess blocking cookies is no-go.

**Comment by jspenguin2017** [comment]
What's your concern about whitelisting that script?

**Comment by okiehsch** [comment]
Yes, fixing without breaking the login is probably not possible, unless you allow the script.

I have no particular concern as every ad related stuff pulled through that script is blocked, I was just curious if there was a better way, i.e. without allowing a 3rd-party script, to fix the issue,

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/23aa500afcd91f8272378cc9d4796326bd1c23d5

**Comment by kajover** [comment]
It worked for a while, and now it starts blocking again. Here is a screenshot of the console:

![screen shot 2018-03-15 at 20 27 20](https://user-images.githubusercontent.com/37370744/37486666-79a780da-288f-11e8-9b2c-9b73df35741a.jpg)

Concerning the login, it would be ok if the login is blocked with your method. The login is just there to leave comments on articles. One can do that through incognito mode (with the extension disabled) or within another browser.

**Comment by jspenguin2017** [comment]
We can't globally apply a solution that breaks login.

**Comment by okiehsch** [comment]
I tried to reproduce, I got the anti adblock message one time after I started a new browser session, I then deleted the existing cookies and I now can't reproduce even if I again start a new browser session.

With Firefox I can't reproduce.

**Comment by kajover** [comment]
Deleting the cookies works on Chrome for a certain time. After a time it starts blocking again (on Chrome at least).

**Comment by jspenguin2017** [comment]
Yea, they seems to have changed something.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/02605791540990f758f81c14c6fd4dfac0971ff2

**Comment by kajover** [comment]
I am sorry to reopen the ticket, but the issue is not fixed on my end. I have purged all caches and updated the filter lists again (adblocker v1.0.0.37), as well as having deleted the website's cookies. The paywall reappears after a while. (The only effective method right now is blocking all cookies for that website within the chrome settings)
![screen shot 2018-03-22 at 20 55 03](https://user-images.githubusercontent.com/37370744/37794949-56d54bbc-2e13-11e8-82e0-b92acf779afd.jpg)

**Comment by jspenguin2017** [comment]
Huh, they might be watching us...

**Comment by okiehsch** [comment]
@jspenguin2017 so you can reproduce?

I can't, I have clicked countless articles with Chrome and Firefox without issue.
If I disable the filter I added yesterday, I can consistently reproduce after clicking two or three articles.

**Comment by jspenguin2017** [comment]
Eh, I can't reproduce anymore... Hum...

**Comment by jspenguin2017** [comment]
I thought I updated the filters... I'll put a whitelist in Nano Defender just in case.

**Comment by kajover** [comment]
I still get this

![screen shot 2018-03-24 at 12 39 42](https://user-images.githubusercontent.com/37370744/37863584-8e35aee6-2f60-11e8-9272-c2f75d93e3cc.jpg)

The links that are blocked:
https://at.staticfiles.at/sites/mainweb/css/adv.css?v=529
oewa.js -> https://dispatcher.oewabox.at/oewa.js
rc -> https://derstandard.nuggad.net/rc?nuggn=1072017547&nuggsid=1660588788&nuggtg=community%2Fautorisierung%2Fpurschranke&nuggrid=https%3A%2F%2Fderstandard.at%2FWeb
s -> https://ad1.adfarm1.adition.com/s?t=irgdzGj&v=1&w=1372691478&a=1&b=11&f=0&o=5&r=11&p=https(1)purwallhit(1&s=3213868

And this blocked link changes the t and w values:
https://ad1.adfarm1.adition.com/s?t=irgdAO1&v=1&w=73084297&a=1&b=11&f=0&o=5&r=11&p=https(1)purwallhit(1)lad(0)artexkl(0&s=3213868

Maybe there is an issue with updating the nano filter list. 64 of 64, after purging all caches and reloading:
https://privatebin.net/?d49193799b3734d7#X499Aj8yUuO3GxQvE1h1C7ZlnJRWUnvvN0e65dyl+P8=

**Comment by jspenguin2017** [comment]
From Quick Issue Reporter: 

Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Nano Defender 14.10

[anti-adblock] `https://derstandard.at/`

**Comment by kajover** [comment]
I am sorry to reopen it again and again, but the problem is still reproducible on my end on multiple machines.

![derstandard](https://user-images.githubusercontent.com/37370744/40385952-a4aa2c02-5e08-11e8-9bfa-ea2b88f86d0d.png)


No other extensions than:
Nano Adblocker 1.0.0.50
Nano Defender 14.37

With filter list:
My filters ​​​​​0 used out of 0​​​​
Built-in (9/12)
Nano Defender Integration​​​​​ 2,711 used out of 2,755​​​​
Nano filters ​​​​​79 used out of 81​​​​
Nano filters – Timer bypassing (sometimes works)​​​​​ 0 used out of 0​​​​
Nano filters – Whitelist ​​​​​0 used out of 0​​​​
uBlock filters ​​​​​5,802 used out of 5,804​​​​
uBlock filters – Badware risks​​​​​ 11 used out of 11​​​​
uBlock filters – Privacy ​​​​​96 used out of 97​​​​
uBlock filters – Resource abuse​​​​​ 256 used out of 258​​​​
uBlock filters – Unbreak​​​​​ 407 used out of 407​​​​
Ads (2/4)
Adblock Warning Removal List ​​​​​419 used out of 435​​​​
EasyList ​​​​​81,955 used out of 82,137​​​​
Privacy (1/3)
EasyPrivacy​​​​​ 14,842 used out of 15,024​​​​
Malware domains (2/4)
Malware Domain List ​​​​​1,116 used out of 1,131​​​​
Malware domains ​​​​​21,693 used out of 21,693​​​​
Annoyances (0/5)
Multipurpose (1/5)
Peter Lowe’s Ad and tracking server list ​​​​​2,640 used out of 2,644​​​​
Regions, languages (1/36)
DEU: EasyList Germany ​​​​​9,412 used out of 9,433​​​​

**Comment by jspenguin2017** [comment]
Try clearing your cookies.

**Comment by kajover** [comment]
I have been blocking any derstandard.at cookie for a long time now. It worked until today. So there were no cookies. But even after deleting all cookies, the adblocking starts after a while.

**Comment by jspenguin2017** [comment]
You aren't blocking cookies in your screenshot.

**Comment by kajover** [comment]
No, I was not. The method of blocking cookies on that site did not work anymore. However, it seems like it is working now. When not visiting the site for some time, it takes three clicks to activate the adblocker warning. But when clicking on another page the adblocker warning is gone. So, thank you. Hopefully closed now forever. Thank you again for your help!

**Comment by kajover** [comment]
Ok, I think I have figured it out... or maybe I am getting crazy.
Windows 10 with Chrome 66 and nano defender/adblocker works fine. But on macOS 10.13.4 and the same Chrome and nano defender/adblocker version (same filter list) does NOT work when blocking the page.
This could be the reason why you cannot reproduce it.

**Comment by jspenguin2017** [comment]
Seriously? Well, I can't access that setup so I can't test.

**Comment by okiehsch** [comment]
@jspenguin2017 do you need to bblock cookies for it to work?

It works on my end with a default setup, I also can't test with a system running macOS.

**Comment by kajover** [comment]
Right now, no cookies are blocked. Just nano defender/adblocker is running. It works on Windows but not on macOS.
If it is not too much to ask, you could run macOS inside a Virtual Machine.

**Comment by jspenguin2017** [comment]
I thought macOS only run on Apple's proprietary hardware.

**Comment by kajover** [comment]
@jspenguin2017 It runs in vmware and virtualbox
https://www.youtube.com/watch?v=9QNlz9FPGI8
https://www.youtube.com/watch?v=szHn5GunojU
https://techsviewer.com/install-macos-high-sierra-vmware-windows/

Just as another idea, alternatively, there are Apple Stores in your country maybe.

**Comment by jspenguin2017** [comment]
> It runs in vmware and virtualbox

Ah, looks like a lot of work, I might try it later. @okiehsch Do you have access to an Apple device? 

> there are Apple Stores in your country maybe

Apple's devices are too overpriced, for $1700 I'd rather get a XPS 13 developer edition which has i7 processor instead of a m3. And the touchscreen is also a bonus. 

Beside, I heard [Apple was sued again](https://9to5mac.com/2018/05/12/apple-keyboard-lawsuit/) for hardware design failure.

**Comment by okiehsch** [comment]
> Do you have access to an Apple device?

Only to mobile devices.

**Comment by kajover** [comment]
Bad news, it started popping up again on Windows. (I will personally browse the website in incognito mode only, or regularly delete cookies)

**Comment by jspenguin2017** [comment]
Works perfectly fine for me, even in incognito mode. What extensions have you installed? 
![image](https://user-images.githubusercontent.com/7283682/40428817-6229c148-5e5e-11e8-9591-6d5d5bcb4130.png)

**Comment by kajover** [comment]
I do not have any special extensions...
![chrome](https://user-images.githubusercontent.com/37370744/40454142-dcc2b390-5ee7-11e8-86c1-9d62a0a3bffa.png)
![extensions](https://user-images.githubusercontent.com/37370744/40454143-dce2f5a6-5ee7-11e8-8d34-07dd4a2848f9.png)
![settings1](https://user-images.githubusercontent.com/37370744/40454144-dd02048c-5ee7-11e8-9d18-ab6e1e710607.png)
![settings2](https://user-images.githubusercontent.com/37370744/40454145-dd1f8188-5ee7-11e8-83a5-211018b8c842.png)

**Comment by jspenguin2017** [comment]
I have no idea why it's not working for you... Is there anything on your side that could interfere with network connection (Pi Hole, Adguard native app, etc.)?

**Comment by kajover** [comment]
No pihole, no special apps, no VPN, no anything. The PC (Windows 10 Pro Version 1803) is my gaming PC, so it is a fairly basic installation with some games. I am also using the MacBook on two locations. First one has a Huawei LTE router and the other one a regular router from the ISP.

**Comment by okiehsch** [comment]
Reading through `https://www.lteforum.at/mobilfunk/derstandard-nur-mehr-kostenpflichtig-mit-adblocker.9763` everybody who used uBO had no issues with standard.at

This is the last post that mentions uBlock `https://www.lteforum.at/mobilfunk/derstandard-nur-mehr-kostenpflichtig-mit-adblocker.9763/seite-9.html#post-172493`

**Comment by Esokrates** [comment]
@kajover is right. I can reproduce. Until the last few days I blocked cookies on that site, now they force you to have cookies enabled so I removed my cookie blocking policy and started browsing in incognito mode. After clicking through a few articles and waiting a bit I was blocked from further accessing the page.

**Comment by kajover** [comment]
@okiehsch I have tried ublock origin, and it does not work.
Is it possible that they block Austrian IPs? Could you try through a VPN? I really cannot understand why it works for you guys.
@Esokrates Yep, I did the same before.. just blocking all cookies on that site. But this workaround does not work anymore.

**Comment by Esokrates** [comment]
It's kinda hard to reproduce though. Happened to me in one incognito session pretty instantly. Closed browser tried again and it took some time to trigger it again. So testing with only a very few click is not enough.

**Comment by okiehsch** [comment]
I did not mean to say that it should work with uBlock, as a rule of thumb ,if it works with Nano it works with uBlock and vice versa.
"Takes 30-40 clicks to get the adblock wall." Well that does really sound strange, which anti-adblock script would only fire after the 30th click, that defeats it's purpose.

**Comment by okiehsch** [comment]
> Is it possible that they block Austrian IPs?
I get blocked if I disable `uBO-filters` and I do not have an austrian IP at the moment.

I have now clicked atleast 50 articles and I still can't reproduce, there is really nothing more I can do, sorry.

**Comment by kajover** [comment]
@okiehsch I know, I just tried it anyway. 
Maybe they want you to have some kind of demo period where you can read and decide if you want to pay for it. But after clicking around the website, as I said around 30-40 clicks, you get a permanent adblock wall. What works are extensions that delete cookies after a while or you manually delete them quite often. Can I help somehow buy running some debugging or logs?

**Comment by Esokrates** [comment]
@okiehsch Open the page, click around, leave the tab with the page open for a while and return a few minutes later to click a few articles. Triggers for me.

**Comment by okiehsch** [comment]
Their adblocking script is not trivial, I would have to reproduce myself to find a working fix.

If you really only get blocked after 40 articles just delete cookies regularly, it is the best advice I got.

**Comment by okiehsch** [comment]
@Esokrates the tab of https://github.com/NanoAdblocker/NanoFilters/issues/45#issuecomment-391892923 is still open and that was 10 minutes ago.
![unbenannt](https://user-images.githubusercontent.com/16838044/40518226-de04ea2a-5fb9-11e8-835c-dbb9bb52a4c3.JPG)

**Comment by okiehsch** [comment]
As you can see from my screenshot I only run uBO, now I have said all there is to say from my end.
I can't reproduce, I can't help.

**Comment by Esokrates** [comment]
I failed to trigger it when tunneling through tor, but maybe that's coincidene.

**Comment by Esokrates** [comment]
@okiehsch Whats the status of this now? I can still reproduce, even faster now.

**Comment by Esokrates** [comment]
If I read https://github.com/uBlockOrigin/uAssets/issues/2632 correctly the fix would be out of scope for uAssets, but maybe @jspenguin2017 could include a fix for NanoDefender?

**Comment by jspenguin2017** [comment]
It works perfectly fine for me. If you are using an Apple device, report to Apple, it's a problem with their OS.
