### ISSUE TITLE
[Ads] controlc.com

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#454]
Split from #368 & #441

It seems they are re-appearing. This time more annoying than before.

Eg link; https://controlc.com/a19e8e3d

**Comment by jspenguin2017** [comment]
Can't reproduce. Closing as invalid as you did not fill the template.

**Comment by Cyberavater** [comment]
It seems it's gone again now. Maybe comes goes and comes back from time to time.

**Comment by jspenguin2017** [comment]
OK, open a new issue with proper details if it comes back.
