### ISSUE TITLE
[Ads] yts.mx

### ISSUE THREAD

**Issue by Signup-pawan** [NanoAdblocker/NanoFilters#456]
### URLs where this issue occurs (Required)
https://yts.mx/

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/55138565/74592667-78ef3a00-5049-11ea-9dbe-53afba8ecd1e.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/55138565/74592676-a63be800-5049-11ea-8aa7-16e9b16089aa.png)

### Describe the issue (Optional if obvious)
Unable to access the content in webpage while Nano Defender/Adblocker is in active status. Page is loading but unable to click any content. It's behaves like a static content. When adblocker in disabled the links and clicks working.

#### Environment (Required)

- Operating System and Version:  Windows 10 Pro & 10.0.18363
- Browser and Version: Chrome 79.0.3945.130
- Nano Adblocker Version: 1.0.0.135
- Nano Defender Version (Optional if you are not using it): 15.0.0.185

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/55138565/74592783-b902ec80-504a-11ea-9de4-8cb35f9fdb73.png)

#### Your custom filters (Required if you have any)
![image](https://user-images.githubusercontent.com/55138565/74592766-a2f52c00-504a-11ea-9d8c-9f0b28cf647a.png)

#### Your other extensions (Required if you have any)

![image](https://user-images.githubusercontent.com/55138565/74592749-8fe25c00-504a-11ea-8b5b-efd0841b0c94.png)

**Comment by jspenguin2017** [comment]
@okiehsch Transparent overlay (popup backdrop?) + sponsored VPN ads.

**Comment by okiehsch** [comment]
I get a connection timed out message on my end.

**Comment by jspenguin2017** [comment]
Yea, it looks like the website is down at the moment.

**Comment by Signup-pawan** [comment]
Yeah, seems site is offline at the moment. Did you get a chance to reproduce the issue?

**Comment by jspenguin2017** [comment]
The website is up again, but the transparent overlay issue is gone. Only VPN ads are left.
