### ISSUE TITLE
[Anti-adblock, Ads] pureinfotech.com

### ISSUE THREAD

**Issue by hossamee44** [NanoAdblocker/NanoFilters#458]
### URLs where this issue occurs (Required)
https://pureinfotech.com/

### Screenshots (Required)
![2020-3-3 13-25-6](https://user-images.githubusercontent.com/50141256/75771545-db874c00-5d52-11ea-844e-4d2205bd4e43.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![2020-3-3 13-26-12](https://user-images.githubusercontent.com/50141256/75771558-e3df8700-5d52-11ea-8423-d1ee5bbfb968.jpg)

#### Environment (Required)

- Operating System and Version: windows 10 1909
- Browser and Version: Microsoft Edge 80.0.361.62 (Official build)
- Nano Adblocker Version: 1.0.0.140
- Nano Defender Version (Optional if you are not using it): 15.0.0.190

#### Your filter lists (Required)
default settings

**Comment by mapx-** [comment]
Did you enable `uBlock filters – Annoyances` ?

**Comment by hossamee44** [comment]
no
![2020-3-3 14-26-18](https://user-images.githubusercontent.com/50141256/75775597-f958af00-5d5a-11ea-9b52-39845e7f12d5.jpg)

**Comment by mapx-** [comment]
You need it. Enable it.

**Comment by hossamee44** [comment]
effective. thnx mapx-
