### ISSUE TITLE
Nano filters not updating

### ISSUE THREAD

**Issue by ghajini** [NanoAdblocker/NanoFilters#460]
### URLs where this issue occurs (Required)
https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt?_=0

https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt?_=0

https://gitcdn.xyz/repo/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt?_=0

### Screenshots (Required)
![IMG_20200317_183303](https://user-images.githubusercontent.com/20338483/76858640-d7444e00-687d-11ea-9882-81060790333d.jpg)

### Screenshot of console (Required, press `F12` to open the console)
Not possible in firefox android

### Describe the issue (Optional if obvious)

Filter lists not updating
### Reproduction Steps =
Try to update filters,update fails

### Anything else you believe to be useful (Optional)

Blocked by easylist rule  
`/^https?:\/\/.*\.(xyz|site|best|club|space|info|bid)\/.*/$xmlhttprequest,3p`
As per ubo logger

#### Environment (Required)

- Operating System and Version: android 7
- Browser and Version: firefox android stable
- Nano Adblocker Version: using ublock origin
- Nano Defender Version (Optional if you are not using it): 15.0.0.194

#### Your filter lists (Required)
the default settings+those required for nano defender to work

#### Your other extensions (Required if you have any)
Decentraleyes+nano defender

**Comment by llacb47** [comment]
Rule removed https://github.com/easylist/easylist/commit/c0f5b38df2bf2fed8d0b5faa9b7b1a66325e9e3b

**Comment by ghajini** [comment]
I force updated easylist, I don't get updated filters, if fixed then no issue
