### ISSUE TITLE
[Anti-adblock] onlinebr.xyz

### ISSUE THREAD

**Issue by sanGtH** [NanoAdblocker/NanoFilters#461]
Link : http://onlinebr.xyz/ads/?file=4f844234a6 detects uBlock Origin
I have updated the filters but the detection continues
**Screenshot :** 
![image](https://user-images.githubusercontent.com/13797193/77084047-6b501a00-6a24-11ea-95f4-8a99fa404927.png)

#### Environment (Required)

- Operating System and Version:  **Win 7 64Bit**
- Browser and Version: **Chrome v80.xx**
- Nano Adblocker Version: **1.0.0.140**
- Nano Defender Version (Optional if you are not using it): **15.0.0.194**

#### Your filter lists (Required)
**uBlock Filters
Adblock Warning Removal
Easylist**
#### Your custom filters (Required if you have any)
**Nano Defender Integration
Nano filters
Nano filters - Whitelist**
#### Your other extensions (Required if you have any)
**uBlock Origin 1.24.4**

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/commit/39affb10f5957cdd444b62f094f87f6473086aa2

**Comment by sanGtH** [comment]
@llacb47 Does this mean that the Nano Defender does not need to be updated ?

**Comment by jspenguin2017** [comment]
ND is only updated when it's needed, for this case, it's not needed.
