### ISSUE TITLE
[Anti-adblock] png.is

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#464]
Eg Link: https://png.is/find?id=1020951850
Alt: https://png.is/f/marinette-dupain-cheng-adrien-agreste-t-shirt-purse/6735541869477888-201901091736.html

**Comment by llacb47** [comment]
`||nohat.me^*/adblock-checker.js`

**Comment by Cyberavater** [comment]
Click on the download link you'll find another [Anti-adblock] there;
https://findandfound.ga/image.php?id=tBFaZRNyupiDfTIBDdx5HgBJhF%2B%2FR8IZ%2BWThygVJ%2BIi4c1yNLK93lnaEPi%2FpHCzEJ8vzrouT%2FOsW580ro%2F1jC54sJP%2FE3J50Y3UNTxbVzjjN%2BNMnrypTuc64MJ7kh62Z7NjgGRau6n%2BEEzHMnpy0rS75QWy7o9jrEO5IFzRY%2Fg%2B%2BryMPrlgnqWtx5Z411EjOvJHlCZ1wpCByA2nGdPydpddYqTcy12e44ah3sd8zpNw%3D
