### ISSUE TITLE
[Anti-adblock] corriere.it

### ISSUE THREAD

**Issue by gershwin82** [NanoAdblocker/NanoFilters#465]
https://www.corriere.it/

### Screenshots (Required)
![Schermata 2020-03-25 alle 12 49 31](https://user-images.githubusercontent.com/62649264/77533442-26e6d300-6e97-11ea-9cd1-909b9a144819.png)

### Describe the issue (Optional if obvious)
nano defender not working on google chrome in this website

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by mapx-** [comment]
It was fixed, update uBO filters list.

**Comment by gershwin82** [comment]
Thank you!
