### ISSUE TITLE
[Breakage] mylifetime.com

### ISSUE THREAD

**Issue by prech** [NanoAdblocker/NanoFilters#466]
### URLs where this issue occurs (Required)

https://play.mylifetime.com/shows/married-at-first-sight/season-2/episode-0
https://play.mylifetime.com/shows/unreal/videos/quinn-tessentials?playlist_slug=unreal-season-1-top-curated-list

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/8314103/77704721-f5473800-6f7a-11ea-9172-1dd4a1205e3e.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/8314103/77704945-90d8a880-6f7b-11ea-85ad-08d3a5a0ab6d.png)

### Describe the issue (Optional if obvious)
Videos on mylifetime.com won't load with Nano Defender enabled

### Reproduction Steps (Optional if trivial)

Go to example URLs above, videos will only load if Nano Defender is disabled

### Anything else you believe to be useful (Optional)
I tried keeping ND enabled, while whitelisting the mylifetime.com domain in my uBlock's Nano Filters - Whitelist, but no change 

#### Environment (Required)

- Operating System and Version: Windows 10 Pro 1909
- Browser and Version: Chrome 80.0.3987.149
- uBlock Origin v1.24.4
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/8314103/77705787-cbdbdb80-6f7d-11ea-8060-35a5f4172682.png)

#### Your custom filters (Required if you have any)
NA

#### Your other extensions (Required if you have any)
 Google Translate : version 2_0_9
 Slides : version 0_10
 Magic Actions for YouTube™ : version 7_9_1_2
 Web Store : version 0_2
 Docs : version 0_10
 Google Drive : version 14_1
 Pop up blocker for Chrome™ - Poper Blocker : version 4_0_8_6
 YouTube : version 4_2_8
 HelloFax : version 2_0_4
 Forecastfox (fix version) : version 4_25
 uBlock Origin : version 1_24_4
 Stylus : version 1_5_9
 IMDb rottentomatoes scores : version 3_4_0
 Tampermonkey : version 4_9
 Old Reddit Redirect : version 1_1_4
 Disable HTML5 Autoplay : version 0_6_2
 Dark Reader : version 4_9_2
 Google Calendar : version 4_5_10
 Wikiwand: Wikipedia Modernized : version 8_2_13
 MyJDownloader Browser Extension : version 3_2_33
 Sheets : version 1_2
 Chrome Remote Desktop : version 77_0_3836_0
 IBA Opt-out (by Google) : version 1_5
 Watcher for Yahoo! Mail™ : version 2_30
 Feedback : version 1_0
 Nano Defender : version 15_0_0_195
 Google Docs Offline : version 1_9_1
 Selection Search : version 0_8_55
 LastPass: Free Password Manager : version 4_44_0_1
 Scroll To Top : version 4_8_1
 Checker Plus for Google Calendar™ : version 26_1_7
 Video Preview : version 2_3_1
 Referer Control : version 1_35
 Disable Content-Security-Policy : version 1_0_6
 Apps Launcher : version 2_4_13
 Imagus : version 0_9_8_73
 Distill Web Monitor : version 1_15_7
 Long Press New Tab : version 3_1
 CrxMouse Chrome™ Gestures : version 4_4_4
 PixelBlock : version 2019_4_9
 Reddit Enhancement Suite : version 5_18_11
 Google Voice (by Google) : version 2_5_8
 The Great Suspender : version 7_1_0
 SimpleExtManager : version 1_4_8
 User Agent Switcher, URL sniffer : version 0_9_3_9
 JP White : version 1_0
 Application Launcher for Drive (by Google) : version 3_2
 Temporary bookmarks : version 2_0_0
 AwardWallet : version 2_34
 Take Webpage Screenshots Entirely - FireShot : version 0_98_97_2
 Cloud Print : version 0_1
 Instant Dictionary by GoodWordGuide.com : version 10_4
 Chrome PDF Viewer : version 1
 Google Network Speech : version 1_0
 Google Hangouts : version 1_3_15
 Chrome Web Store Payments : version 1_0_0_5
 Checker Plus for Gmail™ : version 22_0
 ScriptSafe : version 1_0_9_3
 Sci-hub Links : version 1_2_2
 strikethrough : version 1_2_1_1
 Gmail : version 8_2

**Comment by llacb47** [comment]
```
if (a.domCmp(["history.com", "mylifetime.com"])) {
    a.inject(() => {
        "use strict";
        const f = (e) => { e(false); };
        window._sp_ = {};
        window.Object.defineProperties(window._sp_, {
            "checkState": {
                configurable: false,
                set() { },
                get() {
                    return f;
                },
            },
            "isAdBlocking": {
                configurable: false,
                set() { },
                get() {
                    return f;
                },
            },
            "_detectionInstance": {
                configurable: false,
                set() { },
                get() {
                    return undefined;
                },
            },
        });
    });
}
```

`VM2775:1 Uncaught Error: _sp_.config is not defined`

The player needs `_sp_.config`.

**Comment by prech** [comment]
Thanks much for the fast response @llacb47 and @jspenguin2017!

Working well
