### ISSUE TITLE
[Anti-adblock] bolognatoday.it

### ISSUE THREAD

**Issue by Mons1990** [NanoAdblocker/NanoFilters#468]
### URLs where this issue occurs (Required)
http://www.bolognatoday.it/cronaca/bologna-deserta-coronavirus-autobus-13.html?fbclid=IwAR0CSpmucwOaMsu8m6BaW_uysOe6PeFwyCpYyhFeza5pFND8pZ3iRLQl2q4
every other article

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/11017029/77759624-50d5fc00-7035-11ea-9324-2753bc47813d.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/11017029/77759782-972b5b00-7035-11ea-8cff-64078e98f839.png)

### Describe the issue (Optional if obvious)
Nano Defender does not recognize the anti-adware removal layer

### Anything else you believe to be useful (Optional)
Very compliments for your extensions, your work is something of fantastic!

#### Environment (Required)

- Operating System and Version: Windows 10 1909
- Browser and Version: Chrome 80
- Nano Adblocker Version: uBlock Origin 1.24.4
- Nano Defender Version (Optional if you are not using it): 15.0.0.196

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/11017029/77760048-0ef98580-7036-11ea-94a0-57ddd270c968.png)

Thank you!

**Comment by mapx-** [comment]
fixed
