### ISSUE TITLE
[Anti-adblock] yourtango.com

### ISSUE THREAD

**Issue by chelseaislan** [NanoAdblocker/NanoFilters#47]
### URLs where this issue occurs (Required)
https://www.yourtango.com

### Screenshots (Required)
![screenshot 5](https://user-images.githubusercontent.com/30471081/37700109-de91215e-2d1c-11e8-8227-fc0b803a9597.png)

### Screenshot of console (Required, press `F12` to open the console)
![screenshot 6](https://user-images.githubusercontent.com/30471081/37700114-e1bd808e-2d1c-11e8-8836-a1ec970a4359.png)

### Describe the issue (Optional if obvious)
Anti adblock

#### Environment (Required)
- Operating System and Version: Windows 10 1709
- Browser and Version: Chrome 65
- Nano Adblocker Version: 1.0.0.37
- Nano Defender Version (Optional if you are not using it): 13.47

#### Your filter lists (Required)
Default ones

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/07848eb7dfe870ece3fb5127f34b651278d7aa69
