### ISSUE TITLE
NSFW! [Anti-adblock] javfinder.la

### ISSUE THREAD

**Issue by k4fingers** [NanoAdblocker/NanoFilters#471]
### URLs where this issue occurs (Required)

https://javfinder.la/movie/watch/attackers-sspd-139-super-special-jav-free-xxx-riginal-mido-ran-beautiful-three-sisters-and-prison-prisoners.html

### Screenshots (Required)
<details>

![1](https://user-images.githubusercontent.com/62971401/78087834-82abe180-73ec-11ea-9480-c8a4cd89085c.png)

</details>

### Screenshot of console (Required, press `F12` to open the console)
<details>

![2](https://user-images.githubusercontent.com/62971401/78087893-aa02ae80-73ec-11ea-87fb-527337fb816f.png)

</details>

### Describe the issue (Optional if obvious)
Cannot watch the video

#### Environment (Required)

- Operating System and Version:  Windows 10 
- Browser and Version: Google Chrome Version 80.0.3987.149 (Official Build) (64-bit)
- Nano Adblocker Version: uBlock Origin 1.24.4
- Nano Defender Version (Optional if you are not using it): 15.0.0.196

#### Your filter lists (Required)

Built-in (5/5)
uBlock filters​​​​​21,292 used out of 21,425​​​​
uBlock filters – Badware risks​​​​​847 used out of 857​​​​
uBlock filters – Privacy​​​​​171 used out of 176​​​​
uBlock filters – Resource abuse​​​​​116 used out of 118​​​​
uBlock filters – Unbreak​​​​​1,402 used out of 1,451​​​​
Ads (1/3)
EasyList​​​​​82,540 used out of 82,743​​​​
Privacy (1/3)
EasyPrivacy​​​​​17,348 used out of 17,426​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,104 used out of 1,104​​​​
Malware domains​​​​​26,842 used out of 26,857​​​​
Annoyances (0/7)
Multipurpose (1/4)
Peter Lowe’s Ad and tracking server list​​​​​3,182 used out of 3,274​​​​
Regions, languages (2/34)
JPN: AdGuard Japanese​​​​​1,313 used out of 1,316​​​​
VIE: ABPVN List​​​​​1,221 used out of 1,223​​​​

#### Your custom filters (Required if you have any)
Custom (4/4)
Adblock Warning Removal List​​​​​740 used out of 745​​​​
Nano Defender Integration​​​​​2,632 used out of 2,645​​​​
Nano Filters​​​​​367 used out of 367​​​​
Nano Filters - Whitelist​​​​​1 used out of 1​​​

**Comment by jspenguin2017** [comment]
Can't reproduce.
