### ISSUE TITLE
[Ads] 1shortlink.com

### ISSUE THREAD

**Issue by leanhducch2** [NanoAdblocker/NanoFilters#472]
### URLs where this issue occurs (Required)
  example link: https://1shortlink.com/link-encrypted/eyJpdiI6IkU1NVlXcEg5XC9tU2J6a2JMTXkrY1NBPT0iLCJ2YWx1ZSI6IlpTUkZnMnJ5M0MwT1FPandUUVZqUzQ5bE5zd1pjZlNJamhGMlJJc0tYdGZRQnFLU2F2YUFSMmlIWTlQem1HT3VIajZ1TDhOXC9CTGdMaEdUMXF4UGtTZ2FtblB5TEcreThUYVU2S1h6azdWUGFvNnlGKzdZbXpWYXFxbUVCajUxT0JpTWczbVVEUTlCRW01ZlJzR3l3aHV6TytUOGU0Z0dVUlpBeDJDbVJWMFU9IiwibWFjIjoiZDBhMTU4MTZlZjZiNzJiNTVlOTJiODlmNjg1MTk5MjA1ZDY0NDU2N2E0YjhhMjFhOTAzNmE4MWU4ZDFjNTRjNyJ9

#### Environment (Required)

- Operating System and Version:windows 10 1909 
- Browser and Version: chrome newest
- Nano Adblocker Version: i use ublock origin
- Nano Defender Version (Optional if you are not using it): newest

#### Your filter lists (Required)
    default setting

**Comment by jspenguin2017** [comment]
Has a weird YouTube embed, can't reproduce other issues. 

@okiehsch FYI.

**Comment by okiehsch** [comment]
I blocked the embed.

@jspenguin2017 I am not sure if you are aware of https://github.com/uBlockOrigin/uBlock-issues/issues/956
If you want I can provide you with an invite link.

**Comment by jspenguin2017** [comment]
@okiehsch I did saw that issue, but I wasn't sure what was the decision, the issue was closed without a conclusion. So it's Slack or Riot.im? Also what do you need to send invites? Do you need my email or something else?

**Comment by okiehsch** [comment]
It's on slack, it has been up and running for about 10 days I think.
We want to keep it private so I can't post the link here.
I would need a valid email address from you,

**Comment by jspenguin2017** [comment]
@okiehsch Sounds good, my email: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/51

**Comment by okiehsch** [comment]
I sent the link.

**Comment by jspenguin2017** [comment]
Got it, thanks.
