### ISSUE TITLE
Anti-ads    1shortlink.com

### ISSUE THREAD

**Issue by leanhducch2** [NanoAdblocker/NanoFilters#474]
### Screenshots (Required)
![image](https://user-images.githubusercontent.com/63135374/78977673-bc928b80-7b42-11ea-9864-62a446610b99.png)

#### Environment (Required)

- Operating System and Version:   windows 10
- Browser and Version: edge chromium   (it's do good in chrome)
- Nano Adblocker Version: new
- Nano Defender Version (Optional if you are not using it): new

**Comment by mapx-** [comment]
Example link ?

**Comment by leanhducch2** [comment]
https://1shortlink.com/link-encrypted/eyJpdiI6ImxIb2ZSbjVvY1wvbVpkZTd2NUlcL2hNUT09IiwidmFsdWUiOiJcL3hMTUtUWkMwRDg3OTFzYzVlMHpHSkdrMzUxUmRvTlRzMGZyY0ZIT2hRYUdVa1E5RXRhZHRRU3dJclo3eVwveDZMNGNmbDNJM2JoV0x6S05rNlRPZSs0a2JwSll5dkJQUFN0OFJ4NmM3c051SVZicWRKZlNTMTdOZWJWakJpVXpCQitpY0M0MWtRR2NjcVpYRmZjckZaaEdCY1FqNWR5aFwvTjZVM2RudzBcL0hVPSIsIm1hYyI6IjY1ODNhMzVjZGE3MmY5YzY2MjVkODA0NjBlODA3MzYxOTllOWUyYzYwYWI3NzAxMWZlNmJjMTNhZDBlNmIzYWQifQ==

**Comment by mapx-** [comment]
No issue chrome / edge + uBO on my end

**Comment by jspenguin2017** [comment]
Can't reproduce. Works fine on default setup.
