### ISSUE TITLE
[Anti-adblock] reevown.com

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#478]
Eg link: reevown.com
Use this link to test: http://www.mediafire.com/file/ixjyauefvj0g7kk/Adobe_Photoshop_CC_2020_v21.1.1.121_%255BDeLtA%255D.7z.001/file
![Screenshot (129)](https://user-images.githubusercontent.com/32187927/79094617-f13c5800-7d79-11ea-946d-227c2481d883.png)

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1733
