### ISSUE TITLE
[Anti-adblock] coolsoft.altervista.org

### ISSUE THREAD

**Issue by Mavromatis** [NanoAdblocker/NanoFilters#482]
### URLs where this issue occurs (Required)
https://coolsoft.altervista.org/en/virtualmidisynth

### Screenshots (Required)
https://lithi.io/file/eA3p.png

### Screenshot of console (Required, press `F12` to open the console)
https://lithi.io/file/v3hI.png

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Brave Version 1.7.92 (Brave Shields Disabled)
- Nano Adblocker Version: 1.0.0.142
- Nano Defender Version (Optional if you are not using it): 15.0.0.197

#### Your filter lists (Required)

Nano Defender Integration
Nano filters​​​​​
Nano filters – Whitelist
uBlock filters​​​​​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Adblock Warning Removal
EasyList
Nano contrib filter – Placeholder buster
AdGuard Tracking Protection​​​​
EasyPrivacy
Malware Domain List
Malware domains​​​​​
Anti-Facebook
Nano filters – Annoyance
uBlock filters – Annoyances​​​​​
NoCoin Filter List
Peter Lowe's Ad and tracking server list​​​​​
TUR: AdGuard Turkish

**Comment by jspenguin2017** [comment]
Can't reproduce, website works fine for me.
