### ISSUE TITLE
[Ads] lrepacks.ru

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#486]
### Describe the issue (Required)

It creates empty space for nothing.

### Screenshots (Required)
![Screenshot (136)](https://user-images.githubusercontent.com/32187927/80314783-55005f80-8815-11ea-88ee-2d8f8688db74.png)

### Screenshot of the console (Required, press `F12` to open the console)

![Screenshot (139)](https://user-images.githubusercontent.com/32187927/80314850-e079f080-8815-11ea-9479-c6a0fadafff8.png)
![Screenshot (140)](https://user-images.githubusercontent.com/32187927/80314854-e40d7780-8815-11ea-9883-4328e1bbe6fe.png)

### URLs where this issue occurs (Required if applicable)

https://lrepacks.ru/

### Reproduction Steps (Optional if trivial)

It should be like this; 
![Screenshot (138)](https://user-images.githubusercontent.com/32187927/80314875-0dc69e80-8816-11ea-8a49-ad2715f25ad0.png)

#### Environment (Required)

- Operating System and Version:  Latest
- Browser and Version:  Chrome Latest
- Nano Adblocker Version: Latest
- Nano Defender Version (Optional if you are not using it): Latest

#### Your filter lists (Required)

Default + RUS

#### Your custom filters (Required if you have any)
N/A

#### Your other extensions (Required if you have any)
A lot but it shouldn't affect as I get it fixed only by disabling Nanoadblocker.

**Comment by jspenguin2017** [comment]
Only small placeholders with Russian regional filters enabled. remaining placeholders fixed in the placeholder buster filter.
