### ISSUE TITLE
[Ads] dlapk4all.com

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#487]
https://dlapk4all.com/?app_id=com.easybrain.make.music

Click on download and an ad will open in new tab.

OS: Android 9
Platform: Firefox

**Comment by jspenguin2017** [comment]
@okiehsch Popup.

**Comment by llacb47** [comment]
`||ughhimtoy.com^$3p`

**Comment by jspenguin2017** [comment]
Looks like a throwaway domain... May need a scriptlet to make it more permanent.

**Comment by Cyberavater** [comment]
I'm still having issues here. It still opens up a page in new tab an force downloads an apk file on my Android Firefox. Can you try check in Android and do something for it?

**Comment by llacb47** [comment]
@ghajini can you check?

**Comment by mapx-** [comment]
tested in FF + android => I get no popup

**Comment by jspenguin2017** [comment]
I cannot reproduce popups on Chrome. For Firefox specific issues, you have to open issues here: https://github.com/LiCybora/NanoDefenderFirefox/issues

**Comment by ghajini** [comment]
Works as intended
![Screenshot_2020-04-30-07-09-09-942_org mozilla firefox](https://user-images.githubusercontent.com/20338483/80663996-33240880-8ab3-11ea-8319-eaf16cedf305.png)
Make sure to update the filters

**Comment by Cyberavater** [comment]
Yes its working perfectly now. Not sure why it wasn't working then (I updated the filter & checked it 2 times before reporting again).

**Comment by ghajini** [comment]
For firefox 
 I wait 2-3 hrs after commit to get updated filters(manual force update) or add that filters to my filters to check working...
