### ISSUE TITLE
[Anti-adblock] png.is

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#488]
#464 revived.

**Comment by llacb47** [comment]
They use three different variations of anti-adb code. The first filter fixes breakage from uBlock filters.

Test URL 1: `https://nohat.cc/f/a-software-engineer-programming-at-the-desk-programmer-and-dev/5142416520642560-201810220535.html`
Test URL 2: `https://png.is/find?id=406801399&ref=AVCufrqQ-wnmjsG_IwmFy2jkkNknjM4kV3H34TbrbGMYxjDXXW0yxRmFElOTHBRPNPE`
Test URL 3: `https://findandfound.ga/view/xTYhZpq%2B1bZWY3h%2B6DIZbcY3upANvhr5bjkuNqMIX4wMn6EClvSS%2BkiKMfVIgXD2diSU%2BvdVYC4610xXT5AKnRcHXwFVnPeiBYEIAuYUeLj3HWGt%2BYRgmbov99%2FQO6tCcbkMfhIzpvwE8E1nmF76BaN5fOhIht1NB4jQi2c9SX6rL5nYwFI7GGelhA61GPQr%2Ff9YmtAbxnZICvmRRvLDXZIM2PvdLxx2MHTd9wOErRdkPrrDmGm8GCQaz9ufAOGR`

```
@@||nohat.me/s?*k=$xhr,domain=png.is|nohat.cc
png.is,nohat.cc##+js(aopr, console.log)
png.is,nohat.cc##+js(aopr, $.prototype.offset)
findandfound.ga##+js(aopr, $.prototype.html)
findandfound.ga##+js(aopr, onload)
findandfound.ga##+js(ra, oncontextmenu, body)
```

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
