### ISSUE TITLE
[Anti-adblock] aftonbladet.se

### ISSUE THREAD

**Issue by connylindquist** [NanoAdblocker/NanoFilters#49]
### URLs where this issue occurs (Required)
https://www.aftonbladet.se/nyheter/a/RxqxBa/man-forsokte-bestalla-pa-mcdonalds-drive-through--pa-sin-hast

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/27331939/37900897-dbfdbf34-30ef-11e8-8c71-9a8c84b5612d.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/27331939/37900952-06c733ee-30f0-11e8-852e-f7169aadf148.png)

### Describe the issue (Optional if obvious)
Short, the website seem to have implemented new code to twart anti-adblockers. 

### Reproduction Steps (Optional if trivial)

Cant think of anything... I think the print screens speaks for themselfs.

#### Environment (Required)

- Operating System and Version:  Windows 10, Version 1803, OS version 17128.1
- Browser and Version:  Chrome Version 65.0.3325.181 (64 bit)
- Nano Adblocker Version: 1.0.0.37
- Nano Defender Version (Optional if you are not using it):  13.49

#### Your filter lists (Required)

All the default filters. Havnt added/removed anything. (Using Swedish filter chosen by default). 

#### Your custom filters (Required if you have any)
None

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by lassekongo83** [comment]
Fixed in the regional Swedish filter: https://github.com/lassekongo83/Frellwits-filter-lists/commit/cbdc86e8d3e0e103b9b78fdffeee021f3d5da0ac#diff-56366fad67d18791281de45963cf7a17R364

**Comment by jspenguin2017** [comment]
Fixed in regional filter, so I'm closing this.
