### ISSUE TITLE
NSFW! [Ads] picbaron.com

### ISSUE THREAD

**Issue by htaihunter** [NanoAdblocker/NanoFilters#490]
### URLs where this issue occurs (Required)

`picbaron.com/bexw8x16hhhh/5e246c0280dea.jpeg.html`

### Describe the issue (Optional if obvious)

Redirecting to ads

### Reproduction Steps (Optional if trivial)

Click on "continue to image", after get to the content page, move your mouse around and u will notice the ad link at the bottom of browser, then make left/right click, in some case i reproduce this by making right click.

Then the page will get redirected completely to ads, one of the link i get is

`http://nta1vb6cdlrl.com/r9iu8vde?key=0f22c1fd609f13cb7947c8cabfe1a90d&submetric=14854377`

### Anything else you believe to be useful (Optional)

This website i believe is using some kind of rotating ad script, so sometime the redirect is being blocked by nano adblock, but sometime its not.

#### Environment (Required)

- Operating System and Version: Windows 10 pro
- Browser and Version: Chrome Version 81
- Nano Adblocker Version:  Nano Adblocker v1.0.0.142
- Nano Defender Version (Optional if you are not using it): 15.0.0.197

**Comment by jspenguin2017** [comment]
No popup. Placeholder fixed.
