### ISSUE TITLE
[Ads, Anti-adblock] hacksmile.com

### ISSUE THREAD

**Issue by boywonder1971** [NanoAdblocker/NanoFilters#492]
Nano ad blocker blocks about 8 ads from this url but then defender doesnt do its job.
Just a heads up thanks in advance for all the hard work you guys do.

https://hacksmile.com/solved-usb-debugging-not-working-in-android-studio/

**Comment by llacb47** [comment]
```
hacksmile.com##+js(nostif, keepChecking)
hacksmile.com##.all-ads
```
