### ISSUE TITLE
[Breakage] en.spitogatos.gr, xe.gr

### ISSUE THREAD

**Issue by nicman23** [NanoAdblocker/NanoFilters#494]
### Describe the issue
There are some greek websites that inject their body with an ajax call and if they detect an adblocker they display a blank site with a generic "Pardon Our Interruption" message. Even if you disable the adblock you still get a "Pardon Our Interruption" blank site

### Screenshots (Required)
![no](https://user-images.githubusercontent.com/16306097/80962900-9d6fdc80-8e16-11ea-8344-94003b70f2bd.jpeg)

### Screenshot of console (Required, press `F12` to open the console)
![console](https://user-images.githubusercontent.com/16306097/80962974-b7a9ba80-8e16-11ea-9b4a-977572144e7a.jpeg)

### URLs where this issue occurs (Required if applicable)

multiple sites affected, https://en.spitogatos.gr/, https://xe.gr, some others

### Reproduction Steps (Optional if trivial)
go to site, enter a search

#### Environment (Required)

- Operating System and Version: arch linux latest
- Browser and Version: 75
- Nano Adblocker Version: latest from Mozilla (1.0.0.127)
- Nano Defender Version (Optional if you are not using it): latest from Mozilla (15.0.0.169)

#### Your filter lists (Required)
Nano filters​​​
Nano filters – Whitelist​​​
uBlock filters​​​
uBlock filters – Badware risks​​​
uBlock filters – Privacy​​​
uBlock filters – Resource abuse​​​
uBlock filters – Unbreak​
Adblock Warning Removal​​​
EasyList​
EasyPrivacy​
​​Malware Domain List​​​​​
Malware domains​
AdGuard Annoyances​​​
Fanboy's Annoyance​​​
Nano filters – Annoyance​​​
uBlock filters – Annoyances​
Peter Lowe's Ad and tracking server list​
GRC: Greek AdBlock Filter​

#### Your other extensions (Required if you have any)

tested with only nano adblock and defender enabled

**Comment by nicman23** [comment]
as for the versions, i am using the addons.mozilla.org version and manually checking for updates report none

**Comment by jspenguin2017** [comment]
I don't maintain the Firefox build, I can confirm that auto-update is working properly in Chromium. For Firefox-specific issues, you need to report them here: https://github.com/LiCybora/NanoCoreFirefox/issues
