### ISSUE TITLE
[Annoyance, Cookie Wall] pocztapolska24.pl

### ISSUE THREAD

**Issue by krystian3w** [NanoAdblocker/NanoFilters#496]
### URLs where this issue occurs (Required)

`http://pocztapolska24.pl/`

### Screenshots (Required)

![obraz](https://user-images.githubusercontent.com/35370833/81216618-7e6e7780-8fdb-11ea-9521-ce4958292894.png) | ![obraz](https://user-images.githubusercontent.com/35370833/81216553-5ed74f00-8fdb-11ea-8f6b-994733e5b780.png)
--- | ---
with translation | without translation

### Screenshot of console (Required, press `F12` to open the console)

N/A

### Describe the issue (Optional if obvious)

Cookie wall, without accept do not work drag-and-drop files and standard attach button.

### Reproduction Steps (Optional if trivial)

1. open that site
2. try cut pop-up with
3. try upload file with button or drag-and-drop method
4. site block actions with JavaScript:

```js
function() {
  TweenMax.set($('#drop'), {
    className: 'active'
  });
  cookieData[COOKIE_NAME] = COOKIE_KEY;
  createCookie(cookieData, COOKIE_DAYS);
  activateDropZone();
  var tl = new TimelineMax({});
  tl.to($('#terms').parent(), 1, {
      css: {
        opacity: 0
      },
      ease: Power0.EaseNone
    })
    .set($('#terms-drop'), {
      css: {
        visibility: 'hidden',
        display: 'none'
      }
    });
}
```
```js
$(function() {
    
        // checking cookie
        var x = readCookie(COOKIE_NAME);
        if (x === COOKIE_KEY) {
            activateDropZone();            
        } else {
            TweenMax.set($('#terms-drop'), { css: { visibility: 'visible', display: 'block' }});
            TweenMax.set($('#terms'), { css: { visibility: 'visible', display: 'block' }});            
            TweenMax.set($('#drop'), {className:'-=active'});
        }        
        
        // terms close
        $('#close-me').click(function(){  
            TweenMax.set($('#drop'), {className:'active'});            
            cookieData[COOKIE_NAME] = COOKIE_KEY;        
            createCookie(cookieData, COOKIE_DAYS);
            activateDropZone();
            var tl = new TimelineMax({});
            tl.to($('#terms').parent(), 1, { css: { opacity: 0}, ease: Power0.EaseNone})
            .set($('#terms-drop'), { css: { visibility: 'hidden', display: 'none' }});
        });
        
	//slideshow random
	var randomNumber = Math.floor(Math.random()*($("#slideshow .slide").length));
	$("#slideshow .slide").eq(randomNumber).addClass("active");
	// Background cover zoom on
	if(window.innerWidth>600){
		updateIndicators();
	}
```

### Anything else you believe to be useful (Optional)

`pocztapolska24.pl##+js(nanop-click-elements-onready.js, #terms-drop #terms #close-me)`

If no possible abort above script with standard scriplet filters.

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Chrome 81
- Nano Adblocker Version: v1.0.0.142
- Nano Defender Version (Optional if you are not using it): N/A

#### Your filter lists (Required)

Stock + `Nano filters – Annoyance`

#### Your custom filters (Required if you have any)

N/A

#### Your other extensions (Required if you have any)

N/A

**Comment by jspenguin2017** [comment]
Hum... It does mention other policies and terms beside cookies...

**Comment by jspenguin2017** [comment]
Rule: 
```
# https://github.com/NanoAdblocker/NanoFilters/issues/496
pocztapolska24.pl##+js(nanop-click-elements-onready.js, #terms-drop > #terms > #close-me)
```

**Comment by hawkeye116477** [comment]
Not worth it, cuz it's fake site.

**Comment by krystian3w** [comment]
In addition, maybe after hours developers do the site on private account `home.pl` (instead official `poczta-polska` account on `nazwa.pl`, nobody punishes there to upload private pdf.

**Comment by hawkeye116477** [comment]
`No exist in article`

It exists, there is example SMS message...

**Comment by krystian3w** [comment]
Omitted on [ordered list `<ol>`](https://www.w3schools.com/tags/tag_ol.asp).
