### ISSUE TITLE
[Ads, Anti-adblock] citethisforme.com

### ISSUE THREAD

**Issue by whitecoatblackhat** [NanoAdblocker/NanoFilters#497]
https://www.citethisforme.com/ (Required)

### Screenshots (Required)
![You are seeing this message (bug)](https://user-images.githubusercontent.com/65068012/81469980-218fde80-91e0-11ea-80a3-d3d4adce9672.PNG)

![My Filters](https://user-images.githubusercontent.com/65068012/81470130-f1950b00-91e0-11ea-835a-68c5b05e061f.PNG)

### Describe the issue (Optional if obvious)
uBlock Origin + Nano Defender cannot disable the anti-adblocker script on https://www.citethisforme.com/

### Reproduction Steps (Optional if trivial)
 I'm very new to coding, could you please tell me how to bypass their anti-Adblock script? Thank you!

#### Environment (Required)

- Operating System and Version: Windows 10 Home x64
- Browser and Version: Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
- Nano Adblocker Version: I'm using **uOrigin** Version 1.26.0
- Nano Defender Version (Optional if you are not using it): 15.0.0.197

**Comment by jspenguin2017** [comment]
@okiehsch @mapx-

**Comment by whitecoatblackhat** [comment]
Sorry, I don't get what should filter should I add? Is this fixed? Because I'm still seeing the "_You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page._" message.

Thank you!

**Comment by jspenguin2017** [comment]
You need to update your filters.

**Comment by whitecoatblackhat** [comment]
Excuse my blinding ignorance. It took me a while to find out how to update the filters but I got it. It's all clear now! Thanks so much! I genuinely appreciate it!
