### ISSUE TITLE
[Anti-adblock] duolingo.com

### ISSUE THREAD

**Issue by WG-MakerOfThings** [NanoAdblocker/NanoFilters#499]
### URLs where this issue occurs (Required)
duolingo.com

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/63617338/81575428-05717600-9375-11ea-8214-b3c5f1241f27.png)

### Screenshot of the console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/63617338/81577541-8b8ebc00-9377-11ea-9c8d-359718084739.png)
![image](https://user-images.githubusercontent.com/63617338/81577546-8d587f80-9377-11ea-96d0-72ee12b00860.png)
![image](https://user-images.githubusercontent.com/63617338/81577552-8df11600-9377-11ea-8998-d61facfddeea.png)

### Describe the issue (Optional if obvious)
There is a notification telling you to disable Nano Adblocker. I am using Nano Defender.

### Reproduction Steps (Optional if trivial)
With a free account and using Nano Adblocker and Nano Defender, go to Duolingo.com/learn. You should get a message saying "Using an adblocker? Support free education with Duolingo Plus."

#### Environment (Required)

- Operating System and Version: Windows 10 Home Insider Preview Evaluation copy. Build 19619.rs_prerelease.200425-1827
- Browser and Version: Chrome 81
- Nano Adblocker Version: 1.0.0.142
- Nano Defender Version (Optional if you are not using it): 15.0.0.197

#### Your filter lists (Required)

All of them. :D
Built-in (8/8)
Nano Defender Integration ​​​​​2,434 used out of 2,634​​​​
Nano filters​​​​​ 361 used out of 381​​​​
Nano filters – Whitelist ​​​​​0 used out of 0​​​​
uBlock filters ​​​​​20,216 used out of 21,605​​​​
uBlock filters – Badware risks​​​​​ 839 used out of 857​​​​
uBlock filters – Privacy​​​​​ 182 used out of 207​​​​
uBlock filters – Resource abuse ​​​​​105 used out of 117​​​​
uBlock filters – Unbreak ​​​​​1,344 used out of 1,429​​​​
Ads (5/5)
Adblock Warning Removal ​​​​​0 used out of 753​​​​
AdGuard Base​​​​​ 39,001 used out of 40,241​​​​
AdGuard Mobile Ads ​​​​​4,713 used out of 4,960​​​​
EasyList ​​​​​81,561 used out of 83,860​​​​
Nano contrib filter – Placeholder buster​​​​​ 864 used out of 923​​​​
Privacy (3/3)
AdGuard Tracking Protection ​​​​​8,458 used out of 8,762​​​​
EasyPrivacy​​​​​ 13,220 used out of 17,673​​​​
Fanboy's Enhanced Tracking List ​​​​​3,227 used out of 3,506​​​​
Malware domains (3/3)
Malware Domain List ​​​​​1,100 used out of 1,104​​​​
Malware domains ​​​​​26,823 used out of 26,857​​​​
Spam 404​​​​​7,106 used out of 7,136​​​​
Annoyances (8/8)
AdGuard Annoyances ​​​​​27,329 used out of 27,758​​​​
AdGuard Social Media​​​​​ 9,990 used out of 10,674​​​​
Anti-Facebook ​​​​​47 used out of 68​​​​
EasyList Cookie​​​​​ 3 used out of 17,132​​​​
Fanboy's Annoyance​​​​​ 50,917 used out of 54,412​​​​
Fanboy's Social​​​​​ 0 used out of 23,636​​​​
Nano filters – Annoyance ​​​​​18 used out of 23​​​​
uBlock filters – Annoyances ​​​​​3,122 used out of 3,304​​​​
Multipurpose (3/4)
Dan Pollock's hosts file ​​​​​13,501 used out of 14,453​​​​
NoCoin Filter List ​​​​​484 used out of 1,229​​​​
Peter Lowe's Ad and tracking server list ​​​​​1,190 used out of 3,352​​​​
Regions, languages (34/34)
ARA: Liste AR​​​​​2, 664 used out of 2,703​​​​
BGR: Bulgarian Adblock list ​​​​​1,105 used out of 1,116​​​​
CHN: CJX's EasyList Lite​​​​​ 600 used out of 603​​​​
CHN: EasyList China (中文) ​​​​​22,428 used out of 22,444​​​​
CZE, SVK: EasyList Czech and Slovak ​​​​​697 used out of 700​​​​
DEU: EasyList Germany ​​​​​9,604 used out of 9,605​​​​
EST: Eesti saitidele kohandatud filter​​​​​449 used out of 468​​​​
FIN: Adblock List for Finland ​​​​​850 used out of 852​​​​
FRA: EasyList Liste FR​​​​​23, 366 used out of 23,449​​​​
GRC: Greek AdBlock Filter ​​​​​951 used out of 954​​​​
HUN: hufilter ​​​​​1,997 used out of 2,027​​​​
IDN, MYS: ABPindo ​​​​​8,731 used out of 8,762​​​​
IRN: Adblock-Iran​​​​​ 1,234 used out of 1,241​​​​
ISL: Icelandic ABP List ​​​​​187 used out of 188​​​​
ISR: EasyList Hebrew ​​​​​1,742 used out of 1,745​​​​
ITA: ABP X Files ​​​​​4,655 used out of 4,820​​​​
ITA: EasyList Italy ​​​​​4,674 used out of 4,706​​​​
JPN: AdGuard Japanese​​​​​ 1,329 used out of 1,341​​​​
KOR: YousList ​​​​​7,061 used out of 7,099​​​​
LTU: EasyList Lithuania ​​​​​1,476 used out of 1,482​​​​
LVA: Latvian List​​​​​ 385 used out of 388​​​​
NLD: EasyList Dutch ​​​​​1,429 used out of 1,433​​​​
NOR, DNK, ISL: Dandelion Sprouts nordiske filtre​​​​​ 1,219 used out of 1,225​​​​
POL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda​​​​​ 6,560 used out of 6,714​​​​
POL: Oficjalne polskie filtry przeciwko alertom o Adblocku​​​​​ 1,126 used out of 1,146​​​​
ROU: Romanian Ad (ROad) Block List Light ​​​​​578 used out of 601​​​​
RUS: RU AdList ​​​​​35,926 used out of 36,195​​​​
SPA, POR: AdGuard Spanish/Portuguese​​​​​ 2,780 used out of 2,939​​​​
SPA: EasyList Spanish ​​​​​2,204 used out of 2,337​​​​
SVN: Slovenian List​​​​​ 583 used out of 587​​​​
SWE: Frellwit's Swedish Filter ​​​​​6,097 used out of 6,115​​​​
THA: EasyList Thailand​​​​​ 865 used out of 902​​​​
TUR: AdGuard Turkish​​​​​ 6,159 used out of 6,198​​​​
VIE: ABPVN List ​​​​​1,246 used out of 1,259​​​​
Custom (3/3)
hpHosts' Ad and tracking servers ​​​​​0 used out of 0​​​​
Korean Adblock List ​​​​​1,486 used out of 1,489​​​​
Malvertising filter list by Disconnect ​​​​​2,729 used out of 2,736​​​​

#### Your other extensions (Required if you have any)
- Avast Passwords
- Avast Online Security
- Toucan
- Give With Bing
- FlowCrypt Encryption With Gmail
- DuckDuckGo Privacy Essentials
- Microsoft Rewards
- Grammarly

**Comment by llacb47** [comment]
Subscribing to every list will cause issues. Only use defaults + ones you need.

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/81579653-a3f7da00-9369-11ea-8553-32e815bf3689.png)

**Comment by WG-MakerOfThings** [comment]
Hello Jspenguin2017,
The problem I have described was on duolingo.com/learn and not just duolingo.com. 
You will also need a free account (not a pro account!) to view duolingo.com/learn.
![image](https://user-images.githubusercontent.com/63617338/81580295-410f3e80-937b-11ea-9979-c6dc11db3c03.png)

**Comment by jspenguin2017** [comment]
I need a test account, you can send one privately to me: 
`https://legacy.hugoxu.com/PrivateMessage/`
or
`https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/-/issues`

**Comment by llacb47** [comment]
Test account: 
```
dofike4596@mailcupp.com
dofike4596@mailcupp.com
```

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance. 
```
duolingo.com##button:has-text(Try Plus for free):upward(3)
```

**Comment by okiehsch** [comment]
Fixed.
