### ISSUE TITLE
[Ads] deportesmax.info

### ISSUE THREAD

**Issue by xlollomanx** [NanoAdblocker/NanoFilters#50]
### URLs where this issue occurs (Required): 

http://deportesmax.info/?canal=17

### Screenshots (Required): 
https://prnt.sc/iwjagh

### Screenshot of console (Required, press `F12` to open the console):
 https://prnt.sc/iwjdaa

### Describe the issue (Optional if obvious): 

This streaming site is full of ads and other bad things. I tried to block most of ads by adding this filter from myself:

```
 ! 23/3/2018, 09:23:08 http://deportesmax.info/
||max-deportv.*/lateral.html$subdocument
||static.x64zcsqq.netdna-cdn.com/rectangulo.html$subdocument
deportesmax.*###adsdiv
```

Plus my antivirus track this link as malware and I added it too: 
```
xml.junnify.com
xml.hueads.com
xml.balancer.club
xml.adzgame.com
xml.balancer.club
adk.mybestclick.net
```

With these list I blocked most of ads but there is an overlay too on the video player, that I cannot remove despite any custom filter I create. I can remove it if I delete manually this lines `<div class="load-more"><!-- Mask --></div>`  from elements in console. This overlay block you from set full screen option. 
Another important thing is that streaming isn't working always. It works just in case of some "events" so don't worry if it's not streaming any content.
#### Environment (Required)

- Operating System and Version: windows 10 16299.334
- Browser and Version: Chrome 65.0.3325.181
- Nano Adblocker Version: 1.0.0.37
- Nano Defender Version (Optional if you are not using it): 13.49

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
I fixed everything I could reproduce, now this site has over 60 channels with many different streaming hosters, so there will be more issues, with popups or ads etc.

**Comment by jspenguin2017** [comment]
@xlollomanx  Can you verify?

**Comment by okiehsch** [comment]
FYI, I used Channel 42, because the stream worked and it used the same streaming hoster as
`http://deportesmax.info/?canal=17`.

**Comment by xlollomanx** [comment]
@jspenguin2017 @okiehsch I tested using channel 42, now all add has gone even my filter disabled, but the overlays over the media player is still here as you can here in the screenshoot. I have enabled file even this filter:

- SPA, POR: Adguard Spanish/Portuguese
- SPA: EasyList Spanish​

Then I delete all cache data and clicked update now. In this screenshot it's how I see channel 42 now https://prnt.sc/iwxyr5 . Now in this screenshot how it's if I delete `<div class="load-more"><!-- Mask --></div>` from console https://prnt.sc/iwy00s . The media player should open his bar if pass with the mouse over.

**Comment by okiehsch** [comment]
@jspenguin2017 could you take a look
I can't connect to `http://deportesmax.info` although the site is up, I can ping it, no clue what the problem is on my end.

**Comment by jspenguin2017** [comment]
@okiehsch This is what I see. 
![image](https://user-images.githubusercontent.com/7283682/38003579-573d2d3c-31f5-11e8-8204-574f10753153.png)
There's an invisible overlay on the player, these remove it: 
```
bro.adca.st##.load-more
bro.adca.st##.markup
bro.adca.st##.myiframe
```

**Comment by okiehsch** [comment]
Thx, I can reproduce, after using a proxy, I added your fix.

**Comment by xlollomanx** [comment]
Now is perfect thanks.
