### ISSUE TITLE
[Anti-adblock] aktuality.sk

### ISSUE THREAD

**Issue by skrat** [NanoAdblocker/NanoFilters#507]
### URLs where this issue occurs (Required)
https://www.aktuality.sk/clanok/794026/kotleba-sa-dnes-pre-seky-v-hodnote-1488-eur-opat-postavi-pred-sud/

### Screenshots (Required)

https://imgur.com/HcunIgl.png

### Screenshot of console (Required, press `F12` to open the console)

https://imgur.com/pbqRY1A.png

### Describe the issue (Optional if obvious)

uBlock origin detected, site works when I turn it off

#### Environment (Required)

- Operating System and Version: Arch Linux, up-to-date
- Browser and Version: Chromium 81
- uBlock Version: uBlock Origin 1.26.0
- Nano Defender Version (Optional if you are not using it):  15.0.0.199

#### Your filter lists (Required)

https://imgur.com/jMkaXHM.png

**Comment by mapx-** [comment]
fixed by `CZE, SVK: EasyList Czech and Slovak`

**Comment by skrat** [comment]
@mapx- sorry, I'm new to this, where do I click?

**Comment by mapx-** [comment]
in filter lists, just enable that list I specified above

**Comment by skrat** [comment]
@mapx- ooooh, that helped, thank you
