### ISSUE TITLE
[Anti-adblock] washingtonpost.com

### ISSUE THREAD

**Issue by motorar** [NanoAdblocker/NanoFilters#508]
**Google Chrome
Version 83.0.4103.61 （64）**

![teTnpj.jpg](https://s1.ax1x.com/2020/05/28/teTnpj.jpg)

But it works all right with my firefox browser. So why is it against Chrome?

**Comment by jspenguin2017** [comment]
Can't reproduce. Tested a few random articles. 
![image](https://user-images.githubusercontent.com/7283682/83154739-bab66480-a0bd-11ea-8392-20f349fa9d23.png)

**Comment by jspenguin2017** [comment]
Also duplicate of https://github.com/NanoMeow/QuickReports/issues/3779

**Comment by jspenguin2017** [comment]
Duplicate of NanoMeow/QuickReports#3779
