### ISSUE TITLE
docer.pl

### ISSUE THREAD

**Issue by gzenio22** [NanoAdblocker/NanoFilters#51]
Active adblocker is delete bels serch 

Adblocker off
![bez blockera](https://user-images.githubusercontent.com/21177361/37929018-0ee8c052-313f-11e8-9b87-2222f15cb391.png)

Adblocker on

![z blokerem](https://user-images.githubusercontent.com/21177361/37929171-80b00f42-313f-11e8-89a2-a09ecc08c67d.png)

My list filters: https://gist.github.com/gzenio22/189de57472968088d61e5618463a2844

**Comment by gzenio22** [comment]
When I have the nano adblock turned on, the search engine disappears on the site

**Comment by jspenguin2017** [comment]
I can't reproduce, as seen in the screenshot above, the search bar is still present.

**Comment by krystian3w** [comment]
```
||adk.docer.pl^$subdocument,domain=docer.pl
docer.pl#@#[id*="ad-container"]
```

Block iframe try load ads and recover Search bar (Polish list cut this element).
