### ISSUE TITLE
[Anti-adblock] bcvc.live

### ISSUE THREAD

**Issue by sanGtH** [NanoAdblocker/NanoFilters#513]
### URLs where this issue occurs (Required)
https://bcvc.live/toHTswM

### Screenshots (Required)
There's a message that adblock has been detected. The message disappears quickly
before taking screenshot. Then there is a black screen.

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/13797193/83944559-e8b84900-a821-11ea-9772-f29a9c187ba6.png)

#### Environment (Required)

- Operating System and Version:  Win7 64bit
- Browser and Version: Chrome v83
- Nano Adblocker Version: 1.0.0.148
- Nano Defender Version (Optional if you are not using it): 15.0.0.199

#### Your filter lists (Required)
Easylist
Adblock warning removal list
Nano defender integration
Nano filters

#### Your other extensions (Required if you have any)
UBlock Origin v1.27.10

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/83958464-561ea680-a82f-11ea-8451-142cb6f15a3b.png)

**Comment by sanGtH** [comment]
It's working with Nano adblocker but not with Ublock Origin. Just checked.
Please help bro..

**Comment by llacb47** [comment]
Try updating filters

**Comment by jspenguin2017** [comment]
Works fine with uBO for me as well: 
![image](https://user-images.githubusercontent.com/7283682/83972056-72f0c380-a89b-11ea-9529-76ab6dd8e1d7.png)

**Comment by sanGtH** [comment]
Thanks for the info bro. I purged and updated. Now working fine,
