### ISSUE TITLE
[Ads] dl-android.com

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#519]
Eg link: https://dl-android.com/p/index.php?id=es-file-explorer-file-manager

Popup ads as well as fake download buttons.
Platform: Firefox
OS: Android 10

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ca7bf22ac56f46d0427775ba085b1fcf21f4e350

**Comment by jspenguin2017** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ca7bf22ac56f46d0427775ba085b1fcf21f4e350
