### ISSUE TITLE
[Anti-Adblock] insidemarketing.it

### ISSUE THREAD

**Issue by Dr4gon97** [NanoAdblocker/NanoFilters#52]
### URLs where this issue occurs (Required)
https://www.insidemarketing.it/avviso/?R=https://www.insidemarketing.it/social-media-per-arte-uso-e-best-practice/

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/37912033/38107190-7faff608-3391-11e8-825e-3c7f1a71d2d2.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/37912033/38107219-95e58352-3391-11e8-92c8-e37ad56dbe88.png)

### Describe the issue (Optional if obvious)
Clicking "Ho disabilitato il blocco delle pubblicità" doesn't take me anywhere as I cannot circumvent the block

### Reproduction Steps (Optional if trivial)
Any news page I tried to open in the website besides https://www.insidemarketing.it/ and the dropdown menus triggers the anti-adblock script

#### Environment (Required)

- Operating System and Version: Win8
- Browser and Version:  65.0.3325.181 (64 bit)
- Nano Adblocker Version: 1.0.0.37
- Nano Defender Version (Optional if you are not using it): 13.49

#### Your filter lists (Required)

Nano Defender Integration ​​​​​2.718 usati su 2.757​​​​
Nano filters​​​​​ 62 usati su 65​​​​
Nano filters – Annoyance​​​​​ 12 usati su 12​​​​
Nano filters – Timer bypassing (sometimes works) ​​​​​0 usati su 0​​​​
Nano filters – Whitelist​​​​​ 0 usati su 0​​​​
uBlock filters​​​​​ 4.683 usati su 4.683​​​​
uBlock filters – Annoyances ​​​​​68 usati su 68​​​​
uBlock filters – Badware risks​​​​​ 9 usati su 9​​​​
uBlock filters – Experimental​​​​​ 6 usati su 6​​​​
uBlock filters – Privacy ​​​​​65 usati su 65​​​​
uBlock filters – Resource abuse​​​​​ 236 usati su 238​​​​
uBlock filters – Unbreak​​​​​ 347 usati su 347​​​​
Adblock Warning Removal List ​​​​​399 usati su 415​​​​
Adguard Base Filters​​​​​ 14.455 usati su 15.241​​​​
EasyList ​​​​​80.796 usati su 81.478​​​​
Adguard Spyware Filters​​​​​ 2.409 usati su 6.214​​​​
EasyPrivacy​​​​​ 13.295 usati su 14.577​​​​
Malvertising filter list by Disconnect​​​​​ 272 usati su 4.303​​​​
Malware Domain List​​​​​ 1.127 usati su 1.143​​​​
Malware domains​​​​​ 19.307 usati su 19.323​​​​
Malware filter list by Disconnect​​​​​ 159 usati su 1.567​​​​
Spam404 ​​​​​6.470 usati su 6.470​​​​
Dan Pollock’s hosts file ​​​​​9.793 usati su 13.366​​​​
hpHosts’ Ad and tracking servers​​​​​ 41.641 usati su 45.727​​​​
MVPS HOSTS ​​​​​12.207 usati su 12.714​​​​
NoCoin Filter List ​​​​​211 usati su 328​​​​
Peter Lowe’s Ad and tracking server list ​​​​​2.642 usati su 2.647​​​​
ITA: ABP X Files​​​​​ 4.303 usati su 4.636​​​​
ITA: EasyList Italy ​​​​​4.318 usati su 4.416​​​​
#### Your custom filters (Required if you have any)
@@||*$xmlhttprequest,domain=vvvvid.it
*.xyz

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
