### ISSUE TITLE
[Ads, Anti-adblock] megainteresting.com

### ISSUE THREAD

**Issue by Sopor** [NanoAdblocker/NanoFilters#520]
### URLs where this issue occurs (Required)
https://www.megainteresting.com

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/5789283/84964112-8574c380-b10b-11ea-8fc8-0e98d1d846b8.png)

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Firefox 77.0.1
- Nano Adblocker Version: uBlock Origin 1.27.10
- Nano Defender Version (Optional if you are not using it): 15.0.0.200

#### Your filter lists (Required)
- [x] uBlock filters
- [x] uBlock filters – Annoyances​​​​​
- [x] uBlock filters – Badware risks​
- [x] uBlock filters – Privacy​​​​​
- [x] uBlock filters – Resource abuse​​​​​
- [x] uBlock filters – Unbreak​​​​​
- [x] Adblock Warning Removal List
- [x] EasyPrivacy
- [x] Malware Domain List
- [x] Malware domains
- [x] Fanboy’s Annoyance List
- [x] Peter Lowe’s Ad and tracking server list
- [x] SWE: Frellwit's Swedish Filter​​​​​

**Comment by llacb47** [comment]
`megainteresting.com##+js(set, ads, true)`

Placeholders: 
```
megainteresting.com##.mega--desktop.gallery--mega
megainteresting.com###mega1
megainteresting.com###mega2
```
