### ISSUE TITLE
[Anti-adblock] rottentomatoes.com

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#523]
URLs where this issue occurs (Required)
https://www.rottentomatoes.com/tv/doom_patrol

### Screenshots (Required)
![Screenshot_2020-06-26 Doom Patrol](https://user-images.githubusercontent.com/43067841/85884868-226ae700-b805-11ea-809b-44a32f812037.png)

### Reproduction Steps (Optional if trivial)
Scroll down website

I cannot read your mind, write down what is in your head!
-->

#### Environment (Required)

Operating System and Version: windows 10 x64 2004
Browser and Version: firefox 77.0.1
Nano Adblocker Version: 1.0.0.149
Nano Defender Version (Optional if you are not using it): 15.0.200

#### Your filter lists (Required)
 default settings

**Comment by mapx-** [comment]
You should enable uBO annoyances list
