### ISSUE TITLE
[Anti-adblock] uploadship.com

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#525]
Eg linK: https://www.uploadship.com/68aa92f184daaca8

Doesn't forces to close Adblock, but if detects Adblock, it shows ads specially designed for such.
Might need to clear cookie to reproduce.

**Comment by jspenguin2017** [comment]
Can't reproduce. Screenshot?

**Comment by Cyberavater** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/32187927/86716471-08ba7280-c043-11ea-8337-b88502c2cafc.png)

Can you try clearing cookies? it only happens the first time.
https://www.uploadship.com/human_verification.html?e55318040a854ebdc4d4404d2521bee5=e55318020a154ebdc8d4404d2522bee5-68aa92f184daaca8-e55318020a142ebdc4d4404d2522bee5
