### ISSUE TITLE
[Breakage] youtube.com

### ISSUE THREAD

**Issue by UltraBlackLinux** [NanoAdblocker/NanoFilters#527]
### Screenshots (Required)
The title Explains it.

### Screenshot of console (Required, press `F12` to open the console)
I think this is unnecessary here

### Describe the issue (Optional if obvious)
Nano Defender Integration blocks youtube endscreen video Recommendations, 

### Reproduction Steps (Optional if trivial)
- Enable AdGuard Annoyances Filter list on UBO
- enjoy non existing video recommendations

### Anything else you believe to be useful (Optional)
I know this problem from the AdGuard Annoyances filterlist UBO

#### Environment (Required)

- Operating System and Version: 5.6.16-1-MANJARO
- Browser and Version: firefox nightly 80.0a1
- Nano Adblocker Version: nope
- Nano Defender Version (Optional if you are not using it): 15.0.0.201

#### Your filter lists (Required)
Ublock filterlists: 3/3
Ads: 3/3
Badware: 3/3
Annoyances: Fanboy’s Annoyance, UBO Annoyances
Different Uses: Dan Pollock’s hosts file, Peter Lowe’s Ad and tracking server list
Lanugages: EasyList Germany

#### Your custom filters (Required if you have any)
nope

#### Your other extensions (Required if you have any)
Nano defender + UBO

**Comment by jspenguin2017** [comment]
I don't maintain AdGuard Annoyance filter. Nano Defender's integration filter does not block YouTube end cards for me.

**Comment by jspenguin2017** [comment]
I don't maintain AdGuard Annoyance filter. 

Nano Defender's integration filter does not block YouTube end cards for me.
