### ISSUE TITLE
[Problem] demotywatory.pl

### ISSUE THREAD

**Issue by WowDude** [NanoAdblocker/NanoFilters#53]
https://github.com/MajkiIT/polish-ads-filter/issues/6725#issuecomment-377699210

**Comment by hawkeye116477** [comment]
@WowDude `https://github.com/jspenguin2017/uBlockProtector/commit/3cf73f965089e0da23206c190ccc50f1fc068e0b`

**Comment by WowDude** [comment]
@hawkeye116477 : I confirm too - fixed.
