### ISSUE TITLE
[Ads] bdiptv.stream

### ISSUE THREAD

**Issue by Joyer1234** [NanoAdblocker/NanoFilters#531]
URLs where this issue occurs (Required)
http://bdiptv.stream/live-tv/sony-ten-2.html
Use the domain as the title
-->

### Describe the issue (Optional if obvious)
Clicking on the video stream opens up POP-UP, Ads.
Can't use full screen without opening POP-UP, Ads.

**Environment (Required)**

    Operating System and Version: Windows 10 Pro 2004
    Browser and Version: Firefox 78
    Nano Adblocker Version: 1.0.0.150
    Nano Defender Version (Optional if you are not using it): 15.0.0.201

Your filter lists (Required)
Default
List filters you have enabled or disabled from the default settings.
default setting.

**Comment by jspenguin2017** [comment]
@okiehsch 
Without Bulgarian regional filters: Popups
With Bulgarian regional filters: Video does not load

**Comment by okiehsch** [comment]
Video works on my end with bulg filter list.
![image](https://user-images.githubusercontent.com/16838044/87613311-425b3f80-c70d-11ea-9ac3-f05db0278d61.png)

**Comment by jspenguin2017** [comment]
OK, I think it has something to do with Cloudflare, it works fine after completely clearing site data. 

The full screen button still triggers a popup though. Also is the website in Bulgarian? Or I'm using a wrong regional filter...

**Comment by okiehsch** [comment]
I can't reproduce a popup.
The websites language is Bangladeshi.

**Comment by jspenguin2017** [comment]
Is there a regional filter for that? Without any regional filters, I get a popup when clicking the full screen button for the first time, although the popup is closed after about 2 seconds. 
![image](https://user-images.githubusercontent.com/7283682/87614409-318ad980-c6cd-11ea-9a13-194ae32820e0.png)

**Comment by okiehsch** [comment]
I still can't reproduce, the requests on your end look familiar.
Does `live.bdtv.xyz##+js(acis, Math, zfgloaded)` work for you?

**Comment by jspenguin2017** [comment]
Yep, that works.

**Comment by okiehsch** [comment]
The language is Bengali I think. There is no dedicated filter list for that language that I am aware of.

**Comment by okiehsch** [comment]
Fixed.
