### ISSUE TITLE
[Ads] mhktricks.org

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#533]
### URL where this issue occurs 

https://mhktricks.org/

### Screenshots (Required)

![Annotation 2020-07-19 221823](https://user-images.githubusercontent.com/34688076/87885418-ccf1b680-ca0d-11ea-88c7-9b2550946a09.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![Annotation 2020-07-19 222620](https://user-images.githubusercontent.com/34688076/87885579-00811080-ca0f-11ea-917a-ba6bb3d18534.jpg)

#### Environment (Required)

- Operating System and Version: 
**Windows 10**
- Browser and Version: 
**Chrome latest version**
- Nano Adblocker Version: 
**Latest**
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)

 defaults

**Comment by jspenguin2017** [comment]
Can't reproduce anti-adblock but looks like there's a banner ad.
