### ISSUE TITLE
[Anti-adblock] courses4u.info

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#534]
URL Where issue occured : **https://courses4u.info/**

### Screenshots (Required)
![screenshot-courses4u info-2020 07 23-02_39_46](https://user-images.githubusercontent.com/34688076/88245107-d0937080-cc8d-11ea-9fd7-6026dd5c8f6f.jpg)

### Screenshot of console (Required, press `F12` to open the console)

![Annotation 2020-07-23 024220](https://user-images.githubusercontent.com/34688076/88245188-2831dc00-cc8e-11ea-9ae4-63352050ec00.jpg)

#### Environment (Required)

- Operating System and Version  :  **Windows 10**
- Browser and Version  :  **Chrome latest version**
- Nano Adblocker Version  :   **Latest version**

**Comment by jspenguin2017** [comment]
@okiehsch Hard anti-adblock. 
![image](https://user-images.githubusercontent.com/7283682/88248423-6911fc80-cc5e-11ea-8a96-c8d1bd0bbfe9.png)

**Comment by jspenguin2017** [comment]
Seems to also have ads placeholders, will split off an issue for that later.

**Comment by okiehsch** [comment]
I get the same huge placeholders with uBO disabled.

**Comment by jspenguin2017** [comment]
Huh, weird... I guess that's not ads placeholders then.

**Comment by okiehsch** [comment]
Fixed.
