### ISSUE TITLE
[Anti-adblock] p4fcourses.com

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#535]
URL where this issue occurs : **https://p4fcourses.com/**

### Screenshots (Required)

![screenshot-p4fcourses com-2020 07 23-02_44_12](https://user-images.githubusercontent.com/34688076/88245271-88c11900-cc8e-11ea-8ca3-8162986afc42.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![Annotation 2020-07-23 024731](https://user-images.githubusercontent.com/34688076/88245382-e9505600-cc8e-11ea-95b8-d71d0d5966f4.jpg)

#### Environment (Required)

- Operating System and Version  :  **Windows 10**
- Browser and Version  :  **Chrome latest version**
- Nano Adblocker Version  :   **Latest version**

**Comment by jspenguin2017** [comment]
@okiehsch `anOptions`. 
![image](https://user-images.githubusercontent.com/7283682/88248440-75965500-cc5e-11ea-829b-17606e20fc22.png)

**Comment by jspenguin2017** [comment]
Nano Defender generic solution works.

**Comment by okiehsch** [comment]
Fixed.
