### ISSUE TITLE
[Anti-adblock] toppng.com

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#536]
URL where this issue occurs : **https://toppng.com/**

### Screenshots (Required)
![screenshot-toppng com-2020 07 23-02_50_03](https://user-images.githubusercontent.com/34688076/88245519-667bcb00-cc8f-11ea-91ed-ef95ee70bf61.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![Annotation 2020-07-23 025155](https://user-images.githubusercontent.com/34688076/88245564-8612f380-cc8f-11ea-8da3-26be90d2fd07.jpg)

#### Environment (Required)

- Operating System and Version  :  **Windows 10**
- Browser and Version  :  **Chrome latest version**
- Nano Adblocker Version  :   **Latest version**

#### Your filter lists (Required)   : **Defaults**

**Comment by jspenguin2017** [comment]
@okiehsch `Antiblock.org v3`. 
![image](https://user-images.githubusercontent.com/7283682/88248552-d0c84780-cc5e-11ea-9f69-7605b878eec8.png)

**Comment by jspenguin2017** [comment]
Nano Defender generic solution works.

**Comment by okiehsch** [comment]
Fixed.
