### ISSUE TITLE
[Anti-adblock] friendproject.net

### ISSUE THREAD

**Issue by LegendaryOverlord** [NanoAdblocker/NanoFilters#537]
### URLs where this issue occurs (Required)
https://www.friendproject.net/
https://www.friendproject.net/notice.php

### Screenshots (Required)
https://imgur.com/KXgIr5r

### Screenshot of console (Required, press `F12` to open the console)
https://imgur.com/VScXb3I

### Describe the issue (Optional if obvious)
"friendproject.net/notice.php" seems to pop up whenever checking "Messages" or "New stream comments" from your main page.

#### Environment (Required)

- Operating System and Version: Windows 10 
- Browser and Version: Chromium 84.0.4147.89
- Nano Adblocker Version: uBlock Origin 1.27.10
- Nano Defender Version (Optional if you are not using it): 15.0.0.201

#### Your filter lists (Required)
<!-- uBlock filters 22,564 used out of 23,698

uBlock filters – Badware risks 862 used out of 875

uBlock filters – Privacy 185 used out of 207

uBlock filters – Resource abuse 114 used out of 117

uBlock filters – Unbreak 1,435 used out of 1,473
Ads (2/3)

AdGuard Base 43,319 used out of 43,907

EasyList 82,722 used out of 83,933
Privacy (3/3)

AdGuard Tracking Protection 8,934 used out of 9,038

EasyPrivacy 13,643 used out of 17,990

Fanboy’s Enhanced Tracking List 3,266 used out of 3,512
Malware domains (2/2)

Online Malicious URL Blocklist 5,985 used out of 5,985

Spam404 7,133 used out of 7,137
Annoyances (5/7)

AdGuard Annoyances 29,818 used out of 29,948

EasyList Cookie 3 used out of 17,364

Fanboy’s Annoyance 52,772 used out of 55,196

Fanboy’s Social 0 used out of 23,917

uBlock filters – Annoyances 3,272 used out of 3,473
Multipurpose (2/3)

MVPS HOSTS 9,283 used out of 9,953

Peter Lowe’s Ad and tracking server list 1,396 used out of 3,492
Regions, languages (0/34)
Custom (7/12)

https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt 2,736 used out of 2,736

https://hosts-file.net/.%5Cad_servers.txt 0 used out of 0

Adblock Warning Removal List 741 used out of 758

Nano Defender Integration 2,626 used out of 2,627

Nano Filters 403 used out of 403

Nano Filters - Whitelist 0 used out of 0

**Comment by jspenguin2017** [comment]
Requires account?

**Comment by LegendaryOverlord** [comment]
Yes, I'm pretty sure you need an account. https://www.friendproject.net/statusnotifications.php and https://www.friendproject.net/view_messages.php?folder=inbox seem to be two of the urls that will cause the anti-adblock to appear. If you go to either without an account it will just redirect to the main page.

**Comment by jspenguin2017** [comment]
In that case, I would need a test account. To provide one, you can either: 
Open a confidential issue here: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/-/issues 
Or, submit a private message here with reference `537`: https://legacy.hugoxu.com/PrivateMessage/

**Comment by jspenguin2017** [comment]
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/-/issues/57

**Comment by jspenguin2017** [comment]
@okiehsch @mapx- `friendproject.net##+js(set, adblock, false)`

**Comment by okiehsch** [comment]
Fixed.
