### ISSUE TITLE
[Anti-adblock] yourdictionary.com

### ISSUE THREAD

**Issue by Sopor** [NanoAdblocker/NanoFilters#538]
### URLs where this issue occurs (Required)
https://www.yourdictionary.com

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/5789283/88415067-27a85b00-cdde-11ea-951e-ff8c0ffa9ffa.png)

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Firefox 78.0.2
- Nano Adblocker Version: uBlock Origin 1.28.2
- Nano Defender Version (Optional if you are not using it): 15.0.0.201

#### Your filter lists (Required)
- [x] uBlock filters
- [x] uBlock filters – Annoyances​​​​​
- [x] uBlock filters – Badware risks​
- [x] uBlock filters – Privacy​​​​​
- [x] uBlock filters – Resource abuse​​​​​
- [x] uBlock filters – Unbreak​​​​​
- [x] Adblock Warning Removal List
- [x] EasyPrivacy
- [x] Malware Domain List
- [x] Malware domains
- [x] Fanboy’s Annoyance List
- [x] Peter Lowe’s Ad and tracking server list
- [x] SWE: Frellwit's Swedish Filter​​​​​

**Comment by mapx-** [comment]
fixed
