### ISSUE TITLE
[Anti-adblock] adshrink.it

### ISSUE THREAD

**Issue by gabri25ele** [NanoAdblocker/NanoFilters#539]
URLs where this issue occurs (Required)
https://adshrink.it/NDU5NTI=/aHR0cDovL3d3dy53ZXNhZmUuaW5mby8vP2M9OWUxYzU5

Screenshots (Required)
![Immagine](https://user-images.githubusercontent.com/33927879/88659521-7c492000-d0d5-11ea-9352-2fa2b065cff5.png)

Screenshot of console (Required, press F12 to open the console)
![Immagine2](https://user-images.githubusercontent.com/33927879/88659541-82d79780-d0d5-11ea-93e8-ecffc5c519b0.png)

Environment (Required)
Operating System and Version: Windows 10 Pro
Browser and Version: Firefox 79.0
ublock origin: 1.28.4
Nano Defender Version (Optional if you are not using it): 15.0.0.201

Your filter lists (Required)
https://user-images.githubusercontent.com/33927879/84669666-67e60500-af25-11ea-986d-be6a18be40cb.png

Your other extensions (Required if you have any)
Bypass Paywalls
ClearURLs
Cookiebro
Copy All Tab Urls
Gesturify
I don't care about cookie
Open With
Reddit Enhancement
Simple Translate
Tab session manager
Universal Bypass
Violent Monkey

**Comment by jspenguin2017** [comment]
Can't reproduce. Final destination is `https://www.wesafe.info//?c=9e1c59`.

**Comment by gabri25ele** [comment]
> 
> 
> Can't reproduce. Final destination is `https://www.wesafe.info//?c=9e1c59`.

how is possible?
yes, this is the final destination, ma first of that, there is https://adshrink.it/NDU5NTI=/aHR0cDovL3d3dy53ZXNhZmUuaW5mby8vP2M9OWUxYzU5
(also in edge I see that)

**Comment by mapx-** [comment]
You are using a lot of other addons which could impact the site. 
Try using only uBO (only default settings !) and if works add one by one the other addons to find the "bad" one

**Comment by gabri25ele** [comment]
ClearURLs, the guilty!

**Comment by mapx-** [comment]
well, add an exception for `adshrink.it` (if doable) in `ClearURLs`

**Comment by gabri25ele** [comment]
> 
> 
> well, add an exception for `adshrink.it` (if doable) in `ClearURLs`

is possible? where?

**Comment by mapx-** [comment]
you should read / ask here:
https://gitlab.com/KevinRoebert/ClearUrls/-/wikis/Technical-details/Rules-file

**Comment by mapx-** [comment]
I guess the creator is @KevinRoebert

**Comment by jspenguin2017** [comment]
I can confirm that the website works fine with only NA + ND on default settings.
