### ISSUE TITLE
[Anti-adblock] longecity.org

### ISSUE THREAD

**Issue by MOFTAD** [NanoAdblocker/NanoFilters#540]
### URLs where this issue occurs (Required)

- https://www.longecity.org/forum/page/index.html
- https://www.longecity.org/forum/
- https://www.longecity.org/forum/page/index2.html/_/feature/about

These URLs are some examples, but the issue is reproducible on the majority of the site's pages.

### Screenshots (Required)

<img width="948" alt="ab" src="https://user-images.githubusercontent.com/15206416/88930947-31044e00-d24a-11ea-80b2-c070431a85ad.png">

### Screenshot of console (Required, press `F12` to open the console)

<img width="960" alt="firefox_2020-07-30_09-55-08" src="https://user-images.githubusercontent.com/15206416/88931466-de776180-d24a-11ea-9957-540d45a6f83a.png">

### Anything else you believe to be useful (Optional)

The warning is not triggered by navigation to subsequent pages; it only appears upon loading the initial page.

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Firefox 80.0b1
- Nano Adblocker Version: N/A (uBlock Origin 1.28.4)
- Nano Defender Version (Optional if you are not using it): 15.0.0.201

#### Your filter lists (Required)

<img width="320" alt="firefox_2020-07-30_10-03-08" src="https://user-images.githubusercontent.com/15206416/88932320-ea175800-d24b-11ea-894d-7144fe71f029.png">

#### Your custom filters (Required if you have any)

<img width="306" alt="firefox_2020-07-30_10-01-44" src="https://user-images.githubusercontent.com/15206416/88932167-bb997d00-d24b-11ea-9938-53a890c0c94f.png">

**Comment by mapx-** [comment]
fixed as annoyance
