### ISSUE TITLE
[Ads] forum.xda-developers.com

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#542]
Eg link: https://forum.xda-developers.com/showthread.php?t=1523691

![Screenshot (12)](https://user-images.githubusercontent.com/32187927/89140281-ff99c400-d562-11ea-9fbe-ed7f21d94998.png)

**Comment by Cyberavater** [comment]
Shows ad videos from youtube.

**Comment by jspenguin2017** [comment]
Can't reproduce. Closing as invalid since you did not fill the template.
