### ISSUE TITLE
[Breakage] cyclingnews.com

### ISSUE THREAD

**Issue by whdmike** [NanoAdblocker/NanoFilters#543]
### URLs where this issue occurs (Required)

https://www.cyclingnews.com/

Since some days coments section that is from https://disqus.com/ is not visible anymore - what do I need to enable to get it back. I have only basic settings. If you go to any article, at the end should be comment section, but now is not visible anymore, Using Brave browser

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by mapx-** [comment]
@ryanbr
