### ISSUE TITLE
[Anti-adblock] morningstar.com

### ISSUE THREAD

**Issue by brru8999** [NanoAdblocker/NanoFilters#545]
www.morningstar.com

### Screenshots (Required)

![image](https://user-images.githubusercontent.com/38956371/89918803-1cb43f80-dbc0-11ea-978e-e3112d79e67b.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/38956371/89918949-4a998400-dbc0-11ea-9a91-24d59a4384f4.png)

### Describe the issue (Optional if obvious)
Morningstar.com redirecting to premium splash page upon detection of Nano.

### Reproduction Steps (Optional if trivial)
Basically, just visit the site with Nano enabled.

### Anything else you believe to be useful (Optional)

No account required

#### Environment (Required)

- Operating System and Version: Windows 10
- Browser and Version: Chrome - Version 84.0.4147.105 (Official Build) (64-bit)
- Nano Adblocker Version: Nano Adblocker v1.0.0.152
- Nano Defender Version (Optional if you are not using it): 15.0.0.201

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/38956371/89919324-bb40a080-dbc0-11ea-9a2e-cc3ae0430b1f.png)

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/90319833-455a7300-def9-11ea-8c6e-991420b7e97a.png)
