### ISSUE TITLE
komorkomania.pl

### ISSUE THREAD

**Issue by krystian3w** [NanoAdblocker/NanoFilters#55]
https://github.com/MajkiIT/polish-ads-filter/issues/6969

`https://komorkomania.pl/35812,jaki-byl-twoj-pierwszy-telefon` - demo link

---

List `Nano Defender Integration ` activate social buttons:

![obraz](https://user-images.githubusercontent.com/35370833/38460772-fe8311f0-3ac0-11e8-9d70-1b3ec8f98865.png) |
--- |

![obraz](https://user-images.githubusercontent.com/35370833/38460775-193e8e84-3ac1-11e8-9494-6dd08ae1909f.png) |
--- |

Blocked by **`Fanboy's Social Blocking List`**.

**Comment by jspenguin2017** [comment]
How is that a problem?

**Comment by jspenguin2017** [comment]
Can't reproduce. The button shows even if the integration filter is off.

**Comment by krystian3w** [comment]
OK, now aslo I cannot reproduce (It is strange that earlier switching the list `Nano` unlocked and blocked the button).

Maybe I hadold list and uBlock don't update list.
