### ISSUE TITLE
[Anti-adblock] bitnova.info

### ISSUE THREAD

**Issue by sanGtH** [NanoAdblocker/NanoFilters#550]
### URLs where this issue occurs (Required)
https://bitnova.info/torrenty/gry_komputerowe/18-1

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/13797193/91274936-17005180-e79d-11ea-9d52-31093bb5d706.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/13797193/91275040-39926a80-e79d-11ea-800e-241cd62f0d35.png)

### Reproduction Steps (Optional if trivial)
Just go to any section of the site and you'll see this message.

#### Environment (Required)

- Operating System and Version: **Win 7 64**
- Browser and Version: **Chrome 84.x FF 79**
- Nano Adblocker Version: **1.0.0.152**
- Nano Defender Version (Optional if you are not using it): **15.0.0.205**

#### Your filter lists (Required)
**Easylist
Adblock Warning Removal List
Nano Defender Integration
Nano Filters**

#### Your other extensions (Required if you have any)
**UBlock Origin v 1.29.2**

**Comment by jspenguin2017** [comment]
Works fine with Polish regional filters enabled.
