### ISSUE TITLE
[Anti-adblock] mrkoll.se

### ISSUE THREAD

**Issue by Sopor** [NanoAdblocker/NanoFilters#553]
### URLs where this issue occurs (Required)
https://mrkoll.se

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/5789283/92277823-1e89ce00-eef4-11ea-8a87-eb6427791d5f.png)

### Environment (Required)
- Operating System and Version: Windows 10
- Browser and Version: Firefox 80.0.1
- Nano Adblocker Version: uBlock origin 1.29.2
- Nano Defender Version (Optional if you are not using it): 15.0.0.205

### Your filter lists (Required)
- [x] uBlock filters
- [x] uBlock filters – Annoyances​​​​​
- [x] uBlock filters – Badware risks​
- [x] uBlock filters – Privacy​​​​​
- [x] uBlock filters – Resource abuse​​​​​
- [x] uBlock filters – Unbreak​​​​​
- [x] Adblock Warning Removal List
- [x] EasyPrivacy
- [x] Malware Domain List
- [x] Malware domains
- [x] Fanboy’s Annoyance List
- [x] Peter Lowe’s Ad and tracking server list
- [x] SWE: Frellwit's Swedish Filter​​​​​

**Comment by mapx-** [comment]
@lassekongo83
