### ISSUE TITLE
[Annoyance] youtube.com

### ISSUE THREAD

**Issue by mara004** [NanoAdblocker/NanoFilters#554]
An annoying po-up appears often when attempting to watch a video, despite uBlock's, Fanboy's an Adguard's annoyance filter lists enabled. An example using the German locale is attached.
![Screenshot (33)](https://user-images.githubusercontent.com/65915611/92323839-205ea900-f03c-11ea-9009-2461372fa92e.png)

**Comment by mara004** [comment]
Product version 1.0.0.151
I verified that all filter lists are up-to-date

**Comment by jspenguin2017** [comment]
Out of scope. Report to the maintainers of the annoyance filters that you are using.

**Comment by mara004** [comment]
Okay, sorry for reporting this at the wrong place.

**Comment by mara004** [comment]
Okay, sorry for reporting this at the wrong place.

**Comment by mara004** [comment]
Okay, sorry for reporting this at the wrong place.

**Comment by mara004** [comment]
These two filters fixed the annoyance for me:
||www.gstatic.com/youtube/img/promos/growth/dmod_si_horizontal_ver1_240x400.png$image
www.youtube.com###dialog
