### ISSUE TITLE
[Anti-adblock] phim.vkool.net

### ISSUE THREAD

**Issue by sadtango289** [NanoAdblocker/NanoFilters#555]
### URLs where this issue occurs (Required)
 http://phim.vkool.net/xemphim/ngoi-sao-khoai-tay-8814356.html
Please help me fix

### Screenshots (Required)
When Nano on . No play video 
 ![Alt Text](https://i.imgur.com/J7ppt7R.png)
When Nano off . Video plays well 
 ![Alt Text](https://i.imgur.com/Fwwk0Bk.png)
### Screenshot of console (Required, press `F12` to open the console)
 ![Alt Text](https://i.imgur.com/qRamoVJ.png)

#### Environment (Required)

- Operating System and Version:  Win 7  SP1 Untimate 64 bit
- Browser and Version: CocCoc 89.0.124 32 bit ( Vietnam ) 
- Nano Adblocker Version: 1.0.0.153
- Nano Defender Version (Optional if you are not using it): 15.0.0.205

#### Your filter lists (Required)
Need add translate option 

![Alt Text](https://i.imgur.com/1d6Jq93.png)

List filters you have enabled or disabled from the default settings.
 none

#### Your custom filters (Required if you have any)

none
#### Your other extensions (Required if you have any)

![Alt Text](https://i.imgur.com/icfxUeF.png)

**Comment by jspenguin2017** [comment]
I'm getting Cloudflare error 524. Is the website down right now?

**Comment by sadtango289** [comment]
> I'm getting Cloudflare error 524. Is the website down right now?

no . it's still working .

**Comment by jspenguin2017** [comment]
Okay, the website is up again, but I can't reproduce this issue. 
![image](https://user-images.githubusercontent.com/7283682/92615351-41144200-f27a-11ea-8133-772c3e6517fc.png)

**Comment by sadtango289** [comment]
worked. close .
