### ISSUE TITLE
[Anti-adblock] cbssports.com

### ISSUE THREAD

**Issue by beavislol** [NanoAdblocker/NanoFilters#556]
#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/issues/7866

**Comment by jspenguin2017** [comment]
Can't reproduce. Closing as invalid since you did not fill the template.

**Comment by krystian3w** [comment]
https://github.com/NanoAdblocker/NanoFilters/issues/556
