### ISSUE TITLE
NSFW! [Anti-adblock] av01.tv

### ISSUE THREAD

**Issue by sadtango289** [NanoAdblocker/NanoFilters#557]
### URLs where this issue occurs (Required)
 https://www.av01.tv/video/30940/vagu-221-%E6%9C%80%E6%84%9B%E3%81%AE%E5%A4%AB%E3%81%AE%E3%81%9F%E3%82%81-%E3%83%9E%E3%83%8D%E3%82%AD%E3%83%B3%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%A6%E5%87%BA%E8%8D%B7%E3%81%95%E3%82%8C%E3%81%9F%E5%A6%BB-%E9%BA%97%E3%81%97%E3%81%AE%E3%83%9E%E3%83%8D%E3%82%AD%E3%83%B3%E5%A4%AB%E4%BA%BA%E5%A4%96%E4%BC%9D-%E7%AF%A0%E7%94%B0%E3%82%86%E3%81%86

### Screenshots (Required)
When Nano on , video is blocked
<details>

 ![Alt Text](https://www.upsieutoc.com/images/2020/09/10/Capture.png)
</details>
Nano off , video works 
<details>

![Alt Text](https://www.upsieutoc.com/images/2020/09/10/Capture2.png)
</details>

### Screenshot of console (Required, press `F12` to open the console)
<details>

![Alt Text](https://www.upsieutoc.com/images/2020/09/10/Capture1.png)
</details>

#### Environment (Required)

- Operating System and Version:  Win 7  SP1 Untimate 64 bit
- Browser and Version: CocCoc 89.0.124 32 bit ( Vietnam ) 
- Nano Adblocker Version: 1.0.0.153
- Nano Defender Version (Optional if you are not using it): 15.0.0.205

#### Your filter lists (Required)
 Defalt settings

![Alt Text](https://i.imgur.com/1d6Jq93.png)

#### Your custom filters (Required if you have any)
None

#### Your other extensions (Required if you have any)
![Alt Text](https://i.imgur.com/icfxUeF.png)

**Comment by mapx-** [comment]
fixed by `CHN: EasyList China (中文) `
