### ISSUE TITLE
[Ads] watchcartoononline.com

### ISSUE THREAD

**Issue by poweruser667** [NanoAdblocker/NanoFilters#56]
![console2](https://user-images.githubusercontent.com/38184145/38468619-fb6a7ec6-3b16-11e8-8bd0-23978ca4b30b.jpg)
![ads1](https://user-images.githubusercontent.com/38184145/38468620-fb75ae04-3b16-11e8-9b3b-d6749113d852.jpg)
![ads2](https://user-images.githubusercontent.com/38184145/38468621-fb820712-3b16-11e8-83bc-bd2249fab6ad.jpg)
![console1](https://user-images.githubusercontent.com/38184145/38468622-fb8e779a-3b16-11e8-8780-80fd98041a4b.jpg)

**Comment by jspenguin2017** [comment]
@okiehsch Test link: https://www.watchcartoononline.com/

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/cd5d3ac8b67baae1c5031a1af2f2a570c238d878
