### ISSUE TITLE
[Anti-adblock] linecad.com

### ISSUE THREAD

**Issue by coderLyon** [NanoAdblocker/NanoFilters#568]
### URLs where this issue occurs (Required)

https://www.linecad.com/

### Screenshots (Required)
![20200930150620](https://cdn.jsdelivr.net/gh/coderLyon/ImageHosting/markdown-image/20200930150620.png)

### Screenshot of console (Required, press `F12` to open the console)
![20200930151026](https://cdn.jsdelivr.net/gh/coderLyon/ImageHosting/markdown-image/20200930151026.png)

#### Environment (Required)

- Operating System and Version: Windows 10 1909
- Browser and Version: chrome 83.0.4103.116
- Nano Adblocker Version: 1.0.0.153
- Nano Defender Version (Optional if you are not using it): 15.0.0.205

#### Your filter lists (Required)

![20200930151751](https://cdn.jsdelivr.net/gh/coderLyon/ImageHosting/markdown-image/20200930151751.png)

#### Your other extensions (Required if you have any)
![20200930152055](https://cdn.jsdelivr.net/gh/coderLyon/ImageHosting/markdown-image/20200930152055.png)

**Comment by coderLyon** [comment]
Please, the problem still exists, nano defender is not work.

**Comment by mapx-** [comment]
Did you update your lists ?
