### ISSUE TITLE
[Ads] m.timesofinfia.com

### ISSUE THREAD

**Issue by ghajini** [NanoAdblocker/NanoFilters#57]
@jspenguin2017 
The reason I posted here becoz I see unresolved issues for this in uassets

`https://github.com/uBlockOrigin/uAssets/issues/247`

### URLs where this issue occurs 

https://m.timesofindia.com

https://m.timesofindia.com/sports/cricket/ipl/top-stories/ipl-2018-kolkata-knight-riders-beat-royal-challengers-bangalore-by-four-wickets/articleshow/63672323.cms

### Screenshots (Required) &issue descriptions

I see ads by colombia ad network on toi homepage
1)  as I click on ad on homepage

http://prntscr.com/j2ltmx
      It's logger output
        http://prntscr.com/j2lu6x
     I see in logger 1stly `taboola.com` is whitelisted (found in ublock unbreak list) hence it pass to adservers `adcanopus`

Why taboola is whitelisted globally in ublock origin as it redirects to ad networks
     Depending on which ad it display it passes to revolving adservers
          http://prntscr.com/j2lyfm

2) on individual stories
    I see 'recommended by coloumbia' or 'from around the web' ads

### Describe the issue -
Ads by colombia everywhere on page

### Reproduction Steps (Optional if trivial)
Just go to any invidual stories and see ads

#### Environment (Required)

- Operating System and Version: Android 7.1.2
- Browser and Version: Firefox for Android 59.0.2
- Ublock origin 1.15.24

#### Your filter lists (Required)
default settings+adguard mobile filters

**Comment by ghajini** [comment]
How can I use it on firefox Android .
Can you provide nano defender for Firefox Android(as I know defender is not available for firefox)

**Comment by jspenguin2017** [comment]
You'll need Nano Defender. @krystian3w 
cc @okiehsch

**Comment by jspenguin2017** [comment]
Hold on, it doesn't quite work... The mobile site is structured differently.

**Comment by ghajini** [comment]
Correct ,structured differently.... sometimes filters don't work for m.timesofindia.com if you create one for timesofindia.com

**Comment by jspenguin2017** [comment]
"From around the web" should be blocked too, right?

**Comment by ghajini** [comment]
Yes ....it would be nice if you self sign nano defender version for Firefox & release/autoupdate (like gorhill doing)

**Comment by jspenguin2017** [comment]
Seems that `m.timesofindia.com##.adsinview` would work. 
I also have a backup plan. 
I'll wait for @okiehsch

**Comment by jspenguin2017** [comment]
And the desktop site is still not fixed in uBO. The script rule in Nano Defender seems to still work though.

**Comment by ghajini** [comment]
Still ad on homepage after `m.timesofindia.com##.adsinview`

**Comment by jspenguin2017** [comment]
Eh, I guess not getting away with script rule then.

**Comment by jspenguin2017** [comment]
Alright, I'll call this fixed, unless @okiehsch wants to add the partial fix.

**Comment by ghajini** [comment]
IAM on ubo only,Firefox Android. NOT using nano defender now

**Comment by okiehsch** [comment]
I have reopended  `uBlockOrigin/uAssets/issues/247`, and linked to this issue, I am short of time, so no fix from me for now.

**Comment by ghajini** [comment]
Ok confine to using ubo only, anything other is waste

**Comment by ghajini** [comment]
That's partial fix

**Comment by okiehsch** [comment]
Well, that's why my commit is called "partially address NanoAdblocker/NanoFilters#57 as suggested".

**Comment by jspenguin2017** [comment]
@okiehsch Cool, since you are here... 
Missed ads on `https://btcmanager.com/the-fiery-asic-debate-engulfs-the-bitcoin-and-monero-communities/`
Rule: 
```
btcmanager.com##.wpbanners-banner
btcmanager.com##.advert
```

**Comment by okiehsch** [comment]
Well, that should really be part of `EasyList` in my opinion.
I try to be consistent and only add filters for issues that require extended filter syntax, you may disagree and can open such an issue at `uAssets`.

**Comment by okiehsch** [comment]
I also will add filters for all anti-adblock issues, because `EasyList` does not include such filters for
"legal" reasons.
