### ISSUE TITLE
[Anti-adblock] anime-loads.org

### ISSUE THREAD

**Issue by rix1337** [NanoAdblocker/NanoFilters#6]
### Describe the issue

The click-and-load feature (commonly used with jdownloader) is only available on this site when you 

a) Log in
b) Do not use an ad-blocker

### URLs where this issue occurs

http://www.anime-loads.org/media/yuuki-yuuna-wa-yuusha-de-aru-yuusha-no-shou
and anything else with click-and-load content

### Screenshots
![click-and-load-warning](https://user-images.githubusercontent.com/9930448/34382602-54652456-eb10-11e7-9951-45776e73d99c.JPG)

### Screenshot of console
![console-f12](https://user-images.githubusercontent.com/9930448/34382636-9890d4a4-eb10-11e7-8d97-85da13cac8c5.JPG)

### Reproduction Steps
1. Look for any show/movie on anime-loads.org using Nano Adblocker/Defender (ads should be blocked as expected).
2. Log in/create an account and log in.
3. Click on "Download"
4. Choose any release
5. Click on "Click'n'Load alle Folgen!" (Click-and-Load all Episodes)
6. See result from above, telling you to disable adblock

### Environment

- Operating System and Version: Windows 10 1709 x64
- Browser and Version: Firefox 57.0.2
- Nano Adblocker Version: 1.0.0.21

#### Your filter lists (Required)
Nano Adblock default (which includes the Nano defender lists incl. timer list)

#### Your custom filters
None

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Do you have a test acoount?

**Comment by jspenguin2017** [comment]
@okiehsch Nope... 

@rix1337 Can you provide a test account? Open a confidential issue here: https://gitlab.com/xuhaiyang1234/uBlockProtectorSecretIssues/issues

Or send me a private message though https://jspenguin.com/PrivateMessage/ with reference `Issue NanoFilters 6`.

**Comment by rix1337** [comment]
Sent via option 2.

Ty very much

**Comment by jspenguin2017** [comment]
Doesn't quite need an account to test actually, the message is different if you have adblocker off (or solution activated) but not logged in.

**Comment by rix1337** [comment]
Thanks again, that was quick :D
Confirmed working on Firefox desktop and mobile.

Figured it wasn't elaborate, but that fix looks very simple.
