### ISSUE TITLE
tvn24.pl

### ISSUE THREAD

**Issue by FadeMind** [NanoAdblocker/NanoFilters#62]
https://fakty.tvn24.pl/
https://tvn24.pl
cannot load video stream when Nano Defender is active. 
![screenshot_20180505_150252](https://user-images.githubusercontent.com/9846948/39663536-6697e814-5075-11e8-83e6-11b9f5e7a2c3.png)

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/39664066-e6c59e2c-503a-11e8-9a84-af1621f114b5.png)

**Comment by FadeMind** [comment]
I removed Nano Adblocker and Nano Defender. Next I added them again. 
Additional: added `https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt` suplement for polish and seems works. Regards.
