### ISSUE TITLE
[Anti-adblock] sportsnet.ca

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoFilters#63]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Nano Defender 14.9

`https://www.sportsnet.ca/basketball/nba/twitter-reaction-nba-fraternity-amazed-lebron-game-winner/`
Website displays an "Adblock detected" message.

**Comment by jspenguin2017** [comment]
FYI @okiehsch 
Annoyance

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
Yea, that seems cleaner. 

All I need now is to make a bot to handle reports for me.
