### ISSUE TITLE
[Anti-adblock] ekb.dk.ru

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoFilters#65]
Reference: Quick Issue Reporter

Message:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Nano Defender 14.10

[anti-adblock] `http://ekb.dk.ru/news/8-chasovoy-rabochiy-den-stoilo-otmenit-50-let-nazad-sem-prichin-ego-bessmyslennosti-237103596`
https://imgur.com/a/cmBXIKG

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.

**Comment by okiehsch** [comment]
Added, thx.
