### ISSUE TITLE
businessinsider.com, businessinsider.in

### ISSUE THREAD

**Issue by gparyani** [NanoAdblocker/NanoFilters#68]
### URLs where this issue occurs (Required)

`www.businessinsider.com/programmers-debate-requirements-to-behave-respectfully-ccoc-2018-5`

### Screenshots (Required)
[![It looks like you're using an ad blocker][1]][1]

### Screenshot of console (Required, press `F12` to open the console)
[![enter image description here][2]][2]
[![enter image description here][3]][3]
[![enter image description here][4]][4]

### Describe the issue (Optional if obvious)
Anti-adblock message on page.

### Reproduction Steps (Optional if trivial)

Load the page.

#### Environment (Required)

- Operating System and Version: Windows 10 Fall Creators Update
- Browser and Version: Microsoft Edge 41.16299.371.0
- Nano Adblocker Version: 0.0.46.0
- Nano Defender Version (Optional if you are not using it): 14.11

#### Your filter lists (Required)

- My filters
- Nano Defender Integration
- Nano filters
- Nano filters - Timer bypassing
- Nano filters - Whitelist
- uBlock filters
- uBlock filters - Badware risks
- uBlock filters - Privacy
- uBlock filters - Resource abuse
- uBlock filters - Unbreak
- Adblock Warning Removal List
- EasyList
- EasyPrivacy
- Malware Domain List
- Malware domains
- Peter Lowe's Ad and tracking server list

#### Your custom filters (Required if you have any)
None

  [1]: https://i.stack.imgur.com/p4jRV.png
  [2]: https://i.stack.imgur.com/TcWH4.png
  [3]: https://i.stack.imgur.com/wfhZ5.png
  [4]: https://i.stack.imgur.com/w18C1.png

**Comment by jspenguin2017** [comment]
I rolled out a fix: https://github.com/NanoAdblocker/NanoFilters/commit/04d03c9ffd320031b0b9f3309b216734a150ff25
Does it work for you?

**Comment by jspenguin2017** [comment]
The problem seems to be that Edge treat redirection as canceling the request.

**Comment by jspenguin2017** [comment]
Alright, I'll consider this fixed then. 
Don't forget to use [Feedback Hub](https://aka.ms/extension-request) to ask Microsoft to speed up review process of Nano Defender.

**Comment by ghajini** [comment]
Can not reproduce on ublock edge

**Comment by ghajini** [comment]
@jspenguin2017, I am using your port.....In this website infinite loading of comments, never load

**Comment by jspenguin2017** [comment]
Yea, the fix isn't perfect.

**Comment by jspenguin2017** [comment]
Should be good now. May need to clear your cookies.

**Comment by ghajini** [comment]
Did comments loaded for you in article?

**Comment by jspenguin2017** [comment]
That's `businessinsider.in`, not `businessinsider.com`. 
Yea, the comments are broken, I'll have a look.

**Comment by jspenguin2017** [comment]
Redirection is broken in Edge. Can someone complain to Microsoft?

**Comment by jspenguin2017** [comment]
For the anti-adblock, has to use some power tools, so the solution won't work on uBO.
