### ISSUE TITLE
[Timer] vidto.me

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoFilters#69]
### URLs where this issue occurs (Required)

`http://vidto.me/kdb7qj1i38r3.html`

### Screenshots (Required)
![2018-05-09-orly-z-bostonu-boston-legal-s01e01 lektor pl - vidto](https://user-images.githubusercontent.com/5884000/39822918-22c881ae-53ac-11e8-97af-37e891c7c73d.png)

### Describe the issue (Optional if obvious)
timer

#### Environment (Required)

- Operating System and Version: w10
- Browser and Version: chrome 66.0.3359.139 
- Nano Adblocker Version: ubo 1.16.4
- Nano Defender Version (Optional if you are not using it):  14.14

#### Your filter lists (Required)

https://gist.github.com/KonoromiHimaries/c05bf7f6dd6dcb2d3beb090871985baa

**Comment by jspenguin2017** [comment]
@okiehsch
`vidto.se,vidto.me##+js(nano-setTimeout-booster.js)` seems to work.

**Comment by okiehsch** [comment]
Does not work on my end, I still have to wait 5 seconds, if click "Proceed" immediately the page reloads.

**Comment by jspenguin2017** [comment]
Hum... Yea, seems to be validated on server side. NVM then.
