### ISSUE TITLE
gomovies.cd

### ISSUE THREAD

**Issue by freddieromero23** [NanoAdblocker/NanoFilters#70]
### Screenshots (Required)

![screenshot 13](https://user-images.githubusercontent.com/35078959/39862061-dace3fac-53ff-11e8-92ef-c6699606e623.png)
![screenshot 14](https://user-images.githubusercontent.com/35078959/39862074-e6b6a606-53ff-11e8-99b5-d9127df89c11.png)

### Screenshot of console (Required, press `F12` to open the console)
![screenshot 11](https://user-images.githubusercontent.com/35078959/39862088-f0194b86-53ff-11e8-9d87-ac40e01dadcb.png)
![screenshot 12](https://user-images.githubusercontent.com/35078959/39862097-f652147e-53ff-11e8-838f-d935d332161b.png)

#### Environment (Required)

- Operating System and Version: Windows 10 Home 1709
- Browser and Version: Chrome on Windows | 66.0.3359.139
- Nano Adblocker Version:  1.0.0.48
- Nano Defender Version (Optional if you are not using it): 14.14

#### Your filter lists (Required)

![screenshot 15](https://user-images.githubusercontent.com/35078959/39862409-f8fd4d64-5400-11e8-9ae0-2cad1ea0bda0.png)

#### Your custom filters (Required if you have any)
None

**Comment by jspenguin2017** [comment]
@okiehsch
FuckAdBlock + popup + notification wall

**Comment by okiehsch** [comment]
Does
````
@@||cdn.tnmedia.co/assets/fuckadblock.js$script,domain=streamapi.xyz
@@||streamapi.xyz/ad/banner/*$xmlhttprequest,first-party
@@||gomovies.cd^$generichide
||tnmedia.co^$script,domain=streamapi.xyz
````
fix all issues on your end, I do not get the notification wall.

**Comment by jspenguin2017** [comment]
Yes, that fixes every problem.

**Comment by okiehsch** [comment]
Fixed.
