### ISSUE TITLE
derstandard.at

### ISSUE THREAD

**Issue by KearnAUT** [NanoAdblocker/NanoFilters#74]
### URLs where this issue occurs (Required)

https://derstandard.at/

### Screenshots (Required)
https://prnt.sc/jik8tc

### Screenshot of console (Required, press `F12` to open the console)
https://prnt.sc/jik9ha

#### Environment (Required)

- Operating System and Version: WIN10
- Browser and Version: Google Chrome Version 66.0.3359.170
- Nano Adblocker Version: Newest
- Nano Defender Version (Optional if you are not using it): Newest

#### Your filter lists (Required)

all enabled

**Comment by jspenguin2017** [comment]
Works fine for me, checked 5 articles.

**Comment by gosuroot** [comment]
I still cannot use the site Properly any idea what im doing wrong?

Im using Windows 10 
Newest Chrome Newest Nano Adblocker and newest Nano Defender

All filters enabled
![adb](https://user-images.githubusercontent.com/39370753/40171158-bb157e8e-59ca-11e8-8357-48a211fc02fc.jpg)

**Comment by KearnAUT** [comment]
Hey,
I still have the same problem!

**Comment by jspenguin2017** [comment]
Can you try clearing your cookies? Click the padlock, cookies, then remove. The website works fine for me, I tested it so many times. 
![image](https://user-images.githubusercontent.com/7283682/40184124-ad6775f8-59ac-11e8-95ce-54e02e3d1346.png)

If it is still not working, I need: 
- The country that you are in
- All filter lists that you have enabled
- All custom filters that you have
- All extensions and apps that you have installed

**Comment by KearnAUT** [comment]
Thank you very much! I removed the cookies, now it works :)
