### ISSUE TITLE
[Anti-adblock] washingtonpost.com

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoFilters#76]
```
Reference: Quick Issue Reporter

Message:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Nano Defender 14.30

[Anti-adblock] https://www.washingtonpost.com/world/europe/eu-takes-6-member-states-to-court-over-air-quality/2018/05/17/8582aea4-59f2-11e8-9889-07bcc1327f4b_story.html
```

**Comment by jspenguin2017** [comment]
Upstream: `https://github.com/uBlockOrigin/uAssets/issues/2317`

**Comment by jspenguin2017** [comment]
I'll have a look. Test link: 
`https://www.washingtonpost.com/world/here-are-16-of-the-weeks-best-photos/2018/05/25/2a56c8e4-5bb9-11e8-8836-a4a123c359ab_gallery.html`

**Comment by jspenguin2017** [comment]
@okiehsch 

Also reproduced with uBO. 
![image](https://user-images.githubusercontent.com/7283682/40684699-468bb6ee-634f-11e8-81c1-308353eb2a50.png)

**Comment by okiehsch** [comment]
````
https://www.washingtonpost.com/world/here-are-16-of-the-weeks-best-photos/2018/05/25/2a56c8e4-5bb9-11e8-8836-a4a123c359ab_gallery.html
````
![unbenannt](https://user-images.githubusercontent.com/16838044/40685618-0aaa3eb6-6395-11e8-87b1-a01ce80fb79e.JPG)

**Comment by jspenguin2017** [comment]
If you click the left triangle again does it lock up?

**Comment by okiehsch** [comment]
No. https://github.com/uBlockOrigin/uAssets/issues/2374#issuecomment-392225063

**Comment by okiehsch** [comment]
I can't reproduce, but you are not the only one who raised this issue.
@mapx- could you have a look.

**Comment by jspenguin2017** [comment]
No need, I already rolled out a fix.
