### ISSUE TITLE
filmovizija.live

### ISSUE THREAD

**Issue by JohnMiller9898** [NanoAdblocker/NanoFilters#85]
### URLs where this issue occurs (Required)

http://www.filmovizija.live/movie/unlocked-2017-video_b3f1feb19.html

### Screenshots (Required)
![thevideo me](https://user-images.githubusercontent.com/13141946/40593045-d35fc7fc-6225-11e8-948b-0803481c9ece.JPG)

### Screenshot of console (Required, press `F12` to open the console)
![1](https://user-images.githubusercontent.com/13141946/40593095-263c2678-6226-11e8-816f-d1e15df77ee8.JPG)
![2](https://user-images.githubusercontent.com/13141946/40593099-2a62c18a-6226-11e8-8a96-eb3919b6a3fe.JPG)

### Reproduction Steps (Optional if trivial)
Just enter the URL, and choose the tab circled in red on the screenshot (Stream 5) which embedded video from thevideo.me

#### Environment (Required)

- Operating System and Version: Windows 10 Pro 1709
- Browser and Version: Chrome - 66.0.3359.181
- Nano Adblocker Version: uBlock Origin v1.16.8
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)
Only done as in the instructions for Nano Defender and nothing else.

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/40618503-e83afe7a-624e-11e8-8a71-3d1f27caaaae.png)

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/40618503-e83afe7a-624e-11e8-8a71-3d1f27caaaae.png)
