### ISSUE TITLE
cc.com

### ISSUE THREAD

**Issue by elpanoli** [NanoAdblocker/NanoFilters#88]
### URLs where this issue occurs (Required)
`http://www.cc.com/episodes/pxhhxe/south-park-naughty-ninjas-season-19-ep-1907`

### Screenshots (Required)
https://kek.gg/i/5sHzC_.png

### Screenshot of console (Required, press `F12` to open the console)
https://kek.gg/i/7LNBYX.png

### Describe the issue (Optional if obvious)
There are loads of video ads.

#### Environment (Required)

- Operating System and Version: Win10 
- Browser and Version: Chrome  67.0.3396.62
- Nano Adblocker Version: 1.0.0.52
- Nano Defender Version (Optional if you are not using it): 14.44

#### Your filter lists (Required)
Default setting

**Comment by jspenguin2017** [comment]
The ads are part of the video. 
![image](https://user-images.githubusercontent.com/7283682/40784720-b03865f6-64a3-11e8-8c95-b7426af95524.png)
