### ISSUE TITLE
[Request] Rule for Globally Blocking Facebook Login Nag Screen?

### ISSUE THREAD

**Issue by mikeloeven** [NanoAdblocker/NanoFilters#9]
Does anyone have a solution for blocking facebook's invasive overlay that nags you to log in when browsing the site. I do not have a face book account nor do I intend to register one. 

I have tried blocking the elements manually however the nag screen pops up again when I navigate to another page. 

I found this rule set 
! Remove Facebook Log In / Sign Up banner 
facebook.com###pagelet_growth_expanding_cta
facebook.com###u_0_6

however on adding it my rules this code did not work and in fact blocked all page content from loading

I am using nano adblocker 1.0.0.23 on Waterfox 56.0.1

The behavior can be replicated by navigating to ANY public facebook page while not logged into facebook

**Comment by jspenguin2017** [comment]
Can you show one test link?

**Comment by jspenguin2017** [comment]
Marking as invalid due to lack of response.

**Comment by mikeloeven** [comment]
Sorry about the delay I haven't had much time to check posts due to work. I was able to resolve the issue. It turns out that only the first line is needed

! Remove Facebook Log In / Sign Up banner
facebook.com###pagelet_growth_expanding_cta

the line 
facebook.com###u_0_6 
was what was causing the entire page to be blocked removing that made the rule work properly.
