### ISSUE TITLE
[Anti-adblock] sbs.com.au

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoFilters#98]
```
Reference: Quick Issue Reporter

Message:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36
Nano Defender 14.45

[Anti-adblock] https://www.sbs.com.au/ondemand/video/1201837635549/bad-banks-fired

Stream player now dead
```
![image](https://user-images.githubusercontent.com/7283682/41072135-328b4220-69b9-11e8-9adb-b3ee1388f04e.png)

**Comment by jspenguin2017** [comment]
@okiehsch FYI

**Comment by okiehsch** [comment]
I have no account,
`@@||sbs.com.au^$generichide` disables the detection, I do not know if there are other issues with the player.

**Comment by ghajini** [comment]
User name=
rephoslist@hs130.com

Password=
1234567890

**Comment by jspenguin2017** [comment]
https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/31

**Comment by jspenguin2017** [comment]
This works for me: 
```
@@||sbs.com.au^$generichide
@@||api.sbs.com.au/js/tracking/ondemand.js$script,first-party
```

**Comment by okiehsch** [comment]
Added, thx.

**Comment by ghajini** [comment]
Allow tracking scripts

**Comment by jspenguin2017** [comment]
I'm not bothered by that. Also it's just first party tracking.

**Comment by jspenguin2017** [comment]
Removed test account, it was recorded in the confidential issue linked above.
