### ISSUE TITLE
[Ads, Bundled Download] douploads.com, uplod.org

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoFilters#99]
> `https://douploads.com/otqrbgqeyohu`
> Untick the `Download our offers` by default, because it's just ads. 

See also: https://github.com/jspenguin2017/uBlockProtector/issues/949

**Comment by jspenguin2017** [comment]
@okiehsch Would you consider the checkbox to be ads or annoyance?

**Comment by okiehsch** [comment]
It is adware or malware in my opinion, so I would add a working filter to `uBO-badware`

**Comment by okiehsch** [comment]
I have never seen a bundled download offer that any sane person would see and say:
That eas useful.

**Comment by jspenguin2017** [comment]
I'll have to use `nanop` for this one. So no fix for uBO unfortunately.

**Comment by okiehsch** [comment]
As a side note this is another site that uses `example.com/sw.js` to pull 
````
https://evantative.top/MzAya1VoEgVZYwYEAUl5ERIeSWMAUwAJYwYEHw9lClMfX2QCBR9SbQRUH1w0UAgBCWBRCQVaMBEcEF5sUQYKWWJXHVNaMwIdBlJtAx1TXWUAHQRYMQsDAlpnAlZRXncfEkEcdx8SVx00XURTHzxFVRwfOkMSHklhHQgQNg
````
I am not sure what that script actually does, do you have any idea?

**Comment by jspenguin2017** [comment]
Actually, unchecking a checkbox can be done in uBO: 
```
douploads.com##+js(remove-attr.js, checked, #chkIsAdd)
douploads.com##a[rel="nofollow"]
```

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/41076411-b8f053cc-69ce-11e8-954f-ae85cef2ccdb.png)

The scripts add these event listeners: 
![image](https://user-images.githubusercontent.com/7283682/41076438-db4879f4-69ce-11e8-9d7d-abf94ed305fc.png)

Looks like a library for notification ads.

**Comment by okiehsch** [comment]
Can you download a file?

![unbenannt](https://user-images.githubusercontent.com/16838044/41076539-76cc2658-6a12-11e8-8e29-afd8efe368c4.PNG)


I tried a few links and this is the result with all of them on my end.

**Comment by okiehsch** [comment]
OK, I will add the fix.

**Comment by okiehsch** [comment]
Added, thx.

**Comment by jspenguin2017** [comment]
Even if I don't use the rule or turn off uBO completely, I get the same file (that is flagged as dangerous). 
![image](https://user-images.githubusercontent.com/7283682/41076843-db48ce84-69d0-11e8-88cc-c3915af23335.png)

Also, there is a hidden input that caught my attention, I'm not sure if they are just collecting statistics or it will change the downloaded file. 
![image](https://user-images.githubusercontent.com/7283682/41076956-5e281fee-69d1-11e8-95e4-a83714bbf0c8.png)

**Comment by jspenguin2017** [comment]
I think it is worth to whitelist `.adsbox`. Or `generichide`.

**Comment by okiehsch** [comment]
Well, I do not get any file, but adding
`@@||douploads.com^$generichide`
can't hurt.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/41d929e9929133c60dba26b7e543a6540cb246c9

**Comment by jspenguin2017** [comment]
@okiehsch Also `uplod.org`, same rule should work. Test link: 
```
https://uplod.org/qepvecnvy7qf
```

**Comment by okiehsch** [comment]
Added, thx.
